### ISSUE TITLE
C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1 : Collection is read-only.

### ISSUE THREAD

**Issue by zishbu** [chocolatey/choco#665] opened 2016-03-21 00:00 UTC
It's my first submission, I've searched and tried to make sure I'm submitting this properly. I have been unable to find Collection is read-only, I hope I haven't missed anything. I am in an elevated shell. TIA for your help!

Windows 10
### What You Are Seeing?
after running 
# choco upgrade all -y

When an updated package is identified, like Keepass, this happens on each one when attempting to update:
 C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1 : Collection is read-only.
 At line:1 char:210
 + ... ller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunn ...
 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : NotSpecified: (:) [chocolateyScriptRunner.ps1], NotSupportedException
     + FullyQualifiedErrorId : System.NotSupportedException,chocolateyScriptRunner.ps1
Command ['"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NoLogo -ExecutionPolicy Bypass -Command "[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICul
ture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolate
yInstall.ps1' -installArguments '' -packageParameters ''"'] exited with '1'
Calling command ['"shutdown" /a']
Command ['"shutdown" /a'] exited with '1116'
Capturing package files in 'C:\ProgramData\chocolatey\lib\keepass.install'
 Found 'C:\ProgramData\chocolatey\lib\keepass.install\keepass.install.nupkg'
  with checksum 'CE0E8B3C3DA8B2F36A51640EA9E07478'
 Found 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1'
  with checksum '2F1673A71C6BB8A3EA77E71E703127C2'
 Found 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyUninstall.ps1'
  with checksum '9DF4416C0E3A9B1D3D7F3B557800A769'
Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\keepass.install.2.32\.files.update".
Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\keepass.install.2.32\.sxs".
Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\keepass.install.2.32\.pin".
Attempting to delete directory "C:\ProgramData\chocolatey\lib-bad\keepass.install".
The upgrade of keepass.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1'.
 See log for details.
Moving 'C:\ProgramData\chocolatey\lib\keepass.install'
 to 'C:\ProgramData\chocolatey\lib-bad\keepass.install'
Attempting rollback
Moving 'C:\ProgramData\chocolatey\lib-bkp\keepass.install'
 to 'C:\ProgramData\chocolatey\lib\keepass.install'

### What is Expected?
A successful package update

### How Did You Get This To Happen? (Steps to Reproduce)
choco upgrade all -y

### Output Log

2016-03-20 18:30:53,157 [DEBUG] - _ Chocolatey:ChocolateyUpgradeCommand - Normal Run Mode _
2016-03-20 18:30:53,167 [INFO ] - Upgrading the following packages:
2016-03-20 18:30:53,174 [INFO ] - all
2016-03-20 18:30:53,177 [INFO ] - By upgrading you accept licenses for the packages.
2016-03-20 18:30:53,228 [DEBUG] - Running list with the following filter = ''
2016-03-20 18:30:53,232 [DEBUG] - --- Start of List ---
2016-03-20 18:30:53,373 [DEBUG] - 7zip 15.14
2016-03-20 18:30:53,380 [DEBUG] - 7zip.install 15.14
2016-03-20 18:30:53,391 [DEBUG] - ccleaner 5.15.5513
2016-03-20 18:30:53,397 [DEBUG] - ChocolateyGUI 0.13.2
2016-03-20 18:30:53,400 [DEBUG] - chromium 51.0.2676.0
2016-03-20 18:30:53,404 [DEBUG] - curl 7.28.1
2016-03-20 18:30:53,409 [DEBUG] - disk2vhd 2.01.0.20160213
2016-03-20 18:30:53,415 [DEBUG] - docker 1.10.2
2016-03-20 18:30:53,420 [DEBUG] - git 2.7.4
2016-03-20 18:30:53,427 [DEBUG] - keepass.install 2.31
2016-03-20 18:30:53,432 [DEBUG] - openlivewriter 0.6.0.0
2016-03-20 18:30:53,436 [DEBUG] - openvpn 2.3.10
2016-03-20 18:30:53,441 [DEBUG] - PowerShell 4.0.20141001
2016-03-20 18:30:53,445 [DEBUG] - skype 7.21.0.100
2016-03-20 18:30:53,452 [DEBUG] - sublimetext3 3.0.0.3103
2016-03-20 18:30:53,460 [DEBUG] - sysinternals 2016.02.02
2016-03-20 18:30:53,464 [DEBUG] - winscp 5.7.7
2016-03-20 18:30:53,468 [DEBUG] - winscp.install 5.7.7
2016-03-20 18:30:53,475 [WARN ] - 18 packages installed.
2016-03-20 18:30:53,484 [DEBUG] - --- End of List ---
2016-03-20 18:30:55,482 [INFO ] - 7zip v15.14 is the latest version available based on your source(s).
2016-03-20 18:30:55,997 [INFO ] - 7zip.install v15.14 is the latest version available based on your source(s).
2016-03-20 18:30:57,266 [INFO ] - ccleaner v5.15.5513 is the latest version available based on your source(s).
2016-03-20 18:30:57,925 [INFO ] - ChocolateyGUI v0.13.2 is the latest version available based on your source(s).
2016-03-20 18:31:02,383 [WARN ] - You have chromium v51.0.2676.0 installed. Version 51.0.2683.0 is available based on your source(s).
2016-03-20 18:31:02,398 [DEBUG] - Backing up existing chromium prior to upgrade.
2016-03-20 18:31:02,404 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\chromium'
 to 'C:\ProgramData\chocolatey\lib-bkp\chromium'
2016-03-20 18:31:04,411 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\lib\chromium".
2016-03-20 18:31:04,417 [DEBUG] - Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\chromium\chromium.nupkg"
 to "C:\ProgramData\chocolatey\lib\chromium\chromium.nupkg".
2016-03-20 18:31:04,429 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\lib\chromium\tools".
2016-03-20 18:31:04,434 [DEBUG] - Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\chromium\tools\chocolateyInstall.ps1"
 to "C:\ProgramData\chocolatey\lib\chromium\tools\chocolateyInstall.ps1".
2016-03-20 18:31:05,944 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\chromium'
2016-03-20 18:31:05,950 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\chromium\chromium.nupkg'
  with checksum '29578868538ECAFE17F6842C8E993B31'
2016-03-20 18:31:05,957 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\chromium\tools\chocolateyInstall.ps1'
  with checksum 'F57DA844D97D5CF785FB5797D2D47A37'
2016-03-20 18:31:06,072 [INFO ] - [NuGet] Uninstalling 'chromium 51.0.2676.0'.
2016-03-20 18:31:06,091 [DEBUG] - [NuGet] Removed file 'chocolateyInstall.ps1' to folder 'C:\ProgramData\chocolatey\lib\chromium\tools'.
2016-03-20 18:31:06,100 [DEBUG] - [NuGet] Removed folder 'C:\ProgramData\chocolatey\lib\chromium\tools'.
2016-03-20 18:31:06,108 [DEBUG] - [NuGet] Removed file 'chromium.nupkg' to folder 'C:\ProgramData\chocolatey\lib\chromium'.
2016-03-20 18:31:06,112 [DEBUG] - [NuGet] Removed folder 'C:\ProgramData\chocolatey\lib\chromium'.
2016-03-20 18:31:06,119 [INFO ] - [NuGet] Successfully uninstalled 'chromium 51.0.2676.0'.
2016-03-20 18:31:06,129 [INFO ] - [NuGet] Installing 'chromium 51.0.2683.0'.
2016-03-20 18:31:06,141 [DEBUG] - [NuGet] Added file 'chocolateyInstall.ps1' to folder 'chromium\tools'.
2016-03-20 18:31:06,149 [DEBUG] - [NuGet] Added file 'chromium.nupkg' to folder 'chromium'.
2016-03-20 18:31:06,155 [INFO ] - [NuGet] Successfully installed 'chromium 51.0.2683.0'.
2016-03-20 18:31:06,161 [INFO ] - 
chromium v51.0.2683.0
2016-03-20 18:31:06,216 [DEBUG] - Contents of 'C:\ProgramData\chocolatey\lib\chromium\tools\chocolateyInstall.ps1':
2016-03-20 18:31:06,230 [DEBUG] - $packageName = 'chromium'
$url = 'https://storage.googleapis.com/chromium-browser-continuous/Win/381882/mini_installer.exe'
$url64bit = 'https://storage.googleapis.com/chromium-browser-continuous/Win_x64/381881/mini_installer.exe'
$filePath = "$env:TEMP\chocolatey\$packageName"
$fileFullPath = "$filePath\${packageName}Install.exe"

if (!(Test-Path $filePath)) {
  New-Item -ItemType directory -Path $filePath -Force
}

Get-ChocolateyWebFile -packageName $packageName -fileFullPath `
  $fileFullPath -url $url -url64bit $url64bit
Start-Process $fileFullPath

2016-03-20 18:31:06,248 [DEBUG] - Calling command ['"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NoLogo -ExecutionPolicy Bypass -Command "[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\chromium\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters ''"']
2016-03-20 18:31:06,643 [DEBUG] -  DEBUG: Posh version is 5.1.14291.1001
2016-03-20 18:31:06,802 [DEBUG] -  DEBUG: Loading community extensions
2016-03-20 18:31:06,926 [ERROR] -  C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1 : Collection is read-only.
2016-03-20 18:31:06,934 [ERROR] -  At line:1 char:210
2016-03-20 18:31:06,946 [ERROR] -  + ... ller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunn ...
2016-03-20 18:31:06,952 [ERROR] -  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2016-03-20 18:31:06,960 [ERROR] -      + CategoryInfo          : NotSpecified: (:) [chocolateyScriptRunner.ps1], NotSupportedException
2016-03-20 18:31:06,964 [DEBUG] - Command ['"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NoLogo -ExecutionPolicy Bypass -Command "[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\chromium\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters ''"'] exited with '1'
2016-03-20 18:31:06,965 [ERROR] -      + FullyQualifiedErrorId : System.NotSupportedException,chocolateyScriptRunner.ps1
2016-03-20 18:31:06,971 [DEBUG] - Calling command ['"shutdown" /a']
2016-03-20 18:31:07,017 [DEBUG] - Command ['"shutdown" /a'] exited with '1116'
2016-03-20 18:31:07,087 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\chromium'
2016-03-20 18:31:07,093 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\chromium\chromium.nupkg'
  with checksum 'A1338704A22700D606A5D2BA841EA81B'
2016-03-20 18:31:07,100 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\chromium\tools\chocolateyInstall.ps1'
  with checksum '714E139A7E16824F94157E05D22546A2'
2016-03-20 18:31:07,112 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\chromium.51.0.2683.0\.files.update".
2016-03-20 18:31:07,118 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\chromium.51.0.2683.0\.sxs".
2016-03-20 18:31:07,125 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\chromium.51.0.2683.0\.pin".
2016-03-20 18:31:07,134 [DEBUG] - Attempting to delete directory "C:\ProgramData\chocolatey\lib-bad\chromium".
2016-03-20 18:31:07,140 [ERROR] - The upgrade of chromium was NOT successful.
2016-03-20 18:31:07,148 [ERROR] - Error while running 'C:\ProgramData\chocolatey\lib\chromium\tools\chocolateyInstall.ps1'.
 See log for details.
2016-03-20 18:31:07,156 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\chromium'
 to 'C:\ProgramData\chocolatey\lib-bad\chromium'
2016-03-20 18:31:09,163 [DEBUG] - Attempting rollback
2016-03-20 18:31:09,167 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib-bkp\chromium'
 to 'C:\ProgramData\chocolatey\lib\chromium'
2016-03-20 18:31:11,499 [INFO ] - curl v7.28.1 is the latest version available based on your source(s).
2016-03-20 18:31:11,709 [INFO ] - disk2vhd v2.01.0.20160213 is the latest version available based on your source(s).
2016-03-20 18:31:12,205 [INFO ] - docker v1.10.2 is the latest version available based on your source(s).
2016-03-20 18:31:12,863 [INFO ] - git v2.7.4 is the latest version available based on your source(s).
2016-03-20 18:31:13,361 [WARN ] - You have keepass.install v2.31 installed. Version 2.32 is available based on your source(s).
2016-03-20 18:31:13,366 [DEBUG] - Backing up existing keepass.install prior to upgrade.
2016-03-20 18:31:13,371 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\keepass.install'
 to 'C:\ProgramData\chocolatey\lib-bkp\keepass.install'
2016-03-20 18:31:15,376 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\lib\keepass.install".
2016-03-20 18:31:15,383 [DEBUG] - Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\keepass.install\keepass.install.nupkg"
 to "C:\ProgramData\chocolatey\lib\keepass.install\keepass.install.nupkg".
2016-03-20 18:31:15,391 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\lib\keepass.install\tools".
2016-03-20 18:31:15,395 [DEBUG] - Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\keepass.install\tools\chocolateyInstall.ps1"
 to "C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1".
2016-03-20 18:31:15,403 [DEBUG] - Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\keepass.install\tools\chocolateyUninstall.ps1"
 to "C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyUninstall.ps1".
2016-03-20 18:31:16,943 [INFO ] - [NuGet] Uninstalling 'keepass.install 2.31'.
2016-03-20 18:31:16,948 [DEBUG] - [NuGet] Removed file 'chocolateyInstall.ps1' to folder 'C:\ProgramData\chocolatey\lib\keepass.install\tools'.
2016-03-20 18:31:16,953 [DEBUG] - [NuGet] Removed file 'chocolateyUninstall.ps1' to folder 'C:\ProgramData\chocolatey\lib\keepass.install\tools'.
2016-03-20 18:31:16,959 [DEBUG] - [NuGet] Removed folder 'C:\ProgramData\chocolatey\lib\keepass.install\tools'.
2016-03-20 18:31:16,968 [DEBUG] - [NuGet] Removed file 'keepass.install.nupkg' to folder 'C:\ProgramData\chocolatey\lib\keepass.install'.
2016-03-20 18:31:16,975 [DEBUG] - [NuGet] Removed folder 'C:\ProgramData\chocolatey\lib\keepass.install'.
2016-03-20 18:31:16,981 [INFO ] - [NuGet] Successfully uninstalled 'keepass.install 2.31'.
2016-03-20 18:31:16,990 [INFO ] - [NuGet] Installing 'keepass.install 2.32'.
2016-03-20 18:31:16,997 [DEBUG] - [NuGet] Added file 'chocolateyInstall.ps1' to folder 'keepass.install\tools'.
2016-03-20 18:31:17,007 [DEBUG] - [NuGet] Added file 'chocolateyUninstall.ps1' to folder 'keepass.install\tools'.
2016-03-20 18:31:17,013 [DEBUG] - [NuGet] Added file 'keepass.install.nupkg' to folder 'keepass.install'.
2016-03-20 18:31:17,017 [INFO ] - [NuGet] Successfully installed 'keepass.install 2.32'.
2016-03-20 18:31:17,023 [INFO ] - 
keepass.install v2.32
2016-03-20 18:31:17,065 [DEBUG] - Contents of 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1':
2016-03-20 18:31:17,070 [DEBUG] - $packageName = 'keepass.install'
$installerType = 'exe'
$silentArgs = '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-'
$url = 'https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.32/KeePass-2.32-Setup.exe/download'
$checksum = 'E01935A9EA079EF09EA76B204F1FCF1A2E42504A'
$checksumType = 'sha1'
$validExitCodes = @(0)

Install-ChocolateyPackage -PackageName "$packageName" `
                          -FileType "$installerType" `
                          -SilentArgs "$silentArgs" `
                          -Url "$url" `
                          -ValidExitCodes $validExitCodes `
                          -Checksum "$checksum" `
                          -ChecksumType "$checksumType"
2016-03-20 18:31:17,087 [DEBUG] - Calling command ['"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NoLogo -ExecutionPolicy Bypass -Command "[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters ''"']
2016-03-20 18:31:17,475 [DEBUG] -  DEBUG: Posh version is 5.1.14291.1001
2016-03-20 18:31:17,657 [DEBUG] -  DEBUG: Loading community extensions
2016-03-20 18:31:17,758 [ERROR] -  C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1 : Collection is read-only.
2016-03-20 18:31:17,761 [ERROR] -  At line:1 char:210
2016-03-20 18:31:17,766 [ERROR] -  + ... ller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunn ...
2016-03-20 18:31:17,770 [ERROR] -  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2016-03-20 18:31:17,777 [ERROR] -      + CategoryInfo          : NotSpecified: (:) [chocolateyScriptRunner.ps1], NotSupportedException
2016-03-20 18:31:17,784 [ERROR] -      + FullyQualifiedErrorId : System.NotSupportedException,chocolateyScriptRunner.ps1
2016-03-20 18:31:17,789 [DEBUG] - Command ['"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NoLogo -ExecutionPolicy Bypass -Command "[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters ''"'] exited with '1'
2016-03-20 18:31:17,798 [DEBUG] - Calling command ['"shutdown" /a']
2016-03-20 18:31:17,828 [DEBUG] - Command ['"shutdown" /a'] exited with '1116'
2016-03-20 18:31:17,872 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\keepass.install'
2016-03-20 18:31:17,875 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\keepass.install\keepass.install.nupkg'
  with checksum 'CE0E8B3C3DA8B2F36A51640EA9E07478'
2016-03-20 18:31:17,879 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1'
  with checksum '2F1673A71C6BB8A3EA77E71E703127C2'
2016-03-20 18:31:17,885 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyUninstall.ps1'
  with checksum '9DF4416C0E3A9B1D3D7F3B557800A769'
2016-03-20 18:31:17,896 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\keepass.install.2.32\.files.update".
2016-03-20 18:31:17,901 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\keepass.install.2.32\.sxs".
2016-03-20 18:31:17,906 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\keepass.install.2.32\.pin".
2016-03-20 18:31:17,909 [DEBUG] - Attempting to delete directory "C:\ProgramData\chocolatey\lib-bad\keepass.install".
2016-03-20 18:31:17,915 [ERROR] - The upgrade of keepass.install was NOT successful.
2016-03-20 18:31:17,922 [ERROR] - Error while running 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1'.
 See log for details.
2016-03-20 18:31:17,928 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\keepass.install'
 to 'C:\ProgramData\chocolatey\lib-bad\keepass.install'
2016-03-20 18:31:19,933 [DEBUG] - Attempting rollback
2016-03-20 18:31:19,938 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib-bkp\keepass.install'
 to 'C:\ProgramData\chocolatey\lib\keepass.install'
2016-03-20 18:31:22,125 [INFO ] - openlivewriter v0.6.0.0 is the latest version available based on your source(s).
2016-03-20 18:31:22,342 [INFO ] - openvpn v2.3.10 is the latest version available based on your source(s).
2016-03-20 18:31:22,653 [INFO ] - PowerShell v4.0.20141001 is the latest version available based on your source(s).
2016-03-20 18:31:23,668 [INFO ] - skype v7.21.0.100 is the latest version available based on your source(s).
2016-03-20 18:31:23,822 [INFO ] - sublimetext3 v3.0.0.3103 is the latest version available based on your source(s).
2016-03-20 18:31:24,147 [INFO ] - sysinternals v2016.02.02 is the latest version available based on your source(s).
2016-03-20 18:31:24,369 [INFO ] - winscp v5.7.7 is the latest version available based on your source(s).
2016-03-20 18:31:24,543 [INFO ] - winscp.install v5.7.7 is the latest version available based on your source(s).
2016-03-20 18:31:24,552 [WARN ] - 
Chocolatey upgraded 0/18 package(s). 2 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2016-03-20 18:31:24,557 [ERROR] - Failures:
2016-03-20 18:31:24,561 [ERROR] -  - chromium
2016-03-20 18:31:24,565 [ERROR] -  - keepass.install
2016-03-20 18:31:24,570 [DEBUG] - Exiting with 1

**Comment by gep13** [comment] 2016-03-21 08:50
@zishbu can you confirm what version of Chocolatey you are using?

This seems similar to an issue that was reported here: https://github.com/chocolatey/choco/issues/659 and which was corrected in either 0.9.9.12 or the latest beta of 0.9.10.

**Comment by ferventcoder** [comment] 2016-03-21 13:51
Duplicate of #659

**Closed by ferventcoder** 2016-03-21 13:51 UTC

**Comment by ferventcoder** [comment] 2016-03-21 13:57
Unfortunately you left out the important parts of the output log, seeing all of the environmental information that the configuration contains - see https://gist.github.com/scowalt/5cfc70636850df7cb5f9#file-error-txt-L1-L41 for what is necessary for us. 

However I'm 100% sure it is the same issue, and as @gep13 mentioned, we corrected it already in a newer version of choco. To get that you can't use the usual choco upgrade chocolatey (unfortunately), that's why this was a gating issue that necessitated a 0.9.9.12 release. You can use the install from https://chocolatey.org to get updated to a working version, or you can go into `chocolateyScriptRunner.ps1` and make this change: https://github.com/chocolatey/choco/issues/659#issuecomment-198474858.

Once you make that change you should be good to upgrade as normal.

**Comment by zishbu** [comment] 2016-03-21 14:35
Confirmed - this works for me!


Apologies for leaving out that info and creating a duplicate - I’ve reviewed this JIC I ever need to submit in future.






Thanks!

--

Merci,

Gabriel Beaver





From: Rob Reynolds
Sent: ‎Monday‎, ‎March‎ ‎21‎, ‎2016 ‎09‎:‎57
To: chocolatey/choco
Cc: zishbu





Unfortunately you left out the important parts of the output log, seeing all of the environmental information that the configuration contains - see https://gist.github.com/scowalt/5cfc70636850df7cb5f9#file-error-txt-L1-L41 for what is necessary for us. 

However I'm 100% sure it is the same issue, and as @gep13 mentioned, we corrected it already in a newer version of choco. To get that you can't use the usual choco upgrade chocolatey (unfortunately), that's why this was a gating issue that necessitated a 0.9.9.12 release. You can use the install from https://chocolatey.org to get updated to a working version, or you can go into chocolateyScriptRunner.ps1 and make this change: #659 (comment).

Once you make that change you should be good to upgrade as normal.

**Comment by ferventcoder** [comment] 2016-03-21 14:55
@zishbu don't worry about creating duplicates. If you search and you don't find anything, that is still fine to create an issue. We will triage it appropriately and point you in the right direction! :+1:

**Comment by robertbaker** [comment] 2016-03-21 19:08
@ferventcoder .org install is still referencing broken .11 release.

**Comment by ferventcoder** [comment] 2016-03-21 19:32
Yes, you are correct. I reverted to an older build this morning and it
would have been pointing to the old bits. I will fix that up in a moment.

On Monday, March 21, 2016, Robert Baker <notifications@github.com> wrote:

> @ferventcoder <https://github.com/ferventcoder> .org install is still
> referencing broken .11 release.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/665#issuecomment-199430038>
>


-- 

Rob
"Be passionate in all you do"

http://codebetter.com/robreynolds
http://ferventcoder.com
https://twitter.com/ferventcoder

**Comment by ferventcoder** [comment] 2016-03-21 20:05
Give it a try now.

**Comment by ferventcoder** [comment] 2016-03-21 22:59
My bad, I thought the changes were deployed, but it doesn't appear so. Should be up in a few minutes.

**Comment by ferventcoder** [comment] 2016-03-21 22:59
Just verified that it is live.
