### ISSUE TITLE
Choco list exact + version does not return result

### ISSUE THREAD

**Issue by rdonner** [chocolatey/choco#1856] opened 2019-06-20 12:37 UTC
This concerns Chocolatey 0.10.15. 
### What am I seeing?
I am running some PesterTests in PowerShell and try to get a specific version of SevenZip (among others). Pester does not return the desired results however, as I do not get any packages with the --exact: SevenZip --Version=18.05 command

![image](https://user-images.githubusercontent.com/26113473/59849758-d6bb6d00-9368-11e9-9674-f0ebfa2029c2.png)

### What did I expect
I expect to find a single Package with the name SevenZip and version 18.05

### Steps to Reproduce
I've used the following commands:
choco list --localonly SevenZip
choco list --localonly SevenZip --Version=18.05
choco list --localonly --exact: SevenZip
choco list --localonly --exact: SevenZip --Version=18.05

All of them return a single package, except the last one.
### Output Log
~~~sh
Chocolatey v0.10.15
Chocolatey is running on Windows v 10.0.14393.0
Attempting to delete file "C:/ProgramData/Chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\Chocolatey\choco.exe.old".
Command line: "C:\ProgramData\Chocolatey\choco.exe" list --localonly --exact: SevenZip --Version=18.05 --debug --verbose
Received arguments: list --localonly --exact: SevenZip --Version=18.05 --debug --verbose
RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
Sending message 'PreRunMessage' out if there are subscribers...
[Pending] Removing all pending packages that should not be considered installed...
Performing validation checks.
Global Configuration Validation Checks:
 - Package Exit Code / Exit On Reboot = Checked
System State Validation Checks:
 Reboot Requirement Checks:
 - Pending Computer Rename = Checked
 - Pending Component Based Servicing = Checked
 - Pending Windows Auto Update = Checked
 - Pending File Rename Operations = Checked
 - Pending Windows Package Installer = Checked
 - Pending Windows Package Installer SysWow64 = Checked
The source 'https://xxxx.xxxx.xxx:443/nuget' evaluated to a 'normal' source type

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='list'|
CacheLocation='C:\Users\xxxxxx\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='6000'|WebRequestTimeoutSeconds='30'|
Sources='https://xxxx.xxxx.xxx:443/nuget'|SourceType='normal'|
Debug='True'|Verbose='True'|Trace='False'|Force='False'|Noop='False'|
HelpRequested='False'|UnsuccessfulParsing='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='False'|
AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='SevenZip'|Version='18.05'|
AllVersions='False'|SkipPackageInstallProvider='False'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.14393.0'|
Information.PlatformName='Windows Server 2016'|
Information.ChocolateyVersion='0.10.15.0'|
Information.ChocolateyProductVersion='0.10.15'|
Information.FullName='choco, Version=0.10.15.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxxx'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='xxxxxx'|Information.UserDomainName='xxxxxx'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Information.CurrentDirectory='C:\windows\system32'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
Features.ScriptsCheckLastExitCode='False'|ListCommand.LocalOnly='True'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='True'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|Proxy.BypassOnLocal='True'|
_ Chocolatey:ChocolateyListCommand - Normal Run Mode _
Searching for package information
Running list with the following filter = 'SevenZip'
--- Start of List ---
--- End of List ---
0 packages installed.
Sending message 'PostRunMessage' out if there are subscribers...
Exiting with 0
~~~

**Comment by gep13** [comment] 2019-06-27 06:49
@rdonner thank you for taking the time to report this.  This has also been reported here: https://github.com/chocolatey/choco/issues/1863 so rather than having two open issues for the same item, I am going to close this one in favour of the other.  Please let me know if you have any questions.

**Closed by gep13** 2019-06-27 06:49 UTC
Labels: Duplicate Issue

**Comment by ferventcoder** [comment] 2019-07-02 22:31
Duplicate of #1863
