### ISSUE TITLE
VSTS (azure dev ops) prerelease packages confuse choco

### ISSUE THREAD

**Issue by quasarea** [chocolatey/choco#1696] opened 2018-12-19 10:53 UTC
### What You Are Seeing?
Using VSTS as a package source for chocolatey brings some issues.

    choco sources
    chocolatey - https://chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
    company - https://company-vsts.pkgs.visualstudio.com/_packaging/company/nuget/v2/ (Authenticated)| Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.

Doing:

    choco install ftoc

brings error - note command is without -pre parameter, but it tries to get prerelease version anyway:

    Chocolatey v0.10.11
    Installing the following packages:
    ftoc
    By installing you accept licenses for the packages.
    '1.0.7-feature-ToSandT.ToSandT.11' is not a valid version string.
    Parameter name: version

oddly 

    choco install ftoc -pre

brings exactly the same error. I can be version specific:

    choco install ftoc --version 1.1.13 -y

and then it is ok for package without dependency, but it there are any it propagates:

    Chocolatey v0.10.11
    Installing the following packages:
    ftoc
    By installing you accept licenses for the packages.
    Progress: Downloading FtoC 1.1.13... 100%
    [NuGet] '0.1.0-getGawk.20' is not a valid version string.
    Parameter name: version
    ftoc not installed. An error occurred during installation:
    Unable to resolve dependency 'Gawk (= 4.2.7)'.
    ftoc package files install completed. Performing other installation steps.
    The install of ftoc was NOT successful.
    ftoc not installed. An error occurred during installation:
    Unable to resolve dependency 'Gawk (= 4.2.7)'.

    Chocolatey installed 0/1 packages. 1 packages failed.
    See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

    Failures
    - ftoc (exited 1) - ftoc not installed. An error occurred during installation:
    Unable to resolve dependency 'Gawk (= 4.2.7)'.

if I first do:

    choco install gawk --version 4.2.7 -y

the dependency will be fulfilled and everything will be working fine.

### What is Expected?

To be able to pull latest stable version from vsts package source without having to know exact versions of the package and it dependencies

**Comment by gep13** [comment] 2018-12-19 11:18
@quasarea there are a couple things going on here, which I actually think are different problems, but lets see if we can break them down a bit...

The first thing to point out is that this:

`1.0.7-feature-ToSandT.ToSandT.11`

Is a semantic version v2.0 version number.  Currently, Chocolatey does not support that.  You can follow this issue here: https://github.com/chocolatey/choco/issues/1610 for updates on that.

Similarly, this:

`0.1.0-getGawk.20`

Is a Semantic Version v2 Version number.

For the latter part of your question, can you confirm that the `gawk` package is available on your VSTS feed, or are you trying to use the package that is on the Chocolatey Community Repository?  If the latter, can you confirm that you are not using the `--source` parameter when doing the final installation that you showed the output for.

**Comment by quasarea** [comment] 2018-12-19 12:06
Thanks for so quick response.
Gawk is available on our vsts feed.
I tried to disable chocolatey source to restrict it from noise.
I'm not using --source parameter - commands were copy&pasted here just above their output
When I did:

  choco install ftoc --version 1.1.13 -y

it came back with error, I did

  choco install gawk --version 4.2.7 -y

and it worked

**Comment by quasarea** [comment] 2018-12-19 23:52
Chocolatey v0.10.11

    <?xml version="1.0" encoding="utf-8"?>
    <package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
    <metadata>
        <id>FtoC</id>
        <version>1.1.13</version>
        <title>FtoC</title>
        <authors>Company</authors>
        <owners>Company</owners>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <developmentDependency>true</developmentDependency>
        <licenseUrl>https://www.company.com/Policies_and_Compliance/</licenseUrl>
        <projectUrl>https://confluence.company.com/display/PTFD/FtoC</projectUrl>
        <iconUrl>https://www.company.com/favicon.ico</iconUrl>
        <description>FtoC processes a C/C++ source file containing special format comments and inserts the appropriate code to allow interfacing between C/C++ and Fortran</description>
        <summary>FtoC processes a C/C++ source file containing special format comments and inserts the appropriate code to allow interfacing between C/C++ and Fortran</summary>
        <releaseNotes></releaseNotes>
        <copyright>Copyright 1961 to current year. Company and its subsidiaries. All rights reserved.</copyright>
        <language>en-GB</language>
        <tags>Core</tags>
        <repository type="git" url="https://stash.company.com/scm/EPT/ftoc.git" commit="6918fb9b8536a353ac4b4b515370636a078aff67" />
        <dependencies>
        <dependency id="Perl" version="5.6.9" />
        <dependency id="Gawk" version="4.2.7" />
        </dependencies>
    </metadata>
    </package>

**Comment by gep13** [comment] 2018-12-21 07:58
@quasarea I don't see anything in that nuspec what would suggest things shouldn't work, but I also don't see how that nuspec is resulting in some of the version numbers that you have been describing.  Perhaps I am not following exactly what is going on here.

**Comment by quasarea** [comment] 2018-12-21 12:41
you have all the info I have, the version dependency is set straight and chocko picks it up correctly but then it decides to pull some other version that fails because of not supporting semver 2.0

nuget install ftoc resolves this correctly without any issues

maybe its not that its trying to pull 0.1.0-getGawk.20 but only existence of it makes it flip?

**Comment by gep13** [comment] 2018-12-21 15:57
At this point, I am not sure, if I can, I will try to replicate the situation, to see if I can see what is going on.

Would it be possible for you to list the different package versions that you currently have hosted on your Azure DevOps Feed?  i.e. list out each version of both the gawk, Perl and ftoc packages.

**Comment by quasarea** [comment] 2019-01-14 16:59
nuget list -Prerelease -AllVersions gawk

    Gawk 4.3.0-developmentDependency.17
    Gawk 4.3.0-alpha.18
    Gawk 4.2.7
    Gawk 4.2.6
    Gawk 4.2.5
    Gawk 4.2.4
    Gawk 4.2.2
    Gawk 4.2.1
    Gawk 3.1.7

nuget list -Prerelease -AllVersions perl

    Perl 5.7.0-developmentDependency.23
    Perl 5.7.0-alpha.24
    Perl 5.6.9
    Perl 5.6.8
    Perl 5.6.7
    Perl 5.6.6
    Perl 5.6.5
    Perl 5.6.4
    Perl 5.6.3
    Perl 5.6.2
    Perl 5.6.1

nuget list -Prerelease -AllVersions ftoc

    FtoC 1.2.0-unstable.94
    FtoC 1.2.0-unstable.92
    FtoC 1.2.0-unstable.77
    FtoC 1.2.0-unstable.22
    FtoC 1.2.0-unstable.18
    FtoC 1.2.0-sln.130
    FtoC 1.2.0-PR-8.PullRequest.15
    FtoC 1.2.0-PR-24.PullRequest.96
    FtoC 1.2.0-PR-23.PullRequest.93
    FtoC 1.2.0-PR-22.PullRequest.92
    FtoC 1.2.0-PR-18.PullRequest.80
    FtoC 1.2.0-PR-18.PullRequest.77
    FtoC 1.2.0-PR-13.PullRequest.22
    FtoC 1.2.0-PR-10.PullRequest.16
    FtoC 1.2.0-passInGawk.147
    FtoC 1.2.0-passInGawk.146
    FtoC 1.2.0-passInGawk.145
    FtoC 1.2.0-passInGawk.144
    FtoC 1.2.0-nuspecDevDependencyRemoved.162
    FtoC 1.2.0-noPerl.81
    FtoC 1.2.0-noPerl.80
    FtoC 1.2.0-noPerl.78
    FtoC 1.2.0-editorconfig.128
    FtoC 1.2.0-develop.unstable.10
    FtoC 1.2.0-consumePerl.134
    FtoC 1.2.0-consumePerl.133
    FtoC 1.2.0-cleanup.155
    FtoC 1.2.0-cleanup.154
    FtoC 1.2.0-bump.131
    FtoC 1.2.0-buildProperties.149
    FtoC 1.2.0-bugfix-inconsistency.137
    FtoC 1.2.0-bugfix-bumpVersion.16
    FtoC 1.2.0-bugfix-bumpForVersionFix.11
    FtoC 1.2.0-bugfix-artifact.93
    FtoC 1.2.0-alpha.161
    FtoC 1.2.0-alpha.154
    FtoC 1.2.0-alpha.152
    FtoC 1.2.0-alpha.139
    FtoC 1.2.0-alpha.136
    FtoC 1.2.0-alpha.131
    FtoC 1.2.0-alpha.129
    FtoC 1.2.0-alpha.127
    FtoC 1.2.0-303056-pullPackages.122
    FtoC 1.2.0-303056-pullPackages.109
    FtoC 1.2.0-303056-pullPackages.107
    FtoC 1.2.0-303056-pullPackages.1
    FtoC 1.1.13
    FtoC 1.1.12
    FtoC 1.1.11
    FtoC 1.1.10
    FtoC 1.1.9
    FtoC 1.1.8
    FtoC 1.1.8-validations.11
    FtoC 1.1.8-validations.10
    FtoC 1.1.8-validations.6
    FtoC 1.1.8-PR-26.PullRequest.17
    FtoC 1.1.8-PR-20.PullRequest.10
    FtoC 1.1.8-beta.73
    FtoC 1.1.8-autogenerateMetadata.17
    FtoC 1.1.8-autogenerateMetadata.14
    FtoC 1.1.7
    FtoC 1.1.5
    FtoC 1.1.5-PR-19.PullRequest.60
    FtoC 1.1.5-PR-19.PullRequest.59
    FtoC 1.1.5-PR-17.PullRequest.56
    FtoC 1.1.5-PR-17.PullRequest.50
    FtoC 1.1.5-PR-17.PullRequest.49
    FtoC 1.1.5-PR-12.PullRequest.4
    FtoC 1.1.5-manyTests.48
    FtoC 1.1.5-manyTests.46
    FtoC 1.1.5-manyTests.45
    FtoC 1.1.5-manyTests.44
    FtoC 1.1.4
    FtoC 1.1.4-PR-11
    FtoC 1.1.3-master
    FtoC 1.0.7-PR-7.PullRequest.11
    FtoC 1.0.7-feature-ToSandT.ToSandT.11

**Comment by quasarea** [comment] 2019-01-16 16:22
@ferventcoder how you manage to mark it as duplicate without pointing to one?:)

**Comment by AdmiringWorm** [comment] 2019-01-16 16:57
@quasarea it is the issue that Gary mentioend
issue #1610

**Comment by corbob** [comment] 2022-06-30 16:52
Duplicate of #1610

**Closed by corbob** 2022-06-30 16:52 UTC
Labels: 0 - _Triaging, Duplicate Issue, Question
