### ISSUE TITLE
Management of the Package Manager

### ISSUE THREAD

**Issue by aster94** [chocolatey/choco#1725] opened 2019-02-09 18:15 UTC
hello,
why not supporting packages in a simpler and easier way for everyone?
For example I like the idea how [scoop work](https://github.com/lukesampson/scoop/tree/master/bucket)
This way everyone could add a package and be a mantainer directly pushing a few lines in github

**Comment by FranklinYu** [comment] 2019-02-11 16:17
Are you talking about https://github.com/chocolatey/chocolatey-coreteampackages ?

**Comment by aster94** [comment] 2019-02-11 16:23
Yes

**Comment by ferventcoder** [comment] 2019-03-11 17:55
This appeared to be a question that @FranklinYu has answered. Closing for now. If there is anything here to followup on, please do and we can reopen. Thanks!

**Closed by ferventcoder** 2019-03-11 17:55 UTC
Labels: Question

**Comment by aster94** [comment] 2019-03-11 19:40
This wasn t a question but a request about completely restiling all the code for a smarter and simpler management of the packages

**Comment by FranklinYu** [comment] 2019-03-12 01:20
@aster94 I don’t understand the problem you are describing. Be aware that Chocolatey is distributed by design. For important packages, the Core Team Packages already did the job. What else are you asking for?
