### ISSUE TITLE
ExecuteNonQuery of Microsoft.SqlServer.SMO fails always

### ISSUE THREAD

**Issue by Spamme1** [chocolatey/choco#911] opened 2016-08-16 09:47 UTC
### What You Are Seeing?
ERROR: Exception calling "ExecuteNonQuery" with "1" argument(s): "ExecuteNonQuery failed for Database 'master'. "
 at <ScriptBlock>, C:\ProgramData\chocolatey\lib\test\tools\chocolateyinstall.ps1: line 144

### What is Expected?
SQL query executed successfully 

### How Did You Get This To Happen? (Steps to Reproduce)
Just added the execution of an embedded SQL file, but it happens with any SQL statement, the following example is also not working:
```Powershell
[System.Reflection.Assembly]::LoadWithPartialName( 'Microsoft.SqlServer.SMO') | out-null
$srv = New-Object Microsoft.SqlServer.Management.Smo.Server ".\SQLEXPRESS"
$srv.Databases[0].ExecuteNonQuery("select 1")
```
### Output Log

GIST LINK - Please create a gist and link to that gist here
https://gist.github.com/Spamme1/e45613b0887eba204e7b665d83b326e1

**Comment by Spamme1** [comment] 2016-08-16 10:52
Using the connection to execute the SQL query raises another exception:
ERROR: Exception calling "ExecuteNonQuery" with "1" argument(s): "Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information."

```Powershell
[System.Reflection.Assembly]::LoadWithPartialName( 'Microsoft.SqlServer.SMO') | out-null
$srv = New-Object Microsoft.SqlServer.Management.Smo.Server ".\SQLEXPRESS"
$srv.ConnectionContext.ExecuteNonQuery("select 1")
```

**Comment by ferventcoder** [comment] 2016-08-16 11:59
@Spamme1 this file doesn't exist in our repo, nor do we use SMO

**Comment by ferventcoder** [comment] 2016-08-16 12:02
Oh wait, I see now. This is a duplicate of #640. Please follow up on that ticket. Thanks!

**Closed by ferventcoder** 2016-08-16 12:02 UTC
