### ISSUE TITLE
avira detect some trojan in choco.exe

### ISSUE THREAD

**Issue by dennyhalim** [chocolatey/choco#1242] opened 2017-04-06 04:27 UTC
after happily using choco for few weeks, suddenly today avira remove almost everything in c:\programdata\chocolatey including everything in bin folder

then the folder is set as write protected and cannot reinstall choco, cant even mkdir inside c:\programdata\chocolatey

**Comment by ferventcoder** [comment] 2017-04-06 04:36
Duplicate of #1235. You should contact Avira. It's a false positive.

**Comment by ferventcoder** [comment] 2017-04-06 04:37
In #1235 I linked, it has more details. Please read and comment there. HTH

**Closed by ferventcoder** 2017-04-06 04:36 UTC
