### ISSUE TITLE
Choco list does not give predictable/expected results

### ISSUE THREAD

**Issue by stevenjudd** [chocolatey/choco#1960] opened 2019-11-29 19:36 UTC
### What You Are Seeing?
Running "choco list" and different variations of package names is not returning the expected results.

### What is Expected?
consistent results returning packages with the search text

### How Did You Get This To Happen? (Steps to Reproduce)
run the following commands:
choco list Ink
choco list Ink*
choco list Inksc
choco list Inksc*

Each command returns different or no results. I would expect all of them to return the InkScape package, even if they return other results.

### Output Log
I did not include the output log since this is easily reproducible.

**Comment by ferventcoder** [comment] 2020-01-02 23:15
Duplicate of https://github.com/chocolatey/chocolatey.org/issues/745

**Comment by ferventcoder** [comment] 2020-01-02 23:15
Unfortunately asterisks are not part of search parameters, so those won't work for you.

**Closed by ferventcoder** 2020-01-02 23:15 UTC
