### ISSUE TITLE
PowerShell (Start-ChocolateyProcessAsAdmin) shows error while no error exist

### ISSUE THREAD

**Issue by PatrickKalkman** [chocolatey/choco#1244] opened 2017-04-08 08:55 UTC
### What are you seeing 

Start-ChocolateyProcessAsAdmin shows an error that starts with (<Objs Version="1.1.0.1"..... ) while the command executed as expected.

### What is Expected?

Start-ChocolateyProcessAsAdmin should execute normally without showing an error message. It may be related to issue #1016, but I was not sure.

### How Did You Get This To Happen? (Steps to Reproduce)

Used Install-ChocolateyFileAssociation to install a file association. Install-ChocolateyFileAssociation uses Start-ChocolateyProcessAsAdmin internally.

### Output Log

~~~sh
2017-04-08 10:39:04,881 [DEBUG] - Running Install-ChocolateyFileAssociation -extension 'Nuget.Package' -executable 'C:\ProgramData\chocolatey\lib\NugetPackageExplorer\NugetPackageExplorer.exe' 
2017-04-08 10:39:04,933 [DEBUG] - Running Start-ChocolateyProcessAsAdmin -statements '    cmd /c "assoc .Nuget.Package=NugetPackageExplorer.exe"
    cmd /c 'ftype NugetPackageExplorer.exe="C:\ProgramData\chocolatey\lib\NugetPackageExplorer\NugetPackageExplorer.exe" "%1" "%*"'
    New-PSDrive -Name HKCR -PSProvider Registry -Root HKEY_CLASSES_ROOT
    Set-ItemProperty -Path "HKCR:\NugetPackageExplorer.exe" -Name "(Default)" -Value "NugetPackageExplorer.exe file" -ErrorAction Stop' 
2017-04-08 10:39:04,965 [DEBUG] - Test-ProcessAdminRights: returning True
2017-04-08 10:39:04,996 [DEBUG] - Elevating permissions and running powershell block:
      $noSleep = $False
      #$env:ChocolateyEnvironmentDebug='false'
      #$env:ChocolateyEnvironmentVerbose='false'
      & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1' -Verbose:$false | Out-Null;
      try{
        $progressPreference="SilentlyContinue"
            cmd /c "assoc .Nuget.Package=NugetPackageExplorer.exe"
    cmd /c 'ftype NugetPackageExplorer.exe="C:\ProgramData\chocolatey\lib\NugetPackageExplorer\NugetPackageExplorer.exe" "%1" "%*"'
    New-PSDrive -Name HKCR -PSProvider Registry -Root HKEY_CLASSES_ROOT
    Set-ItemProperty -Path "HKCR:\NugetPackageExplorer.exe" -Name "(Default)" -Value "NugetPackageExplorer.exe file" -ErrorAction Stop
        if(!$noSleep){start-sleep 6}
      }
      catch{
        if(!$noSleep){start-sleep 8}
        throw
      }
This may take a while, depending on the statements.
2017-04-08 10:39:12,117 [ERROR] - #< CLIXML
2017-04-08 10:39:12,135 [INFO ] - VERBOSE: .Nuget.Package=NugetPackageExplorer.exe
2017-04-08 10:39:12,151 [INFO ] - VERBOSE: NugetPackageExplorer.exe="C:\ProgramData\chocolatey\lib\NugetPackageExplorer\NugetPackageExplorer.exe" "%1" "%*"
2017-04-08 10:39:12,168 [INFO ] - VERBOSE: 
2017-04-08 10:39:12,184 [INFO ] - VERBOSE: Name           Used (GB)     Free (GB) Provider      Root                                                                                                                                          CurrentLocation
2017-04-08 10:39:12,201 [INFO ] - VERBOSE: ----           ---------     --------- --------      ----                                                                                                                                          ---------------
2017-04-08 10:39:12,216 [INFO ] - VERBOSE: HKCR                                   Registry      HKEY_CLASSES_ROOT                                                                                                                                            
2017-04-08 10:39:12,230 [INFO ] - VERBOSE: 
2017-04-08 10:39:12,246 [INFO ] - VERBOSE: 
2017-04-08 10:39:12,261 [ERROR] - <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><S S="debug">Host version is 5.1.15063.0, PowerShell Version is '5.1.15063.0' and CLR Version is '4.0.30319.42000'.</S><S S="verbose">Exporting function 'Format-FileSize'.</S><S S="verbose">Exporting function 'Get-ChecksumValid'.</S><S S="verbose">Exporting function 'Get-ChocolateyUnzip'.</S><S S="verbose">Exporting function 'Get-ChocolateyWebFile'.</S><S S="verbose">Exporting function 'Get-EnvironmentVariable'.</S><S S="verbose">Exporting function 'Get-EnvironmentVariableNames'.</S><S S="verbose">Exporting function 'Get-FtpFile'.</S><S S="verbose">Exporting function 'Get-OSArchitectureWidth'.</S><S S="verbose">Exporting function 'Get-ToolsLocation'.</S><S S="verbose">Exporting function 'Get-UACEnabled'.</S><S S="verbose">Exporting function 'Get-UninstallRegistryKey'.</S><S S="verbose">Exporting function 'Get-VirusCheckValid'.</S><S S="verbose">Exporting function 'Get-WebFile'.</S><S S="verbose">Exporting function 'Get-WebFileName'.</S><S S="verbose">Exporting function 'Get-WebHeaders'.</S><S S="verbose">Exporting function 'Install-BinFile'.</S><S S="verbose">Exporting function 'Install-ChocolateyDesktopLink'.</S><S S="verbose">Exporting function 'Install-ChocolateyEnvironmentVariable'.</S><S S="verbose">Exporting function 'Install-ChocolateyExplorerMenuItem'.</S><S S="verbose">Exporting function 'Install-ChocolateyFileAssociation'.</S><S S="verbose">Exporting function 'Install-ChocolateyInstallPackage'.</S><S S="verbose">Exporting function 'Install-ChocolateyPackage'.</S><S S="verbose">Exporting function 'Install-ChocolateyPath'.</S><S S="verbose">Exporting function 'Install-ChocolateyPinnedTaskBarItem'.</S><S S="verbose">Exporting function 'Install-ChocolateyPowershellCommand'.</S><S S="verbose">Exporting function 'Install-ChocolateyShortcut'.</S><S S="verbose">Exporting function 'Install-ChocolateyVsixPackage'.</S><S S="verbose">Exporting function 'Install-ChocolateyZipPackage'.</S><S S="verbose">Exporting function 'Install-Vsix'.</S><S S="verbose">Exporting function 'Set-EnvironmentVariable'.</S><S S="verbose">Exporting function 'Set-PowerShellExitCode'.</S><S S="verbose">Exporting function 'Start-ChocolateyProcessAsAdmin'.</S><S S="verbose">Exporting function 'Test-ProcessAdminRights'.</S><S S="verbose">Exporting function 'Uninstall-BinFile'.</S><S S="verbose">Exporting function 'Uninstall-ChocolateyEnvironmentVariable'.</S><S S="verbose">Exporting function 'Uninstall-ChocolateyPackage'.</S><S S="verbose">Exporting function 'Uninstall-ChocolateyZipPackage'.</S><S S="verbose">Exporting function 'Update-SessionEnvironment'.</S><S S="verbose">Exporting function 'Write-ChocolateyFailure'.</S><S S="verbose">Exporting function 'Write-ChocolateySuccess'.</S><S S="verbose">Exporting function 'Write-FileUpdateLog'.</S><S S="verbose">Exporting function 'Write-FunctionCallLogMessage'.</S><S S="verbose">Exporting alias 'Get-ProcessorBits'.</S><S S="verbose">Exporting alias 'Get-OSBitness'.</S><S S="verbose">Exporting alias 'Get-InstallRegistryKey'.</S><S S="verbose">Exporting alias 'Generate-BinFile'.</S><S S="verbose">Exporting alias 'Add-BinFile'.</S><S S="verbose">Exporting alias 'Start-ChocolateyProcess'.</S><S S="verbose">Exporting alias 'Invoke-ChocolateyProcess'.</S><S S="verbose">Exporting alias 'Remove-BinFile'.</S><S S="verbose">Exporting alias 'refreshenv'.</S><S S="verbose">Exporting function 'Format-FileSize'.</S><S S="verbose">Exporting function 'Get-ChecksumValid'.</S><S S="verbose">Exporting function 'Get-ChocolateyUnzip'.</S><S S="verbose">Exporting function 'Get-ChocolateyWebFile'.</S><S S="verbose">Exporting function 'Get-EnvironmentVariable'.</S><S S="verbose">Exporting function 'Get-EnvironmentVariableNames'.</S><S S="verbose">Exporting function 'Get-FtpFile'.</S><S S="verbose">Exporting function 'Get-OSArchitectureWidth'.</S><S S="verbose">Exporting function 'Get-ToolsLocation'.</S><S S="verbose">Exporting function 'Get-UACEnabled'.</S><S S="verbose">Exporting function 'Get-UninstallRegistryKey'.</S><S S="verbose">Exporting function 'Get-VirusCheckValid'.</S><S S="verbose">Exporting function 'Get-WebFile'.</S><S S="verbose">Exporting function 'Get-WebFileName'.</S><S S="verbose">Exporting function 'Get-WebHeaders'.</S><S S="verbose">Exporting function 'Install-BinFile'.</S><S S="verbose">Exporting function 'Install-ChocolateyDesktopLink'.</S><S S="verbose">Exporting function 'Install-ChocolateyEnvironmentVariable'.</S><S S="verbose">Exporting function 'Install-ChocolateyExplorerMenuItem'.</S><S S="verbose">Exporting function 'Install-ChocolateyFileAssociation'.</S><S S="verbose">Exporting function 'Install-ChocolateyInstallPackage'.</S><S S="verbose">Exporting function 'Install-ChocolateyPackage'.</S><S S="verbose">Exporting function 'Install-ChocolateyPath'.</S><S S="verbose">Exporting function 'Install-ChocolateyPinnedTaskBarItem'.</S><S S="verbose">Exporting function 'Install-ChocolateyPowershellCommand'.</S><S S="verbose">Exporting function 'Install-ChocolateyShortcut'.</S><S S="verbose">Exporting function 'Install-ChocolateyVsixPackage'.</S><S S="verbose">Exporting function 'Install-ChocolateyZipPackage'.</S><S S="verbose">Exporting function 'Install-Vsix'.</S><S S="verbose">Exporting function 'Set-EnvironmentVariable'.</S><S S="verbose">Exporting function 'Set-PowerShellExitCode'.</S><S S="verbose">Exporting function 'Start-ChocolateyProcessAsAdmin'.</S><S S="verbose">Exporting function 'Test-ProcessAdminRights'.</S><S S="verbose">Exporting function 'Uninstall-BinFile'.</S><S S="verbose">Exporting function 'Uninstall-ChocolateyEnvironmentVariable'.</S><S S="verbose">Exporting function 'Uninstall-ChocolateyPackage'.</S><S S="verbose">Exporting function 'Uninstall-ChocolateyZipPackage'.</S><S S="verbose">Exporting function 'Update-SessionEnvironment'.</S><S S="verbose">Exporting function 'Write-ChocolateyFailure'.</S><S S="verbose">Exporting function 'Write-ChocolateySuccess'.</S><S S="verbose">Exporting function 'Write-FileUpdateLog'.</S><S S="verbose">Exporting function 'Write-FunctionCallLogMessage'.</S><S S="verbose">Exporting alias 'Get-ProcessorBits'.</S><S S="verbose">Exporting alias 'Get-OSBitness'.</S><S S="verbose">Exporting alias 'Get-InstallRegistryKey'.</S><S S="verbose">Exporting alias 'Generate-BinFile'.</S><S S="verbose">Exporting alias 'Add-BinFile'.</S><S S="verbose">Exporting alias 'Start-ChocolateyProcess'.</S><S S="verbose">Exporting alias 'Invoke-ChocolateyProcess'.</S><S S="verbose">Exporting alias 'Remove-BinFile'.</S><S S="verbose">Exporting alias 'refreshenv'.</S></Objs>
2017-04-08 10:39:12,295 [DEBUG] - Command ["C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat Text -OutputFormat Text -EncodedCommand IAAgACAAIAAgACAAJABuAG8AUwBsAGUAZQBwACAAPQAgACQARgBhAGwAcwBlAA0ACgAgACAAIAAgACAAIAAjACQAZQBuAHYAOgBDAGgAbwBjAG8AbABhAHQAZQB5AEUAbgB2AGkAcgBvAG4AbQBlAG4AdABEAGUAYgB1AGcAPQAnAGYAYQBsAHMAZQAnAA0ACgAgACAAIAAgACAAIAAjACQAZQBuAHYAOgBDAGgAbwBjAG8AbABhAHQAZQB5AEUAbgB2AGkAcgBvAG4AbQBlAG4AdABWAGUAcgBiAG8AcwBlAD0AJwBmAGEAbABzAGUAJwANAAoAIAAgACAAIAAgACAAJgAgAGkAbQBwAG8AcgB0AC0AbQBvAGQAdQBsAGUAIAAtAG4AYQBtAGUAIAAnAEMAOgBcAFAAcgBvAGcAcgBhAG0ARABhAHQAYQBcAGMAaABvAGMAbwBsAGEAdABlAHkAXABoAGUAbABwAGUAcgBzAFwAYwBoAG8AYwBvAGwAYQB0AGUAeQBJAG4AcwB0AGEAbABsAGUAcgAuAHAAcwBtADEAJwAgAC0AVgBlAHIAYgBvAHMAZQA6ACQAZgBhAGwAcwBlACAAfAAgAE8AdQB0AC0ATgB1AGwAbAA7AA0ACgAgACAAIAAgACAAIAB0AHIAeQB7AA0ACgAgACAAIAAgACAAIAAgACAAJABwAHIAbwBnAHIAZQBzAHMAUAByAGUAZgBlAHIAZQBuAGMAZQA9ACIAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAiAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABjAG0AZAAgAC8AYwAgACIAYQBzAHMAbwBjACAALgBOAHUAZwBlAHQALgBQAGEAYwBrAGEAZwBlAD0ATgB1AGcAZQB0AFAAYQBjAGsAYQBnAGUARQB4AHAAbABvAHIAZQByAC4AZQB4AGUAIgANAAoAIAAgACAAIABjAG0AZAAgAC8AYwAgACcAZgB0AHkAcABlACAATgB1AGcAZQB0AFAAYQBjAGsAYQBnAGUARQB4AHAAbABvAHIAZQByAC4AZQB4AGUAPQAiAEMAOgBcAFAAcgBvAGcAcgBhAG0ARABhAHQAYQBcAGMAaABvAGMAbwBsAGEAdABlAHkAXABsAGkAYgBcAE4AdQBnAGUAdABQAGEAYwBrAGEAZwBlAEUAeABwAGwAbwByAGUAcgBcAE4AdQBnAGUAdABQAGEAYwBrAGEAZwBlAEUAeABwAGwAbwByAGUAcgAuAGUAeABlACIAIAAiACUAMQAiACAAIgAlACoAIgAnAA0ACgAgACAAIAAgAE4AZQB3AC0AUABTAEQAcgBpAHYAZQAgAC0ATgBhAG0AZQAgAEgASwBDAFIAIAAtAFAAUwBQAHIAbwB2AGkAZABlAHIAIABSAGUAZwBpAHMAdAByAHkAIAAtAFIAbwBvAHQAIABIAEsARQBZAF8AQwBMAEEAUwBTAEUAUwBfAFIATwBPAFQADQAKACAAIAAgACAAUwBlAHQALQBJAHQAZQBtAFAAcgBvAHAAZQByAHQAeQAgAC0AUABhAHQAaAAgACIASABLAEMAUgA6AFwATgB1AGcAZQB0AFAAYQBjAGsAYQBnAGUARQB4AHAAbABvAHIAZQByAC4AZQB4AGUAIgAgAC0ATgBhAG0AZQAgACIAKABEAGUAZgBhAHUAbAB0ACkAIgAgAC0AVgBhAGwAdQBlACAAIgBOAHUAZwBlAHQAUABhAGMAawBhAGcAZQBFAHgAcABsAG8AcgBlAHIALgBlAHgAZQAgAGYAaQBsAGUAIgAgAC0ARQByAHIAbwByAEEAYwB0AGkAbwBuACAAUwB0AG8AcAANAAoAIAAgACAAIAAgACAAIAAgAGkAZgAoACEAJABuAG8AUwBsAGUAZQBwACkAewBzAHQAYQByAHQALQBzAGwAZQBlAHAAIAA2AH0ADQAKACAAIAAgACAAIAAgAH0ADQAKACAAIAAgACAAIAAgAGMAYQB0AGMAaAB7AA0ACgAgACAAIAAgACAAIAAgACAAaQBmACgAIQAkAG4AbwBTAGwAZQBlAHAAKQB7AHMAdABhAHIAdAAtAHMAbABlAGUAcAAgADgAfQANAAoAIAAgACAAIAAgACAAIAAgAHQAaAByAG8AdwANAAoAIAAgACAAIAAgACAAfQA=] exited with '0'.
2017-04-08 10:39:12,311 [DEBUG] - Finishing 'Start-ChocolateyProcessAsAdmin'
2017-04-08 10:39:12,318 [INFO ] - 0
2017-04-08 10:39:12,334 [INFO ] - '.Nuget.Package' has been associated with 'C:\ProgramData\chocolatey\lib\NugetPackageExplorer\NugetPackageExplorer.exe'
~~~

**Comment by ferventcoder** [comment] 2017-08-27 20:58
This is a duplicate of https://github.com/chocolatey/choco/issues/1016. It's not actually an error, it's just that the call and redirect of output, PowerShell returns warnings, etc all in the stderr instead of some of them coming to stdout.

**Closed by ferventcoder** 2017-08-27 20:58 UTC
