### ISSUE TITLE
Add option to "pin" an application when installing or upgrading package

### ISSUE THREAD

**Issue by timkatje** [chocolatey/choco#1996] opened 2020-02-04 18:00 UTC
There are several feature requests for improving pinning packages, but I couldn't locate one as simple as my request.  Most are much more advanced methods to automatically pinning applications that self-update.  So sorry if I missed it...

Over time, I've come to understand which applications give me the most trouble, and so I account for that by adding a bunch of `choco pin add`'s to any scripts that I build, but I have two issues with that: 1) it's very redundant to have separate lines for install and then pin and 2) I haven't successfully found a way to add multiple pins in a single command line.

So I would love to see a feature added to _choco.exe_ that permits pinning a package at installation or upgrade, something like `choco install chrome --pin` that would automatically create the .pin file once the package is installed.  I would also love for this to support adding the pin to multiple packages if they're specific at install/upgrade, i.e. `choco install app1 app2 app3 --pin` would add pins to all three installed packages.

After which, scripts become simpler by just grouping all of my trouble apps into a single install command with a list of package names and a `--pin` flag.

And another advantage is that it is not incumbent upon the package maintainers to implement an auto-pin feature for the auto-updating apps (which I think would also be a nice feature to have).  Although, another nice way to approach that is to also create a `--disableAutoUpdates` flag that maintainers could consume to automatically invoke any methods available to them to disable an auto-updater from running, but they'd have to research how each program would implement it.

**Comment by ferventcoder** [comment] 2020-02-04 19:10
Duplicate of #798

**Comment by ferventcoder** [comment] 2020-02-04 19:11
Hi @timkatje, I've marked this as a duplicate. If you can, subscribe and comment on #798. Thanks!

**Closed by ferventcoder** 2020-02-04 19:10 UTC
