### ISSUE TITLE
Remove side-by-side installs

### ISSUE THREAD

**Issue by gep13** [chocolatey/choco#3006] opened 2023-01-30 16:45 UTC
This was deprecated in version 1.2.0 and is ready for removal in 2.0.0

https://github.com/chocolatey/choco/issues/2787

TBD

**Comment by TheCakeIsNaOH** [comment] 2023-01-30 19:39
Looks to be a duplicate of #2788?

**Comment by gep13** [comment] 2023-01-30 20:56
Doh! I went looking for this earlier today, but I couldn't find it. Thank you!

**Closed** 2023-01-30 20:57 UTC
Labels: Duplicate Issue
