### ISSUE TITLE
Gleam installation fails with dependency constraint

### ISSUE THREAD

**Issue by MarkO75SU** [chocolatey/choco#3493] opened 2024-08-02 08:36 UTC
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

PS C:\WINDOWS\system32> choco install gleam
Chocolatey v2.3.0
3 validations performed. 2 success(es), 1 warning(s), and 0 error(s).

Validation Warnings:
 - A pending system reboot request has been detected, however, this is
   being ignored due to the current Chocolatey configuration.  If you
   want to halt when this occurs, then either set the global feature
   using:
     choco feature enable --name="exitOnRebootDetected"
   or pass the option --exit-when-reboot-detected.

Installing the following packages:
gleam
By installing, you accept licenses for the packages.
[NuGet] One or more unresolved package dependency constraints detected in the Chocolatey lib folder. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'python 3.11.4 constraint: python3 (= 3.11.4)'
Unable to resolve dependency 'python311'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - gleam - Unable to resolve dependency 'python311'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.

### What is Expected?

Correct GLEAM installation

### How Did You Get This To Happen?

Running installation command: choco install gleam

### System Details

* Operating System: Windows 10 Pro
* Windows PowerShell version: 5.1
* Chocolatey CLI Version: 2.3.0
* Chocolatey Licensed Extension version:
* Chocolatey License type: Community
* Terminal/Emulator: 

### Installed Packages

```bash
Chocolatey v2.3.0
A single package name is required to run the choco info command.
PS C:\WINDOWS\system32> choco list
Chocolatey v2.3.0
3 validations performed. 2 success(es), 1 warning(s), and 0 error(s).

Validation Warnings:
 - A pending system reboot request has been detected, however, this is
   being ignored due to the current command 'list' being used.
   It is recommended that you reboot at your earliest convenience.

chocolatey 2.3.0
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-windowsupdate.extension 1.0.5
erlang 26.2.5
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
python 3.11.4
python3 3.11.4
vcredist140 14.36.32532
vcredist2015 14.0.24215.20170201
14 packages installed.
```

### Output Log

```bash
2024-08-02 10:29:24,418 7028 [DEBUG] - XmlConfiguration is now operational
2024-08-02 10:29:24,487 7028 [DEBUG] - Adding new type 'CygwinService' for type 'IAlternativeSourceRunner' from assembly 'choco'
2024-08-02 10:29:24,503 7028 [DEBUG] - Adding new type 'CygwinService' for type 'IInstallSourceRunner' from assembly 'choco'
2024-08-02 10:29:24,503 7028 [DEBUG] - Adding new type 'PythonService' for type 'IAlternativeSourceRunner' from assembly 'choco'
2024-08-02 10:29:24,503 7028 [DEBUG] - Adding new type 'PythonService' for type 'IListSourceRunner' from assembly 'choco'
2024-08-02 10:29:24,503 7028 [DEBUG] - Adding new type 'PythonService' for type 'IInstallSourceRunner' from assembly 'choco'
2024-08-02 10:29:24,503 7028 [DEBUG] - Adding new type 'PythonService' for type 'IUninstallSourceRunner' from assembly 'choco'
2024-08-02 10:29:24,503 7028 [DEBUG] - Adding new type 'RubyGemsService' for type 'IAlternativeSourceRunner' from assembly 'choco'
2024-08-02 10:29:24,503 7028 [DEBUG] - Adding new type 'RubyGemsService' for type 'IListSourceRunner' from assembly 'choco'
2024-08-02 10:29:24,503 7028 [DEBUG] - Adding new type 'RubyGemsService' for type 'IInstallSourceRunner' from assembly 'choco'
2024-08-02 10:29:24,503 7028 [DEBUG] - Adding new type 'SystemStateValidation' for type 'IValidation' from assembly 'choco'
2024-08-02 10:29:24,519 7028 [DEBUG] - Adding new type 'CacheFolderLockdownValidation' for type 'IValidation' from assembly 'choco'
2024-08-02 10:29:25,074 7028 [DEBUG] - Adding new type 'EmptyOrInvalidUrlMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2024-08-02 10:29:25,074 7028 [DEBUG] - Adding new type 'FrameWorkReferencesMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2024-08-02 10:29:25,074 7028 [DEBUG] - Adding new type 'IconMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2024-08-02 10:29:25,074 7028 [DEBUG] - Adding new type 'LicenseMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2024-08-02 10:29:25,074 7028 [DEBUG] - Adding new type 'PackageTypesMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2024-08-02 10:29:25,074 7028 [DEBUG] - Adding new type 'ReadmeMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2024-08-02 10:29:25,074 7028 [DEBUG] - Adding new type 'RepositoryMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2024-08-02 10:29:25,074 7028 [DEBUG] - Adding new type 'RequireLicenseAcceptanceMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2024-08-02 10:29:25,074 7028 [DEBUG] - Adding new type 'ServicableMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2024-08-02 10:29:25,089 7028 [DEBUG] - Adding new type 'VersionMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2024-08-02 10:29:25,089 7028 [DEBUG] - Registering new command 'cache' in assembly 'choco'
2024-08-02 10:29:25,089 7028 [DEBUG] - Registering new command 'list' in assembly 'choco'
2024-08-02 10:29:25,105 7028 [DEBUG] - Registering new command 'rule' in assembly 'choco'
2024-08-02 10:29:25,105 7028 [DEBUG] - Registering new command 'template' in assembly 'choco'
2024-08-02 10:29:25,105 7028 [DEBUG] - Registering new command 'export' in assembly 'choco'
2024-08-02 10:29:25,105 7028 [DEBUG] - Registering new command 'info' in assembly 'choco'
2024-08-02 10:29:25,105 7028 [DEBUG] - Registering new command 'help' in assembly 'choco'
2024-08-02 10:29:25,105 7028 [DEBUG] - Registering new command 'config' in assembly 'choco'
2024-08-02 10:29:25,105 7028 [DEBUG] - Registering new command 'feature' in assembly 'choco'
2024-08-02 10:29:25,105 7028 [DEBUG] - Registering new command 'new' in assembly 'choco'
2024-08-02 10:29:25,105 7028 [DEBUG] - Registering new command 'outdated' in assembly 'choco'
2024-08-02 10:29:25,105 7028 [DEBUG] - Registering new command 'pack' in assembly 'choco'
2024-08-02 10:29:25,105 7028 [DEBUG] - Registering new command 'pin' in assembly 'choco'
2024-08-02 10:29:25,105 7028 [DEBUG] - Registering new command 'push' in assembly 'choco'
2024-08-02 10:29:25,105 7028 [DEBUG] - Registering new command 'apikey' in assembly 'choco'
2024-08-02 10:29:25,105 7028 [DEBUG] - Registering new command 'source' in assembly 'choco'
2024-08-02 10:29:25,121 7028 [DEBUG] - Registering new command 'uninstall' in assembly 'choco'
2024-08-02 10:29:25,121 7028 [DEBUG] - Registering new command 'upgrade' in assembly 'choco'
2024-08-02 10:29:25,121 7028 [DEBUG] - Registering new command 'search' in assembly 'choco'
2024-08-02 10:29:25,121 7028 [DEBUG] - Registering new command 'unpackself' in assembly 'choco'
2024-08-02 10:29:25,121 7028 [DEBUG] - Registering new command 'install' in assembly 'choco'
2024-08-02 10:29:25,274 7028 [INFO ] - ============================================================
2024-08-02 10:29:25,437 7028 [INFO ] - Chocolatey v2.3.0
2024-08-02 10:29:25,453 7028 [DEBUG] - Chocolatey is running on Windows v 10.0.19045.0
2024-08-02 10:29:25,453 7028 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2024-08-02 10:29:25,453 7028 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2024-08-02 10:29:25,468 7028 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" install gleam
2024-08-02 10:29:25,475 7028 [DEBUG] - Received arguments: install gleam
2024-08-02 10:29:25,553 7028 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2024-08-02 10:29:25,575 7028 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2024-08-02 10:29:25,591 7028 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
2024-08-02 10:29:25,691 7028 [DEBUG] - Performing validation checks.
2024-08-02 10:29:25,707 7028 [DEBUG] - Global Configuration Validation Checks:
2024-08-02 10:29:25,707 7028 [DEBUG] -  - Package Exit Code / Exit On Reboot = Checked
2024-08-02 10:29:25,707 7028 [DEBUG] - System State Validation Checks:
2024-08-02 10:29:25,707 7028 [DEBUG] -  Reboot Requirement Checks:
2024-08-02 10:29:25,707 7028 [DEBUG] -  - Pending Computer Rename = Checked
2024-08-02 10:29:25,707 7028 [DEBUG] -  - Pending Component Based Servicing = Flagged
2024-08-02 10:29:25,722 7028 [DEBUG] - Cache Folder Lockdown Checks:
2024-08-02 10:29:25,722 7028 [DEBUG] -  - Elevated State = Checked
2024-08-02 10:29:25,722 7028 [DEBUG] -  - Folder Exists = Checked
2024-08-02 10:29:25,722 7028 [DEBUG] -  - Folder lockdown = Checked
2024-08-02 10:29:25,722 7028 [INFO ] - 3 validations performed. 2 success(es), 1 warning(s), and 0 error(s).
2024-08-02 10:29:25,738 7028 [INFO ] - 
2024-08-02 10:29:25,738 7028 [WARN ] - Validation Warnings:
2024-08-02 10:29:25,738 7028 [WARN ] -  - A pending system reboot request has been detected, however, this is
   being ignored due to the current Chocolatey configuration.  If you
   want to halt when this occurs, then either set the global feature
   using:
     choco feature enable --name="exitOnRebootDetected"
   or pass the option --exit-when-reboot-detected.

2024-08-02 10:29:25,754 7028 [DEBUG] - The source 'https://community.chocolatey.org/api/v2/' evaluated to a 'normal' source type
2024-08-02 10:29:25,792 7028 [DEBUG] - 
NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
2024-08-02 10:29:25,823 7028 [DEBUG] - Configuration: CommandName='install'|
CacheLocation='C:\Users\xxx\AppData\Local\Temp\chocolatey'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://community.chocolatey.org/api/v2/'|SourceType='normal'|
IncludeConfiguredSources='False'|ShowOnlineHelp='False'|Debug='False'|
Verbose='False'|Trace='False'|Force='False'|Noop='False'|
HelpRequested='False'|UnsuccessfulParsing='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='True'|
DisableCompatibilityChecks='False'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='gleam'|AllVersions='False'|
SkipPackageInstallProvider='False'|SkipHookScripts='False'|
PackageNames='gleam'|Prerelease='False'|ForceX86='False'|
OverrideArguments='False'|NotSilent='False'|
ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
CacheExpirationInMinutes='30'|AllowDowngrade='False'|
ForceDependencies='False'|PinPackage='False'|
Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.19045.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='2.3.0.0'|
Information.ChocolateyProductVersion='2.3.0'|
Information.FullName='choco, Version=2.3.0.0, Culture=neutral, PublicKeyToken= DELETED

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='DELETED'|/
Information.UserDomainName='DELETED'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|
Information.IsLicensedAssemblyLoaded='False'|
Information.LicenseType='Foss'|
Information.CurrentDirectory='C:\WINDOWS\system32'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
Features.UsePackageHashValidation='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
ListCommand.ExplicitPageSize='False'|
ListCommand.ExplicitSource='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
UpgradeCommand.IgnorePinned='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='Unknown'|
ApiKeyCommand.Command='Unknown'|PinCommand.Command='Unknown'|
OutdatedCommand.IgnorePinned='False'|
ExportCommand.IncludeVersionNumbers='False'|Proxy.BypassOnLocal='True'|
TemplateCommand.Command='unknown'|CacheCommand.Command='Unknown'|
CacheCommand.RemoveExpiredItemsOnly='False'|
2024-08-02 10:29:25,854 7028 [DEBUG] - _ Chocolatey:ChocolateyInstallCommand - Normal Run Mode _
2024-08-02 10:29:25,876 7028 [INFO ] - Installing the following packages:
2024-08-02 10:29:25,891 7028 [INFO ] - gleam
2024-08-02 10:29:25,891 7028 [INFO ] - By installing, you accept licenses for the packages.
2024-08-02 10:29:26,424 7028 [DEBUG] - Running list with the following filter = ''
2024-08-02 10:29:26,556 7028 [DEBUG] - --- Start of List ---
2024-08-02 10:29:26,609 7028 [DEBUG] - Resolving resource PackageSearchResource for source C:\ProgramData\chocolatey\lib
2024-08-02 10:29:26,957 7028 [DEBUG] - chocolatey 2.3.0
2024-08-02 10:29:26,957 7028 [DEBUG] - chocolatey-compatibility.extension 1.0.0
2024-08-02 10:29:26,973 7028 [DEBUG] - chocolatey-core.extension 1.4.0
2024-08-02 10:29:26,979 7028 [DEBUG] - chocolatey-windowsupdate.extension 1.0.5
2024-08-02 10:29:26,979 7028 [DEBUG] - erlang 26.2.5
2024-08-02 10:29:26,979 7028 [DEBUG] - KB2919355 1.0.20160915
2024-08-02 10:29:26,995 7028 [DEBUG] - KB2919442 1.0.20160915
2024-08-02 10:29:26,995 7028 [DEBUG] - KB2999226 1.0.20181019
2024-08-02 10:29:26,995 7028 [DEBUG] - KB3033929 1.0.5
2024-08-02 10:29:27,011 7028 [DEBUG] - KB3035131 1.0.3
2024-08-02 10:29:27,011 7028 [DEBUG] - python 3.11.4
2024-08-02 10:29:27,026 7028 [DEBUG] - python3 3.11.4
2024-08-02 10:29:27,026 7028 [DEBUG] - vcredist140 14.36.32532
2024-08-02 10:29:27,026 7028 [DEBUG] - vcredist2015 14.0.24215.20170201
2024-08-02 10:29:27,026 7028 [DEBUG] - --- End of List ---
2024-08-02 10:29:27,042 7028 [DEBUG] - Resolving resource ListResource for source https://community.chocolatey.org/api/v2/
2024-08-02 10:29:28,028 7028 [INFO ] - [NuGet]   CACHE https://community.chocolatey.org/api/v2/$metadata
2024-08-02 10:29:28,112 7028 [INFO ] - [NuGet]   CACHE https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id)%20eq%20'gleam')%20and%20IsLatestVersion&semVerLevel=2.0.0
2024-08-02 10:29:28,197 7028 [DEBUG] - Resolving resource DependencyInfoResource for source https://community.chocolatey.org/api/v2/
2024-08-02 10:29:28,244 7028 [INFO ] - [NuGet]   CACHE https://community.chocolatey.org/api/v2/Packages(Id='gleam',Version='1.1.0')
2024-08-02 10:29:28,297 7028 [INFO ] - [NuGet]   CACHE https://community.chocolatey.org/api/v2/FindPackagesById()?id='erlang'&semVerLevel=2.0.0
2024-08-02 10:29:28,344 7028 [INFO ] - [NuGet]   CACHE http://community.chocolatey.org/api/v2/FindPackagesById?id='erlang'&$skiptoken='1711020809213','20.2.0','erlang'
2024-08-02 10:29:28,381 7028 [INFO ] - [NuGet]   CACHE http://community.chocolatey.org/api/v2/FindPackagesById?id='erlang'&$skiptoken='1710566321997','15.1.0','erlang'
2024-08-02 10:29:28,529 7028 [WARN ] - [NuGet] One or more unresolved package dependency constraints detected in the Chocolatey lib folder. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'python 3.11.4 constraint: python3 (= 3.11.4)'
2024-08-02 10:29:28,830 7028 [ERROR] - Unable to resolve dependency 'python311'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.
2024-08-02 10:29:28,845 7028 [WARN ] - 
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2024-08-02 10:29:28,861 7028 [INFO ] - 
2024-08-02 10:29:28,861 7028 [ERROR] - Failures
2024-08-02 10:29:28,861 7028 [ERROR] -  - gleam - Unable to resolve dependency 'python311'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.
2024-08-02 10:29:28,861 7028 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2024-08-02 10:29:28,876 7028 [DEBUG] - Exiting with 1
```

**Comment by pauby** [comment] 2024-08-02 09:22
This is a duplicate of #3366 and others.

**Closed by pauby** 2024-08-02 09:22 UTC
Labels: Bug
