### ISSUE TITLE
command `choco uninstall rust` tries to uninstall Visual Studio and Steam

### ISSUE THREAD

**Issue by mbartelsm** [chocolatey/choco#3301] opened 2023-08-17 12:52 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [x] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Running the command `choco uninstall rust` results in the following output 

```
Chocolatey v2.2.2
Uninstalling the following packages:
rust

rust v1.68.0
 Running auto uninstaller...
 Auto uninstaller has successfully uninstalled rust or detected previous uninstall.
 Auto uninstaller has successfully uninstalled rust or detected previous uninstall.

  Did you know licensed versions of Chocolatey are 95% effective with
   Automatic Uninstaller due to licensed enhancements and Package
   Synchronizer?

For the question below, you have 30 seconds to make a selection.
Uninstall may not be silent (could not detect). Proceed?([Y]es/[[N]o]):
```

If I select 'Yes', the GUI uninstaller for VS2022 Installer will show up. If I select 'No', the uninstall process stops.

If I select 'Yes' and then proceed to cancel the GUI uninstaller, the uninstall process continues and the same sequence of messages pop up, but this time the Steam uninstaller will appear.

### What is Expected?

For rust to be uninstalled and nothing else.

### How Did You Get This To Happen?

Ran `choco uninstall rust`

### System Details

* Operating System: Windows 10 x64 22H2
* Windows PowerShell version: 7.3.6
* Chocolatey CLI Version: 2.2.2
* Chocolatey Licensed Extension version: None
* Chocolatey License type: ?
* Terminal/Emulator: Windows Terminal

### Installed Packages

```bash
7zip 23.1.0
7zip.install 23.1.0
audacity 3.3.3
blender 3.6.1
chocolatey 2.2.2
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-fastanswers.extension 0.0.2.2
chocolatey-windowsupdate.extension 1.0.5
dependency-windows10 99.99.99.99
discord 1.0.9005
discord.install 1.0.9005
dotnet-6.0-desktopruntime 6.0.21
dotnet-7.0-desktopruntime 7.0.10
dotnet-desktopruntime 7.0.10
equalizerapo 1.2.0
ffmpeg 6.0.0
git 2.41.0
git.install 2.41.0
go 1.21.0
golang 1.21.0
handbrake 1.6.1
handbrake.install 1.6.1
jdownloader 2.0.0.2023
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
KB3063858 1.0.0
k-litecodecpackmega 17.7.0
mullvad-app 2023.4.0
nodejs 20.5.1
nodejs.install 20.5.1
notepadplusplus 8.5.5
notepadplusplus.install 8.5.6
paint.net 5.0.9
powertoys 0.72.0
python 3.11.4
python3 3.11.4
python311 3.11.4
qbittorrent 4.5.4
vcredist140 14.36.32532
vcredist2008 9.0.30729.616104
vcredist2015 14.0.24215.20170201
vscode 1.80.1
vscode.install 1.80.1

Maybe had more, hard to say what else got uninstalled the first time I ran the command.
```

### Output Log

```bash
https://gist.github.com/mbartelsm/b3126f2a225d94df1b487b90e71cba5b
```

**Comment by pauby** [comment] 2023-08-17 13:15
This appears to be a duplicate of #3277.

**Closed by pauby** 2023-08-17 13:15 UTC
Labels: Bug
