### ISSUE TITLE
Package definition entry to disable auto-shimming

### ISSUE THREAD

**Issue by abejenaru** [chocolatey/choco#1105] opened 2016-12-21 15:32 UTC
Hi, I'm thinking of an entry in the nuspec definition that allows to disables auto shimming, useful in case of program bundles, where you would have to programmatically generate .ignore files for all the .exes

**Comment by ferventcoder** [comment] 2016-12-21 19:16
The concept as we've imagined it is called a shimdirector file. It will be a file placed in the package that tells Chocolatey how to handle executables. When one exists, it uses the file. When one doesn't, it uses the normal process.

**Comment by ferventcoder** [comment] 2016-12-21 19:17
And here is that issue - #306.

**Comment by ferventcoder** [comment] 2016-12-21 19:17
Closing as a duplicate of #306.

**Closed by ferventcoder** 2016-12-21 19:17 UTC
