### ISSUE TITLE
Update-SessionEnvironment changes $Env:USERNAME to System

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/choco#1065] opened 2016-11-30 11:18 UTC
```
PS > $Env:USERNAME
majkinetor

PS > refreshenv
Refreshing environment variables from the registry for powershell.exe. Please wait...
Finished

PS > $Env:USERNAME
SYSTEM
```

**Comment by jberezanski** [comment] 2016-11-30 13:04
Déjà vu...
https://github.com/chocolatey/chocolatey/issues/475#issuecomment-45710349

**Comment by ferventcoder** [comment] 2017-02-02 21:24
Duplicate of #902

**Closed by ferventcoder** 2017-02-02 21:24 UTC
Labels: Duplicate Issue
