### ISSUE TITLE
Get-ChocolateyWebFile.ps1 detected as malicious from ESET

### ISSUE THREAD

**Issue by goshostoychev** [chocolatey/choco#3423] opened 2024-04-18 17:49 UTC
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Hello,
About two hours ago (GMT+3), we started to receive thousands of alarms from our antivirus software, stating that it found a malicious file at C:/ProgramData/chocolatey/helpers/functions/Get‑ChocolateyWebFile.ps1. We checked the file signature, and at first, it says that the file is unsigned, and now, after we tried to make a clean install of chocolatey, the file status in "UnknownError". Have you recently made any changes on your side? What could be the possible reason for this?
Link to the Discord chat, where we had a discussion about the issue - https://discord.com/channels/778552361454141460/897097047801475103

### What is Expected?

No alarm from the antivirus software about a malicious file from chocolatey.

### How Did You Get This To Happen?

We haven't done anything to make this happen. You can reproduce the issue by deleting the chocolatey folder in ProgramData and run the choco install script. This time, our antivirus said that the "infected" file is located in "C:/WINDOWS/TEMP/chocolatey/chocoInstall/tools/chocolateyInstall/helpers/functions/Get‑ChocolateyWebFile.ps1"

### System Details

* Operating System:
* Windows PowerShell version:
* Chocolatey CLI Version:
* Chocolatey Licensed Extension version:
* Chocolatey License type:
* Terminal/Emulator:

### Installed Packages

```bash
Chocolatey v2.2.2 Business
chocolatey 2.2.2
chocolatey.extension 6.1.3
chocolatey-agent 2.1.2
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
chocolatey-windowsupdate.extension 1.0.5
foxit 12.1.1.15289
KB2919442 1.0.20160915
puppet-agent 5.3.3
```

### Output Log

```bash
Chocolatey is running on Windows v 10.0.19045.0
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
Command line: "C:\ProgramData\chocolatey\choco.exe" --debug --verbose
Received arguments: --debug --verbose
RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
CountdownTask is now ready and waiting for PostRunMessage.
Terminal services setup not necessary for this session.
SynchronizeTask is now ready and waiting for PreRunMessage.
PackagesInProgramsAndFeaturesTask is now ready and waiting for PostRunMessage.
Sending message 'PreRunMessage' out if there are subscribers...
[Pending] Removing all pending packages that should not be considered installed...
[Synchronize] Updating packages with Programs and Features
[Synchronize] Currently only supports removals. Soon will handle updates.
Resolving resource PackageSearchResource for source C:\ProgramData\chocolatey\lib
chocolatey 2.2.2
chocolatey.extension 6.1.3
chocolatey-agent 2.1.2
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
chocolatey-windowsupdate.extension 1.0.5
foxit 12.1.1.15289
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3035131 1.0.3
puppet-agent 5.3.3
Sending message 'PostRunMessage' out if there are subscribers...
[Countdown] Determining how long until license expires
chocolatey 2.2.2
chocolatey.extension 6.1.3
chocolatey-agent 2.1.2
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
chocolatey-windowsupdate.extension 1.0.5
foxit 12.1.1.15289
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
puppet-agent 5.3.3
[Programs & Features Package Sync] Ensuring all installed packages that don't have software natively installed are not listed in Programs and Features.
chocolatey 2.2.2
chocolatey.extension 6.1.3
chocolatey-agent 2.1.2
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
chocolatey-windowsupdate.extension 1.0.5
foxit 12.1.1.15289
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3035131 1.0.3
puppet-agent 5.3.3
Exiting with 1
```

**Comment by pauby** [comment] 2024-04-18 19:15
@goshostoychev can you add the link to the Discord chat we had, to the description above?

**Comment by gep13** [comment] 2024-04-19 06:27
> @goshostoychev said...
You can reproduce the issue by deleting the chocolatey folder in ProgramData and run the choco install script. This time, our antivirus said that the "infected" file is located in "C:/WINDOWS/TEMP/chocolatey/chocoInstall/tools/chocolateyInstall/helpers/functions/Get‑ChocolateyWebFile.ps1"

Can you please clarify the exact steps that you are describing here?

**Comment by gep13** [comment] 2024-04-19 07:18
> @goshostoychev said....
Yes, we are deleting the whole choco folder and we are re-installing it

Can I ask that you be very clear about what you are referring to?

Which folder are you referring to here?  The chocolatey folder within the C:\ProgramData folder, or the chocolatey folder within the C:\Windows\Temp folder?

**Comment by goshostoychev** [comment] 2024-04-19 07:19
We are deleting the C:\ProgramData folder, but when we try to re-install choco, our antivirus detects the problematic file in C:\Windows\Temp.

**Comment by goshostoychev** [comment] 2024-04-19 07:54
We have just tested a fresh installation again, and this time the 
'C:\ProgramData\chocolatey\helpers\functions\Get-ChocolateyWebFile.ps1' in  comes with a valid signature. 

Did you made any changes your side?

**Comment by gep13** [comment] 2024-04-19 08:05
> @goshostoychev said...
Did you made any changes your side or maybe after the next update of the antivirus definitions of ESET, the file is no longer marked as malicious?

No, no changes have been made on our side.

**Comment by goshostoychev** [comment] 2024-04-19 08:19
About the response we got from ESET - are you going to take what steps are necessary to submit this file to ESET, so that they can whitelist it?

**Comment by gep13** [comment] 2024-04-19 12:12
@goshostoychev given that this appears to be an isolated incident (i.e. we are not seeing this being reported by lots of people), I don't think there is anything that needs to be done from our side.  The root of the problem seems to be the initial deletion of one of the Chocolatey PowerShell files which was then replaced in by an unsigned version, and ESET triggered on this.

As such, I can going to close this issue, but feel free to respond to it if you have any other comments.

**Comment by m4ttyj** [comment] 2024-04-19 15:44
Not an isolated incident. Weve had this flagged up too!

**Comment by gep13** [comment] 2024-04-19 15:50
@m4ttyj can you confirm what anti-virus you are using, and what file it was triggering on?

**Comment by m4ttyj** [comment] 2024-04-19 20:23
> @m4ttyj can you confirm what anti-virus you are using, and what file it was triggering on?

It was ESET. 
I’ll get you the logs from the portal so you can see what it picked up, but we are experiencing the same as above.

**Comment by m4ttyj** [comment] 2024-04-22 09:02
See attached screenshot @gep13 
![ESETAlert-Choco](https://github.com/chocolatey/choco/assets/13242159/d8a7cfdb-b730-414c-bc13-5adaf6f915ca)

**Comment by gep13** [comment] 2024-04-23 06:26
@m4ttyj thank you for providing that screenshot.

I am not sure how much help we will be able to be with this report.  Chocolatey CLI does not install into that folder by default, and I am not familiar with RepairTech, so I can't speak to what process is being followed to place the files there.

As a side question, was the outcome of this ESEET detection that the file in question was moved to some form of quarantine folder, or did it remain in place in that location?

**Comment by m4ttyj** [comment] 2024-04-23 10:04
Hi

RepairTech is SyncroMSP. It’s used to update default apps like adobe reader etc. 

However I thought it would be useful as it’s the same file and the same reaction (although the location is different)

ESET deletes the file.

**Comment by pauby** [comment] 2024-07-29 15:29
As this issue is now resolved I'll go ahead and close it. We can always reopen it again if necessary.

**Closed by pauby** 2024-07-29 15:29 UTC
Labels: Invalid / Not Issue / No repro / Not Implementing
