### ISSUE TITLE
Packages installed using --x86 don't stay x86 when updated

### ISSUE THREAD

**Issue by blackwind** [chocolatey/choco#636] opened 2016-02-15 04:50 UTC
When a package is installed using --x86, the next update will install the x64 version (unless, I assume, --x86 is specified again during the update). Certain packages have explicit x86 versions that can be installed (like python-x86_32), but for those that don't (like php), this means you can no longer use `cup all`, which is highly counterintuitive.

Either there needs to be a separate x86 package for all packages with x86 versions, or Chocolatey needs to remember when --x86 is specified. I would lean towards the latter.

**Comment by ferventcoder** [comment] 2016-02-15 14:26
Remember is already planned #358

**Comment by ferventcoder** [comment] 2016-02-15 14:28
This is coming for the next version of choco. 

As a workaround for now you can still use cup all, if you pin those particular ones and upgrade them separately. With a pin, they won't be upgraded in the upgrade all (or at all until you remove the pin). 

As an alternative, you can try install the beta and take advantage of the `--except` feature #293 (if the list is small enough).

**Comment by ferventcoder** [comment] 2016-02-15 14:29
I'm going to close this as a duplicate of #358 for now. Please subscribe to that one for updates.

**Closed** 2016-02-15 14:29 UTC
Labels: Duplicate Issue

**Comment by Arnavion** [comment] 2016-11-10 08:09
#358 appears to be marked as fixed in 0.9.10, but as of 0.10.3 this issue doesn't seem to be fixed. I have notepadplusplus.install installed with `--forceX86`, and `cup all` is trying to install the x64 variant of the new version.

**Comment by ferventcoder** [comment] 2016-11-19 01:12
#797 is what the issue is

**Comment by ferventcoder** [comment] 2016-11-19 01:13
It was a dupe when I closed it, but we split #358 to two tickets, one to handle remembering tge args and another to use them during upgrades
