### ISSUE TITLE
Make cpack work with both Chocolatey and CMake, depending on arguments

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1317] opened 2017-06-01 15:22 UTC
Based on @dothebart 's suggestion at https://github.com/chocolatey/choco/issues/89#issuecomment-305508108

**Comment by Marmalade118** [comment] 2018-10-30 11:37
My first time contributing via Code Triage, sorry if I do anything wrong...

I've had a look in to this and according to the choco documentation, cpack is being depreciated due to the conflict with CMake's CPack. Does this issue still need to be open?

I found this in both `CommandsPack.md` and `ChocolateyPackCommand.cs`

```
docs/generated/CommandsPack.md
src/chocolatey/infrastructure.app/commands/ChocolateyPackCommand.cs
```

**Comment by dothebart** [comment] 2018-10-30 12:36
I guess it should be still open as long as chocolatey ships its own cpack alias?

**Comment by Marmalade118** [comment] 2018-11-05 18:44
Ahh, OK. So as the issue is in the current release it should remain and then be removed once its no longer part of the current version?

**Comment by Xav83** [comment] 2019-08-29 07:56
Hi everybody,

I'm currently experiencing this problem too on automation scripts.
I just wanted to know if we have any idea when this issue will be fixed ?

For now, I work around the problem by specifying the full path of the executable.
But it can quicky become complicated, if some of the users of my scripts use custom installation for eitheir chocolatey or cmake.

**Comment by gep13** [comment] 2023-03-20 08:11
Starting with Chocolatey v1.0.0, the cpack alias is no longer shipped as part of Chocolatey.  As such, I do not believe that this issue is required anymore.  If anyone disagrees, please feel free to comment on the issue.

**Closed by gep13** 2023-03-20 08:11 UTC
Labels: Enhancement, Up For Grabs, 0 - Backlog, Priority_LOW
