### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by basictheprogram** [chocolatey/choco#1839] opened 2019-05-31 19:14 UTC
### What You Are Seeing?
If ccleaner is **not** installed choco.exe 0.10.13 returns no values
```
> choco --version
0.10.13
> choco.exe list --local-only --exact --limit-output --all-versions ccleaner
```
If ccleaner is **not** installed choco.exe 0.10.14 throws an error?
```
> choco --version
0.10.14
> choco.exe list --local-only --exact --limit-output --all-versions ccleaner
Object reference not set to an instance of an object
```

### What is Expected?
I am using ansible and the win_chocolatey module and with 0.10.14 installed many of my win_chocolatey module tasks are failing because 0.10.14 returns the message "Object reference not set to an instance of an object" 

I've open an [issue](https://github.com/ansible/ansible/issues/57243) over on their GitHub page to see if the win_chocolatey modules needs to be updated to address how 0.10.14 does return values.

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
> choco list --local-only --exact --limit-output --all-version --debug --
verbose ccleaner
Chocolatey is running on Windows v 10.0.14393.0
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
Command line: "C:\ProgramData\chocolatey\choco.exe" list --local-only --exact --limit-output --all-version --debug --ver
bose ccleaner
Received arguments: list --local-only --exact --limit-output --all-version --debug --verbose ccleaner
RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
Sending message 'PreRunMessage' out if there are subscribers...
[Pending] Removing all pending packages that should not be considered installed...
Performing validation checks.
Global Configuration Validation Checks:
 - Package Exit Code / Exit On Reboot = Checked
System State Validation Checks:
 Reboot Requirement Checks:
 - Pending Computer Rename = Checked
 - Pending Component Based Servicing = Checked
 - Pending Windows Auto Update = Checked
 - Pending File Rename Operations = Checked
 - Pending Windows Package Installer = Checked
 - Pending Windows Package Installer SysWow64 = Checked
The source 'https://chocolatey.org/api/v2/' evaluated to a 'normal' source type

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='list'|
CacheLocation='C:\Users\vagrant\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://chocolatey.org/api/v2/'|SourceType='normal'|
Debug='True'|Verbose='True'|Trace='False'|Force='False'|Noop='False'|
HelpRequested='False'|UnsuccessfulParsing='False'|
RegularOutput='False'|
QuietOutput='False'|PromptForConfirmation='False'|
AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='--all-version ccleaner'|
AllVersions='False'|SkipPackageInstallProvider='False'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.14393.0'|
Information.PlatformName='Windows Server 2016'|
Information.ChocolateyVersion='0.10.14.0'|
Information.ChocolateyProductVersion='0.10.14'|
Information.FullName='choco, Version=0.10.14.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='vagrant'|Information.UserDomainName='VAGRANT'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Information.CurrentDirectory='C:\projects\chocolatey\chocolatey-EasyLogUSB'|

Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='True'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
Features.ScriptsCheckLastExitCode='False'|ListCommand.LocalOnly='True'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='True'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|Proxy.BypassOnLocal='True'|
_ Chocolatey:ChocolateyListCommand - Normal Run Mode _
Using 'C:\ProgramData\chocolatey\lib'.
- Supports prereleases? 'True'.
- Is ServiceBased? 'False'.
Sending message 'PostRunMessage' out if there are subscribers...
Chocolatey had an error occur:
System.NullReferenceException: Object reference not set to an instance of an object.
   at chocolatey.infrastructure.app.services.NugetService.<>c__DisplayClass13.<list_run>b__6()
   at chocolatey.infrastructure.logging.Log4NetLog.Info(Func`1 message)
   at chocolatey.infrastructure.app.services.NugetService.<list_run>d__15.MoveNext()
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.<list_run>d__17.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at chocolatey.infrastructure.app.commands.ChocolateyListCommand.run(ChocolateyConfiguration configuration)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boole
an isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Contai
ner container)
   at chocolatey.console.Program.Main(String[] args)
Exiting with 1
~~~

</p>

</details>

**Comment by AdmiringWorm** [comment] 2019-05-31 19:40
this seem to be a duplicate of #1837 

/cc @gep13

**Comment by ferventcoder** [comment] 2019-05-31 21:00
Duplicate of #1837

**Comment by ferventcoder** [comment] 2019-05-31 21:00
There is a beta out for this now. You should see a quick release of 0.10.15 to address this.

**Closed by ferventcoder** 2019-05-31 21:00 UTC

**Comment by ferventcoder** [comment] 2019-06-03 23:05
https://groups.google.com/forum/#!topic/chocolatey-announce/7VbIZTN1P4o
