### ISSUE TITLE
Uninstallation does not delete files extracted to package directory by chocolateyInstall.ps1

### ISSUE THREAD

**Issue by deckjockey** [chocolatey/choco#1475] opened 2018-01-23 04:20 UTC
### What You Are Seeing?
When using Install-ChocolateyZipPackage to a different location, e.g. C:\ABC, then during uninstall the C:\ABC folder that was created and all files extracted still remain after calling the function Uninstall-ChocolateyZipPackage

### What is Expected?
Folders created and files extracted during Install-ChocolateyZipPackage should be deleted during un-install.

### How Did You Get This To Happen? (Steps to Reproduce)
Call Uninstall-ChocolateyZipPackage in chocolateyUnInstall.ps1

### Output Log
2018-01-23 12:10:50,657 4552 [DEBUG] - Setting installer args for ipscan
2018-01-23 12:10:50,657 4552 [DEBUG] - Setting package parameters for ipscan
2018-01-23 12:10:50,657 4552 [DEBUG] - Contents of 'C:\ProgramData\chocolatey\lib\ipscan\tools\chocolateyuninstall.ps1':
2018-01-23 12:10:50,657 4552 [DEBUG] - $ErrorActionPreference = 'Stop';

$packageName = 'ipscan'
$ZipFileName = 'ipscan.zip'
Uninstall-ChocolateyZipPackage $packageName $ZipFileName

2018-01-23 12:10:50,688 4552 [DEBUG] - Calling built-in PowerShell host with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\ipscan\tools\chocolateyuninstall.ps1' -installArguments '' -packageParameters ''']
2018-01-23 12:10:50,720 4552 [DEBUG] - Redirecting System.Management.Automation.resources, Version=1.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35, requested by ''
2018-01-23 12:10:53,610 4552 [DEBUG] - Host version is 2.0, PowerShell Version is '2.0' and CLR Version is '4.0.30319.36415'.
...
2018-01-23 12:10:54,407 4552 [DEBUG] - Running 'C:\ProgramData\chocolatey\lib\ipscan\tools\chocolateyuninstall.ps1'
2018-01-23 12:10:54,454 4552 [DEBUG] - Running Uninstall-ChocolateyZipPackage -packageName 'ipscan' -zipFileName 'ipscan.zip' 
2018-01-23 12:10:54,517 4552 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\ipscan\tools\chocolateyuninstall.ps1' -installArguments '' -packageParameters '''] exited with '0'.
2018-01-23 12:10:54,517 4552 [INFO ] -  Skipping auto uninstaller - No registry snapshot.
2018-01-23 12:10:54,532 4552 [DEBUG] - Calling command ['"C:\Windows\System32\shutdown.exe" /a']
2018-01-23 12:10:54,579 4552 [DEBUG] - Command ['"C:\Windows\System32\shutdown.exe" /a'] exited with '1116'
2018-01-23 12:10:54,595 4552 [DEBUG] - Attempting to delete directory "C:\ProgramData\chocolatey\.chocolatey\ipscan.2.5.3233".
2018-01-23 12:10:54,595 4552 [DEBUG] - Attempting to delete directory "C:\ProgramData\chocolatey\lib-bkp\ipscan".
2018-01-23 12:10:54,642 4552 [DEBUG] - [NuGet] Removed file 'chocolateyinstall.ps1' to folder 'C:\ProgramData\chocolatey\lib\ipscan\tools'.
2018-01-23 12:10:54,642 4552 [WARN ] - [NuGet] Skipping 'ipscan\tools\chocolateyuninstall.ps1' because it was modified.
2018-01-23 12:10:54,704 4552 [DEBUG] - [NuGet] Removed file 'ipscan.zip' to folder 'C:\ProgramData\chocolatey\lib\ipscan\tools'.
2018-01-23 12:10:54,704 4552 [DEBUG] - [NuGet] Removed file 'ipscan.nuspec' to folder 'C:\ProgramData\chocolatey\lib\ipscan'.
2018-01-23 12:10:54,704 4552 [DEBUG] - [NuGet] Removed file 'ipscan.nupkg' to folder 'C:\ProgramData\chocolatey\lib\ipscan'.
2018-01-23 12:10:54,704 4552 [DEBUG] - [NuGet] The directory is not empty.

2018-01-23 12:10:54,720 4552 [INFO ] - [NuGet] Successfully uninstalled 'ipscan 2.5.3233'.
2018-01-23 12:10:54,735 4552 [INFO ] -  ipscan has been successfully uninstalled.
2018-01-23 12:10:54,735 4552 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\lib\ipscan\ipscan.nupkg".
2018-01-23 12:10:54,751 4552 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\ipscan\ipscanInstall.zip.txt'
  with checksum '2D453B1D235FE67D1280ED54B1A2A1F6'
2018-01-23 12:10:54,751 4552 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\lib\ipscan\ipscanInstall.zip.txt".
2018-01-23 12:10:54,751 4552 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\ipscan\tools\chocolateyuninstall.ps1'
  with checksum 'B7F1CA14B4273CB57ACF066FAF78712F'
2018-01-23 12:10:54,751 4552 [DEBUG] - Attempting to delete directory "C:\Users\p665078d\AppData\Local\Temp\chocolatey\ipscan\2.5.3233".
2018-01-23 12:10:54,798 4552 [WARN ] - 
Chocolatey uninstalled 1/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2018-01-23 12:10:54,798 4552 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2018-01-23 12:10:54,813 4552 [DEBUG] - Exiting with 0
2018-01-23 12:11:56,468 5500 [DEBUG] - XmlConfiguration is now operational

**Comment by ferventcoder** [comment] 2018-01-23 08:31
I believe this is a duplicate of another issue.

**Comment by ferventcoder** [comment] 2018-01-23 08:32
https://github.com/chocolatey/choco/issues/1415

**Closed by ferventcoder** 2018-01-23 08:32 UTC
Labels: 0 - _Triaging
