### ISSUE TITLE
Uninstall-ChocolateyZipPackage fails with "Cannot bind argument" error

### ISSUE THREAD

**Issue by tdunnington** [chocolatey/choco#888] opened 2016-08-02 01:15 UTC
### What You Are Seeing?
Uninstall using Uninstall-ChocolateyZipPackage fails with "ERROR: Cannot bind argument to parameter 'Path' because it is an empty string."

I've found that I can make the uninstall script work properly if I edit the manifest file created by the Install-ChocolateyZipPackage process. The manifest file is C:\ProgramData\chocolatey\lib\ivy\apache-ivy-2.4.0.zip.txt ([see this gist for example](https://gist.github.com/tdunnington/b8dcdeb692d527d95e3720243ca875a7)) and contains two blank lines at the end of the file (as shown in the example). If I edit the file and remove the blank lines, the uninstall will work.

The command is being called from a very simple uninstall script from the ivy package (which I maintain), and [is included in this gist](https://gist.github.com/tdunnington/f141a3a4b308b590bfc846d0b2df3f83)

### What is Expected?
Either the install zip function call needs to not create the blank lines shown in the manifest, or the uninstall needs to ignore them (or both).

### How Did You Get This To Happen? (Steps to Reproduce)
choco install ivy
choco uninstall ivy

### Output Log
Log can be viewed in [this gist file](https://gist.github.com/tdunnington/f141a3a4b308b590bfc846d0b2df3f83)

**Comment by ferventcoder** [comment] 2016-08-02 15:12
I believe this is a duplicate of #871

**Comment by ferventcoder** [comment] 2016-08-02 15:12
Fixed with https://github.com/chocolatey/choco/commit/5664ef3983782d2ff2b088fd3622d18ad54b44e1

**Closed** 2016-08-02 15:12 UTC

**Comment by tdunnington** [comment] 2016-08-03 12:35
@ferventcoder my apologies, I see my mistake. By default issue searching looks for open issues only, so my search did not find #871. My bad!

**Comment by ferventcoder** [comment] 2016-08-03 14:46
No worries, that's why we triage! :)
