### ISSUE TITLE
Choco push times out after 5 minutes on large packages

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#771] opened 2016-06-03 02:09 UTC
When trying to push a 2.1 GB .nupkg (SQL server standard) I was getting a timeout after 5 minutes from BOTH Choco and nuget 3.x

Both were able to push fine on smaller packages from the same client to the same server.

I finally got Nuget working by upgrading to the pre-release version attached to this thread that discusses two internal timeouts in nuget that need to be synced: https://github.com/NuGet/NuGetGallery/issues/1094

The engineer's at Sonatype were able to analyze my Nexus logs for _nuget_ and determine that before I used the above pre-release, the Nexus repo server was not even receiving a "PUT" operation from nuget.exe.  I was not able to vet both clients - so not 100% sure that choco was exhibiting the same behavior.

(Fyi in case anyone tries to repo: Sonatype has their own large package bug which still prevented me from getting an upload - via the logs we were at least able to determine that there are two known bugs and not something else going on - supposed to be fixed in the next release.  That is here: https://issues.sonatype.org/browse/NEXUS-10278)

I'm not sure if it is related, but in my searching I also found a historic issue of nuget 2.x ignoring the timeout value (sorry about the old reference): https://nuget.codeplex.com/SourceControl/network/forks/styx31/nuget/contribution/5969#!/tab/comments

PS - **Pushing the limits of package size trivia**: The package packs fine and installs fine under chocolatey when sourced from a local disk location.

**Comment by ferventcoder** [comment] 2017-04-04 05:28
This may be fixed.

**Comment by vexx32** [comment] 2022-04-01 18:05
Has anyone been able to repro this issue on the current version (v1.x) of Chocolatey?

**Comment by pauby** [comment] 2022-04-12 09:37
Given when this was opened and no additional comments since then, I'm going to go ahead and close this issue, but we can reopen it if necessary.

**Closed by pauby** 2022-04-12 09:37 UTC
Labels: Bug, Up For Grabs, 0 - Backlog, 0 - _Triaging

**Comment by FSpfl** [comment] 2022-05-03 08:36
I think the bug still exists. We set up an internal nexus repository a few days ago. Now we are pushing all our packages from a network share (our previous repository) to the nexus repository. All packages which are bigger than 2 GB fails when we try to push them (timeout after 5-10 minutes). Packages which are 1.75 GB can be pushed to the nexus repository in a few seconds.

When we upload the packages > 2 GB via the nexus webinterface, the upload is successfull.

To reproduce:
- Install nexus-repository
- Configure NuGet repository
- Try to push a package which is bigger than 2 GB with Chocolatey

**Comment by TheCakeIsNaOH** [comment] 2022-05-03 15:33
> Packages which are 1.75 GB can be pushed to the nexus repository in a few seconds.

This would seem to indicate to me that a 2gb package should also be able to be pushed in a few seconds, but they are not. So it seems like there is not a timeout problem directly, but a problem with pushing large packages. It would be on the Chocolatey end or on the Nexus end, or an incompatibility between them.
