### ISSUE TITLE
Search fails, but install works.

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/choco#471] opened 2015-10-27 11:18 UTC
There seems to be an inconsistency between searching for packages and installing/upgrading them. I suspect this is related to case-sensitivity. eg.
```
choco search visualstudiocode
0 packages found.

choco install visualstudiocode
Installing the following packages:
...
```
In this case, the package name according to chocolatey.org is VisualStudioCode

**Comment by gep13** [comment] 2015-10-27 11:57
I suspect that this is related to this:

https://github.com/chocolatey/chocolatey.org/issues/234

If you do `choco search VisualStudioCode` it will return a single package.

**Comment by ferventcoder** [comment] 2015-10-27 14:49
Duplicate of https://github.com/chocolatey/chocolatey.org/issues/234

**Closed by ferventcoder** 2015-10-27 14:49 UTC

**Comment by gep13** [comment] 2015-10-27 14:51
@ferventcoder so nothing needs to change in the choco client to fix this, it is working solely on the results from the search query?  **NOTE:** just want to make sure I am not missing anything :smile:

**Comment by ferventcoder** [comment] 2015-10-27 14:52
Yep, it's entirely a Chocolatey.org issue at the moment.

**Comment by gep13** [comment] 2015-10-27 14:58
:+1:

**Comment by flcdrg** [comment] 2015-10-27 14:59
Sorry for the 'noise'. I did a search before posting this issue, but obviously didn't try enough keywords :-(

**Comment by ferventcoder** [comment] 2015-10-27 15:46
@flcdrg no worries - we're here to make sure things get triaged correctly. :)
