### ISSUE TITLE
Failed update removes package of local library

### ISSUE THREAD

**Issue by jlssmt** [chocolatey/choco#2020] opened 2020-03-29 20:16 UTC
### What You Are Seeing?
if an update fails, the whole package get removed of the local installed library and will never be updated again (with "choco upgrade all")

### What is Expected?
package stays in local library and will be updated the next time "choco upgrade all" gets called.

### How Did You Get This To Happen? (Steps to Reproduce)
enter "choco upgrade all". press ctrl+c while downloading a new update for a package. enter "choco list --localonly". failed package won't be in list.

**Comment by TheCakeIsNaOH** [comment] 2021-10-20 23:21
This appears to be a duplicate of #1548

**Comment by jlssmt** [comment] 2021-10-21 05:59
@OnBeyondBeing
Nope. Never found a solution.
And yes, your description is completely right. This problems will occur over the time and you can't do anything.
I'm currently testing winget. It's not free of bugs also but it detects every application on the system automatically, no matter if it's installed by winget or not and checks for update. This is exactly what I've always missing in chocolatey for years.

**Comment by pauby** [comment] 2024-08-28 08:46
Duplicate of #619

**Closed by pauby** 2024-08-28 08:46 UTC
