### ISSUE TITLE
Corrupt package causes `list` to fail

### ISSUE THREAD

**Issue by gregsdennis** [chocolatey/choco#576] opened 2016-01-25 16:55 UTC
When running `choco list` on a repo that contains a single corrupt package, the command reports no packages.  No error reported.

I have attached a sample package.

![image](https://user-images.githubusercontent.com/12760779/141297395-0870cced-22e8-4c49-928f-1ae0011d86dc.png)

UPDATE: As Chocolatey Gitter chat is now unavailable, I've added a screenshot of the Gitter chat.

**Comment by gregsdennis** [comment] 2016-01-25 16:55
[test.zip](https://github.com/chocolatey/choco/files/103538/test.zip)

**Comment by ferventcoder** [comment] 2016-01-25 17:10
Conversation was at https://gitter.im/chocolatey/choco?at=56a64c5adc33b33c7547c0f4

**Comment by pauby** [comment] 2024-02-04 09:25
This is a duplicate of #3124. As that issue is newer and has more information, I'm going to close this one in favour of that.

**Closed by pauby** 2024-02-04 09:25 UTC
Labels: Bug, 0 - Backlog
