### ISSUE TITLE
Please Support -UpgradeMethod:UninstallCurrentPackage and Client Preference UpgradeMethod:UninstallCurrentPackage

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#621] opened 2016-02-10 18:34 UTC
I scanned the places I know of to check if this was already requested - please let me know if I missed it.

I would like to be able to specify that chocolatey run an uninstall on any packages it is about to upgrade.

Would be great to have this at the per-package transaction level as well as a client preference for all uninstalls.

This is a common practice for mass scale distribution of Windows installation packages of all types.

Basically many installers are not well designed to install over top of a pre-existing version of themselves - especially if the application has been running for a while and dirtied the system with a lot of state data.

Also MSI packages can be very complex to get them to reliably install overtop of previous versions, so many vendor packages actually require this step - but do not offer to do it within the EXE wrapper they provide.

So typically the most reliable way is through external scripting.  Would be way cool if choco had this ability built into a single package transaction, rather than having to call choco twice.

Would also likely stop many upgrade problem reports to chocolatey in general and to individual package maintainers.

PS: Should be ignored for .MSUs if anyone tries to upgrade an MSU based package

**Comment by ferventcoder** [comment] 2016-02-10 18:46
Duplicate of #268

**Comment by ferventcoder** [comment] 2016-02-10 18:46
Found it for you :)

**Comment by ferventcoder** [comment] 2016-02-10 18:46
Feel free to add comments there.

**Comment by ferventcoder** [comment] 2016-02-10 18:47
Not fully a duplicate - but if it should be uninstalled, that is a packaging issue, not a user issue.

**Comment by ferventcoder** [comment] 2016-02-10 18:47
A user could technically uninstall and then install.

**Comment by DarwinJS** [comment] 2016-02-10 19:18
Yes I reviewed that one and do not believe it is a duplicate.

The point of this request is to make it a built in facility for Chocolatey, not something a package maintainer or package consumer has to fuss with.  I can already do that in the enclosing orchestration I put around Choco packages.

By making it an integrated part - the reliability of Chocolatey upgrades (with this setting) should see a dramatic improvement.

So it is not technically a "chocolatey problem" that these installers do not work right - but integrating this well known method causes chocolatey to add a lot of value over just using PowerShell to call MSIs, Setup.exes.

A follow up step would be to start requiring working uninstallers during automated package testing.

**Comment by ferventcoder** [comment] 2016-02-10 20:19
The ticket I haven't brought up yet is that with MSIs, we'll know it is an MSI immediately. We are likely to build in an uninstall/install facility as the default for MSIs.

**Comment by DarwinJS** [comment] 2016-02-10 21:10
That's a great approach - if it would be the default you would also want to have an option to install right over.

If an MSI is large *AND DESIGNED* to install over a previous version - then it can be faster and potentially much less destructive to application state data (user prefs, indexes, etc) than an uninstall before install.

If you implemented it at the choco level as well - then if I a setup.exe package has a chocolateyuninstall.ps1, it could be used to accomplish the same thing for non-MSIs.

D.

**Comment by pauby** [comment] 2024-08-28 09:05
* This really is the maintainers responsibility to ensure that the installer works correctly for an upgrade and take action depending on the result. If the installer misbehaves, then uninstall the software and reinstall it during the upgrade process.
* If the user wants to take responsibility of this, then they can uninstall and then reinstall the package.

Determining what the best thing to do for all the installer types that Chocolatey CLI supports will be very difficult. Even if that were implemented, we would want to have the ability to disable the behaviour for installerX but not installerY. It then gets messy and complicated.

The simplest solution for the user is to either rely on the expert on the installer (the maintainer) or take matters into their own hands (and uninstall /. install the package).

This isn't something we will be looking to add so I'll go ahead and close this issue. We can always reopen again if necessary.

**Closed by pauby** 2024-08-28 09:05 UTC
Labels: 0 - _Triaging
