### ISSUE TITLE
Choco does not detect if the installation of packages has been interrupted

### ISSUE THREAD

**Issue by dcllt** [chocolatey/choco#2757] opened 2022-07-05 15:35 UTC
### What You Are Seeing?

It seems like if user or something else cancel during download or installation, Choco treats package as successful. I can find the package by running 'choco list  -l' .I saw this issue was already reported and closed here #198 . Despite this the problem seems to have reappeared.

### What is Expected?

Detect if package installation was not completed. 

### How Did You Get This To Happen? (Steps to Reproduce)

Abort package installation by pressing Ctrl+C

### System Details

This is on Choco 1.1.0

Also on Choco 1.4.0

### Additional Information
[Zendesk Ticket](https://chocolatey.zendesk.com/agent/tickets/23520)

**Comment by romain-marie** [comment] 2022-08-04 14:19
Hello, same problem for me.

**Comment by vexx32** [comment] 2022-09-30 15:23
Thanks for the report! 

I haven't been able to reproduce what's being described here so far. Can you define:

- Which package(s) you're seeing this on
- Which terminal you're using to run choco (cmd? Windows Terminal? PowerShell? etc)
- When during the installation you're pressing Ctrl+C
- What operating system you're running choco on

I think we need additional detail here to have a better idea of what's going on and be able to reliably reproduce the issue.

**Comment by romain-marie** [comment] 2022-10-03 09:31
Hello, here are the steps to reproduce : 

1. Have a Windows 10 pro 21H2 with chocolatey 1.1.0 installed, following instructions here : https://chocolatey.org/install
2. Open powershell as administrator
3. Enter `choco install firefox` then [ENTER]
4. Wait for the line `Do you want to run the script ... ?`
5. Close powershell window OR turn off PC (immediatly or during download or installation after hitting `y`) 
6. Open powershell again, enter `choco list -l` : firefox is listed, but is not installed on pc

**Comment by vexx32** [comment] 2022-10-03 12:56
Thanks for that! I can confirm I'm seeing the same behaviour in my own environment as well. Definitely looks like something is going wrong with the pending files that we normally use to track incomplete package installations 🤔

**Comment by pauby** [comment] 2024-08-28 08:58
Duplicate of #619

**Closed as not planned by pauby** 2024-08-28 08:58 UTC
Labels: Duplicate Issue
