### ISSUE TITLE
Chocolatey is adding nuget packages to Default profile nuget cache when not executing with a profile

### ISSUE THREAD

**Issue by bender-the-greatest** [chocolatey/choco#1594] opened 2018-06-18 19:28 UTC
Chocolatey version: 0.10.7

### What You Are Seeing?
As packages are installed, the Default profile's LocalAppData folder is used for the nuget cache when the executing user's profile does not have $env:AppData or $env:LocalAppData set, instead of placing it in another suitable location, such as C:\Windows\Temp

This creates an issue in corporate environments where additional profiles are generated as users/admins log onto boxes, because the user profile directory is populated with potentially several hundred megabytes (or more) for each new user logging into the machine.

### What is Expected?
That the Default profile is not used for active data that can potentially be replicated to other users logging onto a server/workstation. The Public profile or C:\Windows\TEMP would be a better suitable cache location when the local user's profile does not exist.

In the case that there is not a suitable location to auto-resolve in this case, I would expect the client to error out stating to set a suitable cache directory for use instead of defaulting to the Default profile that gets copied for new users logging into the machine.

### How Did You Get This To Happen? (Steps to Reproduce)
Install a Chocolatey package as a user without having the profile environment variables set. `runas /noprofile` may be a suitable test. In our environment we are seeing this case when executing Chocolatey installations over the VAPI on a guest Windows OS.

### Output Log
There is no output indicating this, just the end result as viewable on the filesystem. C:\Users\Default\AppData\Local\Nuget\Cache is populated when the above conditions are met, and as new profiles are generated from the Default profile, you can see the cache directory contents eat up valuable disk space for each additional profile created when a new user logs into the machine.

**Comment by ferventcoder** [comment] 2018-06-18 20:17
Does the current release do this?

**Comment by bender-the-greatest** [comment] 2018-06-19 21:19
I will see what we can do to deploy a newer version of Chocolatey - I know we are installing Chocolatey with a Chef recipe but need to see whether one of our wrapper cookbooks is referencing a specific in-house hosted version or not.

Once we begin deploying a newer version, I'll see if the default behavior is still to use the Default profile, then set the cacheLocation.

**Comment by ferventcoder** [comment] 2018-06-22 19:38
Why not 0.10.11?

**Comment by ferventcoder** [comment] 2018-06-22 19:39
Can you confirm you meant Chocolatey v0.10.11? https://chocolatey.org/packages/chocolatey

**Comment by bender-the-greatest** [comment] 2018-06-22 22:22
We have a local mirror via Artifactory (I thought it was merely a proxy but it's clear that 0.10.11 isn't available through it) that makes public Chocolatey packages available (we do not have internet access on these servers). That repo does not have 0.10.11 available on it, .10 is the most recent I can grab at this time.

I did set the cacheLocation as part of our Chef run after installing Chocolatey. I can see the cacheLocation path is populated with installers, but the nuget packages are still being cached in the Default profile. I can try to have the team who manages Artifactory pull in the updated Chocolatey package, but it's unlikely they'll get to it in a timely manner.

**Comment by corbob** [comment] 2024-10-17 14:27
It looks like this issue was resolved with the uplift in Chocolatey 2.0.0 (or possibly a subsequent release). I can confirm that I see this behaviour in 1.4.0, but not in 2.3.0. Based on that, I will close this issue. If it's still an issue that can be reproduced on the latest Chocolatey CLI (2.3.0 as of today), then we can reopen it and update the reproduction steps.

**Closed by corbob** 2024-10-17 14:27 UTC
Labels: 0 - _Triaging

**Comment by pauby** [comment] 2024-10-17 17:19
@corbob can you fix the labels on this now it's closed?

**Comment by corbob** [comment] 2024-10-17 17:24
@pauby good catch. I've updated this and the other two to be `Bug` and `5 - Released`. I have not tagged them to milestones though as I'm not entirely sure which one resolved them (although would wager a guess at 2.0.0).
