### ISSUE TITLE
Enhancement Request: Graceful handling of situation where I run "choco upgrade all" and forget the -y flag.

### ISSUE THREAD

**Issue by ivanatpr** [chocolatey/choco#309] opened 2015-06-05 04:53 UTC
(First of all, I know you can run "choco feature enable -n allowGlobalConfirmation" to turn off all run script confirmation prompts. This is about making chocolatey more user friendly when using the default settings.)

So right now, as far as I can tell, if I have a bunch of packages to upgrade and run "choco upgrade all" and forget the -y flag, I'm basically forced to babysit the command prompt waiting for each individual upgrade to complete so that I can manually hit "yes" on the next upgrade's run script prompt. That's a high cost for a very easily made mistake and there doesn't seem to be an escape valve that allows me to cleanly fix my mistake and do the unattended bulk upgrade that I meant to do in the first place. 

There are a few options I can think of to make this interaction more friendly:

- Add a "yes to this and all future prompts" selection to the run script prompt, effectively running all remaining installs as if the -y flag had been set.
- Add a "Abort" selection the cleanly terminates the chocolatey process and lets me re-input the command with the -y flag added
- Frontload all the script confirmations: Whenever doing a bulk install/update, instead of asking for confirmation for each script right before it runs, ask for confirmations for all scripts to be run as the first step before anything else happens. 
    - An example of this kind of approach is how Eclipse handles the installation of multiple packages. Eclipse lets you install many packages in bulk but individual packages often have licensing agreement has to explicitly sign off on first in order to install. Eclipse's approach to this is that after you select all the packages you wish to install, Eclipse immediately fetches all the licensing agreements and gets the user's confirmation for each one. Only after that's complete does Eclipse begin downloading and installing the actual packages, which it can then do without ever prompting the user until the process is complete.

**Comment by ferventcoder** [comment] 2015-06-05 07:14
Essentially this is a dupe of #53

**Comment by ivanatpr** [comment] 2015-06-05 16:04
Yep, you're right. Sorry about that!

**Comment by ferventcoder** [comment] 2015-06-05 19:20
No worries, just trying to keep things in order. :)

**Closed by ferventcoder** 2015-06-05 19:20 UTC
Labels: 0 - _Triaging, Duplicate Issue
