### ISSUE TITLE
[Bug] Unwanted reset account in chocolatey.org

### ISSUE THREAD

**Issue by Kristinita** [chocolatey/choco#1114] opened 2016-12-29 16:18 UTC
### 1. Actual behavior

1. Sometimes I need clean cookies for chocolatey.org that login in this site.
2. I need enter in my account in chocolatey.org again and again. The data at the input not saved.

### 2. Expected behavior

Never go out into my account.

### 3. Steps to reproduce

1. Sometimes I can not login. I not redirect on **<https://chocolatey.org/users/account/LogOn>** page.

![Chocolatey login](http://i.imgur.com/0R7ZqiB.gif)

2. I enter in my account `oderzhimyi_Sashei` in **<https://chocolatey.org/users/account/LogOn>** page. After 30 minutes — 1 hour account reset and I must enter in my account again.

### 4. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Firefox:**
50.1.0
**Antivirus, ad blockers, flash blockers, Greasemonkey, firewall, Windows Defender:**
disabled

Thanks.

**Comment by ferventcoder** [comment] 2016-12-29 17:14
Howdy, this is a duplicate of https://github.com/chocolatey/chocolatey.org/issues/455.

When you filed the issue, did follow the template note to read over https://github.com/chocolatey/choco#submitting-issues? It would have helped you over to the website github repo?

**Closed by ferventcoder** 2016-12-29 17:14 UTC

**Comment by ferventcoder** [comment] 2016-12-29 17:15
If you would not mind following up over on that repo or creating a new issue for this over there if you don't feel this is a duplicate of that, that would be great. FWIW, I've seen the same behavior. Actually it may be a dupe of https://github.com/chocolatey/chocolatey.org/issues/438

HTH, thanks!
