### ISSUE TITLE
Unable to install choco in Windows 7 32-bit

### ISSUE THREAD

**Issue by superbonaci** [chocolatey/choco#3268] opened 2023-07-15 19:00 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

Trying to fresh install choco.

### What is Expected?

Install or tell me I can't for x reasons.

### How Did You Get This To Happen?

Run the install command according to website https://chocolatey.org/install
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```

### System Details

* Operating System: Windows 7 version 6.1 build 7601 SP1 32-bit
* Windows PowerShell version:
```
$PSVersionTable

Name                           Value
----                           -----
CLRVersion                     2.0.50727.8762
BuildVersion                   6.1.7601.17514
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1
```

### Installed Packages

```bash
none
```

### Output Log

```bash
$ Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [
System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('http
s://community.chocolatey.org/install.ps1'))
Exception setting "SecurityProtocol": "Cannot convert value "3312" to type "System.Net.SecurityProtocolType" due to inv
alid enumeration values. Specify one of the following enumeration values and try again. The possible enumeration values
 are "Ssl3, Tls"."
At line:1 char:85
+ Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]:: <<<< SecurityProtocol = [System.
Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://co
mmunity.chocolatey.org/install.ps1'))
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Exception calling "DownloadString" with "1" argument(s): "The underlying connection was closed: An unexpected error occ
urred on a send."
At line:1 char:219
+ Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.Se
rvicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString <<<< ('https://co
mmunity.chocolatey.org/install.ps1'))
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException
```

**Comment by pauby** [comment] 2023-07-15 19:42
Chocolatey CLI isn't supported on Windows 7 (as mentioned in the [docs](https://chocolatey.org/install#install-step2)) but you can get it [working with tweaking](https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-versions/).

This is also a [duplicate of a previous issue that you raised](https://github.com/chocolatey/choco/issues/3250).

**Closed by pauby** 2023-07-15 19:42 UTC
Labels: Bug

**Comment by superbonaci** [comment] 2023-07-15 20:02
> This is also a [duplicate of a previous issue that you raised](https://github.com/chocolatey/choco/issues/3250).

In that issue I explain that choco was already installed, but not I'm trying a fresh install, since need to report a bug to a package maintainer.
