### ISSUE TITLE
choco list --local-only fails with no sources

### ISSUE THREAD

**Issue by jborean93** [chocolatey/choco#1673] opened 2018-11-06 03:29 UTC
### What You Are Seeing?
When running `choco.exe list --local-only` and no sources are currently configured on the host, it will fail to run with

```
PS C:\Users\vagrant> choco list --local-only                                                                         
Chocolatey v0.10.11    
Unable to search for packages when there are no sources enabled for                                                             
 packages and none were passed as arguments.       
```

There shouldn't be any reason (that I'm aware of) that it would require source access to list local packages and version.

### What is Expected?
The command succeeds and lists all local packages with their versions when no sources are configured.

### How Did You Get This To Happen? (Steps to Reproduce)
```
choco source remove -n=chocolatey
choco list --local-only
```

### Output Log
```
PS C:\Users\vagrant> choco list --local-only --debug --verbose                                                                  
Chocolatey v0.10.11                                                                                                             
Chocolatey is running on Windows v 10.0.17134.0                                                                                 
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".                                                            
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".                                                            
Command line: "C:\ProgramData\chocolatey\choco.exe" list --local-only --debug --verbose                                         
Received arguments: list --local-only --debug --verbose                                                                         
RemovePendingPackagesTask is now ready and waiting for PreRunMessage.                                                           
Sending message 'PreRunMessage' out if there are subscribers...                                                                 
[Pending] Removing all pending packages that should not be considered installed...                                              
The source '' evaluated to a 'normal' source type                                                                               

NOTE: Hiding sensitive configuration data! Please double and triple                                                             
 check to be sure no sensitive data is shown, especially if copying                                                             
 output to a gist for review.                                                                                                   
Configuration: CommandName='list'|                                                                                              
CacheLocation='C:\Users\vagrant\AppData\Local\Temp\chocolatey'|                                                                 
ContainsLegacyPackageInstalls='True'|                                                                                           
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|                                                            
SourceType='normal'|Debug='True'|Verbose='True'|Trace='False'|                                                                  
Force='False'|Noop='False'|HelpRequested='False'|                                                                               
UnsuccessfulParsing='False'|RegularOutput='True'|QuietOutput='False'|                                                           
PromptForConfirmation='True'|AcceptLicense='False'|                                                                             
AllowUnofficialBuild='False'|AllVersions='False'|                                                                               
SkipPackageInstallProvider='False'|Prerelease='False'|ForceX86='False'|                                                         
OverrideArguments='False'|NotSilent='False'|                                                                                    
ApplyPackageParametersToDependencies='False'|                                                                                   
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|                                                         
AllowMultipleVersions='False'|AllowDowngrade='False'|                                                                           
ForceDependencies='False'|Information.PlatformType='Windows'|                                                                   
Information.PlatformVersion='10.0.17134.0'|                                                                                     
Information.PlatformName='Windows Server 2016'|                                                                                 
Information.ChocolateyVersion='0.10.11.0'|                                                                                      
Information.ChocolateyProductVersion='0.10.11'|                                                                                 
Information.FullName='choco, Version=0.10.11.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|                              

Information.Is64BitOperatingSystem='True'|                                                                                      
Information.Is64BitProcess='True'|Information.IsInteractive='False'|                                                            
Information.UserName='vagrant'|                                                                                                 
Information.UserDomainName='WIN-UVRN8896TGT'|                                                                                   
Information.IsUserAdministrator='True'|                                                                                         
Information.IsUserSystemAccount='False'|                                                                                        
Information.IsUserRemoteDesktop='False'|                                                                                        
Information.IsUserRemote='True'|                                                                                                
Information.IsProcessElevated='True'|                                                                                           
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|                                                           
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|                                                                  
Features.AllowEmptyChecksums='False'|                                                                                           
Features.AllowEmptyChecksumsSecure='True'|                                                                                      
Features.FailOnAutoUninstaller='False'|                                                                                         
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|                                                         
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|                                                         
Features.VirusCheck='False'|                                                                                                    
Features.FailOnInvalidOrMissingLicense='False'|                                                                                 
Features.IgnoreInvalidOptionsSwitches='True'|                                                                                   
Features.UsePackageExitCodes='True'|                                                                                            
Features.UseFipsCompliantChecksums='False'|                                                                                     
Features.ShowNonElevatedWarnings='True'|                                                                                        
Features.ShowDownloadProgress='True'|                                                                                           
Features.StopOnFirstPackageFailure='False'|                                                                                     
Features.UseRememberedArgumentsForUpgrades='False'|                                                                             
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|                                                                        
Features.RemovePackageInformationOnUninstall='False'|                                                                           
Features.ScriptsCheckLastExitCode='False'|ListCommand.LocalOnly='True'|                                                         
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|                                                         
ListCommand.PageSize='25'|ListCommand.Exact='False'|                                                                            
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|                                                                     
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|                                                         
ListCommand.ApprovedOnly='False'|                                                                                               
ListCommand.DownloadCacheAvailable='False'|                                                                                     
ListCommand.NotBroken='False'|                                                                                                  
ListCommand.IncludeVersionOverrides='False'|                                                                                    
UpgradeCommand.FailOnUnfound='False'|                                                                                           
UpgradeCommand.FailOnNotInstalled='False'|                                                                                      
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|                                                                             
UpgradeCommand.ExcludePrerelease='False'|                                                                                       
NewCommand.AutomaticPackage='False'|                                                                                            
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|                                                         
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|                                                                   
SourceCommand.AllowSelfService='False'|                                                                                         
SourceCommand.VisibleToAdminsOnly='False'|                                                                                      
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|                                                               
PinCommand.Command='unknown'|OutdatedCommand.IgnorePinned='False'|                                                              
Proxy.BypassOnLocal='True'|                                                                                                     
_ Chocolatey:ChocolateyListCommand - Normal Run Mode _                                                                          
Unable to search for packages when there are no sources enabled for                                                             
 packages and none were passed as arguments.                                                                                    
Sending message 'PostRunMessage' out if there are subscribers...                                                                
Exiting with 1 
```

**Comment by ferventcoder** [comment] 2018-11-06 13:34
Duplicate of #661

**Closed by ferventcoder** 2018-11-06 13:34 UTC
Labels: Duplicate Issue

**Comment by ferventcoder** [comment] 2018-11-06 13:37
Hi @jborean93, definitely agree that this behavior is not wanted. It's something we'll need to correct. Please follow #661 for updates as I marked this a duplicate of that.

**Comment by jborean93** [comment] 2018-11-06 19:29
Thanks @ferventcoder, I mustn't have looked hard enough for an existing ticket.
