### ISSUE TITLE
choco cli options missing in wiki and help function.

### ISSUE THREAD

**Issue by jgoldsteindev** [chocolatey/choco#472] opened 2015-10-27 17:34 UTC
had to ask in the chat how to get the chocolatey version number, which is '-v'. This option, and likely others, are not mentioned anywhere in the wiki or cli help function.

**Comment by i-give-up** [comment] 2015-10-30 09:51
The following outputs chocolatey's version

    choco -v

whereas the following runs the command in verbose mode

    choco 〈command〉 -v

In view of this, how should the `-v` option be explained? Currently when you run `choco -h`, it has this

    -v, --verbose
        Verbose - See verbose messaging

**Comment by TheCakeIsNaOH** [comment] 2022-01-20 18:02
Duplicate of https://github.com/chocolatey/choco/issues/2049

**Closed** 2022-01-20 18:09 UTC
Labels: Up For Grabs, 0 - Backlog, Duplicate Issue, Documentation

**Comment by TheCakeIsNaOH** [comment] 2022-02-04 14:21
Removing from milestone as a duplicate
