### ISSUE TITLE
Choco fails to run after Windows 11 update to (OS Build 22581.1)

### ISSUE THREAD

**Issue by Claustn** [chocolatey/choco#2658] opened 2022-03-24 16:15 UTC
### What You Are Seeing?

After upgrading to Windows 11 22H2 (OS Build 22581.1)
I was unable to run any chocolatey commands it failed with 

```
C:\Windows\System32>choco upgrade chocolatey
Chocolatey v1.0.0 Business
The registered delegate for type IEnumerable<ICommand> threw an exception. Could not load type 'chocolatey.infrastructure.app.commands.ChocolateyVersionCommand' from assembly 'choco, Version=1.0.0.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'.
```
This occurred for all choco commands I tried to run, I tested from both CMD  and Windows terminal

### What is Expected?

That Choco.exe does not fail to execute

### How Did You Get This To Happen? (Steps to Reproduce)

Installed Windows 11 Update, I have had to manually install the 1.0.1 chocolatey in order to get Choco to work again. 

### Output Log
 System.TypeLoadException: Could not load type 'chocolatey.infrastructure.app.commands.ChocolateyVersionCommand' from assembly 'choco, Version=1.0.0.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'.
   at chocolatey.licensed.infrastructure.app.registration.ContainerBinding.#=zwhS3jHbI_7u7JAoHw3YF$A0=.#=zs$Phz8xsnNeFYOpYuw==()
   at DynamicInstanceProducer14.GetInstance(Object[] constants)
   at SimpleInjector.CompilationHelpers.<>c__DisplayClass1b`1.<CompileInDynamicAssemblyAsClosure>b__1a()
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistrationBase`1.CreateInstanceWithNullCheck()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistrationBase`1.BuildExpression()
   at SimpleInjector.Registration.BuildExpression(InstanceProducer producer)
   at SimpleInjector.InstanceProducer.BuildExpressionInternal()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at SimpleInjector.InstanceProducer.BuildInstanceCreator()
   at SimpleInjector.InstanceProducer.GetInstance()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.Container.GetInstance[TService]()
   at chocolatey.infrastructure.app.runners.GenericRunner.find_command(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
2022-03-24 15:07:45,072 31460 [DEBUG] - Exiting with 1
2022-03-24 15:07:53,321 22552 [DEBUG] - XmlConfiguration is now operational
2022-03-24 15:07:53,336 22552 [DEBUG] - Evaluating license file found at 'C:\ProgramData\chocolatey\license\chocolatey.license.xml'
2022-03-24 15:07:54,935 22552 [DEBUG] - Loading Licensed Extensions and Commands
-->

<details>
<summary>

```
2022-03-24 16:38:00,180 21180 [INFO ] - ============================================================
2022-03-24 16:38:00,516 21180 [INFO ] - Chocolatey v1.0.0 Business
2022-03-24 16:38:02,917 21180 [ERROR] - The registered delegate for type IEnumerable<ICommand> threw an exception. Could not load type 'chocolatey.infrastructure.app.commands.ChocolateyVersionCommand' from assembly 'choco, Version=1.0.0.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'.
2022-03-24 16:38:02,920 21180 [ERROR] - More Details: SimpleInjector.ActivationException: The registered delegate for type IEnumerable<ICommand> threw an exception. Could not load type 'chocolatey.infrastructure.app.commands.ChocolateyVersionCommand' from assembly 'choco, Version=1.0.0.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'. ---> System.TypeLoadException: Could not load type 'chocolatey.infrastructure.app.commands.ChocolateyVersionCommand' from assembly 'choco, Version=1.0.0.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'.
   at chocolatey.licensed.infrastructure.app.registration.ContainerBinding.#=zwhS3jHbI_7u7JAoHw3YF$A0=.#=zs$Phz8xsnNeFYOpYuw==()
   at DynamicInstanceProducer14.GetInstance(Object[] constants)
   at SimpleInjector.CompilationHelpers.<>c__DisplayClass1b`1.<CompileInDynamicAssemblyAsClosure>b__1a()
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistrationBase`1.CreateInstanceWithNullCheck()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistrationBase`1.BuildExpression()
   at SimpleInjector.Registration.BuildExpression(InstanceProducer producer)
   at SimpleInjector.InstanceProducer.BuildExpressionInternal()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at SimpleInjector.InstanceProducer.BuildInstanceCreator()
   at SimpleInjector.InstanceProducer.GetInstance()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.Container.GetInstance[TService]()
   at chocolatey.infrastructure.app.runners.GenericRunner.find_command(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
```
</summary>

<p>

~~~sh
PLACE LOG CONTENT HERE - WE NEED _ALL_ DETAILED OUTPUT BASED ON THE ABOVE TO BE ABLE TO PROVIDE SUPPORT (YOU WILL FIND THAT IN THE $env:ChocolateyInstall\logs\chocolatey.log between the `=====`)
~~~

</p>

</details>

As stated above manually upgrading Chocolatey to version 1.0.1 fixed the issues for me, just wanted to raise awareness if other people come across the issue as well

**Comment by gep13** [comment] 2022-03-24 17:11
I am going to close this issue, since this is really a duplicate of the one that I have linked to.

**Closed by gep13** 2022-03-24 17:11 UTC
Labels: Duplicate Issue
