### ISSUE TITLE
ShimGen is slow, it should be replaced

### ISSUE THREAD

**Issue by ImportTaste** [chocolatey/choco#2536] opened 2022-01-18 17:47 UTC
This is something I noticed when installing the sysinternals package. It takes choco a decent chunk of time to generate all the shims. What's more, since ShimGen is essentially initializing a .NET command line app in the background to accomplish what it does, which is much slower than running the executable it's pointing to directly.

ShimGen is a closed source project so it can't be readily modified, right? I propose switching to something based off this project: https://github.com/71/scoop-better-shimexe

Don't let the name fool you, while it's originally intended for scoop, it has no reliance on it whatsoever. I've been using these shims for a while and don't even have scoop installed on my machine.

It's MIT licensed so there shouldn't be any issue in using this or some sort of derivative if need be.

**Comment by TheCakeIsNaOH** [comment] 2022-01-18 18:04
> This is something I noticed when installing the sysinternals package. It takes choco a decent chunk of time to generate all the shims. 

This part is a duplicate of https://github.com/chocolatey/shimgen/issues/47

> ShimGen is a closed source project so it can't be readily modified, right?

Correct, https://github.com/chocolatey/shimgen/blob/master/README.md

>  I propose switching to something based off this project: 

I'm working on a drop in replacement: https://github.com/chocolatey/choco/issues/2174

**Closed** 2022-01-18 18:14 UTC
