### ISSUE TITLE
chocolateyinstall.ps1 no longer allows Read-Host

### ISSUE THREAD

**Issue by The1nternet** [chocolatey/choco#239] opened 2015-04-11 15:23 UTC
Hi, we use "Read-Host" in chocolateyinstall.ps1 in all of our packages, but it no longer works as of 9.9.4.  Read-Host is a powershell command for reading input from the user.  
After updating to chocolatey 9.9.4, whenever the chocolateyinstall.ps1 gets to the Read-Host line, it stops (waiting for user input) but doesn't allow any keyboard input, thereby never getting past the Read-Host line. 
URGENT!

**Comment by ferventcoder** [comment] 2015-04-11 15:31
Duplicate of #219

**Closed by ferventcoder** 2015-04-11 15:31 UTC
Labels: Duplicate Issue
