### ISSUE TITLE
Cannot execute cpack agains a nuspec in the current directory

### ISSUE THREAD

**Issue by alanstevens** [chocolatey/choco#233] opened 2015-04-08 14:40 UTC
Current behavior:
If I am in a directory PackageName, and I execute cpack PackageName.nuspec, I receive the error "The path is not of legal form."

ExpectedBehavior:
The nupkg file is created in the current directory.

Note;
The previous behavior matched the expected behavior

Workaround:
execute cpack .\PackageName.nuspec

**Comment by ferventcoder** [comment] 2015-04-08 19:30
This is already logged

**Comment by ferventcoder** [comment] 2015-04-08 19:31
Duplicate of #164

**Closed by ferventcoder** 2015-04-08 19:31 UTC
