### ISSUE TITLE
Upgrade all - All option is not working

### ISSUE THREAD

**Issue by Mrks83** [chocolatey/choco#2913] opened 2022-11-22 09:37 UTC
### What You Are Seeing?

_"All"_ does not work any more and is similar to _"yes"_. Thus choco prompts for every package, 

### What is Expected?

Only one prompt.

### How Did You Get This To Happen? (Steps to Reproduce)

```
> choco upgrade all
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): a 
``` 

### System Details

* OS Build: 10.0.19045.0
* Windows PowerShell version: 7.2.7
* Chocolatey version: 1.2.0

**Comment by pauby** [comment] 2022-11-22 12:41
This is a duplicate of #2872.

**Closed by pauby** 2022-11-22 12:41 UTC
