### ISSUE TITLE
'choco install --version MAJOR.MINOR' installs MAJOR.MINOR.0 instead of latest patch

### ISSUE THREAD

**Issue by bergmeister** [chocolatey/choco#1874] opened 2019-07-05 09:26 UTC
I know that chocolatey does not support semantic versioning as per issue #1610 but despite that I'd still expect that chocolatey picks the latest patched version when the patch version is not specified.

Example: `choco install kubernetes-cli --version=1.14`
Expected: Installs version `1.14.3`, which is the latest patched version.
Actual: Installs `1.14.0`.

**Comment by AdmiringWorm** [comment] 2019-07-05 13:36
I would say that is expected.
After all the version `1.14` is equal to `1.14.0`. At least in terms of chocolatey.

**Comment by bergmeister** [comment] 2019-07-05 13:45
If I specified `1.14.0` explicitly, yes, but the expectation is that if the full version is not specified the latest patched version is used. Especially for patches, they are by definition not breaking and therefore in the majority of the cases the users wants to use the latest patched version and in terms of security best practices, chocolatey should recommend this as well.

**Comment by AdmiringWorm** [comment] 2019-07-05 17:14
> I disagree, ff I specified 1.14.0 explicitly, yes, but the expectation is that if the full version is not specified the latest patched version is used.

A full version would be a 4 part version, meaning that you would have needed to specify `1.14.0.0` to get the actual version (yes, there are plenty of softwares still using all 4 parts).

> Especially for patches, they are by definition not breaking and therefore in the majority of the cases the users wants to use the latest patched version and in terms of security best practices, chocolatey should recommend this as well.

That is only true if the software actually follows semver, I have seen plenty of softwares that do not. Which adds breaking changes both in minor, patch and build versions.

> I am not sure what the behaviour is in terms of minor version, I suppose for the minor version one should either apply the same or explicitly ask the user but the behaviour for patches is much less debatable IMHO

If going by the semver v2, then minor releases should also be non-breaking. The only accepted (after v 1.0) to include breaking changes is major releases (1.0, 2.0, 3.0, etc), however as I mentioned before not all software developers follow semver v2 (or even v1)

But lets get back on topic, as I already mentioned. The version `1.14` is equal to `1.14.0`, and I believe this is not something that will likely change, and is also how other package managers I have used handles versioning (both on windows, and on linux).
I could be wrong though, I am not a part of the team that maintains choco itself (or even any of the available chocolatey software)

Now, with this said, I would love to see a way to specify a version range that you would want to install (for instance similar to how npm/yarn do this. Using the format `^1.4.0` would typically install the latest minor version, and `~1.4.0` would typically install the latest patch version available).

Allowing version ranges is tracked over here though (but with a different format): https://github.com/chocolatey/choco/issues/800

**Comment by ferventcoder** [comment] 2019-07-06 14:21
Chocolatey supports semver 1, so just wanted to clear that up. 👍

**Comment by ferventcoder** [comment] 2019-07-06 14:23
Chocolatey does not support calling part of a version on the command line and having it find the latest in that range. So it is correct that if you call for 1.14, that is equal to 1.14.0 and 1.14.0.0, thus that is what you should get back, not 1.14.2. Bumping to support SemVer2 won't chamge that aspect.

**Comment by ferventcoder** [comment] 2019-07-06 14:25
Duplicate of #800

**Closed by ferventcoder** 2019-07-06 14:25 UTC

**Comment by ferventcoder** [comment] 2019-07-06 14:29
@bergmeister from what you described, this sounds like #800. If you believe it is different, please let me know. Otherwise please subscribe to that issue. This issue is now linked to that one as well so the conversation here will be take  into account when that is worked on. 👍

**Comment by bergmeister** [comment] 2019-07-06 14:55
Ok, thanks for the feedback and the provided details :-)
