### ISSUE TITLE
Windows feature as a package dependency should be resolved as ordinary package

### ISSUE THREAD

**Issue by 6opuc** [chocolatey/choco#1091] opened 2016-12-15 09:28 UTC
If package has dependency on some windows feature(for example: IIS-WebServerRole) then "choco install" of that package would fail with error message: unable to resolve dependency 'windows feature name'.

If windows feature dependencies were resolved as ordinary packages it would be much easier to deploy software with dependencies on windows features.

**Comment by ferventcoder** [comment] 2016-12-16 08:56
A package could be created that interacts with a particular Windows feature, so then it would be a 1:1 kind of relationship.

However this could be interesting. I thought we already had tickets to address special types as dependencies.

**Comment by ansariwn** [comment] 2018-04-17 15:49
Is there any movement on this enhancement? Would like to know how best to manage windows feature dependencies in the meantime.

**Comment by gep13** [comment] 2022-01-31 13:56
This request is likely a duplicate of this one: https://github.com/chocolatey/choco/issues/879

**Comment by gep13** [comment] 2022-01-31 13:58
Closing this issue as a duplicate, as the original has more discussion about what is required.

**Closed by gep13** 2022-01-31 13:58 UTC
Labels: Duplicate Issue
