### ISSUE TITLE
Command `choco list` should list local packages when called with no parameters

### ISSUE THREAD

**Issue by vexx32** [chocolatey/choco#1701] opened 2019-01-03 02:44 UTC
Disclaimer: I am a casual user who frequently forgets I have chocolatey installed.

As such a casual user, when I remember I have Chocolatey installed, I enjoy being able to update the packages I have installed without manually going and figuring out where they came from myself.

However, it seems strangely obtuse to figure out how to just _list the packages I have installed_. Most package managers I've dabbled in tend to assume that when I look for a list of packages, I generally want to look at already-installed packages _first_. 

Chocolatey does not. If you call `choco list` with no other parameters, it assumes you want every single possible package that is available. I have never wanted this, not even once. Were I to want it, I would expect that a call such as `choco list *` _would_ have this behaviour. 

Instead, I have to muddle through the help screens until I stumble across `--local-only`. So it's about twice as many keystrokes just to get at a list of things I have installed. What is the motivation for this?

I genuinely am having difficulty understanding why it's preferable behaviour to bog down the package servers with a "give me all packages" request as the _default behaviour_ of calling `choco list`. If there is a reason, please enlighten me. 😄

**Comment by ferventcoder** [comment] 2019-01-03 17:15
Duplicate of #158

**Comment by ferventcoder** [comment] 2019-01-03 17:16
FWIW I completely agree with your thoughts. This behavior was inherited by the way that NuGet works. Please see #158 for where this is going to be added as it is a breaking change.

**Closed by ferventcoder** 2019-01-03 17:15 UTC
