### ISSUE TITLE
Select and Monitor Installation Path For Portables

### ISSUE THREAD

**Issue by zero77** [chocolatey/choco#1360] opened 2017-07-13 16:16 UTC
When initially installing portable applications can you add an option for a default path, that will then be used when updating the application.
Thanks

**Comment by ferventcoder** [comment] 2017-07-13 18:26
You mean like in the package directory or outside? We have a ChocolateyToolsFolder, however there are benefits to keeping a portable in the packaging folder that are not realized when it is put outside of there.

**Comment by ferventcoder** [comment] 2017-07-13 18:27
Here is the considerations in much more detail - https://github.com/chocolatey/choco/issues/1303#issuecomment-303804561

**Comment by zero77** [comment] 2017-07-13 21:44
so something like this ?

`choco install sysinternals Install-ChocolateyPath -PathToInstall "C:\Users\User\Desktop\TEST"`

**Comment by ferventcoder** [comment] 2017-07-13 23:55
The comment I pointed you to was from the perspective of the creation of the package.

**Comment by ferventcoder** [comment] 2017-07-13 23:56
We are looking at adding an installation directory override in the licensed edition to match what we do for installers.

**Comment by ferventcoder** [comment] 2017-07-13 23:56
That might match closer with what you are looking to do?

**Comment by zero77** [comment] 2017-07-14 09:44
Ok, I see so it’s not currently supported.
Yes, a directory over right is what I am looking for.
Thanks

**Comment by joyliao** [comment] 2017-07-14 10:02
2017年7月14日 下午5:44，"zero77" <notifications@github.com>寫道：

Ok, I see so it’s not currently supported.
Yes, a directory over right is what I am looking for.
Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/chocolatey/choco/issues/1360#issuecomment-315318504>,
or mute the thread

**Comment by stevenwdv** [comment] 2021-04-16 10:49
Is it currently possible to set the installation path for portable tools? I like to have them all in `C:\prog` but setting `$env:ChocolateyToolsLocation` does not seem to do anything as it still installs to `C:\ProgramData\chocolatey\lib`.

**Comment by TheCakeIsNaOH** [comment] 2021-04-16 13:10
@stevenwdv Yes, it is, possible. 

However, the package itself will still always install to `$env:ChocolateyInstall\lib\<package name>`.

So you need to add a `chocolateyinstall.ps1` and manually copy over the required files to `$env:ChocolateyToolsLocation`, or unzip to there if the software comes in an archive.

**Comment by stevenwdv** [comment] 2021-04-16 14:34
@TheCakeIsNaOH Ok but is it also possible with an existing `chocolateyinstall.ps1` of a portable utility? E.g. https://community.chocolatey.org/packages/cports does not seem to do this, does it?

**Comment by TheCakeIsNaOH** [comment] 2021-04-16 14:41
Correct, it does not have that ability. You would have to ask the maintainer to allow selection of the install location, or wait for this feature to be implemented in the licensed editions as mentioned above and then purchase a license. 
https://github.com/chocolatey/chocolatey-licensed-issues/issues/7

**Comment by stevenwdv** [comment] 2021-04-16 16:51
@TheCakeIsNaOH That's a pity... I guess I could use symlinks and stuff instead.. Any particular reason why this will only be in the licensed version? It seems like a pretty easy function to implement.
By the way, am I misunderstanding what this current issue is for or is it the same feature?

**Comment by TheCakeIsNaOH** [comment] 2021-04-16 16:56
>  Any particular reason why this will only be in the licensed version? It seems like a pretty easy function to implement.

🤷, perhaps because the licensed version already has an override for installers.

@ferventcoder would be the one answer that.

> By the way, am I misunderstanding what this current issue is for or is it the same feature?

I think this issue is for a very similar feature. So it will definitely go into the licensed edition at some point, and it might go into open source as well at some point, but that is undecided as this still has the `triaging` tag.

**Comment by ferventcoder** [comment] 2021-08-04 14:38
>  It seems like a pretty easy function to implement.

While some part of this could be easy to implement, there are a whole list of things that Chocolatey does (shimming, calls to items expected to be in a particular folder, etc) that does not make this as easy as most folks might think. 


After much review and thought, this feels like the same feature that was tagged for licensed editions (Pro+).

**Comment by ferventcoder** [comment] 2021-08-04 14:38
Duplicate of https://github.com/chocolatey/chocolatey-licensed-issues/issues/7

**Closed by ferventcoder** 2021-08-04 14:38 UTC
Labels: Duplicate Issue, Pro/Business
