### ISSUE TITLE
Uninstall-ChocolateyPackage: 'file' argument ignored?

### ISSUE THREAD

**Issue by sergey-s-betke** [chocolatey/choco#881] opened 2016-07-28 11:02 UTC
### What You Are Seeing?

for msi **`$file`** argument ignored!:

```
 if ($fileType -like 'msi') {
    $msiArgs = "/x" 
    if ($overrideArguments) { 
      $msiArgs = "$msiArgs $additionalInstallArgs";
      write-host "Overriding package arguments with `'$additionalInstallArgs`'";
    } else {
      $msiArgs = "$msiArgs $silentArgs $additionalInstallArgs";
    }

    Start-ChocolateyProcessAsAdmin "$msiArgs" 'msiexec' -validExitCodes $validExitCodes
  }
```

Where is `$file` helper argument?

`chocolateyUninstall.ps1` example:

```
    Uninstall-ChocolateyPackage `
        -packageName $env:chocolateyPackageName `
        -installerType msi `
        -silentArgs "$( ( Get-Item -Path ( Join-Path -Path ( Split-Path -Parent $PSCommandPath ) -ChildPath '*.msi' ) )[0].FullName ) /quiet /qn  /norestart" `
        -file ( ( Get-Item -Path ( Join-Path -Path ( Split-Path -Parent $PSCommandPath ) -ChildPath '*.msi' ) )[0].FullName ) `
        -validExitCodes @(0, 3010, 1641) `
    ;
```
### What is Expected?

```
 if ($fileType -like 'msi') {
    $msiArgs = "/x $file" 
    if ($overrideArguments) { 
      $msiArgs = "$msiArgs $additionalInstallArgs";
      write-host "Overriding package arguments with `'$additionalInstallArgs`'";
    } else {
      $msiArgs = "$msiArgs $silentArgs $additionalInstallArgs";
    }

    Start-ChocolateyProcessAsAdmin "$msiArgs" 'msiexec' -validExitCodes $validExitCodes
  }
```

`chocolateyUninstall.ps1` example:

```
    Uninstall-ChocolateyPackage `
        -packageName $env:chocolateyPackageName `
        -installerType msi `
        -silentArgs "/quiet /qn  /norestart" `
        -file ( ( Get-Item -Path ( Join-Path -Path ( Split-Path -Parent $PSCommandPath ) -ChildPath '*.msi' ) )[0].FullName ) `
        -validExitCodes @(0, 3010, 1641) `
    ;
```

**Comment by ferventcoder** [comment] 2016-07-28 20:17
Run `choco new` when creating packages. You will see how it tells you about `$file` not being used.

**Comment by sergey-s-betke** [comment] 2016-07-30 10:34
No, no, no :-) In template:

    [array]$key = Get-ItemProperty -Path @($machine_key6432,$machine_key, $local_key) `
                            -ErrorAction SilentlyContinue `
             | ? { $_.DisplayName -like "$softwareName" }

    if ($key.Count -eq 1) {
      $key | % { 
        $file = "$($_.UninstallString)"

        if ($installerType -eq 'MSI') {
          # The Product Code GUID is all that should be passed for MSI, and very 
          # FIRST, because it comes directly after /x, which is already set in the 
          # Uninstall-ChocolateyPackage msiargs (facepalm).
          $silentArgs = "$($_.PSChildName) $silentArgs"

          # Don't pass anything for file, it is ignored for msi (facepalm number 2) 
          # Alternatively if you need to pass a path to an msi, determine that and 
          # use it instead of the above in silentArgs, still very first
          $file = ''
        }

        Uninstall-ChocolateyPackage -PackageName $packageName `
                                    -FileType $installerType `
                                    -SilentArgs "$silentArgs" `
                                    -ValidExitCodes $validExitCodes `
                                    -File "$file"
      }
    } elseif ($key.Count -eq 0) {
      Write-Warning "$packageName has already been uninstalled by other means."
    } elseif ($key.Count -gt 1) {
      Write-Warning "$key.Count matches found!"
      Write-Warning "To prevent accidental data loss, no programs will be uninstalled."
      Write-Warning "Please alert package maintainer the following keys were matched:"
      $key | % {Write-Warning "- $_.DisplayName"}
    }

But `$file` argument does not used in `Uninstall-ChocolateyPackage.ps1`!

**Comment by sergey-s-betke** [comment] 2016-07-30 10:36
In template You add product GUID to `$silentArgs`. Why? Why not to other specialized for product GUID argument?

**Comment by ferventcoder** [comment] 2016-08-01 13:33
Note the word "facepalm" twice in the comments. I didn't originally write the script, it came in from another committer. 

~~~powershell
      # The Product Code GUID is all that should be passed for MSI, and very 
      # FIRST, because it comes directly after /x, which is already set in the 
      # Uninstall-ChocolateyPackage msiargs (facepalm).
      $silentArgs = "$($_.PSChildName) $silentArgs"
~~~

The important thing to note is that it does instruct you how to pass the file path. First argument in $silentArgs, but without `/x`.

~~~powershell
          # Don't pass anything for file, it is ignored for msi (facepalm number 2) 
          # Alternatively if you need to pass a path to an msi, determine that and 
          # use it instead of the above in silentArgs, still very first
~~~

Since it ***is*** just templated output, you can change it. So for a workaround for now, 

~~~powershell
# do not use /x, it is already part of the msiexec args.
$silentArgs = "$file $silentArgs"
~~~

**Comment by sergey-s-betke** [comment] 2016-08-01 22:47
Yes, I use in https://chocolatey.org/packages/font.gost2.304-81.install `$silentArgs = "$file $silentArgs"`...

I think, `$file` must be added with `/x` to msiexec parameters in `Uninstall-ChocolateyPackage.ps1`. For `ProductGUID` (after `/x` we can write msi file path or `ProductGUID`) - other parameter, may be.

**Comment by ferventcoder** [comment] 2016-08-02 17:36
I believe the instructions state that when it is MSI, the `/x` is already added.

**Comment by sergey-s-betke** [comment] 2016-08-02 18:33
@ferventcoder , there is **TWO** variants to select msi for uninstall:

- `/x msi_file_path`
- `/x ProductGUID`

from `msiexec /?` :-)...

**Comment by ferventcoder** [comment] 2016-08-03 03:28
@sergey-s-betke I understand this. I think we are saying the same thing. 

When you call Uninstall-ChocolateyPackage, and you pass MSI, `$silentArgs` are set like this:

`msiexec /x $silentArgs`

So don't pass `/x` as part of the silent args and ensure you pass silent args with `$file` as I mentioend above.

`$silentArgs = "$file other args here"` (but don't pass `/x` or you will get `msiexec /x /x filepath`).

**Comment by ferventcoder** [comment] 2016-08-03 03:31
Actually, I now we are stating the same thing, as I just read and reunderstood what you were stating with font.gost2.304-81.install.

**Comment by petermbauer** [comment] 2017-02-17 12:07
I also came across this issue and had to add the filename of the .msi to the silentArgs parameter as a workaround. Would be great if this would be fixed, especially since i had to add write a chocolateyBeforeModify.ps1 for my packages using the Uninstall-ChocolateyPackage to uninstall the old version of the .msi on choco upgrade.
Is there a chance to change the irritating behaviour of not running the auto uninstaller for the old package when upgrading to a new version?

**Comment by ferventcoder** [comment] 2017-03-03 16:44
Let's close this as a duplicate of https://github.com/chocolatey/choco/issues/229

**Closed by ferventcoder** 2017-03-03 16:44 UTC
Labels: 0 - Backlog, Bug, Up For Grabs

**Comment by TheCakeIsNaOH** [comment] 2022-02-04 14:19
Removing from milestone as a duplicate of #229
