### ISSUE TITLE
new - Allow creating of packages with a template at an arbitrary location

### ISSUE THREAD

**Issue by JurjenBiewenga** [chocolatey/choco#1637] opened 2018-09-06 08:06 UTC
We have a custom build pipeline for our internal applications that we would like to automatically create packages and push them to our internal Chocolatey feed. These applications can have custom installation steps or dependencies, these requirements would work together with templates great as these do not tend to change often. However as templates are only allowed to live in the chocolatey/templates folder this creates an issue as we can't easily include the template in our source control nor is it easy to find/edit for developers.

My proposal is to allow paths in template parameter of the `new` command, this would allow you to have templates at different locations as following:

`choco new -t testtemplate` would find the template `%programdata%/chocolatey/templates/testtemplate`
`choco new -t "C:/testtemplate"` would find the template `c:/testtemplate`
`choco new -t "./testtemplate"` would find the template relative to the current directory

**Comment by gep13** [comment] 2018-09-06 08:13
Ok, I see what you are saying, but just to confirm one thing...

Have you thought about putting your templates into a Chocolatey Package?  This would allow you to do:

`choco install myproject.template`

Which would then place the template files (contained within the package) into the correct location.  Then, when you need to make a change to the template, you make the change in source control, build the template Chocolatey package, and then you would be able to do:

`choco upgrade myproject.template`

I just want to make sure that this wouldn't fit in with your workflow before going any further.

**Comment by gep13** [comment] 2018-09-06 08:44
@JurjenBiewenga let's wait to get some feedback from the rest of the team first, and then we can discuss implementation details.

//cc @ferventcoder @pauby

**Comment by pauby** [comment] 2018-09-06 09:11
>  force us to run some sort of setup after checking out a repository to get the required templates.

@JurjenBiewenga are you not running a setup before you start the 'build' process in the pipeline, anyway? It's fairly standard practice.

> We could install all templates always however this would result in a lot of unused templates for most developers in our team.

Why would this be an issue - I can only think of disk space being an issue with unused templates but as they are so small it shouldn't be an issue so I'd like to understand what issue it's causing?

Are you talking about building your agents with all the templates and then referencing them with the `choco new` command?

> choco new -t "C:/testtemplate" would find the template c:/testtemplate

I feel it would fit better with the way choco.exe does things to have `choco new -t 'testtemplate' --templateDir 'c:\'` if we were to go forward?

**Comment by pauby** [comment] 2018-09-06 09:27
> Clutter, however this is less of an issue if we put the templates in the project folder then create a package from it that is automatically installed. However this still isn't our preferred solution.

Yeah, I get that. We all work differently but it's not a showstopper to do it this way, at least for the time being?

> We could let our buildtool update the template package however we really do not like this solution as it contains project specific data and it would be a hassle to edit the templates and then create a new package from it before you can build.

I was thinking more along the lines of bundling your templates into a Chocolatey package and then using the build tool to install that package before it does it's build so the templates are available when the build starts? Or am I misunderstanding?

**Comment by JurjenBiewenga** [comment] 2018-09-06 09:30
>Yeah, I get that. We all work differently but it's not a showstopper to do it this way, at least for the time being?

Possibly, however we'd probably rather do our own simple template system by copying it ourselves and insert the data we need.

>I was thinking more along the lines of bundling your templates into a Chocolatey package and then using the build tool to install that package before it does it's build so the templates are available when the build starts? Or am I misunderstanding?

The issue is that you might want to change the template before building which will require you to then make a new package and push that to the feed.

**Comment by ferventcoder** [comment] 2018-09-26 03:06
@JurjenBiewenga this is something that might have already been on the backlog here - I definitely like the use case of pointing to a relative or absolute path for templates.

**Comment by ferventcoder** [comment] 2018-09-26 03:09
Duplicate of #1477

**Comment by ferventcoder** [comment] 2018-09-26 03:10
This is a duplicate of #1477, which already has a PR associated with it. Apologies we were not quicker in triaging that there was an already existing issue. Let's move discussion over there.

**Closed by ferventcoder** 2018-09-26 03:09 UTC
Labels: 0 - _Triaging, Enhancement
