### ISSUE TITLE
[Request] Support Deep link

### ISSUE THREAD

**Issue by Omzig** [chocolatey/choco#1749] opened 2019-03-12 18:00 UTC
Is there any way to extend choco to accept a deep link?

If you notice the url inside the install button on this site: https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview

it uses vscode:action/item

Maybe this is an enhancement request to create a new Chocolatey package called Chocolatey Deep Link or something. or enhance the chocolatey gui to accept the deep link, not sure where it needs to go.

but it would be nice to do something like this:

choco:install/adobereader/y

**Comment by gep13** [comment] 2019-03-12 18:30
@Omzig thanks for opening this issue, however, this is essentially a duplicate of this issue:

https://github.com/chocolatey/choco/issues/1680

As you will see in that issue, @bcurran3 has created an unofficial implementation of this functionality, which will likely make it's way into the choco cli at some point, but there are no estimates on when this might happen.

As such, I am going to close this issue.

**Closed by gep13** 2019-03-12 18:30 UTC
Labels: Duplicate Issue
