### ISSUE TITLE
When a prerelease is installed, it should upgrade to latest prerelease unless excluded - typically seen in choco upgrade all

### ISSUE THREAD

**Issue by ScottRFrost** [chocolatey/choco#686] opened 2016-04-11 14:10 UTC
If you do "choco upgrade all -y" and it encounters a package that's newer than newest, perhaps it should check prerelease or at least offer to do so.

Current: 
`chocolatey v0.9.10-beta-20160402 is newer than the most recent.`

Proposed:
`chocolatey v0.9.10-beta-20160402 is newer than the most recent. Would you like to check prereleases for chocolatey? [y] [n]`

**Comment by ferventcoder** [comment] 2016-04-11 14:20
In the case of automated unattended scripts, how do you see it working?

**Comment by ScottRFrost** [comment] 2016-04-11 14:37
Well, it would be dangerous to ever run "choco upgrade all -y -pre" because then it would upgrade ALL of your stuff to prerelease versions.  Perhaps you could add a flag "-includepre" or something that upgrades packages that are already prerelease to a newer prerelease, but leaves stable packages alone (and does not upgrade them to prerelease versions).

This flag would allow unintended scripts to function without blocking waiting for y/n while still upgrading your prerlease packages to the latest bits.

**Comment by ferventcoder** [comment] 2016-04-11 14:40
@ScottRFrost that makes way too much sense :+1:

**Comment by eeevans** [comment] 2016-09-06 18:26
I'd like to work on this feature and tbh I've already got a lot of the code in place other than the prompting if run without the -includepre switch...I was just wondering if you really want to do that or just spit out info messages informing of the switch to allow it.

**Comment by ferventcoder** [comment] 2016-09-06 18:30
@eeevans let's see what you have.

**Comment by ferventcoder** [comment] 2017-03-19 17:18
So this feature will go into 0.10.4 like this - if you have prereleases installed it will upgrade them without needing to explicitly specify prerelease. This will allow everything to upgrade automatically. When it is a prerelease and the latest version is pre or stable, that is what it will upgrade to.

When you want the old behavior, just add `--exclude-prerelease`. I've tagged this with breaking change as it may have an effect on someone's workflow out there.

**Comment by ferventcoder** [comment] 2017-03-19 17:27
This will be in 0.10.4

**Closed by ferventcoder** 2017-03-19 17:27 UTC
Labels: 3 - Done, BreakingChange, Enhancement, Up For Grabs

**Comment by eeevans** [comment] 2017-03-19 23:43
Awesome, thanks!

**Comment by FranklinYu** [comment] 2019-07-18 18:53
If we upgrade with `--exclude-prerelease`, will the flag of remembered `--pre` be removed (forgotten)? For example, I upgrade from 1.0 to 1.1-rc1 with `--pre`, then upgrade to `1.1` with `--exclude-prerelease`, will it still upgrade to 1.2-rc1 when I `cup all`?

**Comment by bc3tech** [comment] 2019-11-18 19:16
Propose reopening; this doesn't work if your prerelease pkg has a prerelease _dependency_ - it'll fail the upgrade of the meta pkg saying the dependency can't be found.

**Comment by ferventcoder** [comment] 2020-01-02 23:18
@bc3tech that would be a separate issue.

**Comment by ferventcoder** [comment] 2020-02-04 20:51
#1957 follow on - upgrade here doesn't also apply to dependencies that are prereleases.

**Comment by ScottRFrost** [comment] 2020-02-04 21:26
Didn't realize this was still going.  I've since upgraded from chololately to [Scoop](https://github.com/lukesampson/scoop), which allows multiple versions of the same app.  They solve this issue by specifying version.

scoop install git <== installs latest
scoop install git@2.24.1 <== installs an older version side by side with latest, this version will now be called next time I type 'git'
scoop resest git <== default to latest installed version next time I type 'git', but the 2.24.1 version is still installed as well

Hope this helps!

**Comment by bc3tech** [comment] 2020-02-04 21:51
This should be re-opened:

~~~
C:\Users\brand> cup all -y
Chocolatey v0.10.15 Professional
Upgrading the following packages:
all
By upgrading you accept licenses for the packages.
...
You have vivaldi v2.11.1805.3-snapshot installed. Version 2.11.1811.3-snapshot is available based on your source(s).
vivaldi not upgraded. An error occurred during installation:
 Unable to resolve dependency 'vivaldi.portable (= 2.11.1811.3-snapshot)'.
vivaldi package files upgrade completed. Performing other installation steps.
The upgrade of vivaldi was NOT successful.
vivaldi not upgraded. An error occurred during installation:
 Unable to resolve dependency 'vivaldi.portable (= 2.11.1811.3-snapshot)'.

You have vivaldi.portable v2.11.1805.3-snapshot installed. Version 2.11.1811.3-snapshot is available based on your source(s).
vivaldi.portable not upgraded. An error occurred during installation:
 Updating 'vivaldi.portable 2.11.1805.3-snapshot' to 'vivaldi.portable 2.11.1811.3-snapshot' failed. Unable to find a version of 'vivaldi' that is compatible with 'vivaldi.portable 2.11.1811.3-snapshot'.
vivaldi.portable package files upgrade completed. Performing other installation steps.The upgrade of vivaldi.portable was NOT successful.
vivaldi.portable not upgraded. An error occurred during installation:
 Updating 'vivaldi.portable 2.11.1805.3-snapshot' to 'vivaldi.portable 2.11.1811.3-snapshot' failed. Unable to find a version of 'vivaldi' that is compatible with 'vivaldi.portable 2.11.1811.3-snapshot'.

Chocolatey upgraded 2/83 packages. 2 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
~~~

**Comment by ferventcoder** [comment] 2020-02-05 14:59
@ScottRFrost I trust you will understand why I'm going to delete your comment - posting about some alternative product on an issues list is just not something that is considered good etiquette. Plus it has nothing to do with the issue being discussed - Choccolatey has supported side by side package installations since day one.

**Comment by ferventcoder** [comment] 2020-02-05 15:07
@bc3tech can we please stop asking to reopen an issue? There is maybe a regression, but this issue ***was*** fixed in the release it went into. The question of whether it works if the prerelease has prerelease dependencies is a separate issue IMHO. It's likely a bug, but still not the same issue. If it is the same issue, that's called a regression and it still opens as a new issue b/c it cropped back up again later.

However, this issue is whether a prerelease would move to find and upgrade and it does, even based on your log. It found the prerelease: `You have vivaldi v2.11.1805.3-snapshot installed. Version 2.11.1811.3-snapshot is available based on your source(s).` 

Then it was prevented from upgrading based on dependencies. That means we either have a regression or a followup issue to handle prereleases with dependencies.
