### ISSUE TITLE
choco fails to install filezilla

### ISSUE THREAD

**Issue by superbonaci** [chocolatey/choco#2181] opened 2021-01-20 22:05 UTC
Info: https://github.com/chocolatey/choco/issues/2180

Attached chocolatey.log
[chocolatey-install-filezilla.log](https://github.com/chocolatey/choco/files/5845558/chocolatey-install-filezilla.log)

**Comment by pauby** [comment] 2021-01-22 11:40
Duplicate of #2180

**Closed** 2021-01-22 11:40 UTC
Labels: Duplicate Issue
