### ISSUE TITLE
[NuGet] An error occurred while loading packages from 'http://wanuget/bootstrap/nuget': The remote name could not be resolved: 'wanuget'

### ISSUE THREAD

**Issue by jrmcdona** [chocolatey/choco#1672] opened 2018-11-04 19:01 UTC
I am following the instruction from the Service Bus Explorer install site which says to run:
**chocolatey install ServiceBusExplorer**

Doing so just leaves me with this error (see below).   They mentioned this was a chocolately issue and not an issue for Service Bus Explorer.   See here https://github.com/paolosalvatori/ServiceBusExplorer/issues/276

```
C:\WINDOWS\system32>chocolatey install ServiceBusExplorer
Chocolatey v0.10.8
Installing the following packages:
ServiceBusExplorer
By installing you accept licenses for the packages.
[NuGet] An error occurred while loading packages from 'http://wanuget/bootstrap/nuget': The remote name could not be resolved: 'wanuget'
ServiceBusExplorer not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "http://wanuget/bootstrap/nuget"

```

**Comment by bcurran3** [comment] 2018-11-04 20:54
This is not a Chocolatey problem. This is a package problem.

If you click the link http://wanuget/bootstrap/nuget you'll see the reason for the problem.

**Comment by tomkerkhove** [comment] 2018-11-05 08:13
Hm strange as we do not use that anywhere. Isn't this Chocolatey trying to pull down the NuGet package?

**Comment by julienkosinski** [comment] 2018-11-06 17:31
I think NuGet is used in many areas in chocolatey.
I can reproduce the bug with a more explicit error message related with every softwares I'd like to update.
`[NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.`
Here is the problem if you're in Europe it's down...
https://status.verizondigitalmedia.com/#network-status

**Comment by pauby** [comment] 2018-11-06 17:33
@julienkosinski We have a [status page](https://status.chocolatey.org) that you can check. Your issue is not related to the OP's.

**Comment by julienkosinski** [comment] 2018-11-06 17:35
@pauby It is status of CDN of NuGet. So it's not related to NuGet ?
Anyway, thank you, hope this will be back soon :).

**Comment by ferventcoder** [comment] 2018-11-12 21:59
As that source isn't one we set as any default source, it is likely there was a source that wasn't resolving, thus causing that issue. If you reconnect to your VPN (throwing a guess here in the dark), you will probably see things working again. HTH

**Closed** 2018-11-12 21:58 UTC
Labels: Not An Issue / Can't Repro / Not Implementing / Invalid
