### ISSUE TITLE
Long version strings not accepting

### ISSUE THREAD

**Issue by johnnyramos** [chocolatey/choco#1107] opened 2016-12-22 00:56 UTC
### What You Are Seeing?

```
Chocolatey v0.10.3
'11.1.2.5.520' is not a valid version string.
Parameter name: version
```

### What is Expected?

Some programs have longer version strings such as Oracle SmartView.

### How Did You Get This To Happen? (Steps to Reproduce)
```
cpack -d
```
### Output Log

~~~sh
Chocolatey had an error occur:
System.ArgumentException: '11.1.2.5.520' is not a valid version string.
Parameter name: version
   at NuGet.SemanticVersion.Parse(String version)
   at NuGet.ManifestMetadata.NuGet.IPackageName.get_Version()
   at NuGet.PackageBuilder.Populate(ManifestMetadata manifestMetadata)
   at NuGet.PackageBuilder.ReadManifest(Stream stream, String basePath, IPropertyProvider propertyProvider)
   at NuGet.PackageBuilder..ctor(String path, String basePath, IPropertyProvider propertyProvider, Boolean includeEmptyDirectories)
   at chocolatey.infrastructure.app.services.NugetService.pack_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.pack_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
~~~

Let me know if there's something else I can provide. :)

**Comment by johnnyramos** [comment] 2016-12-22 01:02
Tried looking for the code here to contribute, but didn't find. I must be blind.

**Comment by johnnyramos** [comment] 2016-12-22 01:13
Ah, Duh - seems this might need to go to Nuget. My bad.

**Comment by ferventcoder** [comment] 2016-12-22 01:15
@johnnyramos thanks - the problem is the number of version segments. Only 4 are allowed. So that will need to be shortened down for NuGet/Chocolatey.

`1.2.3.4`, not `1.2.3.4.5`

**Comment by johnnyramos** [comment] 2016-12-22 01:17
Gotcha. Sucks though as this product changes their version upgrades on the 5th segment. :(

**Comment by johnnyramos** [comment] 2016-12-22 01:17
You can close if needed to. I'll shorten it.

**Comment by TheCakeIsNaOH** [comment] 2022-07-30 05:05
Yup, closing. 
Chocolatey CLI uses NuGet code, and needs to have compatibility with NuGet repositories, and so supporting a fifth segment to the version is not something that Chocolatey CLI can add unless upstream NuGet were to add it first.

**Comment by TheCakeIsNaOH** [comment] 2022-07-30 05:05
Yup, closing. 
Chocolatey CLI uses NuGet code, and needs to have compatibility with NuGet repositories, and so supporting a fifth segment to the version is not something that Chocolatey CLI can add unless upstream NuGet were to add it first.

**Closed by TheCakeIsNaOH** 2022-07-30 05:05 UTC
Labels: Invalid / Not Issue / No repro / Not Implementing
