### ISSUE TITLE
Install-ChocolateyPinnedTaskBarItem not working

### ISSUE THREAD

**Issue by mwallner** [chocolatey/choco#929] opened 2016-08-24 12:23 UTC
part of boxstarter install-script:

``` sh
Install-ChocolateyPinnedTaskBarItem "$($Boxstarter.programFiles86)\AccuRev\bin\acgui.exe"
Install-ChocolateyPinnedTaskBarItem "$($Boxstarter.programFiles86)\Microsoft Visual Studio 8\Common7\IDE\devenv.exe"
```

output:

``` sh
 TaskBar verb not found for System.__ComObject. It may have already been pinned
 'C:\Program Files (x86)\AccuRev\bin\acgui.exe' has been pinned to the task bar on your desktop
 TaskBar verb not found for System.__ComObject. It may have already been pinned
 'C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE\devenv.exe' has been pinned to the task bar on your deskt
op
```

a 'more simple testcase' also fails:

``` sh
PS C:\Users\mwallner> Import-Module C:\ProgramData\chocolatey\helpers\functions\Install-ChocolateyPinnedTaskBarItem.ps1
PS C:\Users\mwallner> Install-ChocolateyPinnedTaskBarItem C:\Windows\System32\calc.exe
TaskBar verb not found for System.__ComObject. It may have already been pinned
'C:\Windows\System32\calc.exe' has been pinned to the task bar on your desktop
```

**Comment by flcdrg** [comment] 2016-08-24 13:26
Duplicate of #627

**Comment by bc3tech** [comment] 2018-05-10 17:39
Today:
~~~
PS C:\WINDOWS\system32> Install-ChocolateyPinnedTaskBarItem "${env:LocalAppData}\Vivaldi\Application\vivaldi.exe"
Install-ChocolateyPinnedTaskBarItem : The term 'Install-ChocolateyPinnedTaskBarItem' is not recognized as the name of
a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At line:1 char:1
+ Install-ChocolateyPinnedTaskBarItem "${env:LocalAppData}\Vivaldi\Appl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-ChocolateyPinnedTaskBarItem:String) [], CommandNotFoundExceptio
   n
    + FullyQualifiedErrorId : CommandNotFoundException
~~~
This after being in the Boxstarter shell, which loads Boxstarter & Chocolatey modules.

Choco version: v0.10.11 professional

attn: @ferventcoder

**Comment by corbob** [comment] 2022-06-30 17:07
Duplicate of #627

**Closed by corbob** 2022-06-30 17:07 UTC
Labels: 0 - _Triaging, Duplicate Issue
