### ISSUE TITLE
choco feature to enable uninstalling dependencies by default

### ISSUE THREAD

**Issue by sebastian-c** [chocolatey/choco#3071] opened 2023-03-17 08:59 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

I currently have to manually use the `-x` flag when uninstalling packages. I would like to be able to set a flag to be able to set this by default, similar to how you can effectively always allow `-y` when installing packages.

### Describe The Solution. Why is it needed?

I often forget to remove dependencies by setting the `-x` flag, leaving me orphaned dependencies.

### Additional Context

This seems easier to implement and a better preventative solution than a tool to look for orphans.

**Comment by TheCakeIsNaOH** [comment] 2023-03-17 19:19
Duplicate of #2300

**Closed by TheCakeIsNaOH** 2023-03-17 19:19 UTC
Labels: Enhancement
