### ISSUE TITLE
Can't install adittional nodejs tools

### ISSUE THREAD

**Issue by Bogdan-Torkhov** [chocolatey/choco#3481] opened 2024-07-08 13:38 UTC
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Chocolatey v2.3.0
Upgrading the following packages:
python;visualstudio2019-workload-vctools
By upgrading, you accept licenses for the packages.
python v3.12.4 is the latest version available based on your source(s).
visualstudio2019-workload-vctools is not installed. Installing...
[NuGet] One or more unresolved package dependency constraints detected in the Chocolatey lib folder. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'python 3.12.4 constraint: python3 (= 3.12.4)'
Unable to resolve dependency 'kb2919355': Unable to find a version of 'kb2919355' that is compatible with 'dotnetfx 4.7.2.20180712 constraint: kb2919355 (>= 1.0.20160915)', 'KB2999226 1.0.20161023 constraint: kb2919355 (>= 1.0.20160915)', 'vcredist140 14.0.23026 constraint: kb2919355 (>= 1.0.20160915)', 'visualstudio2019buildtools 16.0.0 constraint: kb2919355 (>= 1.0.20160915)'.

Chocolatey upgraded 0/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - visualstudio2019-workload-vctools - Unable to resolve dependency 'kb2919355': Unable to find a version of 'kb2919355' that is compatible with 'dotnetfx 4.7.2.20180712 constraint: kb2919355 (>= 1.0.20160915)', 'KB2999226 1.0.20161023 constraint: kb2919355 (>= 1.0.20160915)', 'vcredist140 14.0.23026 constraint: kb2919355 (>= 1.0.20160915)', 'visualstudio2019buildtools 16.0.0 constraint: kb2919355 (>= 1.0.20160915)'.
Type ENTER to exit:

### What is Expected?

I expected installing all things and closing terminal

### How Did You Get This To Happen?

I ran nodejs installation and installation of additional tools

### System Details

* Operating System: Windows 11
* Windows PowerShell version:5.1.22621.3810
* Chocolatey CLI Version:2.3.0
* Chocolatey Licensed Extension version:Chocolatey v2.3.0
0 packages installed.
* Chocolatey License type:?
* Terminal/Emulator:it starts powershell from admin

### Installed Packages

```bash
chocolatey 2.3.0
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-windowsupdate.extension 1.0.5
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
python 3.12.4
python3 3.12.4
vcredist140 14.40.33810
vcredist2015 14.0.24215.20170201
13 packages installed.
```

### Output Log

```bash
https://gist.github.com/Bogdan-Torkhov/1a4d646395bf7d87b82b56146ea78b25
```

### Additional Context

It's all

**Comment by pauby** [comment] 2024-07-08 14:09
Duplicate of #3480.

While this is a different package, this is still a duplicate.

**Comment by pauby** [comment] 2024-07-08 14:10
While this is a different package, this is still a duplicate.

**Closed by pauby** 2024-07-08 14:09 UTC
Labels: Bug

**Comment by Bogdan-Torkhov** [comment] 2024-07-08 14:34
@pauby I chechked docs, i don't know how to fix these error, do you have any idea?

**Comment by Bogdan-Torkhov** [comment] 2024-07-08 14:36
And i have different error, not like in #3480

**Comment by Bogdan-Torkhov** [comment] 2024-07-08 15:53
https://github.com/chocolatey/choco/issues/3226 these issue is similar to my, but not the same

**Comment by Bogdan-Torkhov** [comment] 2024-07-08 15:54
@pauby please help me solve it

**Comment by Bogdan-Torkhov** [comment] 2024-07-08 17:17
@pauby answer me please

**Comment by Bogdan-Torkhov** [comment] 2024-07-08 18:15
@pauby please answer me?

**Comment by TheCakeIsNaOH** [comment] 2024-07-08 22:44
@Bogdan-Torkhov see the code of conduct: https://github.com/chocolatey/choco?tab=coc-ov-file#readme
This is a community support issue tracker, not one with a SLA: https://chocolatey.org/support

As for your issue, see the dependency trouble docs linked in the other issue: https://docs.chocolatey.org/en-us/choco/troubleshooting/dependency-troubles/

It looks like you are missing the `python312` package, because it failed to install. This left the dependencies in a broken state. You can either install the `python312` package, or uninstall `python` and then `python3` to fix the broken dependency tree.
https://community.chocolatey.org/packages/python312
