### ISSUE TITLE
Push command does not honor proxy settings

### ISSUE THREAD

**Issue by abejenaru** [chocolatey/choco#1271] opened 2017-04-28 11:33 UTC
```
> choco push
Chocolatey v0.10.5
Attempting to push somepackage.nupkg to https://chocolatey.org/
Failed to process request. 'Proxy Authentication Required'.
The remote server returned an error: (407) Proxy Authentication Required.
```

All good for installing & updating packages.

**Comment by ferventcoder** [comment] 2017-08-27 20:59
@abejenaru if you set an explicit proxy, you are seeing this?

**Comment by abejenaru** [comment] 2017-08-28 12:30
Yes, still the same with the latest Chocolatey, with or withour explicit proxy configuration.

> choco push -v --proxy server:port --proxy-user username --proxy-password password
Chocolatey v0.10.7
Attempting to push minishift.1.5.0.nupkg to https://push.chocolatey.org/
PUT http://username:password@proxy/api/v2/package/
PUT http://username:password@proxy/api/v2/package/
Failed to process request. 'Proxy Authentication Required'.
The remote server returned an error: (407) Proxy Authentication Required..

**Comment by ferventcoder** [comment] 2017-08-28 22:06
I wonder if the proxy is ignored for push as it is a different interface than everything else.

**Comment by jansohn** [comment] 2018-05-23 14:37
`choco push` seems to use the environment variables `https_proxy` and `http_proxy` but ignores the `no_proxy` environment variable. I haven't found a way to use `choco push` other than removing the proxy environment variables from the current session with `Remove-Item env:HTTP_PROXY`. This should be fixed in my opinion!

**Comment by TheCakeIsNaOH** [comment] 2023-07-13 01:32
@corbob did you get around to testing this, as I think there is a good chance this would "just work" with the new NuGet libraries.

**Comment by TheCakeIsNaOH** [comment] 2023-07-13 23:08
Wonderful.

I guess this issue can stay open for adding tests.

**Comment by corbob** [comment] 2023-07-14 19:31
I think we might actually have as many tests around this as we can have right now. We have the push tests [here](https://github.com/chocolatey/choco/blob/develop/tests/chocolatey-tests/commands/choco-push.Tests.ps1#L112) that test pushing to a v2 and v3 feed. I have confirmed that our test kitchen suite for proxy tests passes them on choco v2 for configuration, and fails all of them for system set (due to v2 only looking to the registry). When run against v2.1 both sets of test pass.

Based on that, I'll update this issue and tag it against the 2.0.0 milestone, then get the 2.0.0 release notes updated 😁

**Closed** 2023-07-14 19:45 UTC
Labels: Bug, 5 - Released
