### ISSUE TITLE
AutoUninstaller should convert /I to /X for Msi Uninstalls

### ISSUE THREAD

**Issue by mrdima** [chocolatey/choco#271] opened 2015-05-05 07:51 UTC
Many MSI's have an uninstallstring of /I{GUID}, including commercial MSI's, and not /X. Seems this is because it also adds the change/repair option if I can believe the story at: 
http://stackoverflow.com/questions/10280952/uninstallstring-being-set-with-i-not-x-param
Add/Remove Programs or Programs and Features doesn't have a problem uninstalling those programs, neither should chocolatey.

There's a few issues causing the autoinstaller breaking for us in this case.
1. It doesn't uninstall properly...see the output below, I would expect it to change /I to /X (and not just remove the / and leave the I). Now you get a popup from msiexec with the usage when the autouninstaller runs!
2. If uninstall fails, why does chocolatey consider the package removed? I would expect that chocolatey keeps it as installed, which it is...there needs to be some way to force removal in chocolatey but that shouldn't be the default.

 Running auto uninstaller...
 Preparing uninstall key 'MsiExec.exe /I{50CB48BE-3DDC-4245-9E39-432C903336BE}'
 Uninstaller path is 'C:\Windows\system32\MsiExec.exe'
 Installer type is 'MsiInstaller'
 Args are 'I{50CB48BE-3DDC-4245-9E39-432C903336BE} /qn /norestart '
Calling command ['"C:\Windows\system32\MsiExec.exe" I{50CB48BE-3DDC-4245-9E39-43
2C903336BE} /qn /norestart ']
Command ['"C:\Windows\system32\MsiExec.exe" I{50CB48BE-3DDC-4245-9E39-432C903336
BE} /qn /norestart '] exited with '1639'
 Auto uninstaller failed. Please remove machine installation manually.
mypackage uninstall not successful.
 Auto uninstaller failed. Please remove machine installation manually.
Removed file 'chocolateyinstall.ps1' to folder 'C:\Management\Programs\Chocolate
y\lib\mypackage\tools'.
Removed folder 'C:\Management\Programs\Chocolatey\lib\mypackage\tools'.
Removed file 'mypackage.nupkg' to folder 'C:\Management\Programs\Chocolatey\lib\mypackage'.
Removed folder 'C:\Management\Programs\Chocolatey\lib\mypackage'.
Successfully uninstalled 'mypackage 2.84'.
 mypackage has been successfully uninstalled.

Tested on 0.9.9.5

**Comment by ferventcoder** [comment] 2015-05-05 12:39
This is partially a dupe of #212

**Comment by ferventcoder** [comment] 2015-05-05 12:41
The second thing will need it's own issue.

**Comment by ferventcoder** [comment] 2015-05-05 12:41
We'll also need to ensure that /I gets switched to /X

**Comment by mrdima** [comment] 2015-05-05 13:31
Changing /I to /X seems to be the most common solution, keeping /I and adding REMOVE=ALL to the string actually does uninstall as well...but I opt for changing /I to /X

**Comment by ferventcoder** [comment] 2015-05-05 13:49
Of note, the autouninstaller is still in preview while we work the kinks out. For uninstalls - you may want to ensure you have a chocolateyUninstall.ps1 in the package as well.

**Comment by ferventcoder** [comment] 2015-05-16 20:37
This is completed and will be released with 0.9.9.6.

**Closed by ferventcoder** 2015-05-16 20:37 UTC
Labels: 0 - Backlog, Enhancement

**Comment by mrdima** [comment] 2015-05-20 12:41
Awsome, I can confirm this works for me now!

**Comment by ferventcoder** [comment] 2015-05-20 17:08
:+1:
