### ISSUE TITLE
Install-ChocolateyFileAssociation unexpected output

### ISSUE THREAD

**Issue by day1player** [chocolatey/choco#1640] opened 2018-09-12 16:43 UTC
### What You Are Seeing?
When using the Install-ChocolateyFileAssociation command I am receiving a massive CLIXML output that looks like standard error (its red) and then some standard output - "'.file' has been associated with 'C:\Program.exe'" and I am unable to mute it.
### What is Expected?
Expected clean output, or no output.
### How Did You Get This To Happen? (Steps to Reproduce)
Install-ChocolateyFileAssociation ".avi" $vlc
$Null = Install-ChocolateyFileAssociation ".mp3" $vlc
[void](Install-ChocolateyFileAssociation ".mp4" $vlc)
Install-ChocolateyFileAssociation ".mpeg" $vlc > $null
Install-ChocolateyFileAssociation ".wav" $vlc | Out-Null

All I want is to not see the output...

**Comment by bcurran3** [comment] 2018-09-12 18:48
https://chocolatey.org/packages/chocolateypowershell might help you diagnose faster.

Take a look at this:
https://stackoverflow.com/questions/5881174/redirecting-output-to-null-in-powershell-but-ensuring-the-variable-remains-set

**Comment by day1player** [comment] 2018-09-13 17:09
(Install-ChocolateyFileAssociation ".mp3" $vlc) > $null
Install-ChocolateyFileAssociation ".mp4" $vlc 2> $null
(Install-ChocolateyFileAssociation ".mpeg" $vlc) 2> $null
Install-ChocolateyFileAssociation ".wav" $vlc 2>&1> $null
(Install-ChocolateyFileAssociation ".avi" $vlc) 2>&1> $null
Install-ChocolateyFileAssociation ".wmv" $vlc 2>&1 | Out-Null
(Install-ChocolateyFileAssociation ".flv" $vlc) 2>&1 | Out-Null

Tried all of these and still no bueno :-/

**Comment by day1player** [comment] 2018-09-13 17:13
```
#< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS
><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1
"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><S
 S="debug">Host version is 5.1.14409.1012, PowerShell Version is '5.1.14409.1012' and CLR Version is '4.0.30319.42000'.</S><S S="verbose">Exporting function 'Format-FileSize'.</S><S S="verbose">Export
ing function 'Get-ChecksumValid'.</S><S S="verbose">Exporting function 'Get-ChocolateyUnzip'.</S><S S="verbose">Exporting function 'Get-ChocolateyWebFile'.</S><S S="verbose">Exporting function 'Get-En
vironmentVariable'.</S><S S="verbose">Exporting function 'Get-EnvironmentVariableNames'.</S><S S="verbose">Exporting function 'Get-FtpFile'.</S><S S="verbose">Exporting function 'Get-OSArchitectureWid
th'.</S><S S="verbose">Exporting function 'Get-PackageParameters'.</S><S S="verbose">Exporting function 'Get-PackageParametersBuiltIn'.</S><S S="verbose">Exporting function 'Get-ToolsLocation'.</S><S
S="verbose">Exporting function 'Get-UACEnabled'.</S><S S="verbose">Exporting function 'Get-UninstallRegistryKey'.</S><S S="verbose">Exporting function 'Get-VirusCheckValid'.</S><S S="verbose">Exportin
g function 'Get-WebFile'.</S><S S="verbose">Exporting function 'Get-WebFileName'.</S><S S="verbose">Exporting function 'Get-WebHeaders'.</S><S S="verbose">Exporting function 'Install-BinFile'.</S><S S
="verbose">Exporting function 'Install-ChocolateyDesktopLink'.</S><S S="verbose">Exporting function 'Install-ChocolateyEnvironmentVariable'.</S><S S="verbose">Exporting function 'Install-ChocolateyExp
lorerMenuItem'.</S><S S="verbose">Exporting function 'Install-ChocolateyFileAssociation'.</S><S S="verbose">Exporting function 'Install-ChocolateyInstallPackage'.</S><S S="verbose">Exporting function
'Install-ChocolateyPackage'.</S><S S="verbose">Exporting function 'Install-ChocolateyPath'.</S><S S="verbose">Exporting function 'Install-ChocolateyPinnedTaskBarItem'.</S><S S="verbose">Exporting func
tion 'Install-ChocolateyPowershellCommand'.</S><S S="verbose">Exporting function 'Install-ChocolateyShortcut'.</S><S S="verbose">Exporting function 'Install-ChocolateyVsixPackage'.</S><S S="verbose">E
xporting function 'Install-ChocolateyZipPackage'.</S><S S="verbose">Exporting function 'Install-Vsix'.</S><S S="verbose">Exporting function 'Set-EnvironmentVariable'.</S><S S="verbose">Exporting funct
ion 'Set-PowerShellExitCode'.</S><S S="verbose">Exporting function 'Start-ChocolateyProcessAsAdmin'.</S><S S="verbose">Exporting function 'Test-ProcessAdminRights'.</S><S S="verbose">Exporting functio
n 'Uninstall-BinFile'.</S><S S="verbose">Exporting function 'Uninstall-ChocolateyEnvironmentVariable'.</S><S S="verbose">Exporting function 'Uninstall-ChocolateyPackage'.</S><S S="verbose">Exporting f
unction 'Uninstall-ChocolateyZipPackage'.</S><S S="verbose">Exporting function 'Update-SessionEnvironment'.</S><S S="verbose">Exporting function 'Write-ChocolateyFailure'.</S><S S="verbose">Exporting
function 'Write-ChocolateySuccess'.</S><S S="verbose">Exporting function 'Write-FileUpdateLog'.</S><S S="verbose">Exporting function 'Write-FunctionCallLogMessage'.</S><S S="verbose">Exporting alias '
Get-ProcessorBits'.</S><S S="verbose">Exporting alias 'Get-OSBitness'.</S><S S="verbose">Exporting alias 'Get-InstallRegistryKey'.</S><S S="verbose">Exporting alias 'Generate-BinFile'.</S><S S="verbos
e">Exporting alias 'Add-BinFile'.</S><S S="verbose">Exporting alias 'Start-ChocolateyProcess'.</S><S S="verbose">Exporting alias 'Invoke-ChocolateyProcess'.</S><S S="verbose">Exporting alias 'Remove-B
inFile'.</S><S S="verbose">Exporting alias 'refreshenv'.</S><S S="debug">Loading community extensions</S><S S="debug">Importing 'C:\ProgramData\chocolatey\extensions\chocolatey-core\chocolatey-core.ps
m1'</S><S S="verbose">Loading module from path 'C:\ProgramData\chocolatey\extensions\chocolatey-core\chocolatey-core.psm1'.</S><S S="verbose">Exporting function 'Get-UninstallRegistryKey'.</S><S S="ve
rbose">Exporting function 'Get-AppInstallLocation'.</S><S S="verbose">Exporting function 'Get-AvailableDriveLetter'.</S><S S="verbose">Exporting function 'Get-EffectiveProxy'.</S><S S="verbose">Export
ing function 'Get-PackageCacheLocation'.</S><S S="verbose">Exporting function 'Get-PackageParameters'.</S><S S="verbose">Exporting function 'Get-WebContent'.</S><S S="verbose">Exporting function 'Regi
ster-Application'.</S><S S="verbose">Importing function 'Get-AppInstallLocation'.</S><S S="verbose">Importing function 'Get-AvailableDriveLetter'.</S><S S="verbose">Importing function 'Get-EffectivePr
oxy'.</S><S S="verbose">Importing function 'Get-PackageCacheLocation'.</S><S S="verbose">Importing function 'Get-PackageParameters'.</S><S S="verbose">Importing function 'Get-UninstallRegistryKey'.</S
><S S="verbose">Importing function 'Get-WebContent'.</S><S S="verbose">Importing function 'Register-Application'.</S><S S="debug">Importing 'C:\ProgramData\chocolatey\extensions\chocolatey-windowsupda
te\chocolatey-windowsupdate.psm1'</S><S S="verbose">Loading module from path 'C:\ProgramData\chocolatey\extensions\chocolatey-windowsupdate\chocolatey-windowsupdate.psm1'.</S><S S="verbose">Exporting
function 'Install-WindowsUpdate'.</S><S S="verbose">Exporting function 'Test-WindowsUpdate'.</S><S S="verbose">Importing function 'Install-WindowsUpdate'.</S><S S="verbose">Importing function 'Test-Wi
ndowsUpdate'.</S><S S="verbose">Exporting function 'Format-FileSize'.</S><S S="verbose">Exporting function 'Get-ChecksumValid'.</S><S S="verbose">Exporting function 'Get-ChocolateyUnzip'.</S><S S="ver
bose">Exporting function 'Get-ChocolateyWebFile'.</S><S S="verbose">Exporting function 'Get-EnvironmentVariable'.</S><S S="verbose">Exporting function 'Get-EnvironmentVariableNames'.</S><S S="verbose"
>Exporting function 'Get-FtpFile'.</S><S S="verbose">Exporting function 'Get-OSArchitectureWidth'.</S><S S="verbose">Exporting function 'Get-PackageParameters'.</S><S S="verbose">Exporting function 'G
et-PackageParametersBuiltIn'.</S><S S="verbose">Exporting function 'Get-ToolsLocation'.</S><S S="verbose">Exporting function 'Get-UACEnabled'.</S><S S="verbose">Exporting function 'Get-UninstallRegist
ryKey'.</S><S S="verbose">Exporting function 'Get-VirusCheckValid'.</S><S S="verbose">Exporting function 'Get-WebFile'.</S><S S="verbose">Exporting function 'Get-WebFileName'.</S><S S="verbose">Export
ing function 'Get-WebHeaders'.</S><S S="verbose">Exporting function 'Install-BinFile'.</S><S S="verbose">Exporting function 'Install-ChocolateyDesktopLink'.</S><S S="verbose">Exporting function 'Insta
ll-ChocolateyEnvironmentVariable'.</S><S S="verbose">Exporting function 'Install-ChocolateyExplorerMenuItem'.</S><S S="verbose">Exporting function 'Install-ChocolateyFileAssociation'.</S><S S="verbose
">Exporting function 'Install-ChocolateyInstallPackage'.</S><S S="verbose">Exporting function 'Install-ChocolateyPackage'.</S><S S="verbose">Exporting function 'Install-ChocolateyPath'.</S><S S="verbo
se">Exporting function 'Install-ChocolateyPinnedTaskBarItem'.</S><S S="verbose">Exporting function 'Install-ChocolateyPowershellCommand'.</S><S S="verbose">Exporting function 'Install-ChocolateyShortc
ut'.</S><S S="verbose">Exporting function 'Install-ChocolateyVsixPackage'.</S><S S="verbose">Exporting function 'Install-ChocolateyZipPackage'.</S><S S="verbose">Exporting function 'Install-Vsix'.</S>
<S S="verbose">Exporting function 'Set-EnvironmentVariable'.</S><S S="verbose">Exporting function 'Set-PowerShellExitCode'.</S><S S="verbose">Exporting function 'Start-ChocolateyProcessAsAdmin'.</S><S
 S="verbose">Exporting function 'Test-ProcessAdminRights'.</S><S S="verbose">Exporting function 'Uninstall-BinFile'.</S><S S="verbose">Exporting function 'Uninstall-ChocolateyEnvironmentVariable'.</S>
<S S="verbose">Exporting function 'Uninstall-ChocolateyPackage'.</S><S S="verbose">Exporting function 'Uninstall-ChocolateyZipPackage'.</S><S S="verbose">Exporting function 'Update-SessionEnvironment'
.</S><S S="verbose">Exporting function 'Write-ChocolateyFailure'.</S><S S="verbose">Exporting function 'Write-ChocolateySuccess'.</S><S S="verbose">Exporting function 'Write-FileUpdateLog'.</S><S S="v
erbose">Exporting function 'Write-FunctionCallLogMessage'.</S><S S="verbose">Exporting function 'Get-AppInstallLocation'.</S><S S="verbose">Exporting function 'Get-AvailableDriveLetter'.</S><S S="verb
ose">Exporting function 'Get-EffectiveProxy'.</S><S S="verbose">Exporting function 'Get-PackageCacheLocation'.</S><S S="verbose">Exporting function 'Get-WebContent'.</S><S S="verbose">Exporting functi
on 'Register-Application'.</S><S S="verbose">Exporting function 'Install-WindowsUpdate'.</S><S S="verbose">Exporting function 'Test-WindowsUpdate'.</S><S S="verbose">Exporting alias 'Get-ProcessorBits
'.</S><S S="verbose">Exporting alias 'Get-OSBitness'.</S><S S="verbose">Exporting alias 'Get-InstallRegistryKey'.</S><S S="verbose">Exporting alias 'Generate-BinFile'.</S><S S="verbose">Exporting alia
s 'Add-BinFile'.</S><S S="verbose">Exporting alias 'Start-ChocolateyProcess'.</S><S S="verbose">Exporting alias 'Invoke-ChocolateyProcess'.</S><S S="verbose">Exporting alias 'Remove-BinFile'.</S><S S=
"verbose">Exporting alias 'refreshenv'.</S></Objs>
'.wmv' has been associated with 'C:\Program Files\VideoLAN\VLC\vlc.exe'
```

**Comment by bcurran3** [comment] 2018-09-13 17:38
Doesn't happen to me. :)

![image](https://user-images.githubusercontent.com/14026600/45505284-1f425c00-b741-11e8-9d75-0eaf57982689.png)

**Comment by bcurran3** [comment] 2018-09-13 17:46
cmd.exe /c assoc .txt=text >NUL

so...
cmd.exe /c assoc .wav=VLC.wav
and so on...

**Comment by day1player** [comment] 2018-09-13 18:39
I would like to use the Chocolatey function, the assoc command is really not that great. When I use assoc (for text files for example) `assoc .txt=sublime_text.exe` the text file will prompt you for a program, saying it doesn't know how to open the file.. It also removes the feature where you right click, New -> Text Document.. 

Similarly, when I try to `assoc .ps1=Code.exe` the computer gets confused..

**Comment by day1player** [comment] 2018-09-13 18:43
For what its worth, I installed ChocolateyPowerShell and ran the command, there was no standard error displayed in the ChocolateyPowerShell.. But I could not mute the stdout
```
[ChocolateyPS] C:\> $vlc = "C:\Program Files\VideoLAN\VLC\vlc.exe"
[ChocolateyPS] C:\> (Install-ChocolateyFileAssociation ".mp3" $vlc) > $null
'.mp3' has been associated with 'C:\Program Files\VideoLAN\VLC\vlc.exe'
[ChocolateyPS] C:\> Install-ChocolateyFileAssociation ".mp4" $vlc 2> $null
0
'.mp4' has been associated with 'C:\Program Files\VideoLAN\VLC\vlc.exe'
[ChocolateyPS] C:\> (Install-ChocolateyFileAssociation ".mpeg" $vlc) 2> $null
'.mpeg' has been associated with 'C:\Program Files\VideoLAN\VLC\vlc.exe'
0
[ChocolateyPS] C:\> Install-ChocolateyFileAssociation ".wav" $vlc 2>&1> $null
'.wav' has been associated with 'C:\Program Files\VideoLAN\VLC\vlc.exe'
[ChocolateyPS] C:\> (Install-ChocolateyFileAssociation ".avi" $vlc) 2>&1> $null
'.avi' has been associated with 'C:\Program Files\VideoLAN\VLC\vlc.exe'
[ChocolateyPS] C:\> Install-ChocolateyFileAssociation ".wmv" $vlc 2>&1 | Out-Nul
l
'.wmv' has been associated with 'C:\Program Files\VideoLAN\VLC\vlc.exe'
[ChocolateyPS] C:\> (Install-ChocolateyFileAssociation ".flv" $vlc) 2>&1 | Out-N
ull
'.flv' has been associated with 'C:\Program Files\VideoLAN\VLC\vlc.exe'
[ChocolateyPS] C:\>
```

**Comment by bcurran3** [comment] 2018-09-13 19:34
Yes. assoc.exe is not for associating programs, it's for associating file types; which are in turn associated with programs.

REF: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/assoc

Funny thing is, you're getting that output because Chocolatey uses assoc.exe along with other things...

From Install-ChocolateyFileAssociation:
```
  $elevated = @"
    **cmd /c "assoc $extension=$fileType"**
    cmd /c 'ftype $fileType="$executable" "%1" "%*"'
    New-PSDrive -Name HKCR -PSProvider Registry -Root HKEY_CLASSES_ROOT
    Set-ItemProperty -Path "HKCR:\$fileType" -Name "(Default)" -Value "$fileType file" -ErrorAction Stop
"@
```

It really seems there SHOULD be a way to NULL the operation, but maybe the Chocolatey team will need to include it as part of the function....which means you're already here! :) :(

BUT WAIT!

With all that said, this format works:

install-chocolateyfileassociation ".txt" $txt *> $null

Ta da!

Where there's a Will(iam), there's a way. :)

**Comment by day1player** [comment] 2018-09-13 19:41
Yes I am playing around with ftype and assoc now, also looking at reg add for adding icons lol. It is a pain. 

That is so CLOSE! It does work in the chocolatey powershell but it does not mute when using choco install.

The stdout is muted but still getting stderr (I'm only assuming stderr because its all red) when running cinst :-(

**Comment by day1player** [comment] 2018-09-13 19:55
Out of curiosity, do you know how "Install-ChocolateyFileAssociation" assigns icons?

**Comment by bcurran3** [comment] 2018-09-13 19:56
> That is so CLOSE! It does work in the chocolatey powershell but it does not mute when using choco install.

DAMMIT!

Keep on it. You can do it. I'm giving up for the moment to go do paid work. :)

p.s. RE: ChocolateyPowerShell - pushed a cleaner version this morning:
choco upgrade chocolateypowershell --version 0.0.2

**Comment by bcurran3** [comment] 2018-09-13 20:01
> Out of curiosity, do you know how "Install-ChocolateyFileAssociation" assigns icons?

Not really. I'm guessing looking at above that the New-PSDrive line and the line below associate the file type with a class that has the info on that filetype and thus the icon info. Just my guess. If I'm wrong I'm sure Gary or Paul will step in and correct me, they know this stuff much better than me. They just don't seem to like to do the coding for you. :)

**Comment by day1player** [comment] 2018-09-13 20:03
Well thank you so much for your help so far. At the very least, you have pointed me in the right direction.

**Comment by ferventcoder** [comment] 2018-09-26 01:04
Howdy folks - this is a duplicate of https://github.com/chocolatey/choco/issues/1016.

Duplicate of #1016

**Comment by ferventcoder** [comment] 2018-09-26 01:04
Duplicate of #1016

**Closed by ferventcoder** 2018-09-26 01:04 UTC

**Comment by ferventcoder** [comment] 2018-09-26 02:53
That other ticket provides more context for you.
