### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\chocolatey\.chocolatey' is denied.

### ISSUE THREAD

**Issue by SamuelMarks** [chocolatey/choco#3512] opened 2024-09-14 17:26 UTC
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

First time I've ever used choco, followed your guide from an elevated PowerShell.

### What is Expected?

Should just work

### How Did You Get This To Happen?

```powershell
PS > choco install tinytex -params "/AddToSystemPath"
Chocolatey v2.3.0
Chocolatey detected you are not running from an elevated command shell
 (cmd/powershell).

 You may experience errors - many functions/packages
 require admin rights. Only advanced users should run choco w/out an
 elevated shell. When you open the command shell, you should ensure
 that you do so with "Run as Administrator" selected. If you are
 attempting to use Chocolatey in a non-administrator setting, you
 must select a different location other than the default install
 location. See
 https://docs.chocolatey.org/en-us/choco/setup#non-administrative-install
 for details.


 Do you want to continue?([Y]es/[N]o):

Timeout or your choice of '' is not a valid selection.
Installing the following packages:
tinytex
By installing, you accept licenses for the packages.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading tinytex 2024.9.0... 100%
tinytex not installed. An error occurred during installation:
 Unable to obtain lock file access on 'C:\ProgramData\chocolatey\lib\0724ce60519461a65e94895eb331d2f358744272' for operations on 'C:\ProgramData\chocolatey\lib\tinytex'. This may mean that a different user or administrator is holding this lock and that this process does not have permission to access it. If no other process is currently performing an operation on this file it may mean that an earlier NuGet process crashed and left an inaccessible lock file, in this case removing the file 'C:\ProgramData\chocolatey\lib\0724ce60519461a65e94895eb331d2f358744272' will allow NuGet to continue.
tinytex package files install failed with exit code 1. Performing other installation steps.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 Access to the path 'C:\ProgramData\chocolatey\.chocolatey' is denied.
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Access to the path 'C:\ProgramData\chocolatey\.chocolatey' is denied.
Maximum tries of 3 reached. Throwing error.
Cannot create directory "C:\ProgramData\chocolatey\.chocolatey". Error was:
System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\chocolatey\.chocolatey' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at chocolatey.infrastructure.filesystem.DotNetFileSystem.<>c__DisplayClass63_0.<CreateDirectory>b__1()
   at chocolatey.infrastructure.tolerance.FaultTolerance.<>c__DisplayClass1_0.<Retry>b__0()
   at chocolatey.infrastructure.tolerance.FaultTolerance.Retry[T](Int32 numberOfTries, Func`1 function, Int32 waitDurationMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent)
   at chocolatey.infrastructure.tolerance.FaultTolerance.Retry(Int32 numberOfTries, Action action, Int32 waitDurationMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent)
   at chocolatey.infrastructure.filesystem.DotNetFileSystem.CreateDirectory(String directoryPath, Boolean isSilent)
   at chocolatey.infrastructure.filesystem.DotNetFileSystem.EnsureDirectoryExists(String directoryPath, Boolean ignoreError, Boolean isSilent)

Chocolatey installed 0/0 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Access to the path 'C:\ProgramData\chocolatey\.chocolatey' is denied.
PS > mkdir C:\ProgramData\chocolatey\.chocolatey
mkdir : Access to the path '.chocolatey' is denied.
At line:1 char:1
+ mkdir C:\ProgramData\chocolatey\.chocolatey
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\ProgramData\chocolatey\.chocolatey:String) [New-Item], Unauthorize
   dAccessException
    + FullyQualifiedErrorId : CreateDirectoryUnauthorizedAccessError,Microsoft.PowerShell.Commands.NewItemCommand
```

So then I tried running `mkdir C:\ProgramData\chocolatey\.chocolatey` which didn't work from that PowerShell, so I ran it in an elevated CMD which worked and then I was able to proceed in PowerShell.

### System Details

* Operating System: `10.0.22631.0`
* Windows PowerShell version:
```
* Name                           Value
----                           -----
PSVersion                      5.1.22621.4111
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.4111
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
* Chocolatey CLI Version: `2.3.0`
* Chocolatey Licensed Extension version:
* Chocolatey License type:
* Terminal/Emulator: default

### Installed Packages

```bash
Chocolatey v2.3.0
chocolatey 2.3.0
1 package installed.
```

### Output Log

```bash
N/A
```

**Comment by pauby** [comment] 2024-09-15 22:16
The problem is shown on the output:

> Chocolatey detected you are not running from an elevated command shell
 (cmd/powershell).
> 
> You may experience errors - many functions/packages
 require admin rights. Only advanced users should run choco w/out an
 elevated shell. When you open the command shell, you should ensure
 that you do so with "Run as Administrator" selected. If you are
 attempting to use Chocolatey in a non-administrator setting, you
 must select a different location other than the default install
 location. See
 https://docs.chocolatey.org/en-us/choco/setup#non-administrative-install
 for details.

Which you confirmed:

> So then I tried running mkdir C:\ProgramData\chocolatey\.chocolatey which didn't work from that PowerShell, so I ran it in an elevated CMD which worked and then I was able to proceed in PowerShell.

If you can't access it without an elevated session, Chocolatey CLI is not going to be able to do it either.

There is nothing for us to do here, so I'm going to close this issue. We can always reopen it again if necessary.

**Closed by pauby** 2024-09-15 22:16 UTC
Labels: Bug
