### ISSUE TITLE
Different versions of choco with different behavior - How to handle this in packages?

### ISSUE THREAD

**Issue by dhilgarth** [chocolatey/choco#128] opened 2015-02-26 20:45 UTC
I am wondering how to handle the different behavior of different choco versions in packages.
For example, PowerShell choco removed the unzipped files. Choco 0.9.9-rc8 doesn't.
Likewise, PowerShell choco doesn't have `Install-ChocolateyShortcut` but the new choco does.

What is the best practice in making packages work in all environments?

**Comment by ferventcoder** [comment] 2015-02-26 23:57
#121 will handle the unzipped files. That is not a package script concern.

**Comment by ferventcoder** [comment] 2015-02-26 23:59
When things get added you have to decide whether to use and when to use. That's how you handle new things. You can also add the script to the package and use it if a command for it is not found.

**Comment by ferventcoder** [comment] 2015-02-26 23:59
There are examples of doing that with bin root. Also, this seems more like a question than an issue - please use the gitter chat room for that - https://gitter.im/chocolatey/choco

**Comment by ferventcoder** [comment] 2015-02-27 00:00
I think this can be closed, unless we want this to be a documentation issue. We've added new functions over time before though.

**Comment by jberezanski** [comment] 2015-02-27 14:08
Perhaps we could document a way for the package to determine Chocolatey version.

**Comment by dhilgarth** [comment] 2015-02-27 14:12
In most cases, feature detection would be better. You can see an example here: https://github.com/dhilgarth/chocolatey-packages/blob/master/automatic/procmon/tools/chocolateyinstall.ps1#L12

**Comment by ferventcoder** [comment] 2015-02-27 14:16
@dhilgarth yes, but it's a bit more work on the maintainer to do so.

**Comment by ferventcoder** [comment] 2015-02-27 14:18
@dhilgarth found an example for you - https://github.com/ferventcoder/chocolatey-packages/blob/37b7131868dbf761ffc0e6625702a0d2fe422c28/manual/ruby/tools/chocolateyInstall.ps1#L4-L11

**Comment by dhilgarth** [comment] 2015-02-27 14:19
So you propose to include the new module with the package?

**Comment by ferventcoder** [comment] 2015-02-27 14:55
Usually if you want to take advantage of the feature but support older versions, you either do all of the work yourself or just include the function. It's less boilerplate for you to write.

**Comment by jberezanski** [comment] 2015-02-28 21:36
I agree that feature detection is generally more robust. However, in Chocolatey, only the presence of helper functions can be currently detected, so this method could not be used to handle Chocolatey behavior changes (such as the removal of unzipped files - fortunately, this one will not change after all).

**Comment by corbob** [comment] 2022-06-30 17:05
Duplicate of #121

**Closed by corbob** 2022-06-30 17:05 UTC
Labels: Duplicate Issue, Documentation
