### ISSUE TITLE
choco install/upgrade stuck on "Calling built-in PowerShell host with"

### ISSUE THREAD

**Issue by gynt** [chocolatey/choco#3059] opened 2023-03-09 16:30 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

The program is getting stuck using all CPU resources when using `choco install` or `choco upgrade` for any package I try it on (`ffmpeg`, `chocolatey`).
Using the `--verbose` and `--debug` options I noticed it is tuck on the last part: Calling built-in PowerShell host.

When I copy the command it is executing (`[System.Threading ... $null`) and run that in PowerShell, it runs fine and is done in seconds.

```
The package ffmpeg wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): A

Calling built-in PowerShell host with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\ffmpeg\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '' -preRunHookScripts $null -postRunHookScripts $null']
Redirecting System.Management.Automation.resources, Version=3.0.0.0, Culture=en-GB, PublicKeyToken=31bf3856ad364e35, requested by ''
```

### What is Expected?

Succesfull installation of the package

``` 
Extracting 64-bit C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg-release-essentials.7z to C:\ProgramData\chocolatey\lib\ffmpeg\tools...
C:\ProgramData\chocolatey\lib\ffmpeg\tools
Removing extracted archive.
Sleeping for 2 seconds to allow anti-viruses to finish scanning...
Renaming ffmpeg directory to common name (Try 1 / 3)
Successfully renamed directory.
```

### How Did You Get This To Happen?
```
choco upgrade all -y
```
I hadn't used chocolatey in a while, so I tried to upgrade, and then I noticed this issue.
So, I started fresh by removing the ProgramData chocolatey folder. I am using version 1.3.0
But that did not help.

Chocolatey has worked for me on my pc in the past (like a year ago), but not anymore.

### System Details

* Operating System: Windows 10
* Windows PowerShell version: 5.1
* Chocolatey CLI Version: 1.3.0
* Chocolatey Licensed Extension version: Chocolatey v1.3.0
* Chocolatey License type: ?
* Terminal/Emulator: powershell

### Installed Packages

```bash
N/A
```

### Output Log

```bash
Chocolatey v1.3.0
Chocolatey is running on Windows v 10.0.19045.0
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
Command line: "C:\ProgramData\chocolatey\choco.exe" install ffmpeg --verbose --debug --force
Received arguments: install ffmpeg --verbose --debug --force
RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
Sending message 'PreRunMessage' out if there are subscribers...
[Pending] Removing all pending packages that should not be considered installed...
Performing validation checks.
Global Configuration Validation Checks:
 - Package Exit Code / Exit On Reboot = Checked
System State Validation Checks:
 Reboot Requirement Checks:
 - Pending Computer Rename = Checked
 - Pending Component Based Servicing = Checked
 - Pending Windows Auto Update = Checked
 - Pending File Rename Operations = Ignored
 - Pending Windows Package Installer = Checked
 - Pending Windows Package Installer SysWow64 = Checked
The source 'https://community.chocolatey.org/api/v2/' evaluated to a 'normal' source type

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='install'|
CacheLocation='C:\Users\gynt\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://community.chocolatey.org/api/v2/'|SourceType='normal'|
Debug='True'|Verbose='True'|Trace='False'|Force='True'|Noop='False'|
HelpRequested='False'|UnsuccessfulParsing='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='True'|
DisableCompatibilityChecks='False'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='ffmpeg'|AllVersions='False'|
SkipPackageInstallProvider='False'|SkipHookScripts='False'|
PackageNames='ffmpeg'|Prerelease='False'|ForceX86='False'|
OverrideArguments='False'|NotSilent='False'|
ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|PinPackage='False'|
Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.19045.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='1.3.0.0'|
Information.ChocolateyProductVersion='1.3.0'|
Information.FullName='choco, Version=1.3.0.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='gynt'|Information.UserDomainName='GYNT'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Information.CurrentDirectory='C:\Windows\System32'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
ListCommand.LocalOnly='False'|ListCommand.IdOnly='False'|
ListCommand.IncludeRegistryPrograms='False'|ListCommand.PageSize='25'|
ListCommand.Exact='False'|ListCommand.ByIdOnly='False'|
ListCommand.ByTagOnly='False'|ListCommand.IdStartsWith='False'|
ListCommand.OrderByPopularity='False'|ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|
ExportCommand.IncludeVersionNumbers='False'|Proxy.BypassOnLocal='True'|
TemplateCommand.Command='unknown'|
_ Chocolatey:ChocolateyInstallCommand - Normal Run Mode _
Installing the following packages:
ffmpeg
By installing, you accept licenses for the packages.
ffmpeg v6.0 already installed. Forcing reinstall of version '6.0'.
 Please use upgrade if you meant to upgrade to a new version.
Attempting to delete directory "C:\ProgramData\chocolatey\lib-bkp\ffmpeg".
Backing up existing ffmpeg prior to operation.
Moving 'C:\ProgramData\chocolatey\lib\ffmpeg'
 to 'C:\ProgramData\chocolatey\lib-bkp\ffmpeg'
Attempting to create directory "C:\ProgramData\chocolatey\lib\ffmpeg".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\.chocolateyPending"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\.chocolateyPending".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\ffmpeg.nupkg"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\ffmpeg.nupkg".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\ffmpeg.nuspec"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\ffmpeg.nuspec".
Attempting to create directory "C:\ProgramData\chocolatey\lib\ffmpeg\legal".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\legal\LICENSE.txt"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\legal\LICENSE.txt".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\legal\VERIFICATION.txt"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\legal\VERIFICATION.txt".
Attempting to create directory "C:\ProgramData\chocolatey\lib\ffmpeg\tools".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\chocolateyInstall.ps1"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\chocolateyInstall.ps1".
Attempting to create directory "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\LICENSE"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\LICENSE".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\README.txt"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\README.txt".
Attempting to create directory "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\bin".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\bin\ffmpeg.exe"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\bin\ffmpeg.exe".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\bin\ffplay.exe"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\bin\ffplay.exe".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\bin\ffprobe.exe"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\bin\ffprobe.exe".
Attempting to create directory "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\bootstrap.min.css"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\bootstrap.min.css".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\default.css"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\default.css".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\developer.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\developer.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\faq.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\faq.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\fate.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\fate.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\ffmpeg-all.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\ffmpeg-all.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\ffmpeg-bitstream-filters.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\ffmpeg-bitstream-filters.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\ffmpeg-codecs.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\ffmpeg-codecs.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\ffmpeg-devices.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\ffmpeg-devices.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\ffmpeg-filters.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\ffmpeg-filters.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\ffmpeg-formats.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\ffmpeg-formats.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\ffmpeg-protocols.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\ffmpeg-protocols.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\ffmpeg-resampler.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\ffmpeg-resampler.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\ffmpeg-scaler.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\ffmpeg-scaler.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\ffmpeg-utils.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\ffmpeg-utils.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\ffmpeg.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\ffmpeg.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\ffplay-all.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\ffplay-all.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\ffplay.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\ffplay.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\ffprobe-all.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\ffprobe-all.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\ffprobe.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\ffprobe.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\general.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\general.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\git-howto.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\git-howto.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\libavcodec.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\libavcodec.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\libavdevice.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\libavdevice.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\libavfilter.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\libavfilter.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\libavformat.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\libavformat.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\libavutil.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\libavutil.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\libswresample.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\libswresample.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\libswscale.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\libswscale.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\mailing-list-faq.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\mailing-list-faq.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\nut.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\nut.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\platform.html"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\platform.html".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\doc\style.min.css"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\doc\style.min.css".
Attempting to create directory "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\presets".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\presets\libvpx-1080p.ffpreset"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\presets\libvpx-1080p.ffpreset".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\presets\libvpx-1080p50_60.ffpreset"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\presets\libvpx-1080p50_60.ffpreset".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\presets\libvpx-360p.ffpreset"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\presets\libvpx-360p.ffpreset".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\presets\libvpx-720p.ffpreset"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\presets\libvpx-720p.ffpreset".
Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\ffmpeg\tools\ffmpeg\presets\libvpx-720p50_60.ffpreset"
 to "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\presets\libvpx-720p50_60.ffpreset".
[NuGet] Uninstalling 'ffmpeg 6.0'.
[NuGet] Removed file 'chocolateyInstall.ps1' to folder 'C:\ProgramData\chocolatey\lib\ffmpeg\tools'.
[NuGet] Removed file 'LICENSE.txt' to folder 'C:\ProgramData\chocolatey\lib\ffmpeg\legal'.
[NuGet] Removed file 'VERIFICATION.txt' to folder 'C:\ProgramData\chocolatey\lib\ffmpeg\legal'.
[NuGet] Removed folder 'C:\ProgramData\chocolatey\lib\ffmpeg\legal'.
[NuGet] Removed file 'ffmpeg.nuspec' to folder 'C:\ProgramData\chocolatey\lib\ffmpeg'.
[NuGet] Removed file 'ffmpeg.nupkg' to folder 'C:\ProgramData\chocolatey\lib\ffmpeg'.
[NuGet] The directory is not empty.

[NuGet] Successfully uninstalled 'ffmpeg 6.0'.
Attempting to delete directory "C:\ProgramData\chocolatey\lib\ffmpeg".
Ensuring removal of package cache files.
[NuGet] Installing 'ffmpeg 6.0'.
[NuGet] Added file 'chocolateyInstall.ps1' to folder 'ffmpeg\tools'.
[NuGet] Added file 'ffmpeg-release-essentials.7z' to folder 'ffmpeg\tools'.
[NuGet] Added file 'LICENSE.txt' to folder 'ffmpeg\legal'.
[NuGet] Added file 'VERIFICATION.txt' to folder 'ffmpeg\legal'.
[NuGet] Added file 'ffmpeg.nupkg' to folder 'ffmpeg'.
[NuGet] Added file 'ffmpeg.nuspec' to folder 'ffmpeg'.
[NuGet] Successfully installed 'ffmpeg 6.0'.

ffmpeg v6.0 (forced) [Approved]
ffmpeg package files install completed. Performing other installation steps.
Setting installer args for ffmpeg
Setting package parameters for ffmpeg
Contents of 'C:\ProgramData\chocolatey\lib\ffmpeg\tools\chocolateyInstall.ps1':
$ErrorActionPreference = 'Stop'

$toolsPath = Split-Path $MyInvocation.MyCommand.Definition

$packageArgs = @{
  PackageName    = $env:ChocolateyPackageName
  FileFullPath64 = "$toolsPath\ffmpeg-release-essentials.7z"
  Destination    = $toolsPath
}

Get-ChildItem $toolsPath\* | Where-Object { $_.PSISContainer } | Remove-Item -Recurse -Force #remove older package dirs
Get-ChocolateyUnzip @packageArgs

Write-Host "Removing extracted archive."
Remove-Item $packageArgs['FileFullPath64'] -ea 0

$maxTries = 3

for ($tries = 0; $tries -lt $maxTries; $tries++) {
  Write-Host "Sleeping for 2 seconds to allow anti-viruses to finish scanning..."
  Start-Sleep -Seconds 2
  try {
    Write-Host "Renaming ffmpeg directory to common name (Try $($tries + 1) / $maxTries)"
    Move-Item $toolsPath\ffmpeg-* $toolsPath\ffmpeg
    Write-Host "Successfully renamed directory."
    break
  }
  catch {
    if (($tries + 1) -eq $maxTries) {
      throw "Unable to rename directory, and max tries achieved. Aborting installation..."
    }
    else {
      Write-Warning "Unable to rename directory. Retrying..."
    }
  }
}

The package ffmpeg wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): A

Calling built-in PowerShell host with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\ffmpeg\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '' -preRunHookScripts $null -postRunHookScripts $null']
Redirecting System.Management.Automation.resources, Version=3.0.0.0, Culture=en-GB, PublicKeyToken=31bf3856ad364e35, requested by ''
```

**Comment by pauby** [comment] 2023-03-09 18:08
Is this a duplicate of #3049 ?

**Comment by pauby** [comment] 2023-03-09 18:19
I cannto reproduce this. As there are no reproduction steps and I had to guess what was being done.

![image](https://user-images.githubusercontent.com/12760779/224118842-067f20e9-eb75-4d66-8f82-75ed3374345f.png)

@gynt If this is not a duplicate of #3049, then please go back to the first and original issue comment and update the section 'How Did You Get This To Happen' with steps (in the format of 1., 2. etc.) of we can reproduce this including any steps that make your environment unique.

**Comment by gynt** [comment] 2023-03-09 19:58
@pauby Done! As this issue appeared out of nowhere, there is not much to say about it.
I am using Avast, so I switched it off and added chocolatey to the exceptions, but to no avail! The issue persists.

**Comment by gynt** [comment] 2023-03-09 20:02
FYI, I am forcing Avast to upgrade now.

**Comment by gynt** [comment] 2023-03-09 20:16
I just upgraded Avast and now it is all working again (Avast version 23.2)
It all makes sense with the issue, as it started out of "nowhere" (who thinks of AV updates breaking stuff?)

Thanks for your help.

Maybe an idea to keep the previous issue open for a little while more?

**Comment by pauby** [comment] 2023-03-10 11:10
The previous issue is resolved so I think being closed is the right step. But I did also unpin it from the repository so I'll add the pin again so it shows up at the top.

Thanks for the suggestion!

**Closed by pauby** 2023-03-10 11:10 UTC
Labels: Bug, 0 - Waiting on User

**Comment by wjb127** [comment] 2024-04-12 07:24
thx I fixed same problem with upgrade
