### ISSUE TITLE
https://chocolatey.org/install.ps1 broken, !Test-Path : The term '!Test-Path' is not recognized as the name of a cmdlet, function, script file, or operable 

### ISSUE THREAD

**Issue by ChrisMagnuson** [chocolatey/choco#1288] opened 2017-05-09 20:58 UTC
### What You Are Seeing?
`cmd /c "@powershell -NoProfile -ExecutionPolicy Bypass -Command ``"iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))``" && SET ``"PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin``""` is erroring with the following output:

```
Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----         5/9/2017   1:45 PM                chocInstall                                                           
Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.5.
!Test-Path : The term '!Test-Path' is not recognized as the name of a cmdlet, function, script file, or operable 
    + CategoryInfo          : NotSpecified: (!Test-Path : Th...e, or operable :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : redacted
 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:188 char:11
+ } elseif (!Test-Path $7zaExe) {
+           ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (!Test-Path:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
NotSpecified: (:) [], RemoteException
Extracting C:\Users\redacted\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\redacted\AppData\Local\Temp\chocolatey\chocInstall...
```

It looks like the issue is in line 188 of install.ps1 `} elseif (!Test-Path $7zaExe) {` should have a space after `!` before `Test-Path`.

**Comment by ReidE96** [comment] 2017-05-09 21:36
Having the same issue here. Space made ISE cry but wrapping parentheses (so `elseif(!(Test-Path $7zaExe))`) worked nicely.

**Comment by ferventcoder** [comment] 2017-05-10 04:36
Howdy folks - this is a duplicate of https://github.com/chocolatey/chocolatey.org/issues/511. We got this corrected at 17:10 CDT after deploying a piece of code that has issues in some versions of PowerShell at 15:23 CDT. The link has more details.

**Closed by ferventcoder** 2017-05-10 04:36 UTC
