### ISSUE TITLE
Linux container only works as root

### ISSUE THREAD

**Issue by adrianschneider94** [chocolatey/choco#3016] opened 2023-02-07 16:08 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

Choco only works in the linux container when it is used with root.

### What is Expected?

Choco in the chocolatey/choco:latest-linux container should work with a non-root user.

### How Did You Get This To Happen?

`docker run -it -u 1000 chocolatey/choco:latest-linux`
`choco -v`

### System Details

* Operating System: Windows 10/Linux Docker
* Windows PowerShell version: -
* Chocolatey CLI Version: latest
* Chocolatey Licensed Extension version: - 
* Chocolatey License type: - 
* Terminal/Emulator: -

### Installed Packages

```bash
N/A
```

### Output Log

```bash
No output appears, just exit code -1.
```

### Additional Context

It works when you run `chmod -R o+rwx /opt/chocolatey && choco -v` as root before running as non-root.

**Comment by TheCakeIsNaOH** [comment] 2023-02-07 18:00
Duplicate of #2942

**Closed by TheCakeIsNaOH** 2023-02-07 18:00 UTC
Labels: Bug
