### ISSUE TITLE
choco pack .\mywebsite.nuspec does NOT resolve/prompt for $variable$ used in nuspec

### ISSUE THREAD

**Issue by curiousdev** [chocolatey/choco#1354] opened 2017-07-05 23:18 UTC
### What You Are Seeing?
```choco pack .\mywebsite.nuspec```
Does NOT fail or warn when `$variable$` used inside the `mywebsite.nuspec` file remains unresolved. This results in the user unware the package is incomplete and missing artifacts.

### What is Expected?
I would expect this to fail or prompt me to pass in the missing variables. Does something like this exist?
```
choco pack .\mywebsite.nuspec -properties "Configuration=Release;Platform=x64"
```

NOTE: The nuget tooling directly supports this:
```
nuget pack .\mywebsite.nuspec -properties "Configuration=Release;Platform=x64"
```

### How Did You Get This To Happen? (Steps to Reproduce)
Try 'choco pack' on a nuspec with $variable$ like the one below
```
<package>
  ...
  <files>
    <file src="..\mywebiste\bin\$platform$\$configuration$\**\*" target="iiswebsite"/>
  </files>
</package>
```

**Comment by ferventcoder** [comment] 2017-07-06 22:54
Duplicate of https://github.com/chocolatey/choco/issues/1313. Please subscribe to that issue and comment there. Thanks!

**Closed by ferventcoder** 2017-07-06 22:54 UTC
