### ISSUE TITLE
Option -l and -e doesn't works both when searching multiple packages

### ISSUE THREAD

**Issue by WiVi71** [chocolatey/choco#2152] opened 2020-11-10 18:31 UTC
### What is Expected?
```choco search -l``` supports multiple package search, for example:
```
C:\windows\system32>choco search gawk curl -l
Chocolatey v0.10.15
curl 7.68.0
gawk 5.1.0
2 packages installed.
```
but this command searches package **contains** the searching filter
```
C:\windows\system32>choco search chocolatey -l
Chocolatey v0.10.15
chocolatey 0.10.15
chocolatey-core.extension 1.3.5.1
chocolatey-dotnetfx.extension 1.0.1
deepl 1.14.1
dotnetfx 4.8.0.20190930
yarn 1.22.5
6 packages installed.
```
to avoid this, -e is required.
```
C:\windows\system32>choco search chocolatey -l -e
Chocolatey v0.10.15
chocolatey 0.10.15
1 packages installed.
```
but it seems that -e does not works with -al when searching multiple packages 
```
C:\windows\system32>choco search chocolatey awk -l -e
Chocolatey v0.10.15
0 packages installed.

Did you know Pro / Business automatically syncs with Programs and
 Features? Learn more about Package Synchronizer at
 https://chocolatey.org/compare
```
If there are hundreds of packages installed with choco, checking if the package is installed with choco list -al will be slow, so I think this should work properly.

### How Did You Get This To Happen? (Steps to Reproduce)
```choco serach curl  jq -l ``` -- works well
```choco serach        jq -l -e``` -- works well
```choco serach curl     -l -e``` -- works well
```choco serach curl jq -l -e``` -- not works

### Output Log
<details>
<summary>Full Log Output</summary>

<p>

~~~sh
C:\windows\system32>choco search chocolatey awk -l -e -v
Chocolatey v0.10.15
0 packages installed.
~~~

</p>

</details>

**Comment by ferventcoder** [comment] 2020-12-08 18:41
Howdy - I found a very similar issue in #2153. I believe this is resolved by the beta version of choco available - `choco upgrade chocolatey --pre`.

**Comment by ferventcoder** [comment] 2020-12-08 18:42
I'm going to mark this as a duplicate for now, but let me know if it needs to be reopened and assessed separately. Thanks in advance!

**Comment by ferventcoder** [comment] 2020-12-08 18:42
Duplicate of #1843

**Closed by ferventcoder** 2020-12-08 18:42 UTC
