### ISSUE TITLE
Choco outdated -r doesn't fully/properly limit the output to only data

### ISSUE THREAD

**Issue by dragon788** [chocolatey/choco#1260] opened 2017-04-21 21:24 UTC
### What You Are Seeing?
`choco outdated -r`
Outdated Packages
 Output is package name | current version | available version | pinned?

7zip|16.04|16.4.0.20170420|false
7zip.install|16.04|16.4.0.20170420|false
Boxstarter|2.8.29|2.9.5|false
Boxstarter.Bootstrapper|2.8.29|2.9.5|false
Boxstarter.Chocolatey|2.8.29|2.9.5|false
Boxstarter.HyperV|2.8.29|2.9.5|false
Boxstarter.WinConfig|2.8.29|2.9.5|false
chocolatey|0.10.3|0.10.5|false
chocolatey-core.extension|1.1.0|1.3.0|false
Clover|3.0.4060.20160428|3.3.4|false
git|2.12.0|2.12.2.2|false
git.install|2.12.0|2.12.2.2|false
notepadplusplus|7.3.2|7.3.3|false
notepadplusplus.install|7.3.2|7.3.3|false
NuGet.CommandLine|3.4.3|3.5.0|false
NugetPackageExplorer|3.21|3.22|false
openssh|0.0.9.20170226|0.0.12.0|false
P4Merge|2015.2.1|2017.1.1491634|false
packer|0.12.2|1.0.0|false
PowerShell|5.1.14409.20170214|5.1.14409.20170402|false
putty|0.68|0.68.0.20170412|false
putty.portable|0.68|0.68.0.20170412|false
python|3.6.0|3.6.1|false
python3|3.6.0|3.6.1|false
rdm|11.6.2.0|12.0.5.0|false
screentogif|2.3.161201|2.7.1|false
temp_BoxstarterPackage|1.0.0|1.0.0|false
vagrant|1.8.6|1.9.3|false
vim-tux|8.0.0320|8.0.0430|false
vim-tux.install|8.0.0320|8.0.0430|false
virtualbox|5.1.14|5.1.20|false
visualstudiocode|1.9.1|1.11.2|false
winmerge|2.14.0|2.14.0.20170224|false

### What is Expected?
No "Outdated Packages and Output is" header

### How Did You Get This To Happen? (Steps to Reproduce)
`choco outdated -r`

**Comment by ferventcoder** [comment] 2017-04-22 00:46
Are you seeing this on 0.10.5?

**Comment by ferventcoder** [comment] 2017-04-22 00:47
Related to #457

**Comment by ferventcoder** [comment] 2017-04-22 00:49
Duplicate of https://github.com/chocolatey/choco/issues/1222. Please upgrade

**Closed by ferventcoder** 2017-04-22 00:49 UTC
