### ISSUE TITLE
Support for MinimumOSVersion

### ISSUE THREAD

**Issue by matbech** [chocolatey/choco#2311] opened 2021-08-07 17:10 UTC
Does the package manifest already support something like "MinimumOSVersion"? If not, it would make sense to support this (including optional MaximumOSVersion) instead of doing the version check in the package chocolateyInstall.ps1 file.

**Comment by corbob** [comment] 2021-08-07 20:28
The package manifest is a nuspec file. IIRC there's nothing in a chocolatey package nuspec that is not in the nuspec reference here: https://docs.microsoft.com/en-us/nuget/reference/nuspec. Given that nuspec doesn't have any way to specify minimum os version, I wouldn't expect to find it in a chocolatey package.

**Comment by TheCakeIsNaOH** [comment] 2021-08-07 20:34
I think this issue is already covered by https://github.com/chocolatey/choco/issues/325. 

> IIRC there's nothing in a chocolatey package nuspec that is not in the nuspec reference here: 

Actually, there are some custom Chocolatey properties that have been added to the `nuget-chocolatey` library. 

- `projectSourceUrl`
- `packageSourceUrl`
- `docsUrl`
- `mailingListUrl`
- `bugTrackerUrl`
- `provides` (not implemented in choco yet)
- `conflicts` (not implemented in choco yet)
- `replaces`(not implemented in choco yet)

See https://github.com/chocolatey/choco/issues/205

**Comment by ferventcoder** [comment] 2021-08-21 15:41
Duplicate of #205

**Closed by ferventcoder** 2021-08-21 15:41 UTC
Labels: Duplicate Issue

**Comment by ferventcoder** [comment] 2021-08-21 15:43
@matbech Thanks for asking about this! Yes, it appears we have an issue that is covering this already. I am not sure if it covers minimum OS version, so it might be a good idea to head over to #325 and add to that discussion.
