### ISSUE TITLE
Can't install on windows 10

### ISSUE THREAD

**Issue by mdrijwan** [chocolatey/choco#2303] opened 2021-07-22 15:36 UTC
STOP RIGHT HERE - DO NOT CREATE A TICKET FOR PACKAGES ON THIS REPOSITORY

This is the repository for choco.exe, the command line interface for Chocolatey, and issues/feature suggestions should be limited to only choco. For a package failure, typically you would be reporting an issue with a package on the community package repository, which is not what this repository represents. In fact, the community repository and all of its packages represents about 5% of the packages in existence and less than half of the usage of choco itself.

  In other words Chocolatey != Chocolatey.org Packages.

For all things packages, you have two routes:

1. If you are having issue with a package or you want to see an enhancement, please see https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process (Package Triage Process / Becoming a maintainer of existing packages).
2. If you are looking for packages to be added to the community package repository (aka https://community.chocolatey.org/packages), please see https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#package-request-package-missing (Package Requests).

NOTE: Keep in mind we have an etiquette regarding communication that we expect folks to observe when they are looking for support in the Chocolatey community. https://github.com/chocolatey/choco/blob/master/README.md#etiquette-regarding-communication
<img width="575" alt="choco" src="https://user-images.githubusercontent.com/22044931/126666981-6ca85712-edfd-4fca-ae4e-79f3ffd1e953.png">

**Comment by corbob** [comment] 2021-08-09 21:51
@mdrijwan Could you provide further information about what issue you're seeing? It looks like you just added a screenshot of a 403 error. Have you done any further troubleshootiing? Have you retried the install since opening this issue? What happens if you try to go to https://chocolatey.org/install.ps1 in a web browser? What about https://community.chocolatey.org/install.ps1?

**Comment by pauby** [comment] 2021-08-11 09:33
I'm going to go ahead and close this as there is not enough information provided to troubleshoot or reproduce.

**Closed by pauby** 2021-08-11 09:33 UTC
Labels: 0 - Waiting on User, Invalid / Not Issue / No repro / Not Implementing
