### ISSUE TITLE
Choco download command ignores --no-progress switch

### ISSUE THREAD

**Issue by peterbarendse** [chocolatey/choco#2065] opened 2020-06-12 07:36 UTC
### What You Are Seeing?
Choco download <package> command ignores --no-progress switch. Also the 'choco feature disable -n=showDownloadProgress' doesn't solve the issue.

### What is Expected?
That choco download <package> download progress can be disabled. It generates massive log files.

### How Did You Get This To Happen? (Steps to Reproduce)
run: choco download <package> --no-progress

**Comment by vexx32** [comment] 2020-06-12 12:16
I'm pretty sure this one's been resolved; see https://github.com/chocolatey/chocolatey-licensed-issues/issues/104

**Comment by ferventcoder** [comment] 2020-06-15 20:58
@peterbarendse done, working on release at the moment. This is a duplicate of what @vexx32 mentioned. I'm going to move this issue to that repo and mark it as a duplicate properly. Thanks for the report!

**Closed by ferventcoder** 2020-06-15 20:58 UTC
