### ISSUE TITLE
Installing a prerelease package without `--pre` doesn't produce a useful error message

### ISSUE THREAD

**Issue by Spitzbub** [chocolatey/choco#749] opened 2016-05-26 21:50 UTC
See #553 

Without realising it I created a pre-release package, i.e. by putting a `-` in its version. When I tried to install I received an error message that didn't lead me to what the problem was. Instead I almost got to the point of submitting a bug report.... and now I'm submitting this one instead :-)

```
C:\Users\RussellMora\Dropbox (aboutGolf)\Chocolatey\aG Sim Setup\agsimsetup\src\main>choco install agsimsetup.2.2.1.0-b40.nupkg
Installing the following packages:
agsimsetup.2.2.1.0-b40.nupkg
By installing you accept licenses for the packages.
agsimsetup not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "C:\Users\RussellMora\Dropbox (aboutGolf)\Chocolatey\aG Sim Setup\agsimsetup\src\main"

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - agsimsetup

C:\Users\RussellMora\Dropbox (aboutGolf)\Chocolatey\aG Sim Setup\agsimsetup\src\main>
```

**Comment by ferventcoder** [comment] 2016-05-27 22:55
I think #750 is a duplicate of this, even though it may not seem like it - it's essentially not accounting for the prerelease switch, so it will either find another package or nothing at all.

**Comment by ferventcoder** [comment] 2016-05-27 22:55
#523

**Comment by ferventcoder** [comment] 2016-05-27 22:56
Now that I think of it, these are both duplicates of #523.

**Comment by ferventcoder** [comment] 2016-05-27 22:59
@Spitzbub please subscribe to that other issue 👍

**Closed** 2016-05-27 22:59 UTC
Labels: Duplicate Issue
