### ISSUE TITLE
Problems to update some softwares

### ISSUE THREAD

**Issue by patdu59** [chocolatey/choco#1954] opened 2019-11-14 16:51 UTC
Hi everyone :)
I've been using chocolatey in my school for a couple of months now. So far, it has always worked very fine.
Today, I wanted to update my softwares.
As usual, I opened a CMD window as an administrator and typed :
choco update all -y
About half of the softwares could get the update.
There were errors for the other half.

I tried to update again. Same problem.

With the choco GUI, I clicked on the softwares that couldn't get the update and chose "update".
Same problem, impossible to update them and I got an error message
![Choco 2](https://user-images.githubusercontent.com/30406004/68877792-ef0c9980-0706-11ea-91d8-3d71546dee4d.jpg)

It is impossible to update them
![Choco 3](https://user-images.githubusercontent.com/30406004/68877885-15cad000-0707-11ea-8d77-fbf3f36e14a8.jpg)

When I uninstalled flash player for instance, I tried to reinstall it with my CMD window (as an administrator), but nothing happened :
![Choco 1](https://user-images.githubusercontent.com/30406004/68878007-4579d800-0707-11ea-976b-c690b2bd84c5.jpg)

Any idea how I can solve this problem please ?
Thanks in advance :)

**Comment by AdmiringWorm** [comment] 2019-11-14 17:03
duplicate of #1953 and not a problem with choco itself, but rather an extension that the package uses (A new version to fix that issue have been pushed, and is currently going through moderation).

See issue: https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1373 for more information

**Comment by patdu59** [comment] 2019-11-14 17:14
Thanks for your answer !
Any idea why when I type choco install plashplayerplugin nothing happens ?

**Comment by AdmiringWorm** [comment] 2019-11-14 17:19
Assuming that you meant `flashplayerplugin`, then no I don't really know.

There is one possibility that I am aware of though, powershell sometimes have a tendency to stop outputting any text to the console, if that is the case all you should need to do is press `{Enter}` to get it started again.

**Comment by patdu59** [comment] 2019-11-18 16:41
Hi again :)
I tried to update some softwares.
Chocolatey Core is uptodate. Powershell too.
When I type "cup all -y" nothing happens
When I use chocolatey GUI, it keeps failing because of a checksums problem...
Any idea how I can solve this problem please ?
Thanks in advance

**Comment by ferventcoder** [comment] 2020-02-04 20:55
As this doesn't appear to be an issue with choco.exe, I'm going to close the issue on this repo.

**Closed by ferventcoder** 2020-02-04 20:55 UTC
Labels: 0 - _Triaging
