### ISSUE TITLE
Choco not pushing with stored api key for source

### ISSUE THREAD

**Issue by bc3tech** [chocolatey/choco#234] opened 2015-04-09 02:28 UTC
Trying to push to choco.org:
```
> choco apikey https://chocolatey.org

Chocolatey v0.9.9.4
https://chocolatey.org - 0a00....
```
Now trying to push a pkg out to choco (w/o specifying api key cuz I shouldn't have to now)
```
> choco push .\mypkg.nupkg
Chocolatey v0.9.9.4
An ApiKey was not found for 'https://chocolatey.org/'. You must either set an api key in the configuration or specify one with --api-key.
```

**Comment by ferventcoder** [comment] 2015-04-09 02:45
Note the `/`

**Comment by ferventcoder** [comment] 2015-04-09 02:46
As in the difference between `https://chocolatey.org` and `https://chocolatey.org/`

**Comment by bc3tech** [comment] 2015-04-09 02:55
oof. yup that did it.
any way we could make this a non-issue?

**Comment by ferventcoder** [comment] 2015-04-09 03:23
Shall we file a new issue?

**Comment by bc3tech** [comment] 2015-04-09 11:43
I could just rename this one if that's acceptable.

**Comment by ferventcoder** [comment] 2015-04-09 15:20
Yeah, the problem is the conversation would need to be deleted...

**Comment by ferventcoder** [comment] 2015-04-09 15:20
Open a new one and reference this. Then we will close this one.

**Closed** 2015-04-10 00:25 UTC
Labels: 0 - _Triaging
