### ISSUE TITLE
"exit 0" fails

### ISSUE THREAD

**Issue by Link-Satonaka** [chocolatey/choco#514] opened 2015-12-22 21:32 UTC
Start-ChocolateyProcessAsAdmin "/K $toolsDir\mpv-install.bat" 'cmd.exe' -validExitCodes $validExitCodes

where mpv-install.bat has the line 
`exit 0`
https://github.com/rossy/mpv-install/blob/master/mpv-install.bat#L179

The above chocolatey command interprets this as an error
` [ERROR] Running cmd.exe with /K C:\ProgramData\chocolatey\lib\mpv\tools\mpv-install.bat was not successful. Exit code was '0' Error Message:`

Is zero not a valid exit code?

**Comment by ferventcoder** [comment] 2015-12-22 21:49
Duplicate of another issue.

**Comment by ferventcoder** [comment] 2015-12-22 21:50
Duplicate of  https://github.com/chocolatey/choco/issues/445

**Comment by ferventcoder** [comment] 2015-12-22 21:51
For reference it has nothing to do with the exit 0, and it has everything to do with something in the stderr stream.

**Closed by ferventcoder** 2015-12-22 21:51 UTC
Labels: Duplicate Issue

**Comment by Link-Satonaka** [comment] 2015-12-22 22:08
Ah, sorry

**Comment by ferventcoder** [comment] 2015-12-22 22:32
No worries, it's not necessarily easy to know it's a duplicate. That's why I'm here to help triage. :)
