### ISSUE TITLE
Chocolatey in other languages...

### ISSUE THREAD

**Issue by WaggBR** [chocolatey/choco#2000] opened 2020-02-08 01:43 UTC
I am using Choco for a short time, and I believe that it is entirely in English, but I would like to know if it is possible to translate the phrases, dialogues of the program that is answered to the user after a cmd command.
For example:
**What is answered when typing** _choco -?_

How could I translate it into my language?
Not changing the commands, just replying them.

Sorry if this is not the right place for this type of doubt.

**Comment by ferventcoder** [comment] 2020-04-15 18:08
This is something we want to do, but no small undertaking. We would be looking to implement similar to what Chocolatey GUI is doing using Transifex. That said, we are still quite aways off from this.

**Comment by ferventcoder** [comment] 2020-04-15 18:08
Might be related to #1441

**Comment by ferventcoder** [comment] 2020-04-15 18:08
Duplicate of #1441.

**Comment by ferventcoder** [comment] 2020-04-15 18:09
@WaggBR I found the issue we had for this - please follow #1441 and comment there. Thanks!

**Closed by ferventcoder** 2020-04-15 18:08 UTC
