### ISSUE TITLE
Add possibility to set an output folder for choco pack

### ISSUE THREAD

**Issue by laedit** [chocolatey/choco#598] opened 2016-02-01 13:50 UTC
Like [`nuget pack`](https://docs.nuget.org/consume/command-line-reference#pack-command) it could be useful to have the `-OutputDirectory` option.

**Comment by ferventcoder** [comment] 2016-02-01 14:50
possible dupe of #173

**Comment by ferventcoder** [comment] 2016-02-01 14:52
Actually, just related to. We'll work on adding this behavior as part of this issue.

**Comment by gep13** [comment] 2016-02-01 19:46
When this gets added, I will update the Cake integration to add this additional parameter to the ChocolateyPack command that it has.

**Comment by laedit** [comment] 2016-02-02 05:19
Since it is up for grabs, I volunteer to contribute.
If I understand, the evolution will consist to add a `PackCommandConfiguration` in `ChocolateyConfiguration` with a `OutputDirectory` property and use it from the command to the `NugetService`.

**Comment by ferventcoder** [comment] 2016-02-02 18:20
Not quite, we already have an output directory? If not, then yes.

**Comment by ferventcoder** [comment] 2016-02-02 18:54
Output directory at top level, not inside of the other commands that is.

**Comment by laedit** [comment] 2016-02-03 06:52
Since it can be used by other command (like new in #448) I wonder if it's preferable to add the `OutputDirectory` property to `ChocolateyConfiguration` directly and not in a subcommand configuration?

**Comment by ferventcoder** [comment] 2016-02-03 17:55
I think it would be good as a top level configuration, but perhaps each command has to opt in to offering it though.

**Comment by ferventcoder** [comment] 2016-08-10 11:07
Merged into stable at https://github.com/chocolatey/choco/commit/4da5a6f61023e8a2686f55a91c7933429e7b773e to release in 0.10.0.

**Closed by ferventcoder** 2016-08-10 11:08 UTC
Labels: 3 - Done, Enhancement, Priority_LOW, Up For Grabs
