### ISSUE TITLE
Unable to upgrade chocolatey/install new packages

### ISSUE THREAD

**Issue by corbinabeebe** [chocolatey/choco#3040] opened 2023-02-21 16:41 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

Chocolatey stalls when trying to install new packages.  

I first tried to install yarn and for the following message `Performing other installation steps.` however, the system does nothing after this. Ctrl-C to exit, ran yarn start - system replied with no yarn installed.

Tried to upgrade choco with choco upgrade chocolatey -y, got the same error messages: `Upgrading the following packages:
chocolatey
By upgrading you accept licenses for the packages.
chocolatey is not installed. Installing...

chocolatey v1.3.0
chocolatey package files upgrade completed. Performing other installation steps.
`

### What is Expected?

I expect all required packages to be installed and I should be able to enter another command into the shell

### How Did You Get This To Happen?

 upgrade choco with choco upgrade chocolatey -y

### System Details

* Operating System: Windows
* Windows PowerShell version:5 and 7
* Chocolatey CLI Version: v.10.15
* Chocolatey Licensed Extension version: not sure
* Chocolatey License type: not sure
* Terminal/Emulator: powershell via terminal

### Installed Packages

```bash
this is occuring when trying to upgrade choocolatey and when trying to install any new package
```

### Output Log

```bash
`


2023-02-21 08:39:02,651 30760 [INFO ] - chocolatey package files upgrade completed. Performing other installation steps.
2023-02-21 08:39:02,786 30760 [DEBUG] - Setting installer args for chocolatey
2023-02-21 08:39:02,787 30760 [DEBUG] - Setting package parameters for chocolatey
2023-02-21 08:39:02,787 30760 [DEBUG] - Contents of 'C:\ProgramData\chocolatey\lib\chocolatey\tools\chocolateyInstall.ps1':
2023-02-21 08:39:02,796 30760 [DEBUG] - $toolsPath = Split-Path -Parent $MyInvocation.MyCommand.Definition

# Ensure module loading preference is on
$PSModuleAutoLoadingPreference = "All"

$licensedAssembly = [System.AppDomain]::CurrentDomain.GetAssemblies() |
    Where-Object { $_.GetName().Name -eq 'chocolatey.licensed' } |
    Select-Object -First 1

if ($null -ne $licensedAssembly) {
    # The licensed assembly is installed, check its supported Chocolatey versions and/or the assembly
    # version so we can attempt to determine whether it's compatible with this version of Chocolatey.
    $attributeData = $licensedAssembly.GetCustomAttributes($true)

    $minVersion = $attributeData |
        Where-Object { $_.TypeId -like '*MinimumChocolateyVersion*' } |
        Select-Object -ExpandProperty Version -First 1

    $borderWidth = 70
    try {
        $borderWidth = [System.Console]::BufferWidth - 10
    } catch {
        # Do nothing. This means we're in a non-interactive environment without a console attached.
    }

    $messageBorder = '=' * $borderWidth
    $extensionVersionWarning = @"
$messageBorder

You are installing a version of Chocolatey that may not be compatible with the currently installed version of the chocolatey.extension package.
Running Chocolatey with the current version of the chocolatey.extension package is an unsupported configuration.
See https://ch0.co/compatibility for more information.

If you are also modifying the chocolatey.extension package, you can ignore this warning.

$messageBorder
"@

    if ($null -ne $minVersion) {
        # Found an explicit attribute declaring what version(s) of Chocolatey the current licensed
        # assembly is known to work with.
        # Check what Chocolatey version we're installing in Major.Minor.Patch form, stripping off any prerelease suffix
        $packageVersion = $env:ChocolateyPackageVersion -replace '-.+$' -as [System.Version]

        if ($packageVersion -lt $minVersion) {
            Write-Warning $extensionVersionWarning
        }
    }
    else {
        $version = $attributeData |
            Where-Object { $_.TypeId -like '*AssemblyInformationalVersion*' } |
            Select-Object -ExpandProperty InformationalVersion -First 1

        # Strip off quotes and prerelease suffix if present, that's not critical for this check.
        $version = $version -replace '-.+$' -as [System.Version]

        if ($version.Major -lt 4) {
            Write-Warning $extensionVersionWarning
        }
    }
}

$modules = Get-ChildItem $toolsPath -Filter *.psm1
$modules | ForEach-Object {
	  $psm1File = $_.FullName
	  $moduleName = [System.IO.Path]::GetFileNameWithoutExtension($psm1File)

	  if (Get-Module $moduleName) {
        Remove-Module $moduleName -ErrorAction SilentlyContinue
    }

	  Import-Module -Name $psm1File
}

Initialize-Chocolatey


2023-02-21 08:39:02,809 30760 [DEBUG] - Calling built-in PowerShell host with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\chocolatey\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters ''']
2023-02-21 08:39:02,810 30760 [DEBUG] - Redirecting System.Management.Automation.resources, Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35, requested by ''
`
```

**Comment by pauby** [comment] 2023-02-21 16:51
Are you running Avast? If so it would be a duplicate of this issue #3034

**Comment by pauby** [comment] 2023-02-24 15:31
I appreciate it's been a short time, but I am fairly certain thsi is a duplicate of #3034. Closing the issue but we can always reopn it again if that is not the case.

**Closed by pauby** 2023-02-24 15:31 UTC
Labels: Bug
