### ISSUE TITLE
pack - does not support semantic versioning v2

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/choco#1528] opened 2018-03-27 10:55 UTC
### What You Are Seeing?
cpack complains that the version 6.1.0-preview.1 is not valid when used in a dependency. 

### What is Expected?
pre-release versions with a "." after the "-" appear to be valid - however the semver.org page is a bit ambigeous as it does not show it in the character list, but does show it in an example on item 9 here: https://semver.org/

### How Did You Get This To Happen? (Steps to Reproduce)
Create a .nuspec which uses 6.1.0-preview.1 it's version and dependency.

### Output Log

**In this screenshot the first error appears to be generated by the dependency, the dependency was reformatted to pass validation (the way it is in the screenshot) and the second error specifically identifies the version tag - so it appears to check both.**  

![image](https://user-images.githubusercontent.com/11597190/37963176-7a866afc-318b-11e8-975a-2d262748c9e8.png)

**Comment by ferventcoder** [comment] 2018-09-26 03:41
Duplicate of #1610

**Comment by ferventcoder** [comment] 2018-09-26 03:41
I marked it this way as a duplicate as the other was filed as an enhancement, which this would be.

**Closed by ferventcoder** 2018-09-26 03:41 UTC
Labels: Duplicate Issue
