### ISSUE TITLE
RefreshEnv not working

### ISSUE THREAD

**Issue by joeledwardson** [chocolatey/choco#3058] opened 2023-03-07 11:59 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

`RefreshEnv` does not load environment variables

### What is Expected?

`NVM_HOME` to be set after calling `RefreshEnv`

### How Did You Get This To Happen?

1. Run `choco install nvm`
2. Run `RefreshEnv`
3. Run `$env:NVM_HOME` and it will be blank
4. Open a new powershell terminal and `$env:NVM_HOME` will be set

### System Details

* Operating System:  10.0.22621.0   
* Windows PowerShell version:   5.1.22621.963   
* Chocolatey CLI Version: 1.3.0
* Chocolatey Licensed Extension version:
Chocolatey v1.3.0                                                                                                       
 packages installed.  
* Chocolatey License type:
* Terminal/Emulator:

### Installed Packages

```bash
PS C:\WINDOWS\system32> choco list -lo                                                                                  Chocolatey v1.3.0                                                                                                       adb 34.0.0                                                                                                              chocolatey 1.3.0                                                                                                        chocolatey-compatibility.extension 1.0.0                                                                                chocolatey-core.extension 1.4.0                                                                                         chocolatey-windowsupdate.extension 1.0.5                                                                                git 2.39.2                                                                                                              git.install 2.39.2                                                                                                      KB2919355 1.0.20160915                                                                                                  KB2919442 1.0.20160915                                                                                                  KB2999226 1.0.20181019                                                                                                  KB3033929 1.0.5                                                                                                         KB3035131 1.0.3                                                                                                         nvm 1.1.9                                                                                                               nvm.install 1.1.9                                                                                                       openssl 1.1.1.2000                                                                                                      scrcpy 1.24                                                                                                             vcredist140 14.34.31938                                                                                                 vcredist2015 14.0.24215.20170201                                                                                        18 packages installed.
```

### Output Log

```bash
PS C:\WINDOWS\system32> cat C:\ProgramData\chocolatey\logs\chocolatey.log | findstr nvm                                 2023-03-07 11:32:19,777 9084 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" install git scrcpy adb nvm cloudflared openssl                                                                                                       2023-03-07 11:32:19,777 9084 [DEBUG] - Received arguments: install git scrcpy adb nvm cloudflared openssl               Input='git scrcpy adb nvm cloudflared openssl'|AllVersions='False'|                                                     PackageNames='git;scrcpy;adb;nvm;cloudflared;openssl'|                                                                  2023-03-07 11:32:19,882 9084 [INFO ] - git;scrcpy;adb;nvm;cloudflared;openssl                                           2023-03-07 11:34:01,257 9084 [DEBUG] - Package 'nvm' found on source 'https://community.chocolatey.org/api/v2/'         2023-03-07 11:34:01,257 9084 [INFO ] - [NuGet] Attempting to resolve dependency 'nvm.install (= 1.1.9)'.                2023-03-07 11:34:02,741 9084 [INFO ] - [NuGet] Installing 'nvm.install 1.1.9'.                                          2023-03-07 11:34:02,741 9084 [DEBUG] - [NuGet] Added file 'chocolateyinstall.ps1' to folder 'nvm.install\tools'.        2023-03-07 11:34:02,741 9084 [DEBUG] - [NuGet] Added file 'chocolateyuninstall.ps1' to folder 'nvm.install\tools'.      2023-03-07 11:34:02,756 9084 [DEBUG] - [NuGet] Added file 'nvm.install.nupkg' to folder 'nvm.install'.                  2023-03-07 11:34:02,964 9084 [DEBUG] - [NuGet] Added file 'nvm.install.nuspec' to folder 'nvm.install'.                 2023-03-07 11:34:02,964 9084 [INFO ] - [NuGet] Successfully installed 'nvm.install 1.1.9'.                              nvm.install v1.1.9 [Approved]                                                                                           2023-03-07 11:34:02,964 9084 [INFO ] - nvm.install package files install completed. Performing other installation steps.                                                                                                                        2023-03-07 11:34:02,975 9084 [DEBUG] - Setting installer args for nvm.install                                           2023-03-07 11:34:02,975 9084 [DEBUG] - Setting package parameters for nvm.install                                       2023-03-07 11:34:02,975 9084 [DEBUG] - Contents of 'C:\ProgramData\chocolatey\lib\nvm.install\tools\chocolateyinstall.ps1':                                                                                                                     $nvmPath = Join-Path $env:ProgramData 'nvm'                                                                               url           = 'https://github.com/coreybutler/nvm-windows/releases/download/1.1.9/nvm-setup.zip'                    New-Item -Path "$toolsDir\nvm-setup.exe.ignore" -ItemType File                                                          Start-Process $toolsDir\nvm-setup.exe -ArgumentList "/VERYSILENT /NOCIONS /DIR=$nvmPath"                                2023-03-07 11:34:02,975 9084 [DEBUG] - Calling built-in PowerShell host with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\nvm.install\tools\chocolateyinstall.ps1' -installArguments '' -packageParameters '' -preRunHookScripts $null -postRunHookScripts $null']                                                                 2023-03-07 11:34:03,138 9084 [DEBUG] - Running 'ChocolateyScriptRunner' for nvm.install v1.1.9 with packageScript 'C:\ProgramData\chocolatey\lib\nvm.install\tools\chocolateyinstall.ps1', packageFolder:'C:\ProgramData\chocolatey\lib\nvm.install', installArguments: '', packageParameters: '', preRunHookScripts: '', postRunHookScripts: '',                       2023-03-07 11:34:03,154 9084 [DEBUG] - Running package script 'C:\ProgramData\chocolatey\lib\nvm.install\tools\chocolateyinstall.ps1'                                                                                                           2023-03-07 11:34:03,163 9084 [DEBUG] - Running Install-ChocolateyZipPackage -unzipLocation 'C:\ProgramData\chocolatey\lib\nvm.install\tools' -checksum '93c135ba59f13b7138a8216b3ef03d88f88d1e3e8420ccbb681244a9070aa475' -checksumType 'sha256' -url 'https://github.com/coreybutler/nvm-windows/releases/download/1.1.9/nvm-setup.zip' -packageName 'nvm.install'     2023-03-07 11:34:03,163 9084 [DEBUG] - Running Get-ChocolateyWebFile -checksum '93c135ba59f13b7138a8216b3ef03d88f88d1e3e8420ccbb681244a9070aa475' -checksumType 'sha256' -checksum64 '' -checksumType64 '' -options 'System.Collections.Hashtable' -getOriginalFileName 'True' -packageName 'nvm.install' -fileFullPath 'C:\Users\Mobile_Four\AppData\Local\Temp\chocolatey\nvm.install\1.1.9\nvm.installInstall.zip' -url 'https://github.com/coreybutler/nvm-windows/releases/download/1.1.9/nvm-setup.zip' -url64bit ''                                                                                              2023-03-07 11:34:03,170 9084 [DEBUG] - Running Get-WebFileName -url 'https://github.com/coreybutler/nvm-windows/releases/download/1.1.9/nvm-setup.zip' -defaultName 'nvm.installInstall.zip'                                                    2023-03-07 11:34:03,612 9084 [DEBUG] - File name determined from url is 'nvm-setup.zip'                                 2023-03-07 11:34:03,612 9084 [DEBUG] - Running Get-WebHeaders -url 'https://github.com/coreybutler/nvm-windows/releases/download/1.1.9/nvm-setup.zip' -ErrorAction 'Stop'                                                                       2023-03-07 11:34:03,752 9084 [DEBUG] -   'Content-Disposition':'attachment; filename=nvm-setup.zip'                     2023-03-07 11:34:03,752 9084 [INFO ] - Downloading nvm.install                                                            from 'https://github.com/coreybutler/nvm-windows/releases/download/1.1.9/nvm-setup.zip'                               2023-03-07 11:34:03,768 9084 [DEBUG] - Running Get-WebFile -url 'https://github.com/coreybutler/nvm-windows/releases/download/1.1.9/nvm-setup.zip' -fileName 'C:\Users\Mobile_Four\AppData\Local\Temp\chocolatey\nvm.install\1.1.9\nvm-setup.zip' -options 'System.Collections.Hashtable'                                                                               2023-03-07 11:34:05,225 9084 [DEBUG] - Downloading https://github.com/coreybutler/nvm-windows/releases/download/1.1.9/nvm-setup.zip to C:\Users\Mobile_Four\AppData\Local\Temp\chocolatey\nvm.install\1.1.9\nvm-setup.zip                       2023-03-07 11:34:05,944 9084 [INFO ] - Download of nvm-setup.zip (4.14 MB) completed.                                   2023-03-07 11:34:08,951 9084 [DEBUG] - Verifying package provided checksum of '93c135ba59f13b7138a8216b3ef03d88f88d1e3e8420ccbb681244a9070aa475' for 'C:\Users\Mobile_Four\AppData\Local\Temp\chocolatey\nvm.install\1.1.9\nvm-setup.zip'.      2023-03-07 11:34:08,951 9084 [DEBUG] - Running Get-ChecksumValid -file 'C:\Users\Mobile_Four\AppData\Local\Temp\chocolatey\nvm.install\1.1.9\nvm-setup.zip' -checksum '93c135ba59f13b7138a8216b3ef03d88f88d1e3e8420ccbb681244a9070aa475' -checksumType 'sha256' -originalUrl 'https://github.com/coreybutler/nvm-windows/releases/download/1.1.9/nvm-setup.zip'         2023-03-07 11:34:08,951 9084 [DEBUG] - Executing command ['C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe' -c="93c135ba59f13b7138a8216b3ef03d88f88d1e3e8420ccbb681244a9070aa475" -t="sha256" -f="C:\Users\Mobile_Four\AppData\Local\Temp\chocolatey\nvm.install\1.1.9\nvm-setup.zip"]                                                                          2023-03-07 11:34:08,998 9084 [DEBUG] - Command ['C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe' -c="93c135ba59f13b7138a8216b3ef03d88f88d1e3e8420ccbb681244a9070aa475" -t="sha256" -f="C:\Users\Mobile_Four\AppData\Local\Temp\chocolatey\nvm.install\1.1.9\nvm-setup.zip"] exited with '0'.                                                                   2023-03-07 11:34:08,998 9084 [DEBUG] - Running Get-ChocolateyUnzip -disableLogging 'False' -fileFullPath 'C:\Users\Mobile_Four\AppData\Local\Temp\chocolatey\nvm.install\1.1.9\nvm-setup.zip' -destination 'C:\ProgramData\chocolatey\lib\nvm.install\tools' -specificFolder '' -packageName 'nvm.install'                                                              2023-03-07 11:34:08,998 9084 [INFO ] - Extracting C:\Users\Mobile_Four\AppData\Local\Temp\chocolatey\nvm.install\1.1.9\nvm-setup.zip to C:\ProgramData\chocolatey\lib\nvm.install\tools...                                                      2023-03-07 11:34:08,998 9084 [DEBUG] - Executing command ['C:\ProgramData\chocolatey\tools\7z.exe' x -aoa -bd -bb1 -o"C:\ProgramData\chocolatey\lib\nvm.install\tools" -y "C:\Users\Mobile_Four\AppData\Local\Temp\chocolatey\nvm.install\1.1.9\nvm-setup.zip"]                                                                                                         2023-03-07 11:34:09,061 9084 [INFO ] - VERBOSE: Extracting archive: C:\Users\Mobile_Four\AppData\Local\Temp\chocolatey\nvm.install\1.1.9\nvm-setup.zip                                                                                          2023-03-07 11:34:09,061 9084 [INFO ] - VERBOSE: Path = C:\Users\Mobile_Four\AppData\Local\Temp\chocolatey\nvm.install\1.1.9\nvm-setup.zip                                                                                                       2023-03-07 11:34:09,061 9084 [INFO ] - VERBOSE: - nvm-setup.exe                                                         2023-03-07 11:34:09,061 9084 [DEBUG] - Command ['C:\ProgramData\chocolatey\tools\7z.exe' x -aoa -bd -bb1 -o"C:\ProgramData\chocolatey\lib\nvm.install\tools" -y "C:\Users\Mobile_Four\AppData\Local\Temp\chocolatey\nvm.install\1.1.9\nvm-setup.zip"] exited with '0'.                                                                                                  2023-03-07 11:34:09,069 9084 [INFO ] - C:\ProgramData\chocolatey\lib\nvm.install\tools                                  2023-03-07 11:34:09,069 9084 [INFO ] - C:\ProgramData\chocolatey\lib\nvm.install\tools\nvm-setup.exe.ignore             2023-03-07 11:34:09,132 9084 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\nvm.install\tools\chocolateyinstall.ps1' -installArguments '' -packageParameters '' -preRunHookScripts $null -postRunHookScripts $null'] exited with '0'.                                                 2023-03-07 11:34:09,163 9084 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\nvm.install'           2023-03-07 11:34:09,163 9084 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\nvm.install\nvm-setup.zip.txt'             2023-03-07 11:34:09,163 9084 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\nvm.install\nvm.install.nupkg'             2023-03-07 11:34:09,163 9084 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\nvm.install\nvm.install.nuspec'            2023-03-07 11:34:09,163 9084 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\nvm.install\tools\chocolateyinstall.ps1'   2023-03-07 11:34:09,172 9084 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\nvm.install\tools\chocolateyuninstall.ps1' 2023-03-07 11:34:09,172 9084 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\nvm.install\tools\nvm-setup.exe'           2023-03-07 11:34:09,172 9084 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\nvm.install\tools\nvm-setup.exe.ignore'    2023-03-07 11:34:09,172 9084 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\.chocolatey\nvm.install.1.1.9".                                                                                                                2023-03-07 11:34:09,172 9084 [DEBUG] - There was no original file at 'C:\ProgramData\chocolatey\.chocolatey\nvm.install.1.1.9\.files'                                                                                                           2023-03-07 11:34:09,187 9084 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\nvm.install.1.1.9\.extra".                                                                                                              2023-03-07 11:34:09,187 9084 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\nvm.install.1.1.9\.version".                                                                                                            2023-03-07 11:34:09,187 9084 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\nvm.install.1.1.9\.sxs".                                                                                                                2023-03-07 11:34:09,187 9084 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\nvm.install.1.1.9\.pin".                                                                                                                2023-03-07 11:34:09,187 9084 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\lib\nvm.install\.chocolateyPending".                                                                                                                2023-03-07 11:34:09,187 9084 [INFO ] -  The install of nvm.install was successful.                                      2023-03-07 11:34:09,187 9084 [INFO ] -   Software installed to 'C:\ProgramData\chocolatey\lib\nvm.install\tools'        2023-03-07 11:34:09,194 9084 [INFO ] - [NuGet] Installing 'nvm 1.1.9'.                                                  2023-03-07 11:34:09,194 9084 [DEBUG] - [NuGet] Added file 'nvm.nupkg' to folder 'nvm'.                                  2023-03-07 11:34:09,409 9084 [DEBUG] - [NuGet] Added file 'nvm.nuspec' to folder 'nvm'.                                 2023-03-07 11:34:09,409 9084 [INFO ] - [NuGet] Successfully installed 'nvm 1.1.9'.                                      nvm v1.1.9 [Approved]                                                                                                   2023-03-07 11:34:09,413 9084 [INFO ] - nvm package files install completed. Performing other installation steps.        2023-03-07 11:34:09,413 9084 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\nvm'                   2023-03-07 11:34:09,413 9084 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\nvm\nvm.nupkg'                             2023-03-07 11:34:09,413 9084 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\nvm\nvm.nuspec'                            2023-03-07 11:34:09,425 9084 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\.chocolatey\nvm.1.1.9".                                                                                                                        2023-03-07 11:34:09,425 9084 [DEBUG] - There was no original file at 'C:\ProgramData\chocolatey\.chocolatey\nvm.1.1.9\.files'                                                                                                                   2023-03-07 11:34:09,425 9084 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\nvm.1.1.9\.extra".                                                                                                                      2023-03-07 11:34:09,425 9084 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\nvm.1.1.9\.version".                                                                                                                    2023-03-07 11:34:09,425 9084 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\nvm.1.1.9\.sxs".                                                                                                                        2023-03-07 11:34:09,425 9084 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\nvm.1.1.9\.pin".                                                                                                                        2023-03-07 11:34:09,425 9084 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\lib\nvm\.chocolateyPending".                                                                                                                        2023-03-07 11:34:09,425 9084 [INFO ] -  The install of nvm was successful.                                              2023-03-07 11:34:09,425 9084 [INFO ] -   Software installed to 'C:\ProgramData\chocolatey\lib\nvm'                      2023-03-07 11:34:09,425 9084 [DEBUG] - Attempting to delete file "C:\Users\Mobile_Four\AppData\Local\NuGet\Cache\nvm.1.1.9.nupkg".                                                                                                              2023-03-07 11:40:09,116 9084 [INFO ] -  - nvm.install v1.1.9                                                            2023-03-07 11:40:09,116 9084 [INFO ] -  - nvm v1.1.9                                                                    2023-03-07 11:40:53,971 13996 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" install git scrcpy adb nvm openssl                                                                                                                  2023-03-07 11:40:53,971 13996 [DEBUG] - Received arguments: install git scrcpy adb nvm openssl                          AllowUnofficialBuild='False'|Input='git scrcpy adb nvm openssl'|                                                        SkipHookScripts='False'|PackageNames='git;scrcpy;adb;nvm;openssl'|                                                      2023-03-07 11:40:54,097 13996 [INFO ] - git;scrcpy;adb;nvm;openssl                                                      2023-03-07 11:40:54,208 13996 [WARN ] - nvm v1.1.9 already installed.                                                   2023-03-07 11:40:54,239 13996 [WARN ] -  - nvm - nvm v1.1.9 already installed.                                          2023-03-07 11:57:44,769 14256 [INFO ] - nvm 1.1.9                                                                       2023-03-07 11:57:44,769 14256 [INFO ] - nvm.install 1.1.9                                                               2023-03-07 11:58:02,506 9184 [INFO ] - nvm 1.1.9                                                                        2023-03-07 11:58:02,506 9184 [INFO ] - nvm.install 1.1.9
```

**Comment by pauby** [comment] 2023-03-07 12:25
This appears to be a duplicate of #1417

**Closed by pauby** 2023-03-07 12:25 UTC
Labels: Bug
