### ISSUE TITLE
Trying to install a prerelease package without `--pre` in presence of a release package installs the release package

### ISSUE THREAD

**Issue by Spitzbub** [chocolatey/choco#750] opened 2016-05-26 21:58 UTC
When I create a prerelease and release package in the same directory and then try to install the prerelease package without the `--pre` option, chocolatey will install the release package instead. Take careful note of the versions below....

```
C:\Users\RussellMora\Dropbox (aboutGolf)\Chocolatey\aG Sim Setup\agsimsetup\src\main>dir
 Volume in drive C is Windows8_OS
 Volume Serial Number is 08E6-FB9D

 Directory of C:\Users\RussellMora\Dropbox (aboutGolf)\Chocolatey\aG Sim Setup\agsimsetup\src\main

05/26/2016  05:52 PM    <DIR>          .
05/26/2016  05:52 PM    <DIR>          ..
05/24/2016  03:51 PM             1,923 agsimsetup.nuspec
03/31/2016  03:55 PM    <DIR>          tools
               1 File(s)          1,923 bytes
               3 Dir(s)  162,836,271,104 bytes free

C:\Users\RussellMora\Dropbox (aboutGolf)\Chocolatey\aG Sim Setup\agsimsetup\src\main>choco pack --version 2.2.1.0-b40
Attempting to build package from 'agsimsetup.nuspec'.
Successfully created package 'agsimsetup.2.2.1.0-b40.nupkg'

C:\Users\RussellMora\Dropbox (aboutGolf)\Chocolatey\aG Sim Setup\agsimsetup\src\main>choco pack
Attempting to build package from 'agsimsetup.nuspec'.
Successfully created package 'agsimsetup.2.2.1.0.nupkg'

C:\Users\RussellMora\Dropbox (aboutGolf)\Chocolatey\aG Sim Setup\agsimsetup\src\main>choco install agsimsetup.2.2.1.0-b40.nupkg
Installing the following packages:
agsimsetup.2.2.1.0-b40.nupkg
By installing you accept licenses for the packages.

agsimsetup v2.2.1.0         <<<<< WRONG VERSION HERE
The package agsimsetup wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?
 1) yes
 2) no
 3) print
```

**Comment by ferventcoder** [comment] 2016-05-27 22:56
Duplicate of #523.

**Closed by ferventcoder** 2016-05-27 22:56 UTC
Labels: 0 - Backlog, Bug, Priority_LOW
