### ISSUE TITLE
Chocolatey ExitCode 60008

### ISSUE THREAD

**Issue by weiner22** [chocolatey/choco#3038] opened 2023-02-20 07:18 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

I´m getting ExitCode 60008 during package installation on FIPS enabled Domain Controller.

### What is Expected?

Install nuget packages well.

### How Did You Get This To Happen?

choco installl <packagename> -y -source <https://internalnuget.server>

### System Details

* Operating System: Windows Server 2019 Standard CORE
* Windows PowerShell version: 5.1
* Chocolatey CLI Version: 1.1.0
* Chocolatey Licensed Extension version: N/A
* Chocolatey License type: Free
* Terminal/Emulator: N/A

### Installed Packages

```bash
Trying packages from different vendors - I can install them out of FIPS enabled DC well. Even on other FIPS enabled DC outside domain.
Agents
-Microsoft Monitoring Agent
-Cortex XDR
-Guardicore
-Splunk Universal Forwarder
```

### Output Log

```bash
Already described here 
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/753
```

**Comment by pauby** [comment] 2023-02-20 10:28
Can you upgrade to the latest 1.3.0 version and retry all of the tests?

**Comment by weiner22** [comment] 2023-02-23 11:27
Hello @pauby,

To answer you questions:
- Upgrade to the latest 1.3.0 version and retry all of the tests?
I tried, but still the same issue

- Confirm that you are NOT using this through PSAppDeployToolkit but by running the command you stated in the issue?
Well I do use it. What´s wrong using it? Attaching sceen shot of single package. One package installed well even PS App Deploy Toolkit used.
![PSDK_screen](https://user-images.githubusercontent.com/74319641/220893262-b1e340ba-f136-4f86-a6b0-31a504c1b5f6.PNG)

- Can you confirm you can install the software manually (ie. without using Chocolatey)?
I can install it on the other systems even without Chocolatey.

**Comment by pauby** [comment] 2023-02-23 11:48
> Well I do use it. What´s wrong using it?

There is nothing wrong with using it, but it's not something we produce, support or know about. A standard troubleshooting process is to remove all the layers of complexity to get to the bottom, and then work your way back up to find the issue. So, we need to understand where the issue is coming from, and to do that we have to strip away PSAppDeployToolkit and Chocolatey CLI.

> I can install it on the other systems even without Chocolatey.

**On the system you are having the issue on (i.e. the one above)**, can you:

1. Can you download the installer and run it manually and see if it installs (note this is without Chocolatey CLI or PSAppDeployToolkit).
2. Can you install the software using Chocolatey CLI (note this is without PSAppDeployToolkit).

**Comment by pauby** [comment] 2023-02-24 15:30
> What do you mean by Chocolatey CLI? 

I'm not sure I understand your question. This repository is for Chocolatey CLI and you've reported the issue about this.

> This is just set of choco cmdlets isn´t it?

No. My understanding is that PSAppDeployToolkit is PowerShell scripts.

> If I try choco install it fails. I don´t have server connected to the internet.

I'm nto sure I understand again. How did you get it to install originally? All I'm asking you to do is the same again, but by using Chocolatey CLI directly and without using PSAppDeployToolkit.

It might be easier to go back to the [original issue comment](https://github.com/chocolatey/choco/issues/3038#issue-1591294896) and under 'How did you get this to happen?' add steps that allow us to reproduce the issue. Without that we're unlikely to be able to move forward.

**Comment by TheCakeIsNaOH** [comment] 2023-02-24 20:52
> Can you install the software using Chocolatey CLI (note this is without PSAppDeployToolkit).
> What do you mean by Chocolatey CLI? This is just set of choco cmdlets isn´t it? If I try choco install it fails. I don´t have server connected to the internet.

Chocolatey CLI is the `choco.exe` program. It is written in C#, and is a package manager. It installs Chocolatey packages (`.nupkg` files), using the `choco install` command. During a package installation, if the `.nupkg` contains a `chocolateyInstall.ps1`, then `choco` will start up a custom PowerShell host with a number of helper functions/cmdlets and run the `chocolateyInstall.ps1`.

Much of the time, a  `chocolateyInstall.ps1` will run an installer or extract an archive. But it can also run other PowerShell code, pretty much anything required. 

Inside a `chocolateyInstall.ps1`, it is possible to use PSAppDeployToolkit, but PSAppDeployToolkit is completely separate program from Chocolatey CLI.

**Comment by weiner22** [comment] 2023-02-27 06:50
Hello @pauby  I have got custom developed NuGet packages, stored on local NuGet server, so that´s explaining why I´m not connected to the internet, and from where packages are taken.
After @TheCakeIsNaOH ´s answer I understand your second question - this is something I have to try.

**Comment by TheCakeIsNaOH** [comment] 2023-04-12 13:46
Thanks for letting us know how you fixed it @weiner22 

I'll close this issue as it was resolved with a PSAppDeploy toolkit update.

**Closed by TheCakeIsNaOH** 2023-04-12 13:46 UTC
Labels: Bug, 0 - Waiting on User
