### ISSUE TITLE
CLI subcommand choco info is very slow

### ISSUE THREAD

**Issue by 1bacon** [chocolatey/choco#3259] opened 2023-07-09 20:23 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

There is a noticeable delay (>3s), when querying packages using `choco info`.

Both requests that are made (Log:110) and (Log:113), are finished in under 25ms. Manual requesting is around the same speed.
There seems to be an ~1s pause before each request.

Then after a consistent 3s, the output is produced.

Here's a demo:
![2023-07-09 22-16-04](https://github.com/chocolatey/choco/assets/55542353/07a71123-a69a-41ce-968d-bdbefa651692)
Especially in the second run (without -dw), you can really feel it grind it's gears.

### What is Expected?

The same output but in significantly less time.

### How Did You Get This To Happen?

1. I run `choco info firefox`
2. I wait for 3 seconds
3. The expected output is produced

### System Details

* Operating System: 10.0.19045.0
* Windows PowerShell version: 7.3.5
* Chocolatey CLI Version: 2.0.0
* Chocolatey Licensed Extension version: N/A
* Chocolatey License type: Personal (?)
* Terminal/Emulator: Windows Terminal (Powershell preset)

### Installed Packages

```bash
chocolatey 2.0.0
```

### Output Log

```bash
https://gist.github.com/1bacon/6d89a57ad8eb8eac5f1be6ef2e733aea
```

### Additional Context

This might be 100% user error, and in that case I'm really sorry, but also intrigued how I could've messed this up on a fresh install...

I hope I met all the requirements.

Thank you and best wishes
Marc

**Comment by 1bacon** [comment] 2023-07-09 20:44
I build the solution and now it's a lot faster.
`choco info firefox` now takes around 0.7 seconds.

although it is running `2.2.0-alpha-20230709-d8361381`

**Comment by TheCakeIsNaOH** [comment] 2023-07-10 22:04
Duplicate of https://github.com/chocolatey/choco/issues/3183

@1bacon try upgrading to v2.1.0 of Chocolatey CLI

**Closed by TheCakeIsNaOH** 2023-07-10 22:04 UTC
Labels: Bug
