### ISSUE TITLE
Request: switch to apply package parameters to dependent packages

### ISSUE THREAD

**Issue by eirikatdips** [chocolatey/choco#839] opened 2016-06-29 06:59 UTC
From chocolatey version 9.10, package parameters will not be applied to dependent packages. That makes sense, as it could cause unexpected behavior. However, there are situations where it would be very useful to be able to do that. We have divided our application into multiple packages, which all makes use of the same input parameters. So it would be very useful if we could apply the parameters also to dependent packages. It should be a switch, named something like --applytoallpackages, --applytoall, etc

It should be easy to implement, I think, looking at the code change done for this issue:
https://github.com/chocolatey/choco/commit/0e0ddfa6d510b9fb7c025ca4e3650ffe32c59c1b

**Comment by ferventcoder** [comment] 2016-06-29 16:04
This was caused by #733

**Comment by ferventcoder** [comment] 2016-08-17 21:02
I think we will implement this as 

* `--apply-package-parameters-to-dependencies`
* `--apply-install-arguments-to-dependencies`

**Comment by ferventcoder** [comment] 2016-09-12 15:42
Merged into stable at https://github.com/chocolatey/choco/commit/315a882b0c4bd7adfab46e316f86d96b6bff2591 and will be included in 0.10.1.

**Closed by ferventcoder** 2016-09-12 15:42 UTC
Labels: 3 - Done, Enhancement

**Comment by DJCrashdummy** [comment] 2021-11-06 08:36
i'm not sure if i'm embarrassing my self right now (i'm just a casual windows user), so please bear with me.

is there a way to specify `--apply-package-parameters-to-dependencies` (and `--apply-package-parameters-to-dependencies`) in a config file **just for certain packages** to be on the safe side?
...or do i really have to split all these packages from my `install.config` into a separate `parameters_passthrough.config` where i specify `--apply-package-parameters-to-dependencies` (and `--apply-package-parameters-to-dependencies`) in the command because it applies to all of its contained packages?!?

**Comment by TheCakeIsNaOH** [comment] 2021-11-06 16:21
I do not think that option has been added to `.config` files yet.
https://github.com/chocolatey/choco/issues/886
