### ISSUE TITLE
Support for msp files

### ISSUE THREAD

**Issue by tobias-geiser** [chocolatey/choco#518] opened 2015-12-24 10:30 UTC
Would be great to have an additional filetype in Install-ChocolateyInstallPackage.ps1

  if ($fileType -like 'msp') {
    $msiArgs = "/p `"$file`""
    if ($overrideArguments) {
      $msiArgs = "$msiArgs $additionalInstallArgs";
      write-host "Overriding package arguments with `'$additionalInstallArgs`'";
    } else {
      $msiArgs = "$msiArgs $silentArgs $additionalInstallArgs";
    }

    Start-ChocolateyProcessAsAdmin "$msiArgs" 'msiexec' -validExitCodes $validExitCodes
    #Start-Process -FilePath msiexec -ArgumentList $msiArgs -Wait

**Comment by ferventcoder** [comment] 2015-12-25 16:47
I'm surprised an issue isn't already logged?

**Comment by ferventcoder** [comment] 2015-12-25 16:47
Duplicate of #509.

**Closed by ferventcoder** 2015-12-25 16:47 UTC
Labels: 0 - _Triaging
