### ISSUE TITLE
Chocolatey 0.9.9.3 upgrade errors

### ISSUE THREAD

**Issue by ianchanning** [chocolatey/choco#216] opened 2015-03-30 08:49 UTC
The v0.9.8.33 - v0.9.9.3 upgrade worked for me but had errors that weren't just missing logs. I'd guess because it is Power Shell v2. I'm on Windows 7, 64-bit.

* Log file: https://gist.github.com/ianchanning/da00bd79a8a2c6395f9b

```console
C:\Windows\system32>cup
!!ATTENTION!!
The next version of Chocolatey (v0.9.9) will require -y to perform
  behaviors that change state without prompting for confirmation. Start
  using it now in your automated scripts.

  For details on the all new Chocolatey, visit http://bit.ly/new_choco
Updating chocolatey from 0.9.8.33 to 0.9.9.3
Chocolatey (v0.9.8.33) is installing 'chocolatey' and dependencies. By installin
g you accept the license for 'chocolatey' and each dependency you are installing
.

chocolatey v0.9.9.3
Chocolatey v0.9.9.3
Chocolatey is unpacking required files for use. Overwriting? True
The term 'false' is not recognized as the name of a cmdlet, function, script fi
le, or operable program. Check the spelling of the name, or if a path was inclu
ded, verify that the path is correct and try again.
At C:\ProgramData\chocolatey\lib\chocolatey.0.9.9.3\tools\chocolateyInstall\hel
pers\chocolateyInstaller.psm1:24 char:22
+ $overrideArgs = false <<<<
    + CategoryInfo          : ObjectNotFound: (false:String) [], ParentContain
   sErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

Import-Module : The specified module 'C:\ProgramData\chocolatey\lib\chocolatey.
0.9.9.3\tools\chocolateyInstall\helpers\chocolateyInstaller.psm1' was not loade
d because no valid module file was found in any module directory.
At C:\ProgramData\chocolatey\lib\chocolatey.0.9.9.3\tools\chocolateysetup.psm1:
50 char:16
+   Import-Module <<<<  $installModule -Force
    + CategoryInfo          : ResourceUnavailable: (C:\ProgramData\...yInstall
   er.psm1:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Comm
   ands.ImportModuleCommand

Creating ChocolateyInstall as an environment variable (targeting 'Machine')
  Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
WARNING: It's very likely you will need to close and reopen your shell
  before you can use choco.
Adding Modify permission for current user to 'C:\ProgramData\chocolatey'
We are setting up the Chocolatey package repository.
The packages themselves go to 'C:\ProgramData\chocolatey\lib'
  (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
  and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName
'.

Creating Chocolatey folders if they do not already exist.

WARNING: You can safely ignore errors related to missing log files when
  upgrading from a version of Chocolatey less than 0.9.9.
  'Batch file could not be found' is also safe to ignore.
  'The system cannot find the file specified' - also safe.
Chocolatey v0.9.9.3
Chocolatey is unpacking required files for use. Overwriting? True
Ensuring 'C:\ProgramData\chocolatey\lib\chocolatey' exists.
The term 'false' is not recognized as the name of a cmdlet, function, script fi
le, or operable program. Check the spelling of the name, or if a path was inclu
ded, verify that the path is correct and try again.
At C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1:24 char:22
+ $overrideArgs = false <<<<
    + CategoryInfo          : ObjectNotFound: (false:String) [], ParentContain
   sErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

Import-Module : The specified module 'C:\ProgramData\chocolatey\helpers\chocola
teyInstaller.psm1' was not loaded because no valid module file was found in any
 module directory.
At C:\ProgramData\chocolatey\lib\chocolatey.0.9.9.3\tools\chocolateysetup.psm1:
110 char:16
+   Import-Module <<<<  "$realModule" -Force
    + CategoryInfo          : ResourceUnavailable: (C:\ProgramData\...yInstall
   er.psm1:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Comm
   ands.ImportModuleCommand

Chocolatey (choco.exe) is now ready.
You can call choco from anywhere, command line or powershell by typing choco.
Run choco /? for a list of functions.
You may need to shut down and restart powershell and/or consoles
 first prior to using choco.
Finished installing 'chocolatey' and dependencies - if errors not shown in conso
le, none detected. Check log for errors if unsure.
The batch file cannot be found.
```

**Comment by JohnLudlow** [comment] 2015-03-30 09:19
I think it's caused by this change: https://github.com/chocolatey/choco/commit/abe92f3f86b0fd0ce5cd2ace7a87b89edde0a5df

    $overrideArgs = false

should be

    $overrideArgs = $false

Assuming that the variable should be a `[bool]` (I can't see where it's used so not 100% sure - it could be used as a string somewhere). 

There's another few lines afterward which seem to have the same problem.

**Comment by Taomyn** [comment] 2015-03-30 12:44
Wow that script is really messed up, even a few incorrect "true" as well - no way it was tested

**Comment by ianchanning** [comment] 2015-03-30 13:43
The same bug has been noted in chocolatey https://github.com/chocolatey/chocolatey/issues/701

**Comment by ferventcoder** [comment] 2015-03-30 14:00
@Taomyn it was tested - I thought in multiple versions of Posh. Apparently not.

**Comment by ferventcoder** [comment] 2015-03-30 14:00
@Taomyn some versions of POSH allow it, others do not.

**Comment by ferventcoder** [comment] 2015-03-30 14:28
This is a duplicate of #215.

**Closed by ferventcoder** 2015-03-30 14:28 UTC
Labels: Duplicate Issue

**Comment by ianchanning** [comment] 2015-03-31 09:01
Cheers for the quick fix. Took two attempts at running `choco upgrade chocolatey` to get from v0.9.9.3 to v0.9.9.4, but all seems to be happy now.

**Comment by ferventcoder** [comment] 2015-03-31 11:32
Apologies on that - thought I had tested on several variants of POSH prior to release but guess I had not.
