### ISSUE TITLE
[RFC] Nuget API v3 Support

### ISSUE THREAD

**Issue by svmastersamurai** [chocolatey/choco#1697] opened 2018-12-19 17:30 UTC
Is there any plans on the roadmap to support the V3 version of the Nuget API?

We've been experimenting with [alternative tools to run nuget feeds](https://github.com/emgarten/sleet) within our infrastructure but the chocolatey client doesn't seem to be able to speak V3 :cry:

**Comment by ferventcoder** [comment] 2019-01-18 01:41
Duplicate of #508

**Closed by ferventcoder** 2019-01-18 01:41 UTC

**Comment by ferventcoder** [comment] 2019-01-18 01:42
Howdy @svmastersamurai! While I like the name of this issue better, we definitely already have an issue surrounding the upgrade. There are plans, and we are hoping this is the year! We'll see, it's not exactly the easiest thing to move up to from where we are at currently.

**Comment by RPitt** [comment] 2023-05-22 12:11
@ferventcoder @gep13 
#508 has been closed but with comments suggesting that official v3 feed support work is still on-going.
Can I encourage you to either re-open this issue, otherwise clarify.

Also ideally update the documentation/FAQ to clarify the status of things.

Thanks!

**Comment by gep13** [comment] 2023-05-22 12:19
@RPitt #508 has been marked as `Done` and `Closed`, since we believe that the work has been completed.  However, the issue hasn't been moved to `Released` which is when you can expect to have a Chocolatey CLI version that provides this capability.

There are a number of open PR's to address various documentation changes that will come with this new functionality.

**Comment by RPitt** [comment] 2023-05-22 12:27
Thanks Gary, I thought that might be the case but was struggling to follow the development and understand the state right now.

**Comment by gep13** [comment] 2023-05-22 14:40
@RPitt there is a beta version available, which you can find here: https://community.chocolatey.org/packages/chocolatey/2.0.0-beta-20230426

See here for more information:
https://github.com/chocolatey/choco/discussions/2995
