### ISSUE TITLE
choco list shows less versions than Chocolatey version history web page

### ISSUE THREAD

**Issue by margani** [chocolatey/choco#2133] opened 2020-10-16 10:10 UTC
### What You Are Seeing?
list command showing results different from the chocolatey web page version history.
### What is Expected?
Same results as in the [this page](https://chocolatey.org/packages/filebeat#versionhistory) which shows 65 versions. for example version 6.8.7 exists in the page but not in the result of below commands.
### How Did You Get This To Happen? (Steps to Reproduce)
- `choco list filebeat -a`
- `choco list "filebeat" -a --page=0 --page-size=1000`
- `choco search "filebeat" -a --page=0 --page-size=1000`
### Output Log
```
Chocolatey v0.10.15
2 validations performed. 1 success(es), 1 warning(s), and 0 error(s).

filebeat.msi 7.9.2
filebeat 7.4.0 [Approved] Downloads cached for licensed users
filebeat 6.3.2 [Approved] Downloads cached for licensed users
filebeat 7.4.1 [Approved]
filebeat 6.4.0 [Approved] Downloads cached for licensed users
filebeat 7.4.2 [Approved] Downloads cached for licensed users
filebeat 6.4.1 [Approved] Downloads cached for licensed users
filebeat 5.1.2 [Approved]
filebeat 6.4.2 [Approved] Downloads cached for licensed users
filebeat 5.2.0 [Approved]
filebeat 7.5.0 [Approved] Downloads cached for licensed users
filebeat 5.2.1 [Approved] Downloads cached for licensed users
filebeat 7.5.1 [Approved] Downloads cached for licensed users
filebeat 5.2.2 [Approved] Downloads cached for licensed users
filebeat 5.3.0 [Approved] Downloads cached for licensed users
filebeat 7.5.2 [Approved] Downloads cached for licensed users
filebeat 6.4.3 [Approved] Downloads cached for licensed users
filebeat 5.3.1 [Approved]
filebeat 5.3.2 [Approved] Downloads cached for licensed users
filebeat 6.5.0 [Approved] Downloads cached for licensed users
filebeat 5.4.0 [Approved] Downloads cached for licensed users
filebeat 7.6.0 [Approved] Downloads cached for licensed users
filebeat 6.5.1 [Approved] Downloads cached for licensed users
filebeat 6.5.3 [Approved] Downloads cached for licensed users
filebeat 6.5.2 [Approved] Downloads cached for licensed users
filebeat 6.5.4 [Approved] Downloads cached for licensed users
filebeat 7.6.1 [Approved] Downloads cached for licensed users
filebeat 5.5.0 [Approved] Downloads cached for licensed users
filebeat 5.5.0.20170710 [Approved] Downloads cached for licensed users
filebeat 5.4.3 [Approved] Downloads cached for licensed users
filebeat 6.8.7 [Approved]
filebeat 5.6.2 [Approved] Downloads cached for licensed users
filebeat 5.6.1 [Approved] Downloads cached for licensed users
filebeat 5.5.1 [Approved] Downloads cached for licensed users
filebeat 5.6.4 [Approved] Downloads cached for licensed users
filebeat 5.6.0 [Approved] Downloads cached for licensed users
filebeat 5.5.2 [Approved] Downloads cached for licensed users
filebeat 6.6.0 [Approved] Downloads cached for licensed users
filebeat 5.6.3 [Approved] Downloads cached for licensed users
filebeat 6.1.2 [Approved] Downloads cached for licensed users
filebeat 6.2.2 [Approved] Downloads cached for licensed users
filebeat 6.2.0 [Approved] Downloads cached for licensed users
filebeat 6.6.2 [Approved] Downloads cached for licensed users
filebeat 6.6.1 [Approved] Downloads cached for licensed users
filebeat 6.2.1 [Approved] Downloads cached for licensed users
filebeat 6.2.4 [Approved] Downloads cached for licensed users
filebeat 6.1.1.20180115 [Approved] Downloads cached for licensed users
filebeat 6.1.3 [Approved] Downloads cached for licensed users
filebeat 6.7.1 [Approved] Downloads cached for licensed users
filebeat 7.0.0 [Approved] Downloads cached for licensed users
filebeat 6.2.3 [Approved] Downloads cached for licensed users
filebeat 6.7.0 [Approved] Downloads cached for licensed users
filebeat 7.2.1 [Approved] Downloads cached for licensed users
filebeat 7.3.1 [Approved] Downloads cached for licensed users
filebeat 7.3.0 [Approved] Downloads cached for licensed users
55 packages found.
```

**Comment by sukucorp** [comment] 2022-01-16 11:34
Might be duplicate of #2001

**Comment by TheCakeIsNaOH** [comment] 2022-02-09 18:25
Agreed @sukucorp 

As noted in #2001, this is a limitation with how the community repository infrastructure works, and #820 is the planned resolution.

**Closed by TheCakeIsNaOH** 2022-02-09 18:25 UTC
