### ISSUE TITLE
Install specific package version like package@1.2.3

### ISSUE THREAD

**Issue by doublemcz** [chocolatey/choco#1909] opened 2019-08-28 11:28 UTC
It would be more convinient to set package version after @ to install specific version of a package like 
`choco install nodejs@10.2.13` instead of specifing longer `choco install nodejs --version 10.2.13`.

**Comment by ExE-Boss** [comment] 2019-08-31 05:09
This might be a duplicate of #1278.

**Comment by wbreza** [comment] 2021-08-31 17:41
You can specify the version through the `--version` flag.  

Example `choco install nodejs --version=10.2.13`

**Closed** 2022-06-30 15:31 UTC
Labels: Invalid / Not Issue / No repro / Not Implementing
