### ISSUE TITLE
Basic Authentication Sources fail to install when using PHPNuGet

### ISSUE THREAD

**Issue by ixeous** [chocolatey/choco#1785] opened 2019-04-02 13:27 UTC
After upgrading to 0.10.13, sources with basic authentication fail to install packages.  I am using phpnuget as the source server.  This is what Rene mentioned in the comments for the package at https://chocolatey.org/packages/chocolatey.

Trying both 0.10.13 and 0.10.14-beta have the same issue.  Reverting to 0.10.11 allows the installations to work.  I have tried disabling the enhanced exit codes, but that did not help.  I am able to install from the chocolatey.org source.

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh

C:\>choco install -y myPackage -d --verbose
Chocolatey v0.10.14-beta
Chocolatey is running on Windows v 10.0.17134.0
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
Command line: "C:\ProgramData\chocolatey\choco.exe" install -y myPackage -d --verbose
Received arguments: install -y myPackage -d --verbose
RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
Sending message 'PreRunMessage' out if there are subscribers...
[Pending] Removing all pending packages that should not be considered installed...
Performing validation checks.
Global Configuration Validation Checks:
 - Package Exit Code / Exit On Reboot = Checked
System State Validation Checks:
 Reboot Requirement Checks:
 - Pending Computer Rename = Checked
 - Pending Component Based Servicing = Checked
 - Pending Windows Auto Update = Checked
 - Pending File Rename Operations = Checked
 - Pending Windows Package Installer = Checked
 - Pending Windows Package Installer SysWow64 = Checked
The source 'https://mySourceServer/sourceA/api/v2/;https://mySourceServer/sourceB/api/v2/;https://mySourceServer/sourceC/api/v2/;https://chocolatey.org/api/v2/' evaluated to a 'normal' source type

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='install'|
CacheLocation='C:\Users\myUser\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='0'|
WebRequestTimeoutSeconds='30'|
Sources='https://mySourceServer/sourceA/api/v2/;https://mySourceServer/sourceB/api/v2/;https://mySourceServer/sourceC/api/v2/;https://chocolatey.org/api/v2/'|

SourceType='normal'|Debug='True'|Verbose='True'|Trace='False'|
Force='False'|Noop='False'|HelpRequested='False'|
UnsuccessfulParsing='False'|RegularOutput='True'|QuietOutput='False'|
PromptForConfirmation='False'|AcceptLicense='True'|
AllowUnofficialBuild='False'|Input='myPackage'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='myPackage'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.17134.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='0.10.14.0'|
Information.ChocolateyProductVersion='0.10.14-beta'|
Information.FullName='choco, Version=0.10.14.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='myUser'|Information.UserDomainName='AD'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|Proxy.BypassOnLocal='True'|
_ Chocolatey:ChocolateyInstallCommand - Normal Run Mode _
Installing the following packages:
myPackage
By installing you accept licenses for the packages.
Using 'https://mySourceServer/sourceA/api/v2/'.
Attempting to gather credentials for 'https://mySourceServer/sourceA/api/v2/'
Source selected will be 'https://mySourceServer/sourceA/api/v2'
Using saved credentials
- Supports prereleases? 'True'.
- Is ServiceBased? 'True'.
Using 'https://mySourceServer/sourceB/api/v2/'.
Attempting to gather credentials for 'https://mySourceServer/sourceB/api/v2/'
Source selected will be 'https://mySourceServer/sourceB/api/v2'
Using saved credentials
- Supports prereleases? 'True'.
- Is ServiceBased? 'True'.
Using 'https://mySourceServer/sourceC/api/v2/'.
Attempting to gather credentials for 'https://mySourceServer/sourceC/api/v2/'
Source selected will be 'https://mySourceServer/sourceC/api/v2'
Using saved credentials
- Supports prereleases? 'True'.
- Is ServiceBased? 'True'.
Using 'https://chocolatey.org/api/v2/'.
- Supports prereleases? 'True'.
- Is ServiceBased? 'True'.
myPackage not installed. The package was not found with the source(s) listed.
 Source(s): 'https://mySourceServer/sourceA/api/v2/;https://mySourceServer/sourceB/api/v2/;https://mySourceServer/sourceC/api/v2/;https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - myPackage - myPackage not installed. The package was not found with the source(s) listed.
 Source(s): 'https://mySourceServer/sourceA/api/v2/;https://mySourceServer/sourceB/api/v2/;https://mySourceServer/sourceC/api/v2/;https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.
Sending message 'PostRunMessage' out if there are subscribers...
Exiting with 1
~~~

</p>

</details>

**Comment by ferventcoder** [comment] 2019-04-02 14:23
Could this be a duplicate of #1770?

**Comment by ferventcoder** [comment] 2019-04-02 14:25
Or at least related to it? 
Can you install the beta and follow the turn off optimizations and see if that fixes the issue.

**Comment by ixeous** [comment] 2019-04-02 15:02
Yes.  0.10.14-beta works when disabling package repository optimizations.  I'll bounce this the the phpnuget side.  Thanks.

**Comment by ferventcoder** [comment] 2019-04-02 15:03
@ixeous this was for PHPNuGet?

**Comment by ixeous** [comment] 2019-04-02 15:09
Yes, version 4.0.0.1.

**Comment by gep13** [comment] 2019-04-03 13:12
@ixeous can you confirm if you are referring to [this](https://github.com/Daniel15/simple-nuget-server) or one of the other implementations?

**Comment by ixeous** [comment] 2019-04-03 14:00
@gep13 it's a different implementation

**Comment by gep13** [comment] 2019-04-03 14:18
@ixeous could you provide a link to the one that you are using please?  Thanks

**Comment by ixeous** [comment] 2019-04-03 14:52
http://www.kendar.org/?p=/dotnet/phpnuget.  It hasn't been updated in long enough that it looks like it's time for me to find another option.

**Comment by ferventcoder** [comment] 2019-04-04 21:18
Duplicate of #1770

**Closed by ferventcoder** 2019-04-04 21:18 UTC
Labels: Duplicate Issue

**Comment by kendarorg** [comment] 2019-06-21 07:58
Now fixed PHPuget: https://github.com/chocolatey/choco/issues/1770#issuecomment-498731821
