### ISSUE TITLE
Unable to install or upgrade using choco

### ISSUE THREAD

**Issue by ssbarnea** [chocolatey/choco#336] opened 2015-06-19 09:15 UTC
It seems that for some really strange reason the `choco upgrade` will no longer be able to install missing packages, making much harder to have simple prepare scripts.

We need a command that would install a package if it is missing or upgrade it. If there are reasons for not using upgrade verb for that you can always use "instgrade" or add a parameter for that.

**Comment by ferventcoder** [comment] 2015-06-19 18:14
Duplicate of #300

**Closed by ferventcoder** 2015-06-19 18:14 UTC
