### ISSUE TITLE
Allow querying package list for a specific source origin `choco list -l -s internalnuget`

### ISSUE THREAD

**Issue by dragon788** [chocolatey/choco#1066] opened 2016-11-30 14:55 UTC
### What You Are Seeing?
I can install from a specific source, I can search a specific source, but I can't find which packages locally installed came from a specific source.

### What is Expected?
As a user and/or maintainer I would like to be able to find out the origin of an installed package. This would be useful if I have a dependency on a package that exists both on Chocolatey.org and internally.  I have an internal fork of that particular package due to a missing feature in the publicly available versions and I want to be able to check whether the internal or external version of a package got installed on a machine to ensure the feature I added is available.

**Comment by ferventcoder** [comment] 2017-03-19 11:13
I like this, however it requires first knowing locally where the package came from.

**Comment by gep13** [comment] 2022-08-04 09:40
I am going suggest that this is a duplicate of https://github.com/chocolatey/chocolatey-licensed-issues/issues/316 which has been moved to the licensed issues repository.  As such, we can go ahead and close this one out.

**Closed by gep13** 2022-08-04 09:40 UTC
Labels: Duplicate Issue
