### ISSUE TITLE
Package not reporting correctly when interrupted during installation

### ISSUE THREAD

**Issue by DamianBis** [chocolatey/choco#782] opened 2016-06-10 00:40 UTC
### What You Are Seeing?

When something interrupts chocolatey install. Say a computer is rebooted during the install of firefox. Chocolatey thinks that the application is installed and if you run a choco list -lo it will show up as installed. But the MSI has actually failed to install.. In order to install again you either need 
1. a new version to be detected or
2. run with --force

### What is Expected?

Some sort of checks (even if this has to be done in the package) to do a confirmation of successful installation.

### How Did You Get This To Happen? (Steps to Reproduce)

choco install (any package really) and remove power during the installation. i believe other things can cause it but this is one thing i know causes issues.

Use Case this effects:

We use chocolatey with our private repo to install software via group policy scripts. sometimes these scripts get interrupted as they're running in the background without users being aware. Our scripts don't install with --force (as they would be installing every time the script runs) so it requires manual intervention

**Comment by ferventcoder** [comment] 2016-06-10 03:52
Duplicate of #198. Already fixed in 0.9.10 (will be in next beta release).

**Comment by ferventcoder** [comment] 2016-06-10 03:54
I take it back - it's in the current beta - 0.9.10-beta-20160531 - so you can run `choco upgrade chocolatey -pre` and take advantage of the fix now.

**Comment by DamianBis** [comment] 2016-06-10 07:00
Perfect i've just installed the beta and it works. any idea on timeline before beta becomes production?

**Comment by ferventcoder** [comment] 2016-06-10 12:36
Real Soon Now  - https://github.com/chocolatey/choco/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.9.10

**Closed by ferventcoder** 2016-06-10 12:36 UTC
Labels: Duplicate Issue

**Comment by romain-marie** [comment] 2022-07-01 08:19
Hello, same problem for me. If installation of a package is interrupted during download or while installer is running, chocolatey says package is installed.
