### ISSUE TITLE
Install-ChocolateyFileAssociation creating unnecessary 3rd parameter in registry command, causing error in app when opening associated filetype 

### ISSUE THREAD

**Issue by mica** [chocolatey/choco#3444] opened 2024-05-17 08:41 UTC
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

The value being created by `Install-ChocolateyFileAssociation` at `HKEY_CLASSES_ROOT\infekt-win64.exe\Shell\Open\Command\` has one too many parameters (`"path\to\exe" "%1" "%*"` vs `"path\to\exe" "%1"`). This is causing [the app](https://infekt.ws/) to throw a "too many positional options have been specified" error when opening associated files.

### What is Expected?

.nfo files should be able to open in the app without issue

### How Did You Get This To Happen?

Here's part of the chocolateyInstall.ps1—hopefully enough to reproduce:

```
Install-ChocolateyZipPackage `
    -PackageName 'iNFekt' `
    -Url64 'https://syndicode.org/infekt/downloads/v1.3.0/iNFekt-v1.3.0-64bit-Portable.rar' `
    -Checksum64 '673B3AF9ED0E3DC42C6C2CD8308A815FCC3141C2D97EE9E4FA88E182AC56898E' `
    -ChecksumType64 'SHA256' `
    -UnzipLocation $env:ProgramFiles\iNFekt\

Install-ChocolateyFileAssociation `
    -Extension .nfo `
    -Executable $env:ProgramFiles\iNFekt\iNFekt-64bit-Portable\infekt-win64.exe 
```

You can create an empty .nfo text file and attempt to open it to reproduce the error message. 

Then if you edit the value at `HKEY_CLASSES_ROOT\infekt-win64.exe\Shell\Open\Command\`, removing `"%*"`, it will open fine.

### System Details

* Operating System: Windows 10.0.19045.0
* Windows PowerShell version: 7.4.2
* Chocolatey CLI Version: 2.2.2
* Chocolatey Licensed Extension version: 2.2.2
* Chocolatey License type: ?
* Terminal/Emulator: pwsh

**Comment by pauby** [comment] 2024-05-17 09:14
@mica Can you go back amend your description above to include:

1. Full reproducible steps for this in the 'How did you get this to happen'? Note that those steps must include everything that we need to do to reproduce it. 
2. Include the output you are seeing with the error message and the output from Chocolatey CLI when install the package in the 'Output Log' section above.

Without both of those we cannot look at this issue.

Thanks.

**Comment by mica** [comment] 2024-05-17 10:18
Not sure how relevant it would be, as the error is within [another program](https://infekt.ws/)—one that just happens to crash if passed a third parameter, even when it's an empty string. For example, `& .\infekt-win64.exe file.txt`  works fine, whereas `& .\infekt-win64.exe file.txt ""` doesn't.

The issue is that in line 78 of [Install-ChocolateyFileAssociation.ps1](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Install-ChocolateyFileAssociation.ps1), it's registering `$fileType="$executable" "%1" "%*"` where `$fileType="$executable" "%1"` would suffice.

**Comment by pauby** [comment] 2024-05-17 11:13
@mica Just to be clear, without reproducible steps, we are unable to accept this issue.

**Comment by mica** [comment] 2024-05-19 09:12
Ok, I've edited above, thanks!

**Comment by mica** [comment] 2024-07-31 05:24
Hard to say what other apps out there might struggle when launched with an extra empty parameter. My question is whether [Install-ChocolateyFileAssociation.ps1](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Install-ChocolateyFileAssociation.ps1) really needs to include `%*` when registering the association with `ftype`... `%1` contains the path of the file being opened, which you'd think is all you'd need. 

Could `%*` have been added just because documentation sometimes includes it in examples, or is there some actual need for it?.. 
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/ftype
https://ss64.com/nt/ftype.html

**Comment by pauby** [comment] 2024-07-31 08:36
To provide some context from this side of the fence, we have a PowerShell function doing what it does successfully for many years without issue.

We have one third-party application that doesn't like the way the PowerShell function works.

That to me says that the third-party application is the root of the issue, not the PowerShell function.

Changing how the PowerShell function works, is a breaking change that has much bigger implications than one third-party application.

So my gut here tells me that this is not a bug in Chocolatey CLI and rather than the third-party application and the third-party application should handle the issue gracefully instead of throwing an error.

> Could %* have been added just because documentation sometimes includes it in examples, or is there some actual need for it?..

I can't speak as to why it was added. But having it widely documented and having many examples, would indicate it is the correct way of doing things. Which comes back to the third-party application not handling a widely documented way of doing things. That again would indicate that this is a third-party application issue.

My suggestion would be to get the changes made in the third-party application.

I'm going to go ahead and close this, as there isn't anything more we can do. We can always reopen it if necessary,

**Closed by pauby** 2024-07-31 08:36 UTC
Labels: Bug, 0 - Waiting on User
