### ISSUE TITLE
Cannot find chocolatey.cmd after v0.9.9-rc5 upgrade

### ISSUE THREAD

**Issue by ianchanning** [chocolatey/choco#96] opened 2015-02-11 14:02 UTC
I did a `cup` from v0.9.8.28 to v0.9.8.32 followed by an install of the pre-release version using `choco install chocolatey -pre`.

The `cup` worked fine and according to the log file the pre-release installation worked fine. There are two errors about missing log files which come after a warning saying that you can ignore those errors.

However after the errors of the missing log files I got a `The system cannot find the path specified.` error in the output.

Then further attempts to run any `choco` commands return the following error:

```
C:\Users\ian>choco -v
Cannot find file at '../chocolateyInstall/chocolatey.cmd' (C:\ProgramData\chocolatey\chocolateyInstall\chocolatey.cmd). This usually indicates a missing or moved file.
```

Log files:
* [log.sh gist](https://gist.github.com/ianchanning/ab601ca043002944145a)
* [Command prompt output with errors gist](https://gist.github.com/ianchanning/a7f4d22fc830abc4bd17)

**Comment by ferventcoder** [comment] 2015-02-11 14:18
This is a duplicate of #91

**Closed** 2015-02-11 14:18 UTC
Labels: Duplicate Issue
