### ISSUE TITLE
Add a '--skip-shimgens' switch to choco.exe

### ISSUE THREAD

**Issue by roysubs** [chocolatey/choco#2929] opened 2022-12-05 16:39 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

The problem is performance of chocolatey when installing multiple packages

### Describe The Solution. Why is it needed?

The solution is a switch to skip shim generation for a package.

My use case is that I install a lot of apps like sysinternals that have a large number of shims creaated. The shims slow down the installation a lot, and I don't use them because as soon as the installation completes I copy over all small tools like these to my `C:\ConsoleTools` folder (which I keep in my PATH environment variable). Thus, if I had an option like `--skip-shimgens` I could use that switch for any app that I am going to manage myself in this way, and this would speed up installation a lot.

### Additional Context

I am not suggesting getting rid of the `lib` folder. I keep that constantly for use with larger apps. It's just that for a lot of small / console apps, I can better manage them from a single folder. Not all sysinternals are console apps, but they fall under the small-useful-apps in my book, and I throw them into C:\ConsoleTools. Other similar apps are: cw, cmail, ntop, fzf, fd, syspin, winfetch, xxd etc, all things that are primarily single executables that I can keep on the PATH in a single folder).

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/shimgen/-/issues/43) by [Unito](https://www.unito.io)

**Comment by TheCakeIsNaOH** [comment] 2023-06-19 22:08
Duplicate of #1670

**Closed by TheCakeIsNaOH** 2023-06-19 22:08 UTC
Labels: Improvement, 0 - Backlog
