### ISSUE TITLE
Dissallow passing in a path to a NUPKG file directly when installing/upgrading packages

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/choco#3008] opened 2023-01-31 14:07 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

There are already known problems in Chocolatey CLI v1 that causes installations of a nupkg file to not behave as expected when the path is passed in directly.
With the uplift being done for Chocolatey CLI v2 this problem added even more problems with this behavior and ended with it not actually using the passed in nupkg file.

### Describe The Solution. Why is it needed?

As part of an internal discussion that was had, we have decided to no longer allow a path to a nupkg file when installing or upgrading packages. Instead it needs to be specified as it would normally be done when installing a package with a specific version on a specific source instead.
ie
using `choco install packageName --version="packageVersion" --source "directory"`.

This issue is about adding additional validation that a nupkg or nuspec file is not passed directly, and when possible give an example of how to install that package instead.

### Related Issues

- #508 
- https://app.clickup.com/t/20540031/PROJ-464

**Comment by TheCakeIsNaOH** [comment] 2023-01-31 15:22
Potential duplicate of #2982?

**Comment by AdmiringWorm** [comment] 2023-02-01 13:17
@TheCakeIsNaOH thanks for finding that issue, I somehow completely missed it.
As this issue contains more information and is the one being referenced in the commits and PR, I will close the other duplicated issue

**Closed** 2023-02-03 15:03 UTC
Labels: Breaking Change, 3 - Review
