### ISSUE TITLE
Restarted computer yet " - A pending system reboot request has been detected, however, this is"

### ISSUE THREAD

**Issue by musm** [chocolatey/choco#1792] opened 2019-04-04 19:54 UTC
Hi I've restarted my computer yet I keep seeing
```
Chocolatey v0.10.13
[Pending] Removing incomplete install for 'powershell-core'
2 validations performed. 1 success(es), 1 warning(s), and 0 error(s).

Validation Warnings:
 - A pending system reboot request has been detected, however, this is
   being ignored due to the current Chocolatey configuration.  If you
   want to halt when this occurs, then either set the global feature
   using:
     choco feature enable -name=exitOnRebootDetected
   or pass the option --exit-when-reboot-detected.


```

I keep seeing this message in all choco operations

**Comment by ferventcoder** [comment] 2019-04-04 21:16
Duplicate of #1768

**Comment by ferventcoder** [comment] 2019-04-04 21:17
Howdy @musm - this is a duplicate of #1768. Please read that issue for details on what is going on and why we are ignoring File Renames as of 0.10.14+. We've already put out a beta you can install to test that this behavior is fixed.

**Closed by ferventcoder** 2019-04-04 21:16 UTC
