### ISSUE TITLE
install.ps1 signed by expired cert

### ISSUE THREAD

**Issue by pivotalgeorge** [chocolatey/choco#1553] opened 2018-04-27 22:37 UTC
### How Did You Get This To Happen? (Steps to Reproduce)
- download https://chocolatey.org/install.ps1 on April 27, 2018 ~5:30pm
- `(Get-AuthenticodeSignature -FilePath .\install.ps1).SignerCertificate | Format-List`

### What You Are Seeing?
an old thumbprint:
```
Subject      : CN="Chocolatey Software, Inc.", O="Chocolatey Software, Inc.", L=Topeka, S=Kansas, C=US
Issuer       : CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
Thumbprint   : 493018BA27EAA09B895BC5660E77F694B84877C7
FriendlyName :
NotBefore    : 3/27/2017 7:00:00 PM
NotAfter     : 4/3/2018 7:00:00 AM
Extensions   : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid...}
```

### What is Expected?
the newer thumbprint, as documented in the [security wiki page](https://github.com/chocolatey/choco/wiki/Security) and http://chocolatey.org/security
```
Subject      : CN="Chocolatey Software, Inc.", O="Chocolatey Software, Inc.", L=Topeka, S=Kansas, C=US
Issuer       : CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
Thumbprint   : 4BF7DCBC06F6D0BDFA8A0A78DE0EFB62563C4D87
FriendlyName :
NotBefore    : 3/29/2018 7:00:00 PM
NotAfter     : 4/14/2021 7:00:00 AM
Extensions   : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid,
               System.Security.Cryptography.Oid...}
```

**Comment by ferventcoder** [comment] 2018-04-27 22:42
@pivotalgeorge I literally just closed this over at the chocolatey.org repo. 

Duplicate of https://github.com/chocolatey/chocolatey.org/issues/559

**Comment by ferventcoder** [comment] 2018-04-27 22:42
Jump over to https://github.com/chocolatey/chocolatey.org/issues/559 for more details. This is going with a fix soon.

**Closed by ferventcoder** 2018-04-27 22:42 UTC

**Comment by ferventcoder** [comment] 2018-04-27 22:45
https://chocolatey.org/security#chocolatey-binaries-and-the-chocolatey-package (note the header). Install.ps1 comes from https://chocolatey.org/install.ps1 ;)

**Comment by ferventcoder** [comment] 2018-04-27 22:51
And more important, it's fixed now. 👍
