### ISSUE TITLE
Possible issue with spacing on file path for msu packages

### ISSUE THREAD

**Issue by tirolo** [chocolatey/choco#500] opened 2015-12-04 19:00 UTC
Sorry I don't have the logs available now but it's quite easy to reproduce:

Steps to reproduce:
(Make sure you **don't** have posh 4.0 installed on the machine you are reproducing the steps)
* Create two users: `nospace` and `with space`
* Try to run: `cinst powershell` on both

Current:
It fails to the `with space` user but works to the `nospace`

Expected:
Should work for both

The error message lead me to the following line, and I believe that the fix would be to wrap the `$file` parameter with double quotes (eg.: `Start-ChocolateyProcessAsAdmin "$silentArgs $additionalInstallArgs" "$file" -validExitCodes $validExitCodes`
https://github.com/chocolatey/choco/blob/0ec22c8cfa5d71933fc2a378ddee62d195f8199b/src/chocolatey.resources/helpers/functions/Install-ChocolateyInstallPackage.ps1#L93

**Comment by aronovgj** [comment] 2015-12-04 21:05
https://gitter.im/chocolatey/choco?at=556c35e4777c17d06a13710c
might be related.

**Comment by tirolo** [comment] 2015-12-07 11:05
Log for the failure:
https://gist.github.com/tirolo/7cab36764617984c74dc

I actually managed to make the change I suggested and it works, although I think its touching point is quite critical and impact is probably over what I can image I will make a PR just so that we don't lose the "potential fix"

**Comment by tirolo** [comment] 2015-12-07 11:47
It's still intermittent, I'm doing further tests now to try to get what's going on

**Comment by tirolo** [comment] 2015-12-07 13:47
I'm only to reproduce the issue when it goes all the way through the boxstarter flow, if I try to reproduce the same behaviour using any other flow it works just fine. Will try to capture the logs to post more information but basically it failure described occurs when executing the following command from the boxstarter context: `cmd /c start powershell -NoProfile -ExecutionPolicy Bypass -NoExit -Command { choco install powershell }`

**Comment by ferventcoder** [comment] 2015-12-07 14:34
@tirolo I'm thinking it may be a boxstarter issue? @mwrock how close is it to using the c# version of choco? Are you aware of any spacing issues?

**Comment by mwrock** [comment] 2015-12-07 16:04
Its extremely [close now](https://github.com/mwrock/boxstarter/pull/122#issuecomment-162561709). Not aware of spacing issues but it would be helpful to see a failed boxstarter log.

**Comment by tirolo** [comment] 2015-12-10 08:39
Finally I found the cause of the problem. It seems to be related to updating chocolatey within the boxstarter session, an easy way to reproduce: `http://boxstarter.org/package/chocolatey,powershell`
or by running boxstarter with the following script (which is how I actually found the issue):
```
choco update chocolatey
choco install powershell
```

phew! was not easy to figure it out what the issue was :sweat_smile:

**Comment by ferventcoder** [comment] 2015-12-23 15:49
So am I right to close this as an environmental issue?

**Comment by tirolo** [comment] 2016-01-29 15:39
@ferventcode it does seems to be a boxstarter issue, I will create an issue there.

**Comment by ferventcoder** [comment] 2016-01-29 17:47
Does this mean the issue is invalid here?

**Comment by tirolo** [comment] 2016-02-01 16:26
@ferventcoder  not 100% sure, we need to further investigate that.. can one of you guys try to reproduce the issue and see if it rings a bell? I'm using your `win7pro-x64-nocm-lite` box to test it, just install IE and run `http://boxstarter.org/package/chocolatey,powershell` and you should be able to get the error

**Comment by mwrock** [comment] 2016-02-02 10:42
I just took a look at this. I am able to install chocolatey and powershell without error via `http://boxstarter.org/package/chocolatey,powershell` on a clean win2k8r2 machine both using a user with a space and without. Using `win7pro-x64-nocm-lite` however this fails for any user even outside of boxstarter. The reason is that box has the windows update service disabled which the wmf4 install uses to grab some of the bits.

It succeeds if you change the startup type to manual.

**Comment by ferventcoder** [comment] 2016-04-10 18:24
So coming back - I'm going to say this is invalid for now. If we feel this needs to be revisited then we should reopen it at that time.

**Closed by ferventcoder** 2016-04-10 18:24 UTC
Labels: 0 - _Triaging, Bug
