### ISSUE TITLE
Just installed Chocolatey v2.0.0 on new Windows 11 Enterprise 10.0.22621 Build 22621 Cannot search or find

### ISSUE THREAD

**Issue by jpsebasti** [chocolatey/choco#3232] opened 2023-06-27 21:27 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

Start a terminal in Admin mode
choco find <packagename>
The 'br' start tag on line 61 position 103 does not match the end tag of 'h1'. Line 61, position 145

### What is Expected?

I expect to see the package list

### How Did You Get This To Happen?

1. Start Admin terminal
2. run choco search or choco find command
3.

### System Details

* Operating System: windows 11 Build 22621
* Windows PowerShell version: 5.1.22621.1778
* Chocolatey CLI Version: 2.0.0
* Chocolatey Licensed Extension version:
* Chocolatey License type: free
* Terminal/Emulator: Windows Terminal and CMD 

### Installed Packages

```bash
choco list
Chocolatey v2.0.0
chocolatey 2.0.0
1 package installed.
```

### Output Log

```bash
2023-06-27 09:43:59,305 5896 [DEBUG] - XmlConfiguration is now operational
2023-06-27 09:43:59,383 5896 [DEBUG] - Adding new type 'CygwinService' for type 'IAlternativeSourceRunner' from assembly 'choco'
2023-06-27 09:43:59,383 5896 [DEBUG] - Adding new type 'CygwinService' for type 'IInstallSourceRunner' from assembly 'choco'
2023-06-27 09:43:59,383 5896 [DEBUG] - Adding new type 'PythonService' for type 'IAlternativeSourceRunner' from assembly 'choco'
2023-06-27 09:43:59,398 5896 [DEBUG] - Adding new type 'PythonService' for type 'IListSourceRunner' from assembly 'choco'
2023-06-27 09:43:59,398 5896 [DEBUG] - Adding new type 'PythonService' for type 'IInstallSourceRunner' from assembly 'choco'
2023-06-27 09:43:59,398 5896 [DEBUG] - Adding new type 'PythonService' for type 'IUninstallSourceRunner' from assembly 'choco'
2023-06-27 09:43:59,398 5896 [DEBUG] - Adding new type 'RubyGemsService' for type 'IAlternativeSourceRunner' from assembly 'choco'
2023-06-27 09:43:59,398 5896 [DEBUG] - Adding new type 'RubyGemsService' for type 'IListSourceRunner' from assembly 'choco'
2023-06-27 09:43:59,398 5896 [DEBUG] - Adding new type 'RubyGemsService' for type 'IInstallSourceRunner' from assembly 'choco'
2023-06-27 09:43:59,414 5896 [DEBUG] - Adding new type 'SystemStateValidation' for type 'IValidation' from assembly 'choco'
2023-06-27 09:44:00,117 5896 [DEBUG] - Adding new type 'EmptyOrInvalidUrlMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2023-06-27 09:44:00,117 5896 [DEBUG] - Adding new type 'FrameWorkReferencesMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2023-06-27 09:44:00,117 5896 [DEBUG] - Adding new type 'IconMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2023-06-27 09:44:00,133 5896 [DEBUG] - Adding new type 'LicenseMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2023-06-27 09:44:00,133 5896 [DEBUG] - Adding new type 'PackageTypesMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2023-06-27 09:44:00,133 5896 [DEBUG] - Adding new type 'ReadmeMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2023-06-27 09:44:00,133 5896 [DEBUG] - Adding new type 'RepositoryMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2023-06-27 09:44:00,133 5896 [DEBUG] - Adding new type 'RequireLicenseAcceptanceMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2023-06-27 09:44:00,133 5896 [DEBUG] - Adding new type 'ServicableMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2023-06-27 09:44:00,133 5896 [DEBUG] - Adding new type 'VersionMetadataRule' for type 'IMetadataRule' from assembly 'choco'
2023-06-27 09:44:00,164 5896 [DEBUG] - Registering new command 'list' in assembly 'choco'
2023-06-27 09:44:00,164 5896 [DEBUG] - Registering new command 'template' in assembly 'choco'
2023-06-27 09:44:00,164 5896 [DEBUG] - Registering new command 'export' in assembly 'choco'
2023-06-27 09:44:00,164 5896 [DEBUG] - Registering new command 'info' in assembly 'choco'
2023-06-27 09:44:00,164 5896 [DEBUG] - Registering new command 'help' in assembly 'choco'
2023-06-27 09:44:00,180 5896 [DEBUG] - Registering new command 'config' in assembly 'choco'
2023-06-27 09:44:00,180 5896 [DEBUG] - Registering new command 'feature' in assembly 'choco'
2023-06-27 09:44:00,180 5896 [DEBUG] - Registering new command 'new' in assembly 'choco'
2023-06-27 09:44:00,180 5896 [DEBUG] - Registering new command 'outdated' in assembly 'choco'
2023-06-27 09:44:00,180 5896 [DEBUG] - Registering new command 'pack' in assembly 'choco'
2023-06-27 09:44:00,180 5896 [DEBUG] - Registering new command 'pin' in assembly 'choco'
2023-06-27 09:44:00,195 5896 [DEBUG] - Registering new command 'push' in assembly 'choco'
2023-06-27 09:44:00,195 5896 [DEBUG] - Registering new command 'apikey' in assembly 'choco'
2023-06-27 09:44:00,195 5896 [DEBUG] - Registering new command 'source' in assembly 'choco'
2023-06-27 09:44:00,195 5896 [DEBUG] - Registering new command 'uninstall' in assembly 'choco'
2023-06-27 09:44:00,195 5896 [DEBUG] - Registering new command 'upgrade' in assembly 'choco'
2023-06-27 09:44:00,195 5896 [DEBUG] - Registering new command 'search' in assembly 'choco'
2023-06-27 09:44:00,211 5896 [DEBUG] - Registering new command 'unpackself' in assembly 'choco'
2023-06-27 09:44:00,211 5896 [DEBUG] - Registering new command 'install' in assembly 'choco'
2023-06-27 09:44:00,352 5896 [INFO ] - ============================================================
2023-06-27 09:44:01,039 5896 [INFO ] - Chocolatey v2.0.0
2023-06-27 09:44:01,055 5896 [DEBUG] - Chocolatey is running on Windows v 10.0.22621.0
2023-06-27 09:44:01,055 5896 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2023-06-27 09:44:01,070 5896 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2023-06-27 09:44:01,086 5896 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" search firefox
2023-06-27 09:44:01,086 5896 [DEBUG] - Received arguments: search firefox
2023-06-27 09:44:01,148 5896 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2023-06-27 09:44:01,164 5896 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2023-06-27 09:44:01,180 5896 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
2023-06-27 09:44:01,227 5896 [DEBUG] - Performing validation checks.
2023-06-27 09:44:01,242 5896 [DEBUG] - Global Configuration Validation Checks:
2023-06-27 09:44:01,242 5896 [DEBUG] -  - Package Exit Code / Exit On Reboot = Checked
2023-06-27 09:44:01,242 5896 [DEBUG] - System State Validation Checks:
2023-06-27 09:44:01,258 5896 [DEBUG] -  Reboot Requirement Checks:
2023-06-27 09:44:01,258 5896 [DEBUG] -  - Pending Computer Rename = Checked
2023-06-27 09:44:01,258 5896 [DEBUG] -  - Pending Component Based Servicing = Checked
2023-06-27 09:44:01,258 5896 [DEBUG] -  - Pending Windows Auto Update = Checked
2023-06-27 09:44:01,273 5896 [DEBUG] -  - Pending File Rename Operations = Checked
2023-06-27 09:44:01,273 5896 [DEBUG] -  - Pending Windows Package Installer = Checked
2023-06-27 09:44:01,273 5896 [DEBUG] -  - Pending Windows Package Installer SysWow64 = Checked
2023-06-27 09:44:01,273 5896 [INFO ] - 2 validations performed. 2 success(es), 0 warning(s), and 0 error(s).
2023-06-27 09:44:01,305 5896 [DEBUG] - The source 'https://community.chocolatey.org/api/v2/' evaluated to a 'normal' source type
2023-06-27 09:44:01,305 5896 [DEBUG] - 
NOTE: Hiding sensitive configuration data! Please double and triple
check to be sure no sensitive data is shown, especially if copying
output to a gist for review.
2023-06-27 09:44:01,320 5896 [DEBUG] - Configuration: CommandName='search'|
CacheLocation='C:\Users\jsebast\AppData\Local\Temp\chocolatey'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://community.chocolatey.org/api/v2/'|SourceType='normal'|
ShowOnlineHelp='False'|Debug='False'|Verbose='False'|Trace='False'|
Force='False'|Noop='False'|HelpRequested='False'|
UnsuccessfulParsing='False'|RegularOutput='True'|QuietOutput='False'|
PromptForConfirmation='True'|DisableCompatibilityChecks='False'|
AcceptLicense='False'|AllowUnofficialBuild='False'|Input='firefox'|
AllVersions='False'|SkipPackageInstallProvider='False'|
SkipHookScripts='False'|Prerelease='False'|ForceX86='False'|
OverrideArguments='False'|NotSilent='False'|
ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowDowngrade='False'|ForceDependencies='False'|PinPackage='False'|
Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.22621.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='2.0.0.0'|
Information.ChocolateyProductVersion='2.0.0'|
Information.FullName='choco, Version=2.0.0.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='jsebast'|Information.UserDomainName='SANDIA'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Information.CurrentDirectory='C:\Users\jsebast'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
ListCommand.LocalOnly='False'|ListCommand.IdOnly='False'|
ListCommand.IncludeRegistryPrograms='False'|ListCommand.PageSize='25'|
ListCommand.Exact='False'|ListCommand.ByIdOnly='False'|
ListCommand.ByTagOnly='False'|ListCommand.IdStartsWith='False'|
ListCommand.OrderByPopularity='False'|ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
ListCommand.ExplicitPageSize='False'|
ListCommand.ExplicitSource='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='Unknown'|
ApiKeyCommand.Command='Unknown'|PinCommand.Command='Unknown'|
OutdatedCommand.IgnorePinned='False'|
ExportCommand.IncludeVersionNumbers='False'|Proxy.BypassOnLocal='True'|
TemplateCommand.Command='unknown'|
2023-06-27 09:44:01,320 5896 [DEBUG] - _ Chocolatey:ChocolateySearchCommand - Normal Run Mode _
2023-06-27 09:44:01,336 5896 [DEBUG] - Searching for package information
2023-06-27 09:44:01,336 5896 [DEBUG] - Running list with the following filter = 'firefox'
2023-06-27 09:44:01,352 5896 [DEBUG] - --- Start of List ---
2023-06-27 09:44:01,555 5896 [DEBUG] - Resolving resource PackageSearchResource for source https://community.chocolatey.org/api/v2/
2023-06-27 09:44:03,242 5896 [WARN ] - The source https://community.chocolatey.org/api/v2/ failed to get a NuGet.Protocol.Core.Types.PackageSearchResource resource
2023-06-27 09:44:03,242 5896 [DEBUG] - Resolving resource ListResource for source https://community.chocolatey.org/api/v2/
2023-06-27 09:44:03,289 5896 [INFO ] - [NuGet] Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
2023-06-27 09:44:04,414 5896 [INFO ] - [NuGet]   GET https://community.chocolatey.org/api/v2/Packages()?$filter=((((Id ne null) and substringof('firefox',tolower(Id))) or ((Description ne null) and substringof('firefox',tolower(Description)))) or ((Tags ne null) and substringof(' firefox ',tolower(Tags)))) and IsLatestVersion&$orderby=Id&$skip=0&$top=30&semVerLevel=2.0.0
2023-06-27 09:44:04,539 5896 [INFO ] - [NuGet]   OK https://community.chocolatey.org/api/v2/Packages()?$filter=((((Id ne null) and substringof('firefox',tolower(Id))) or ((Description ne null) and substringof('firefox',tolower(Description)))) or ((Tags ne null) and substringof(' firefox ',tolower(Tags)))) and IsLatestVersion&$orderby=Id&$skip=0&$top=30&semVerLevel=2.0.0 118ms
2023-06-27 09:44:04,539 5896 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2023-06-27 09:44:04,555 5896 [ERROR] - The 'br' start tag on line 61 position 103 does not match the end tag of 'h1'. Line 61, position 145.
2023-06-27 09:44:04,555 5896 [ERROR] - More Details: System.Xml.XmlException: The 'br' start tag on line 61 position 103 does not match the end tag of 'h1'. Line 61, position 145.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.Protocol.V2FeedParser.<LoadXmlAsync>d__90.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.V2FeedParser.<>c__DisplayClass88_0.<<LoadXmlAsync>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.V2FeedParser.<LoadXmlAsync>d__88.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.V2FeedParser.<QueryV2FeedAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.V2FeedParser.<GetPackagesPageAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EnumeratorAsync.<MoveNextAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at chocolatey.infrastructure.app.nuget.NugetList.<SearchPackagesAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at chocolatey.infrastructure.app.nuget.NugetList.GetPackages(ChocolateyConfiguration configuration, ILogger nugetLogger, IFileSystem filesystem)
   at chocolatey.infrastructure.app.services.NugetService.<List>d__15.MoveNext()
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.<List>d__23.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at chocolatey.infrastructure.app.commands.ChocolateySearchCommand.Run(ChocolateyConfiguration configuration)
   at chocolatey.infrastructure.app.runners.GenericRunner.Run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.Run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
2023-06-27 09:44:04,555 5896 [DEBUG] - Exiting with 1
```

**Comment by pauby** [comment] 2023-06-29 16:11
I can't reproduce this locally:

![image](https://github.com/chocolatey/choco/assets/12760779/c852afaf-0153-4a20-a7ea-1df70b51c866)
![image](https://github.com/chocolatey/choco/assets/12760779/7782f5fb-233f-4951-8a25-da7a93950bad)

Are you able to consistently reproduce it?

**Comment by jacobonorte** [comment] 2023-06-30 16:08
I have this issue also it seems. I can provide logs etc.

We have a repo and have our own packages. SInce updating to 2.0.0 (I can roll back to any previous version and not see this)
I have not been able to pull every package. 100 plus exist in the repo and using choco search xxxx I see 18 packages (not close to them all).

**Comment by pauby** [comment] 2023-06-30 16:18
@jacobonorte Can you raise a new issue so that we can capture all of the information needed?

**Comment by jpsebasti** [comment] 2023-07-02 19:05
Yes I can try.

________________________________

**Comment by gep13** [comment] 2023-07-03 14:19
@jpsebasti I have put together a short video of how to look at the request/responses that are being used by the Chocolatey CLI in this short video:

https://youtu.be/z4CwJ-MF7ik

It would be great if you could have a watch of that video, and then grab the session archive at the time you are seeing the problem in Chocolatey CLI.

Let me know here if you run into any problems with grabbing the required information.  Thanks!

**Comment by jpsebasti** [comment] 2023-07-03 22:01
Hi Gary,

So this is a bit strange.  Our company has an outbound forward facing proxy that does interception inspection.  As I understand it, requests are intercepeted byt the outbound proxy, unencrypted, inspected and then re-incrypted to send on their way to the internet.

I installed Fiddler.  When I turn on the Capture mode in fiddler, the following Chocolately command works just fine:
PS C:\Users\jsebast> choco search firefox
Chocolatey v2.0.0
adblockplusfirefox 0.0.0.2 [Approved]
adblockplus-firefox 2.7.1 [Approved]
basilisk 2022.1.27 [Approved]
  .
  .
  .
67 packages found.


When I turn off capture mode, then this happens:

PS C:\Users\jsebast> choco search firefox
Chocolatey v2.0.0
The 'br' start tag on line 61 position 103 does not match the end tag of 'h1'. Line 61, position 145.

I'm thinking now that this is something on our side

**Comment by gep13** [comment] 2023-07-04 08:53
@jpsebasti do you have any details of the outbound proxy that is being used, or any way to look at the request/responses that are going through it?

Based on what you have said here, "something" is happening to the response that is being given to Chocolatey CLI, where an extra `br` element is being added, which means that Chocolatey CLI isn't able to work with the response.  Unfortunately, there is very little that Chocolatey CLI can do here, as this is something that is being done outside of its control.

**Comment by jpsebasti** [comment] 2023-07-04 14:34
Yes thanks. I don't have any details to share but I can successfully use Chocolatey when not connected to the corporate VPN so I will just do that in the future. Thank you for responding

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gep13** [comment] 2023-07-07 10:41
@jacobonorte thank you for confirming.

Since this seems to be an environmental issue, and not an issue with Chocolatey CLI itself, I am going to go ahead and close it out.

Feel free to comment again on this issue, if there is more that you would like to discuss.

**Closed by gep13** 2023-07-07 10:41 UTC
Labels: Bug, 0 - Waiting on User
