### ISSUE TITLE
do not show which file names are being extracted

### ISSUE THREAD

**Issue by rgl** [chocolatey/choco#693] opened 2016-04-14 11:28 UTC
I'm installing msys2 inside a vagrant environment, but showing the extracted file names is making things hard for me, as it "pollutes" the output and makes it hard to find any errors on the output. can you omit the extracted file names from the output? I'm talking about these lines:

```
Extracting  msys64\var\lib\pacman\local\libtasn1-4.7-1\install
Extracting  msys64\var\lib\pacman\local\libtasn1-4.7-1\mtree
Extracting  msys64\var\lib\pacman\local\libutil-linux-2.26.2-1
```

This can be done by adding the `-bd` to the [Get-ChocolateyUnzip 7z parameters](https://github.com/chocolatey/choco/blob/329c797ddb126add58a5194b34bd3d0d821b2f06/src/chocolatey.resources/helpers/functions/Get-ChocolateyUnzip.ps1#L94).

**Comment by ferventcoder** [comment] 2016-04-14 12:06
Duplicate of #476

**Closed by ferventcoder** 2016-04-14 12:06 UTC

**Comment by ferventcoder** [comment] 2016-04-14 12:07
Short story, install the `0.9.10` beta if you want to take advantage of this immediately - `choco upgrade chocolatey -pre`
