### ISSUE TITLE
chromium package lost when I did CTRL C

### ISSUE THREAD

**Issue by networkproblemsolver** [chocolatey/choco#3397] opened 2024-02-15 16:11 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

I stopped a frozen "choco upgrade all" and "chromium" was removed from my list of installed apps.

### What is Expected?

I expected to be able to use CTRL C and run "choco upgrade all" again, and have "chromium" upgraded (instead of lost and no longer in my list of apps).  I was forced to "choco upgrade chromium" manually to get chromium to once again be listed when I checked using "choco list -lai -r"

### How Did You Get This To Happen?

I have Windscribe VPN with their firewall enabled.  I use split tunneling and had "chocolatey.org" in the exceptions list.

Today I was trying to update my apps with "choco upgrade all" and this happened:

chromium|121.0.6167.161|121.0.6167.185|false
Failed to fetch results from V2 feed at 'https://community.chocolatey.org/api/v2/ ...
[NuGet] Error downloading 'chromium.121.0.6167.185 : chocolatey [0.10.5, )'
[NuGet] The read operation failed, see inner exception.
[NuGet]   The operation has timed out.
[NuGet] Error downloading 'chromium.121.0.6167.185 : chocolatey [0.10.5, )'
[NuGet] Unable to read data from the transport connection: An existing
[NuGet]   An existing connection was forcibly closed by the remote host

It just sat there for 20 mins so I did a CTRL C:

Terminate batch job (Y/N)? y

I then added "community.chocolatey.org" to the split tunneling exceptions list and ran "choco upgrade all" again.

PROBLEM:  All apps updated, but "chromium" had been "lost" and didn't even show up in the list.

I did "choco upgrade chromium" and all was well again, but I thought I should report this.

### System Details

Windows 10 22H2 (10.0.19045.4046)
Windows PowerShell version 5.1.19041.4046 (but v7.4.1 is also installed)
Chocolatey CLI Version: 2.2.2
Chocolatey License type: free

### Installed Packages

```bash
I tried to include the list of pkgs, but it said "too long max is 65536"
```

### Output Log

```bash
2024-02-15 15:18:32,199 7816 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = '';[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::SystemDefault; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\chromium\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '' -preRunHookScripts $null -postRunHookScripts $null'] exited with '0'.
2024-02-15 15:18:32,203 7816 [DEBUG] - Calling command ['"C:\Windows\System32\shutdown.exe" /a']
2024-02-15 15:18:32,269 7816 [DEBUG] - Command ['"C:\Windows\System32\shutdown.exe" /a'] exited with '1116'
2024-02-15 15:18:32,422 7816 [INFO ] -   chromium may be able to be automatically uninstalled.
2024-02-15 15:18:32,540 7816 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\chromium'
2024-02-15 15:18:33,204 7816 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\chromium\chromium.nupkg'
  with checksum 'BD674FE40BFAC6A7B6C858A733AC01DE'
2024-02-15 15:18:33,206 7816 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\chromium\chromium.nuspec'
  with checksum 'DE8622122C2EB740810CFBC216CE036D'
2024-02-15 15:18:33,208 7816 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\chromium\legal\LICENSE.txt'
  with checksum '153BB85C038685126078B87011A386D6'
2024-02-15 15:18:33,209 7816 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\chromium\legal\VERIFICATION.txt'
  with checksum '3F4152C0BFA6EB5483524CEFA4AD4F98'
2024-02-15 15:18:33,210 7816 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\chromium\tools\chocolateyInstall.ps1'
  with checksum '5ACFA168AB32FA5CB89A039240F06582'
2024-02-15 15:18:33,212 7816 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\chromium\tools\chocolateyUninstall.ps1'
  with checksum '5E16E109D59D7159376C0C92EBCA752E'
2024-02-15 15:18:33,213 7816 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\chromium\tools\helper.ps1'
  with checksum '56C72A92432207759202A84664A32052'
2024-02-15 15:18:33,265 7816 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\.chocolatey\chromium.121.0.6167.185".
2024-02-15 15:18:33,274 7816 [DEBUG] - There was no original file at 'C:\ProgramData\chocolatey\.chocolatey\chromium.121.0.6167.185\.registry'
2024-02-15 15:18:33,279 7816 [DEBUG] - There was no original file at 'C:\ProgramData\chocolatey\.chocolatey\chromium.121.0.6167.185\.files'
2024-02-15 15:18:33,282 7816 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\chromium.121.0.6167.185\.extra".
2024-02-15 15:18:33,283 7816 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\chromium.121.0.6167.185\.version".
2024-02-15 15:18:33,284 7816 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\chromium.121.0.6167.185\.sxs".
2024-02-15 15:18:33,284 7816 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\chromium.121.0.6167.185\.pin".
2024-02-15 15:18:33,287 7816 [DEBUG] - Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
2024-02-15 15:18:33,289 7816 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\lib\chromium\.chocolateyPending".
2024-02-15 15:18:33,297 7816 [DEBUG] - Attempting to delete directory "C:\ProgramData\chocolatey\lib-bkp\chromium".
2024-02-15 15:18:33,321 7816 [INFO ] -  The upgrade of chromium was successful.
2024-02-15 15:18:33,324 7816 [INFO ] -   Software installed to 'C:\Program Files\Chromium\Application'
2024-02-15 15:18:33,346 7816 [WARN ] - 
Chocolatey upgraded 1/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2024-02-15 15:18:33,350 7816 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2024-02-15 15:18:33,353 7816 [DEBUG] - Exiting with 0
```

### Additional Context

n/a

**Comment by networkproblemsolver** [comment] 2024-02-15 16:12
NOTE:  Though your instructions says to "include the entire log" I was unable, due to "max is 65536"

**Comment by pauby** [comment] 2024-02-15 16:23
There are a few issues in here that are around using Control-C. The last one, and the ones that are seemingly most relevant to me, is #2757. I'm going to mark this a duplicate of that.

**Closed by pauby** 2024-02-15 16:23 UTC
Labels: Bug

**Comment by TheCakeIsNaOH** [comment] 2024-02-15 17:24
> NOTE: Though your instructions says to "include the entire log" I was unable, due to "max is 65536"

For future reference, use a Github gist, as have a much larger maximum size as compared to the body of the issue.
