### ISSUE TITLE
Implement DefaultPushSource like nuget

### ISSUE THREAD

**Issue by bc3tech** [chocolatey/choco#228] opened 2015-04-08 02:37 UTC
To save choco from removing packages on request and also save many users a lot of stress, it'd be great to have `DefaultPushSource` implemented like nuget does so users (corporate in particular) can set up the source that's pushed to when `-source` isn't given to `choco push`

http://docs.nuget.org/Consume/NuGet-Config-Defaults#sample-nugetdefaults.config

eg: `nuget config -set DefaultPushSource=http://mynuget.company.com`

**Comment by ferventcoder** [comment] 2015-04-08 03:05
This is a duplicate of either a conversation or an issue, but I'm not finding the issue. So I'm going to likely edit this a bit.

**Comment by ferventcoder** [comment] 2015-04-08 03:06
#62

**Comment by ferventcoder** [comment] 2015-04-08 03:06
Let's move the conversation over there. :)

**Closed** 2015-04-08 03:06 UTC
Labels: Duplicate Issue

**Comment by bc3tech** [comment] 2015-04-08 03:13
roger!
