### ISSUE TITLE
Error with IXmlService and IHashProvider with a fresh installation v0.9.9.11

### ISSUE THREAD

**Issue by amarhin** [chocolatey/choco#540] opened 2016-01-12 13:32 UTC
On a Windows 2008 R2 SP1, with a fresh Chocolatey installation, I've got the following error:

```shell
choco --help
```

> 2016-01-12 14:28:55,037 [DEBUG] - Configured chocolatey.infrastructure.logging.log4net.config.xml from assembly choco, Version=0.9.9.11, Culture=neutral, PublicKeyToken=79d02ea9cad655eb
2016-01-12 14:28:55,037 [DEBUG] - Configured chocolatey.infrastructure.logging.log4net.config.xml from assembly choco, Version=0.9.9.11, Culture=neutral, PublicKeyToken=79d02ea9cad655eb
2016-01-12 14:28:55,068 [DEBUG] - XmlConfiguration is now operational
2016-01-12 14:28:55,193 [ERROR] - The registered delegate for type IXmlService threw an exception. The registered delegate for type IHashProvider threw an exception. Exception has been thrown by the target of an invocation.
2016-01-12 14:28:55,208 [DEBUG] - Exiting with 1

Does someone has the same issue ?

**Comment by ferventcoder** [comment] 2016-01-12 13:40
Is #446 your issue?

**Comment by amarhin** [comment] 2016-01-12 14:14
It seems the same.
After registry modification on the specified Key, it works !

**Comment by ferventcoder** [comment] 2016-01-12 14:16
Okay sweet - note that we are adding a different hashing algorithm option for folks who run into this.

**Comment by ferventcoder** [comment] 2016-01-12 14:16
Closed as duplicate of #446.

**Closed by ferventcoder** 2016-01-12 14:16 UTC
Labels: 0 - _Triaging
