### ISSUE TITLE
Cannot install Chocolatey due to Windows Defender AMSI (Anti-Malware Scan Interfaces) blocking installation - "This script contains malicious content and has been blocked by your antivirus software"

### ISSUE THREAD

**Issue by nimpossible** [chocolatey/choco#2132] opened 2020-10-15 12:59 UTC
I am using the Licenced version of McAfee AV on my licenced Windows 10 Home Edition. Not sure what is interfering with Chocolatey, but it is not letting me install even being an Administrator.

Please note: I have already followed your documents for setting the ExecutionPolicies and all okay from my end. 

Also, attached the error as per the below screengrab: -

![Chocolatey_AV_Issue](https://user-images.githubusercontent.com/16114850/96129193-f4282900-0f13-11eb-99dc-c3dadedaaf51.png)

**Comment by vexx32** [comment] 2020-10-15 13:03
You might want to check your AV settings and make sure they allow signed scripts, at least while you run the installation. I'm not familiar enough with McAfee itself to know exactly where that's at, though.

**Comment by nimpossible** [comment] 2020-10-17 13:02
Okay. I will check the same. The only concern I have is after installing Chocolatey, will it do the same for every software install through its CLI. Also unsure, about being compromising with my System's Security too. So for now, will drop the plan to go ahead with Chocolatey; even though its a great package/concept/thought. Will check and explore WinGet.

**Comment by ferventcoder** [comment] 2020-10-20 19:59
I would love to know what it thinks is malicious?

**Comment by ferventcoder** [comment] 2020-10-20 20:03
Looks like Windows Defender AMSI - https://evotec.xyz/import-module-this-script-contains-malicious-content-and-has-been-blocked-by-your-antivirus-software/

**Comment by ferventcoder** [comment] 2020-10-20 20:05
https://acloud.guru/forums/python-for-beginners/discussion/-MBzMjt-giG46LHJjxwv/chocolatey%20won't%20install

**Comment by ferventcoder** [comment] 2020-10-20 20:06
https://superuser.com/q/1503345

**Comment by vexx32** [comment] 2020-10-20 20:22
It's possible simple `Invoke-Expression` / `iex` usage is enough to trigger Defender at this point tbh. 🤔

**Comment by TanishqPal** [comment] 2020-11-03 08:09
Hi! I was also facing the same problem but I was able to install chocolatey by opening McAfee app and disabling Real Time scanning and Firewall
<img width="656" alt="Screenshot 2020-11-03 133849" src="https://user-images.githubusercontent.com/73876202/97961823-fc200e00-1dd9-11eb-8863-661803a5aeb8.png">

**Comment by navaneethavarier** [comment] 2020-12-03 17:27
@TanishqPal Thanks! I was also facing the same issue and now it is working fine!

**Comment by nimpossible** [comment] 2020-12-06 11:36
@TanishqPal, @navaneethavarier: There is no point using Antivirus then! Though I know this works, it is not what is expected to be solution. Thanks!

**Comment by TanishqPal** [comment] 2020-12-09 15:30
Can you please close this issue ?

**Comment by pauby** [comment] 2021-01-13 10:46
@TanishqPal The issue is not yet resolved, so we should keep it open.

**Comment by Liegia** [comment] 2021-02-14 22:29
you have to re launch the shell after disabling real-time scan and firewall for the install to work if you have McAffe

**Comment by nimpossible** [comment] 2021-02-17 09:45
@Liegia: This isn't a solution! There should be a way like we usually have with other programs.

**Comment by pauby** [comment] 2021-02-17 10:00
@nimpossible The issue is invalid as the problem lies with McAfee and not Chocolatey.

And with all due respect, if the solution @Liegia posted works, then it is the solution.

> There should be a way like we usually have with other programs.

What did you have in mind?

**Comment by pauby** [comment] 2021-02-24 19:04
There has been no response to this so I'm going to go ahead and close it.

**Closed by pauby** 2021-02-24 19:04 UTC
Labels: Invalid / Not Issue / No repro / Not Implementing

**Comment by elouem7** [comment] 2021-03-01 17:16
> you have to re launch the shell after disabling real-time scan and firewall for the install to work if you have McAffe

THANK YOU

**Comment by msharp19** [comment] 2021-04-28 09:09
Run as admin.

**Comment by Sdrp2021** [comment] 2021-05-27 05:41
Ty so much guys. I was enable to install chocolatey. I have McAfee and I disable Firewall + Real-Time scan and then I launch PowerShell as admin and it works! Ty ty ty

**Comment by rejithnair** [comment] 2021-06-08 07:50
The issue is due to downloading the scripts from URL. I would suggest to download the chocolatey installation script from https://chocolatey.org/install.ps1 to a folder and edit the command

`Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('<full local downloaded path>/install.ps1'))`

**Comment by SA-Commit** [comment] 2021-06-11 09:01
> @TanishqPal Thanks! I was also facing the same issue and now it is working fine!

Thanks a lot, it worked!

**Comment by vmj** [comment] 2022-01-01 22:46
> The issue is due to downloading the scripts from URL. I would suggest to download the chocolatey installation script from https://chocolatey.org/install.ps1 to a folder and edit the command
> 
> `Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('<full local downloaded path>/install.ps1'))`

Thanks!  This works without tampering with security settings in McAcfee.
