### ISSUE TITLE
Upgrade Chocolately to .Net Core

### ISSUE THREAD

**Issue by genifycom** [chocolatey/choco#3350] opened 2023-10-27 17:53 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

For new machines, installing Chocolately requires both .Net framrwork and a reboot

".NET Framework 4.8 was installed, but a reboot is required.
 Please reboot the system and try to install/upgrade Chocolatey again."

Considering that .Net 4.8 is now 5 years old, can we please get an updated version that uses .Net Core like everything else.

### Describe The Solution. Why is it needed?

Installing .Net Framework 4.8 is completely redundant for the rest of the software suite that is currently in use.

**Comment by TheCakeIsNaOH** [comment] 2023-10-27 18:31
Duplicate of #2173

**Closed by TheCakeIsNaOH** 2023-10-27 18:31 UTC

**Comment by genifycom** [comment] 2023-10-27 23:14
Ah thanks for that. I searched but probably used the wrong keywords.
