### ISSUE TITLE
`choco upgrade <package>` error: "Already referencing a newer version of 'chocolatey-core.extension'"

### ISSUE THREAD

**Issue by Michal-Mikolas** [chocolatey/choco#2721] opened 2022-05-16 13:22 UTC
### What You Are Seeing?

```
Failures
 - git (exited 1) - git not upgraded. An error occurred during installation:
 Already referencing a newer version of 'chocolatey-core.extension'.
```

### What is Expected?

I expect Chocolatey to upgrade the package. Or give me specific reason what I did wrong. 

### How Did You Get This To Happen? (Steps to Reproduce)

1. I installed Git some time ago (v2.31.1). 
2. Today I wanted to upgrade to a new version. 
3. So I run `choco upgrade git`. 

### Output Log

```
PS C:\Users\mikolas> choco upgrade git
Chocolatey v1.1.0
Upgrading the following packages:
git
By upgrading, you accept licenses for the packages.

You have git v2.31.1 installed. Version 2.36.0 is available based on your source(s).
git not upgraded. An error occurred during installation:
 Already referencing a newer version of 'chocolatey-core.extension'.
git package files upgrade failed with exit code 1. Performing other installation steps.
The upgrade of git was NOT successful.
git not upgraded. An error occurred during installation:
 Already referencing a newer version of 'chocolatey-core.extension'.
 Unsuccessful operation for git.
  Rollback to previous version (package files only)?([Y]es/[N]o):

Timeout or your choice of '' is not a valid selection.
You must select an answer
 Unsuccessful operation for git.
  Rollback to previous version (package files only)?([Y]es/[N]o): N


Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
 Already referencing a newer version of 'chocolatey-core.extension'.
```

### Additional info

- I've experienced the same error with other packages: 7-zip, AutoHotkey, Google Chrome, Composer, CopyQ, Cygwin, pgAdmin, Python, VLC, VS Code. 
- But still some packages upgraded just fine: Java SE Runtime Environment, FileZilla, Node JS, ... 
- I have currently Windows 10 Home 21H2
- I've tried upgrading packages from Windows Terminal, PowerShell, Chocolatey GUI. Always with the same error. 
- I run the terminals / Chocolatey GUI as an administrator.

**Comment by pauby** [comment] 2022-05-16 14:43
This looks to be a duplicate of [this issue](https://github.com/chocolatey/choco/issues/1956).

**Closed by pauby** 2022-05-16 14:43 UTC
