### ISSUE TITLE
Upgrade chocolatey v0.10.7 to 0.10.8 fails.

### ISSUE THREAD

**Issue by jcsston** [chocolatey/choco#1483] opened 2018-02-05 20:17 UTC
### What You Are Seeing?
Trying to upgrade from chocolatey v0.10.7 to 0.10.8 fails with a "Value cannot be null. Parameter name: s" on Windows 10 Pro 64-bit

### What is Expected?
Chocolatey upgraded

### How Did You Get This To Happen? (Steps to Reproduce)
  chocolatey.exe upgrade cocolatey -vd

### Output Log
[GIST](https://gist.github.com/jcsston/0f62ab9726af90a821c648c144a8a9b4)

**Comment by ferventcoder** [comment] 2018-02-06 01:59
@jcsston There is something you need to turn off for it to be successful. One sec

**Comment by ferventcoder** [comment] 2018-02-06 02:01
This is a duplicate of #1383 (see the log https://gist.github.com/SaintGimp/4387a3415e40f36ced6118c8f3b9bb60).

Your fix is in the comment https://github.com/chocolatey/choco/issues/1383#issuecomment-322294286. Once you switch that, you can upgrade, then turn it back on as it is fixed in 0.10.8.

**Closed by ferventcoder** 2018-02-06 02:01 UTC
