### ISSUE TITLE
Filename too long error when Install-ChocolateyZipPackage invoked with unzip location = "C:\Program Files"

### ISSUE THREAD

**Issue by MaxFrost** [chocolatey/choco#671] opened 2016-03-25 03:45 UTC
### What You Are Seeing?
Failure to install win32-openssh version 2016.03.19 due to path too long error from function "Write-FileUpdateLog" with "C:\Program Files" expected as target

### What is Expected?
Normal install. Works with previous version of the package (which didn't use Install-ChocolateyZipPackage, instead directly invoking Get-ChocolateyUnzip without a packagename (and thus not invoking Write-FileUpdateLog)

### How Did You Get This To Happen? (Steps to Reproduce)
Dove into the scripts, error appears to specifically come from this line in Write-FileUpdateLog

$originalContents = Get-ChildItem -Recurse $locationToMonitor | Select-Object LastWriteTimeUTC,FullName,Length

I manually ran the following command, and noted some return errors regarding path length, specifically in my install directory for Microsoft Office 2016 O365 version (thanks microsoft!)

Get-ChildItem -recurse "C:\Program Files"

Trace was as follows
Install-ChocolateyZipPackage invokes Get-ChocolateyUnzip with a $unzipLocation value of $env:ProgramFiles and a $packageName value of Win32-openssh

$unzipLocation maps to $destination in get-chocolateyUnzip
Get-ChocolateyUnzip - if $packageName exists, it creates $zipExtractLogFullPath

If  $zipExtractLogFullPath exists, it calls Write-FileUpdateLog with -locationtoMonitor $destination.
remember, $destination = "C:\Program Files"

Write-FileUpdateLog calls  Get-ChildItem -Recurse $locationToMonitor, or more specifically in this case, Get-ChildItem -recurse "C:\Program Files"

Any script that ends up calling Install-ChocolateyZipPackage with an $unziplocation of "C:\Program Files", where said get-child C:\Program Files -recurse has a path that ends up being too long (and I'll fix mine) will end up throwing the error and forcing the install to stop. The problem I'm noting is that because its watching ALL program file folders, all it takes is one long path that isn't even the intended watch target of the function to force it to fail.

### Output Log

GIST LINK - Please create a gist and link to that gist here
https://gist.github.com/MaxFrost/0fd4247bd23a5dcedc6f

**Comment by ferventcoder** [comment] 2016-03-25 05:34
0.9.10 should not have this issue - can you install the beta and try this again?

`choco upgrade chocolatey -pre`

**Comment by ferventcoder** [comment] 2016-03-25 05:36
Possible Duplicate of #156

**Comment by ferventcoder** [comment] 2016-03-25 05:38
#155

**Comment by ferventcoder** [comment] 2016-03-25 05:47
Duplicate of #155 which was closed by #616.

**Closed by ferventcoder** 2016-03-25 05:47 UTC
Labels: 0 - _Triaging

**Comment by ferventcoder** [comment] 2016-03-25 05:52
Note the green ball in the title at https://chocolatey.org/packages/win32-openssh is a link - https://gist.github.com/choco-bot/2ecb8c43ac53fde70a0a

**Comment by MaxFrost** [comment] 2016-03-25 11:49
Beta works fine! Glad that it was already sorted out.

**Comment by ferventcoder** [comment] 2016-03-25 12:23
Sweet. :+1:
