### ISSUE TITLE
Choco does not delete the package on choco uninstall command

### ISSUE THREAD

**Issue by pradeeps** [chocolatey/choco#1533] opened 2018-04-04 10:30 UTC
### What You Are Seeing?
choco uninstall myMod

### What is Expected?
delete the package (including package folder from C:\Python27\Lib\site-packages\myProg\**myMod**)

### How Did You Get This To Happen? (Steps to Reproduce)
choco uninstall myMod

### Output Log
It says the package has been uninstalled by other means

Choco version used in this case is 0.10.0

**Comment by pradeeps** [comment] 2018-04-04 11:56
@ferventcoder , can you please help?

**Comment by ferventcoder** [comment] 2018-04-04 12:50
Hi @pradeeps. We'll need you to upgrade to 0.10.9 as 0.10.0 is very old and it's likely this was fixed. Once you've confirmed whether this is still an issue in the latest version, then we could continue to look more into this. 

For us to help, you need to follow the instructions as posted when you create an issue. That means full output log in a gist that is linked here. Without that, we won't be able to really help at all. 

Please don't file duplicate issues. This is the same as https://github.com/chocolatey/choco/issues/1455

> @ferventcoder , can you please help?

Please read and understand this section (open source support) at https://chocolatey.org/support#foss:

For open source users, please remember the [etiquette guidelines](https://github.com/chocolatey/choco/blob/master/README.md#etiquette-regarding-communication) when requesting support. If we've broken something and have acknowledged that we will fix it immediately, that is one thing. However "urgent" situations only apply to commercial editions (that include support). If you find yourself in an "urgent" situation, it may be time to look at [our commercial options](https://chocolatey.org/pricing#compare).

**Comment by ferventcoder** [comment] 2018-04-04 12:50
Duplicate of https://github.com/chocolatey/choco/issues/1455

**Comment by ferventcoder** [comment] 2018-04-04 12:51
Let's keep the conversation over there. Thanks!

**Closed by ferventcoder** 2018-04-04 12:50 UTC
Labels: Duplicate Issue, Not An Issue / Can't Repro / Not Implementing / Invalid
