### ISSUE TITLE
Have `choco list` without the package name run offline

### ISSUE THREAD

**Issue by ExE-Boss** [chocolatey/choco#1922] opened 2019-10-01 02:15 UTC
Currently, running
```pwsh
choco list
```
causes Chocolatey to try and fetch the entire package list from the package repository, which hangs for several minutes, while the entire list downloads with no feedback to the user as to what’s happening.

The most common usage of running such a command would instead be to list currently installed packages, which is what the `list` command does in all other package managers that I know of.

---

Preferably, `choco list <pkg>` would also run offline, with `choco search <pkg>` being the command that does the online search.

**Comment by AdmiringWorm** [comment] 2019-10-01 16:52
In chocolatey, to list only installed packages you need to pass in the argument `-lo` (local only). Otherwise it will indeed list packages from your sources.

**Comment by ExE-Boss** [comment] 2019-10-01 17:31
I know that, but I keep forgetting to pass the `‑‑local‑only` argument.

**Comment by AdmiringWorm** [comment] 2019-10-01 17:35
I understand, however I think it would be unlikely to be changed as it have been this way for so many years, and would be a major breaking change (think of everyone using it already in automation scripts).

Maybe when the 1.0 release comes 😀 (ie, some day in the future far away).

**Comment by vexx32** [comment] 2019-10-01 18:03
This is a duplicate of #158; this is a desired change but as @AdmiringWorm states it is one we must take caution before doing. 

However, I'm personally in full support. 😁

**Comment by ferventcoder** [comment] 2019-10-02 20:36
Duplicate of #158

**Comment by ferventcoder** [comment] 2019-10-02 20:37
I know it feels like I just repeated @vexx32, but I wanted it to add the automatic tracking to what this was a duplicate of and that requires it written a particular way. 

There are going to be other issues that will allow you to change the default earlier than v1 and #158. I don't remember the issue off hand but I believe it is there as well.

**Closed by ferventcoder** 2019-10-02 20:37 UTC
Labels: Duplicate Issue

**Comment by ferventcoder** [comment] 2019-10-02 20:39
I'm 100% in support of this as well - have been for years but like @vexx32 and @AdmiringWorm mentioned it would be known to break EVERY integration tool that is using Chocolatey were we to change it without plenty of planning, notice, and on a major version.
