### ISSUE TITLE
Add `fetch` command to download (but not install) packages, including external URLs

### ISSUE THREAD

**Issue by alexchandel** [chocolatey/choco#660] opened 2016-03-14 20:24 UTC
It is impossible to install Chocolatey or ~~most~~ community chocolatey packages on a computer that isn't connected to the internet. However, offline systems are often the ones where chocolatey would be most useful.

While it's possible to effectively "transplant" an installation by copying the chocolatey folder to the ProgramData of a new machine, this only works for "simple" packages. Packages that install outside of chocolatey, and especially packages that install services (like [Win32-OpenSSH](https://chocolatey.org/packages/win32-openssh)), are broken by this.

There should be a way to cache packages for chocolatey, and complementarily a way to install packages from this local cache. For example, if I were to do `choco download win32-openssh`, I should later be able to do `choco install win32-openssh` without an internet connection. This should work both with packages that bundle their own installers like Win32-OpenSSH and with packages that download an archive/installer from a URL.

To give an example of a good implementation, [Homebrew](https://github.com/Homebrew/homebrew/) caches the most recent version of every package you install. Even when `brew cleanup` is run, cached archives for currently installed packages are not deleted. So if one does `brew install wine; brew uninstall wine; brew install wine`, Homebrew will not redownload `wine` the second time.

**Comment by ferventcoder** [comment] 2016-03-14 22:01
> It is impossible to install chocolatey or most chocolatey packages on a computer that isn't connected to the internet. However, offline systems are often the ones where chocolatey would be most useful.

This is factually incorrect. Almost every organization that uses Chocolatey now does exactly this. 

Let's fix up your terminology a bit.

"It is impossible to use Chocolatey.org and the community packages from Chocolatey.org from a computer that is not connected to the internet, even if you have cached those packages locally."

That sounds more appropriate.

**Comment by ferventcoder** [comment] 2016-03-14 22:02
Packages on dot org must work with software distribution laws and so they must point off to internet resources. Internal packages are not bound by this limitation at all. That's why we need to fix up the wording of this a bit.

**Comment by ferventcoder** [comment] 2016-03-14 22:03
> if I were to do choco download win32-openssh, I should later be able to do choco install win32-openssh without an internet connection. This should work both with packages that bundle their own installers like Win32-OpenSSH and with packages that download an archive/installer from a URL.

Sort of duplicates #108.

**Comment by ferventcoder** [comment] 2016-03-14 22:06
> So if one does brew install wine; brew uninstall wine; brew install wine, Homebrew will not redownload wine the second time.

Not to harp on this too much, but if one does:

~~~sh
choco install 1password 
choco uninstall 1password 
choco install 1password
~~~

Chocolatey also doesn't download the 1password installer a second time. Only the package.

**Comment by ferventcoder** [comment] 2016-03-14 22:08
> There should be a way to cache packages for chocolatey, and complementarily a way to install packages from this local cache.

I feel this is really the ask here. Which is handled by #108 mostly.

**Comment by ferventcoder** [comment] 2016-03-14 22:10
> This should work both with packages that bundle their own installers like Win32-OpenSSH and with packages that download an archive/installer from a URL.

The second part is the tricky part here. How would you go about doing this now?

**Comment by alexchandel** [comment] 2016-03-15 17:16
> "It is impossible to use Chocolatey.org and the community packages from Chocolatey.org from a computer that is not connected to the internet, even if you have cached those packages locally."

Fixed for community packages.

> This is factually incorrect. Almost every organization that uses Chocolatey now does exactly this.

But is it entirely? If so, how does one install Chocolatey without an internet connection?

> Packages on the community feed (https://chocolatey.org/packages aka dot org) must work with software distribution laws and so they must point off to internet resources. Internal packages are not bound by this limitation at all. That's why we need to fix up the wording of this a bit.

Is this a limitation of Chocolatey beyond licensing? Because AFAIK the GPL, MIT, BSD, and Apache license would all permit chocolatey to install a cached copy without hitting the internet (consider Homebrew). They would probably also permit such packages to be downloaded but not installed, to be installed later.

> Chocolatey also doesn't download the 1password installer a second time. Only the package.

Does it connect to the internet at all?

**Comment by ferventcoder** [comment] 2016-03-15 17:22
> But is it entirely? If so, how does one install Chocolatey without an internet connection?

With the Chocolatey nupkg and some PowerShell. Or whatever. The Puppet and Chef providers both support exactly this scenario.

**Comment by ferventcoder** [comment] 2016-03-15 17:23
> Does it connect to the internet at all?

It depends on where it is getting the package from. In my demos for Puppet and Chocolatey, I switch off all internet access.

**Comment by ferventcoder** [comment] 2016-03-15 17:23
> Is this a limitation of Chocolatey beyond licensing? Because AFAIK the GPL, MIT, BSD, and Apache license would all permit chocolatey to install a cached copy without hitting the internet (consider Homebrew). They would probably also permit such packages to be downloaded but not installed, to be installed later.

You may likely see more embedded packages where it is allowed. It increases the stability of Chocolatey to have things embedded.

**Comment by alexchandel** [comment] 2016-03-15 21:31
> With the Chocolatey nupkg and some PowerShell

That's cool, I never looked into how `install.ps1` installed chocolatey. It seems like the steps are unzipping the nupkg and running `/tools/chocolateyInstall.ps1`, setting $ChocolateyInstall to `C:\ProgramData\Chocolatey`, and appending `C:\ProgramData\Chocolatey\bin` to the $PATH.

> It depends on where it is getting the package from. In my demos for Puppet and Chocolatey, I switch off all internet access.

Not sure about internet access for `Install-ChocolateyZipPackage -URL`, but it seems like it is necessary to copy the `%TEMP%/chocolatey` folder's contents for them.

> You may likely see more embedded packages where it is allowed. It increases the stability of Chocolatey to have things embedded.

So downloading "embedded" packages will be possible with #108?

Though the model is a little different, I like Homebrew's approach of distinguishing between a package (which is described by a single file, hosted in some repository) and various "bottles" for that package (compiled for different systems and architectures).

**Comment by alexchandel** [comment] 2016-05-17 21:43
Thinking about it, I think the command should be called `fetch`, and have similar semantics to Homebrew's `brew fetch`. Download the package and any associated files

>> This should work both with packages that bundle their own installers like Win32-OpenSSH and with packages that download an archive/installer from a URL.

> The second part is the tricky part here. How would you go about doing this now?

That's the thing. It may call for a more advanced API, or perhaps special treatment of `Install-ChocolateyZipPackage`. I like how Homebrew handles this: the package scripts (e.g. [this](https://github.com/Homebrew/homebrew-core/blob/master/Formula/moreutils.rb)) declare both resources they will download AND the "install" script.

**Comment by ferventcoder** [comment] 2016-07-28 21:44
This is a duplicate of #108

**Closed by ferventcoder** 2016-07-28 21:44 UTC
Labels: Duplicate Issue
