### ISSUE TITLE
Upgrade all reuses overridden package parameters when useRememberedArgumentsForUpgrades feature is turned on

### ISSUE THREAD

**Issue by dinfinity** [chocolatey/choco#1443] opened 2017-11-06 13:35 UTC
### What You Are Seeing?
I have a multitude of packages installed via chocolatey, a number of which I have set custom install directories for. Chocolatey regularly shows error messages that indicate that the overridden parameters for another package are used. For instance:

```
ERROR: Running ["C:\Users\Dual Infinity\AppData\Local\Temp\chocolatey\TotalCommander\9.10\INSTALL.exe" INSTALLDIR=C:\Frameworks\NodeJS] was not successful. Exit code was '1'. See log for possible error messages.
The upgrade of totalcommander was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\TotalCommander\tools\chocolateyInstall.ps1'.
 See log for details.
```

It seems to use the last overridden parameters encountered.

Addendum 2017-11-07:
The issue is usually resolved by running the upgrade all command multiple times. It does not seem random, but it does seem that if a package with custom parameters was installed successfully its parameters are not read and do not conflict in the subsequent run of upgrade all.

### What is Expected?
Chocolatey should (obviously) not reuse package parameters for other packages.

### How Did You Get This To Happen? (Steps to Reproduce)
In essence, this would entail setting custom install dirs for multiple packages and running chocolatey upgrade all.

### Output Log
See zip:
[dinfinity.chocolatey.log.2017-11-06.zip](https://github.com/chocolatey/choco/files/1446353/dinfinity.chocolatey.log.2017-11-06.zip)

### Related 
* https://github.com/chocolatey/choco/issues/797

**Comment by ferventcoder** [comment] 2017-11-06 16:19
This sounds like a bug, and a major one.

**Comment by ferventcoder** [comment] 2017-11-06 16:44
This isn't going to be quite as easy to find the cause of as hoped. Thanks for the log file. The code in question doesn't reuse parameters (on first glance, there could be a small bug in there). 

I think to really find this, we're going to need to understand how you installed everything and possibly take a much closer look (if you are up for it).  

How did you install things? One at a time or did you run multiple choco.exe processes at the same time?

**Comment by dinfinity** [comment] 2017-11-07 20:24
Taking a closer look is no problem. I like chocolatey a lot.

I have been ignoring this issue for a couple of months now, so I can't say for sure I did not run multiple simultaneous choco commands, although I can't remember doing so and deem it quite unlikely.

I could provide a zip of (parts of) my ProgramData\chocolatey directory if that helps.

I'm adding the following to the issue description:
"The issue is usually resolved by running the upgrade all command multiple times. It does not seem random, but it does seem that if a package with custom parameters was installed successfully its parameters are not read and do not conflict in the subsequent run of upgrade all."

**Comment by ferventcoder** [comment] 2018-02-12 18:07
Without a repo, we'll need to bump this to vNext.

**Comment by Vankog** [comment] 2018-03-07 21:23
As it turns out, this also happened to me: 
http://disq.us/p/1qp8o56

VLC got "upgraded" from 64 to 32bit on *upgrade all* after reusing remembered arguments that forced the 32bit upgrade for notepadplusplus earlier.

**Comment by francois-iveo** [comment] 2018-04-22 12:12
This is still happening. I have created a new issue for a related problem.

**Comment by ferventcoder** [comment] 2018-05-04 19:34
I'm wondering if packages getting upgraded as a result of being a dependency of another package are getting hit by this...

**Comment by ferventcoder** [comment] 2018-05-04 19:35
Adding a partial adjustment for 0.10.11, but we'll need to see if it alleviates the bigger issue  - I don't think it will until we isolate for each package.

**Comment by dinfinity** [comment] 2018-12-28 18:13
In my case this seems very very similar to what is reported here: https://github.com/chocolatey/choco/issues/797

There are 2 packages (out of many) that I installed with -ia "INSTALLDIR=C:\aaa\bbb" (Vagrant and NodeJS) and some other packages (Total Commander, Mysql Workbench, Google Earth Pro) want to install into the NodeJS and Vagrant directories.

I see a fix has been added in 347f09f
I am hoping that will solve this very, very annoying issue.

**Comment by ferventcoder** [comment] 2019-03-04 18:54
The fix has been implemented, but it won't correct where it is already wrong. That involves running an upgrade for items with the arguments you want to be used. Given this was known to have issues and was in early preview, unfortunately I'm not sure what additional fixes we'll take on for that.

**Comment by musm** [comment] 2019-03-04 19:07
can we set this as the default option  (useRememberedArgumentsForUpgrades true)?

**Comment by ferventcoder** [comment] 2019-03-13 21:54
Closing this as fixed for 0.10.12. We want to watch this closely. If you run into this, consider the bug occurs LONG before it is seen so you may have already had this with an older version of Chocolatey. We are looking specifically for folks who are starting with 0.10.12 and run into this later to know if we've fixed the issue or not.

**Comment by akaleeroy** [comment] 2019-04-25 18:54
Please add some documentation about how this system works. Specifically how to reset the state.

Here's what I ran into: I set up `choco feature enable -n useRememberedArgumentsForUpgrades` then did a few botched upgrades (wrong parameters). I `disable`d the feature thinking I would start over from scratch, that no package parameters would be remembered. 

Then after hunting down all the install args for no bloody desktop shortcut for each and every package (the Windows Group Policy conveniently named _Prevents users from changing the desktop icons_ inconveniently fails to stop packages from installing a desktop icon AGAIN on every upgrade) I re-enabled `useRememberedArgumentsForUpgrades` and started upgrading with valid args. 

Except when it came to a package with botched arguments. That first run was unexpectedly remembered! I thought flipping the setting off then on again would get me to a clean slate.

Why isn't this a text config again? Where are these remembered arguments stored?

**Comment by ferventcoder** [comment] 2019-04-26 13:00
@akaleeroy leave the feature turned off while running the upgrades. Choco always records the args passed, the feature being turned on is just about whether it applies them at upgrade or not.

**Comment by francois-iveo** [comment] 2020-05-01 20:45
@ferventcoder I am _still_ struggling with this issue.
1. I have deleted all old versions of package directories in `C:\ProgramData\chocolatey\.chocolatey`
2. I have corrected all `.arguments` files in `C:\ProgramData\chocolatey\.chocolatey` by decrypting them, removing the spurious install dir and package parameters from them and reencrypting them.
3. On a run of `choco upgrade all`, Calibre, the package _after_ Apache2 in that run immediately took on the parameters of Apache2:
` --package-parameters="'/installLocation:C:\Frameworks\Apache2'" --allow-downgrade --cache-location="'C:\Temp\Windows\Dual Infinity\chocolatey'"`
That is, the new version of Calibre in `C:\ProgramData\chocolatey\.chocolatey` contained those arguments in `.arguments`.

My chocolatey version is 0.10.15 and it is **still** absolutely unclear to me how to prevent these remembered arguments from being transferred to other packages whilst retaining the remembered arguments for the packages for which I do want customized directories.

I think this issue has not been fixed at all, or the remembered arguments are stored somewhere else than where I fixed them.

**Comment by dinfinity** [comment] 2020-05-01 20:48
@ferventcoder I am _still_ struggling with this issue.
1. I have deleted all old versions of package directories in `C:\ProgramData\chocolatey\.chocolatey`
2. I have corrected all `.arguments` files in `C:\ProgramData\chocolatey\.chocolatey` by decrypting them, removing the spurious install dir and package parameters from them and reencrypting them.
3. On a run of `choco upgrade all`, Calibre, the package _after_ Apache2 in that run immediately took on the parameters of Apache2:
` --package-parameters="'/installLocation:C:\Frameworks\Apache2'" --allow-downgrade --cache-location="'C:\Temp\Windows\Dual Infinity\chocolatey'"`
That is, the new version of Calibre in `C:\ProgramData\chocolatey\.chocolatey` contained those arguments in `.arguments`.

My chocolatey version is 0.10.15 and it is **still** absolutely unclear to me how to prevent these remembered arguments from being transferred to other packages whilst retaining the remembered arguments for the packages for which I do want customized directories.

I think this issue has not been fixed at all, or the remembered arguments are stored somewhere else than where I fixed them.
(reposted with personal account)

**Comment by ferventcoder** [comment] 2020-06-15 20:32
@dinfinity we are going to be looking much closer at this in the coming weeks. We want to get this ironed out and working.

**Comment by ferventcoder** [comment] 2020-06-15 20:32
However, if you can, this should be a new issue that links back to this issue.

**Comment by ferventcoder** [comment] 2020-06-15 20:33
Actually, I'm going to reopen this issue.

**Comment by ruedigerk** [comment] 2020-06-19 18:47
I am also seeing this issue most of the time running "choco upgrade all". I tried uninstalling and reinstalling the packages that have wrong arguments, force upgraded them, deleted the .arguments file for them - this resolves the problems for a single run of "upgrade all" (I think) but on the next run, the problems reoccur.

**Comment by gep13** [comment] 2021-04-21 08:33
A reproducible test was documented in this issue: https://github.com/chocolatey/choco/issues/2111 and a fix has been put in place to address that issue.

We believe that this will also address the problems in this issue.  As such, I am going to go out this issue, and we can come back to it if there are still issues being reported after we ship 0.10.16 of Chocolatey.

**Comment by tylerszabo** [comment] 2021-09-03 15:05
I'm still hitting this issue in 0.11.1

I attempted `choco upgrade all` and every package after `git.install` used `--package-parameters="'/GitAndUnixToolsOnPath /WindowsTerminal /NoAutoCrlf /NoShellIntegration'"`

**Comment by gep13** [comment] 2021-09-03 15:28
@TheCakeIsNaOH any chance you can take a look at this, based on the test that you put forward in the linked issue?

**Comment by TheCakeIsNaOH** [comment] 2021-09-03 16:24
@gep13 
I'm working on it, the test environment is being fussy about upgrading to 0.11.1

@tylerszabo 
Is there any chance that these parameters could be coming from saved arguments that got "contaminated" when packages were upgraded when choco 0.10.15 was installed? I may be able to come up with a better test in a bit.

**Comment by tylerszabo** [comment] 2021-09-03 16:26
@TheCakeIsNaOH the versions prior were set properly in the `.arguments` files; checked with the following script:

```powershell
Get-ChildItem -Filter ".arguments" -Path "C:\ProgramData\chocolatey\.chocolatey" -Recurse | ForEach-Object { Write-Output ("{0}: {1}" -f $_.Directory.BaseName, [System.Text.Encoding]::UTF8.GetString([System.Security.Cryptography.ProtectedData]::Unprotect([System.Convert]::FromBase64String(($_ | Get-Content -Encoding UTF8)), [System.Text.Encoding]::UTF8.GetBytes("Chocolatey"), [System.Security.Cryptography.DataProtectionScope]::LocalMachine))) }
```

**Comment by TheCakeIsNaOH** [comment] 2021-09-03 16:57
Ah, interesting. And not really in a good way. I thought I had this one figured out.

The good news  is that the issue with packages switching to prerelease (#2111) seems to have been fixed, in my testing. The reproduction I had in that other issue is no longer switching python3 to prerelease.

**Comment by TheCakeIsNaOH** [comment] 2021-09-03 17:09
@gep13 @tylerszabo 

I've got a reproduction in the test environment:

Steps:
1. Setup/start the test environment, and do a fresh `vagrant sandbox rollback`. 
2. Make sure it is running choco `0.11.1`
2. Download [wget 1.21.1](https://community.chocolatey.org/packages/Wget/1.21.1), [wget 1.21.1.20210323](https://community.chocolatey.org/packages/wget/1.21.1.20210323), [git.install 2.33.0](https://community.chocolatey.org/packages/git.install/2.33.0) and [git.install 2.33.0.2](https://community.chocolatey.org/packages/git.install/2.33.0.2) into the packages directory for the test environment.
3. Add these lines to the `vagrantfile` in the standard "THIS IS WHAT YOU UNCOMMENT" place:
```
choco.exe feature enable -n userememberedargumentsforupgrades
choco.exe install -fdvy git.install --version=2.33.0 --package-parameters="'/GitAndUnixToolsOnPath /WindowsTerminal /NoAutoCrlf /NoShellIntegration'" --source "'c:\\packages'"
choco.exe install -fdvy wget --version=1.21.1 --source "'c:\\packages'"
choco.exe upgrade -dvy all --source "'c:\\packages'"
```
4. Run `vagrant provision`
5. See that `wget` `1.21.1.20210323` has the `git.install` package parameters included as well.
```
Running 'ChocolateyScriptRunner' for Wget v1.21.1.20210323 with packageScript 'C:\ProgramData\chocolatey\lib\Wget\tools\chocolateyinstall.ps1', packageFolder:'C:\ProgramData\chocolatey\lib\Wget', installArguments: '', packageParameters: '/GitAndUnixToolsOnPath /WindowsTerminal /NoAutoCrlf /NoShellIntegration',
```

**Comment by TheCakeIsNaOH** [comment] 2021-10-06 21:53
I've done a bit more debugging, and this reuse is not just applicable to package parameters, but also to other arguments. Specifically, I've tested `--forcex86` and `--install-arguments`, and both of those get reused as well.

Everything is fine inside `chocolatey.infrastructure.app.services.NugetService.upgrade_run()`, but once the nuget package has been installed, and it goes onto `chocolatey.infrastructure.app.services.ChocolateyPackageService.handle_package_result()` to run the powershell script (and other stuff), the arguments from the previous package pop back into the config.

**Comment by TheCakeIsNaOH** [comment] 2021-12-05 15:01
I think I may have found a fix for this, PR opened: #2484

I still have to do more through testing.

**Comment by tylerszabo** [comment] 2022-01-18 22:39
For the purposes of tracking may this issue be re-opened? It's not the end of the world to avoid `cup all` . I'm currently working around by calling one of the following:

```powershell
choco outdated --ignore-pinned --limitoutput | % { $_ -replace "(^[^|]*).*", '$1' } | % { & cup $_; if($LASTEXITCODE -ne 0) { throw "cup failed $LASTEXITCODE"} }
```

```cmd
for /f "delims=|" %i in ('choco outdated --ignore-pinned --limitoutput') do ( cup %i )
```

This CMD script isn't particularly error safe; if put into a script it'd need to be modified to do `call`/`goto` in order to safely handle errors because CMD parameter expansion is wonky.

**Comment by gep13** [comment] 2022-01-19 13:54
@tylerszabo said...
For the purposes of tracking may this issue be re-opened?

Yes, I think that this would make sense.  The work that was already done on this fixed _part_ of the problem, but there are obviously still other places where it needs to be addressed.

**Comment by mu88** [comment] 2022-03-17 11:38
Any updates on this?  I ran into that issue today and a fix for `choco upgrade all` would be really cool

**Comment by TheCakeIsNaOH** [comment] 2022-03-17 17:59
@mu88  There is an open PR that should fix this issue, #2484

**Comment by mu88** [comment] 2022-03-17 18:13
@TheCakeIsNaOH Thank you, that looks promising! Do you know what blocks it from being merged? It seems that it hasn't seen a lot of attention since December 2021

**Comment by pauby** [comment] 2022-03-18 00:35
The stream wouldn't be the best place to discuss that. [Discord](https://ch0.co/community) would be better.

**Comment by mu88** [comment] 2022-03-18 12:10
I habe an absolutely crazy idea: rather than discussing it on another medium, why not... here? 😋😉 The code is here, the issue is here, the PR is here.

Simply not answering to an open PR for more than
three months does not really motivate people to OSS projects - at least give feedback like "we want it, but..." or "this and that is missing" or "we're not interested".

**Comment by pauby** [comment] 2022-03-18 13:13
It's not a crazy idea. But discussing it on a Stream isn't workable and it's not going to answer your question.

Once this is allocated to a milestone, we will then be able to pick this up and review it. Until that time this is unlikely to get attention as we will be focusing on other areas, products and milestones.

I appreciate it is frustrating. It is just as frustrating for the Chocolatey Team. However, there are only so many of us to go around and so many hours in the day. We have many priorities to juggle, and sometimes we have to prioritise one area over another. That means some people will be happy and some frustrated.

**Comment by mu88** [comment] 2022-03-18 14:59
So what would you recommend? Should we ask on Discord how the future of this issue and the related PR will look like? Or is the team now aware of it and will discuss about it?

**Comment by pauby** [comment] 2022-03-18 18:14
> So what would you recommend? 

Waiting until it's allocated to a specific milestone.

**Comment by ScoobyDone** [comment] 2022-05-12 01:44
Oh this has been a long road....  :(   
Is this bug what would cause many (many!) packages pick up remembered args from other packages?  I know that it's happening because I dumped the .arguments files (using the snippet above from @tylerszabo and packages are picking up options from other packages (custom paths, so definitive pollution).  and then they (obviously) keep using them.  Also, just as in #797...

Been using remembered args since:
```
2021-07-06 14:04:42,184 18196 [INFO ] - ============================================================
2021-07-06 14:04:42,296 18196 [INFO ] - Chocolatey v0.10.15
2021-07-06 14:04:42,301 18196 [DEBUG] - Chocolatey is running on Windows v 10.0.19043.0
2021-07-06 14:04:42,303 18196 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2021-07-06 14:04:42,303 18196 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2021-07-06 14:04:42,308 18196 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" feature enable -n useRememberedArgumentsForUpgrades
2021-07-06 14:04:42,309 18196 [DEBUG] - Received arguments: feature enable -n useRememberedArgumentsForUpgrades
```

If this isn't going to be fixed anytime soon, the docs should be updated to warn users that this is broken in a major way that will, at a minimum, be painful to correct.  

How can I programmatically edit all the arguments files?  I can pseudo-code it in my head but I don't know PS that well.  bash, yes but...

A command to redirect the encrypted file into an unencrypted one and then the command to encrypt it back would be great.  I can handle the rest but my head hurts from researching this.

Thanks.

**Comment by opoplawski** [comment] 2022-07-11 22:07
Even when upgrading a single package, I cannot add additional options.  E.g. if thunderbird was installed with:
```
choco install thunderbird --version 102.0.0 --force  -y --package-parameters='/l:en-US'
```
and I upgrade with:
```
choco.exe upgrade thunderbird --fail-on-unfound --yes --no-progress --params "/NoStop /l:en-US" --timeout 14400 --debug
```
I get:
```
Running Get-PackageParameters
Parsing $env:ChocolateyPackageParameters and $env:ChocolateyPackageParametersSensitive for parameters
Adding package param 'l'='en-US'
```
So the /NoStop is dropped.  Is this the same bug that is reported here?

**Comment by TheCakeIsNaOH** [comment] 2022-07-11 22:21
@opoplawski no it is not the same bug.

**Closed** 2022-09-22 17:56 UTC
Labels: Bug, Priority_HIGH, 3 - Review, ADD AUTO TESTS

**Comment by escalonn** [comment] 2022-10-23 04:34
five years to get such a basic part of one of the most obvious use cases fixed
