### ISSUE TITLE
Add shortcut "i" for install

### ISSUE THREAD

**Issue by CodingSpiderFox** [chocolatey/choco#2256] opened 2021-05-02 16:23 UTC
Typing a lot annoys me.

Instead of "choco install -y openhardwaremonitor" I want to be able to use "choco i -y openhardwaremonitor"

**Comment by TheCakeIsNaOH** [comment] 2021-05-03 14:05
I would suggest using `cinst` which translates to `choco install` and is available as a shim on the path.

Also, this is a duplicate of #1921

**Comment by CodingSpiderFox** [comment] 2021-05-03 15:39
thx for the hint

**Comment by gep13** [comment] 2021-05-05 11:43
@TheCakeIsNaOH thanks for spotting that.  I have marked this as a duplicate, and will go ahead and close this out.

**Closed by gep13** 2021-05-05 11:43 UTC
Labels: Duplicate Issue
