### ISSUE TITLE
$Env:ChocolateyPackageParameters Not created in installscript context.

### ISSUE THREAD

**Issue by GitAMBS** [chocolatey/choco#1375] opened 2017-08-03 09:09 UTC
### What You Are Seeing?
$Env:ChocolateyPackageParameters not created during install script execution.

$packageparameters is available and valid. 

$Env:ChocolateyPackageParameters is referenced serveral times and is as the default value for the extension function Get-PackageParameters.

We have been able to reproduce across windows installs. 
### What is Expected?
$Env:ChocolateyPackageParameters Should contain the package parameters passed from "choco install"

### How Did You Get This To Happen? (Steps to Reproduce)
On Windows 10 1703 build

During execution script the above mentioned environment variable is not available. It does not exist in the session. 

Package is executed locally. with the following command.
```powershell
#chocolatey-core.extension 1.3.1 installed from source prior to running this command. 
choco install C:\Temp\plastertest\VendorPest\AppPest\0.1.0\VendorPest.AppPest.0.1.0.nupkg --package-parameters "'/arg1 1'" -y -f -d -s C:\Temp\plastertest\VendorPest\AppPest\0.1.0
```

Simple package that outputs variable to files.
## Install script
```powershell
#Requires -Version 3 -RunAsAdministrator
$ErrorActionPreference = 'stop'

#ModuleName is package name without prefix
$prefix = $env:chocolateyPackageName.Split('.')[0]
$ModuleName = $env:chocolateyPackageName.TrimStart("$prefix").TrimStart('.')

Update-SessionEnvironment

#Get Parameters
$CmdParam = Get-PackageParameters $Env:ChocolateyPackageParameters

$envvars = gci env:\
$envvars | Select-Object 'name', 'Value' | ConvertTo-Json | Out-File -FilePath C:\Temp\chocoenv.txt

####
#IA behaviour not tested.
####

$Env:ChocolateyPackageParameters | Out-File -FilePath C:\Temp\chocoparamRaw.txt
#$env:ChocolateyInstallArguments | Out-File -FilePath C:\Temp\chocoiaRaw.txt
$PackageParameters | Out-File -FilePath C:\Temp\chocoparamRaw2.txt
#$InstallArguments | Out-File -FilePath C:\Temp\chocoiaRaw2.txt

```

### Result 
The result from outputting the content of the different variables.

$Env:ChocolateyPackageParameters = "" _empty_

$PackageParameters = "/arg1 1"

## All env. var in session, like Choco*
_Side Note. 
version numbers here do not match what is shown in the console._ v0.10.7
```json
{
        "Name":  "CHOCOLATEY_VERSION",
        "Value":  "0.10.5.0"
    },
    {
        "Name":  "CHOCOLATEY_VERSION_PRODUCT",
        "Value":  "0.10.5"
    },
    {
        "Name":  "ChocolateyAllowEmptyChecksumsSecure",
        "Value":  "true"
    },
    {
        "Name":  "ChocolateyEnvironmentDebug",
        "Value":  "true"
    },
    {
        "Name":  "ChocolateyEnvironmentVerbose",
        "Value":  "true"
    },
    {
        "Name":  "ChocolateyForce",
        "Value":  "true"
    },
    {
        "Name":  "ChocolateyInstall",
        "Value":  "C:\\WINDOWS\\DIR\\Chocolatey"
    },
    {
        "Name":  "ChocolateyLastPathUpdate",
        "Value":  "fr apr  7 13:55:19 2017"
    },
    {
        "Name":  "chocolateyPackageFolder",
        "Value":  "C:\\WINDOWS\\DIR\\Chocolatey\\lib\\VendorPest.AppPest"
    },
    {
        "Name":  "chocolateyPackageName",
        "Value":  "VendorPest.AppPest"
    },
    {
        "Name":  "chocolateyPackageTitle",
        "Value":  "VendorPest.AppPest"
    },
    {
        "Name":  "chocolateyPackageVersion",
        "Value":  "0.1.0"
    },
    {
        "Name":  "chocolateyPackageVersionPackageRelease",
        "Value":  "0"
    },
    {
        "Name":  "ChocolateyPath",
        "Value":  "C:\\Chocolatey"
    },
    {
        "Name":  "ChocolateyPowerShellHost",
        "Value":  "true"
    },
    {
        "Name":  "chocolateyRequestTimeout",
        "Value":  "30000"
    },
    {
        "Name":  "chocolateyResponseTimeout",
        "Value":  "2700000"
    }
```
## Gist
chocolatey Log
https://gist.github.com/GitAMBS/96c801cb71b8d492532a21ef71fbdf19

**Comment by ferventcoder** [comment] 2017-08-03 13:33
I'm a little surprised [this warning](https://github.com/chocolatey/choco/blob/e96fb159e0957d9e2fee1e738d42dcc414957c91/src/chocolatey.console/Program.cs#L165) did not show up: 

> "The use of .nupkg or .nuspec in for package name or source is known to cause issues. Please use the package id from the nuspec `<id />` with `-s .` (for local folder where nupkg is found)."

The warning should have shown up, but I think I see why it did not - "--package-parameters" contains "pack".

Here's the deal - if the warning would have shown up, you would have learned that calling install to a nupkg file is known to have some pretty big issues, especially surrounding passing package parameters and install arguments. This is why your package parameters do not make it through.

OT: The use of force (`-f`, `--force`) is an anti-pattern. Don't use it outside of testing. It short-circuits some behaviors you want Chocolatey to have.

HTH

**Comment by ferventcoder** [comment] 2017-08-03 14:05
Can you include a log where you had the environment variable output to screen as part of the run?

**Comment by ferventcoder** [comment] 2017-08-03 14:05
Also, consider using `--noop` with `-d` to see what the config gets set to for package parameters without actually performing the install.

**Comment by ferventcoder** [comment] 2017-08-06 22:39
@GitAMBS any chance you can provide the requested information?

**Comment by GitAMBS** [comment] 2017-08-07 10:19
absolutely. 
i'll get back asap

**Comment by GitAMBS** [comment] 2017-08-07 10:56
@ferventcoder 

New gist with env. vars. + output .

https://gist.github.com/GitAMBS/3eb8b0e7a08e749a794b0f79bb4d2075

**Comment by ferventcoder** [comment] 2017-08-24 22:47
Found the issue - you are still not calling Chocolatey correctly. https://github.com/chocolatey/choco/issues/1375#issuecomment-319970008 

Once you call `choco install VendorPest.AppPest -s C:\Temp\plastertest\VendorPest\AppPest\0.1.0 --package-parameters "'/arg1 1'"` you will see it work appropriately.

**Comment by ferventcoder** [comment] 2017-08-24 22:56
The only time you should have nupkg in your command is when you are push a nupkg to a remote source. We've found issues with using it. 

What you are seeing here is a duplicate of #1155.

**Closed by ferventcoder** 2017-08-24 22:56 UTC
Labels: 0 - Waiting on User, 0 - _Triaging
