### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by PetreHoffmann** [chocolatey/choco#3211] opened 2023-06-12 08:41 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

Is Version 2.0.0 very slow, or it's, me? It takes more than 1 Minute top Start upgrading.

### What is Expected?

faster reaction on choco upgrade.

### How Did You Get This To Happen?

I ran command `choco upgrade all`

### System Details

* Operating System: Windows 11 10.0.22621.0
* Windows PowerShell version: 5.1.22621.1778
* Chocolatey CLI Version: 2.0.0
* Chocolatey Licensed Extension version: Chocolatey v2.0.0
* Chocolatey License type: Community
* Terminal/Emulator: Microsoft Terminal

### Installed Packages

```bash
7zip 22.1.0
7zip.install 22.1.0
audacity 3.3.3
autohotkey.install 1.1.36.2
chocolatey 2.0.0
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
chocolateygui 2.0.0
chocolatey-windowsupdate.extension 1.0.5
discord 1.0.9005
discord.install 1.0.9005
DotNet4.5 4.5.20120822
DotNet4.6 4.6.81.20150925
dotnetfx 4.8.0.20220524
filezilla 3.64.0
git 2.41.0
git.install 2.41.0
goggalaxy 2.0.67.2
GoogleChrome 114.0.5735.110
greenshot 1.2.10.6
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
keepass 2.53.1
keepass.install 2.54.0
masterpackager 23.3.8528
microsoft-edge 114.0.1823.43
microsoft-teams.install 1.6.0.12455
notepadplusplus.install 8.5.3
obs-studio 29.1.2
obs-studio.install 29.1.2
openssl 1.1.1.2100
openvpn 2.6.4.1
origin 10.5.122.52971
pdf24 11.12.1
postman 10.14.2
putty.install 0.78.0
rufus 4.1.0
spotify 1.2.13.661
streamlabs-obs 1.13.1
sysinternals 2023.6.7
teamspeak 3.5.6
teamviewer 15.42.7
treesizefree 4.6.3
vcredist140 14.36.32532
vcredist2010 10.0.40219.32503
vcredist2013 12.0.40660.20180427
vcredist2015 14.0.24215.20170201
vcredist2017 14.16.27033
vnc-viewer 7.5.1
vscode 1.79.0
vscode.install 1.79.0
winscp 6.1.0
winscp.install 6.1.0
```

### Output Log

```bash
https://gist.github.com/PetreHoffmann/64826e5e3c230d172407ae4e69dd7efc
```

**Comment by pauby** [comment] 2023-06-12 09:03
This is a duplicate of #3183. 

Please see [this comment](https://github.com/chocolatey/choco/issues/3208#issuecomment-1583435452) and the sticky issue in this repository..

**Closed** 2023-06-12 09:03 UTC
Labels: Duplicate Issue
