### ISSUE TITLE
"Unable to read from path" after disk exhaustion issue

### ISSUE THREAD

**Issue by djechelon** [chocolatey/choco#1829] opened 2019-05-17 15:13 UTC
### What You Are Seeing?
```
Chocolatey installed 0/0 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.lo
Sending message 'PostRunMessage' out if there are subscribers...
Unable to read package from path 'wiztree\wiztree.nupkg'.
```

### What is Expected?

To install package WizTree, because now I have enough space

### How Did You Get This To Happen? (Steps to Reproduce)

I had a disk space issue with the server. Disk was (almost) full but I still tried to install WizTree by doing `choco install wiztree`. First attempt reported the error that the disk was full.
However, even after freeing enough space I am getting the current error consistently.

### Output Log

Find it here: https://gist.github.com/djechelon/1d0854681403fed751d4129752778e60

### Other considerations

I think that the partial download broke the file. I believe `choco` should have been abkle to either recover itself or delete temporary created files on a crash.

Deleting C:\ProgramData\chocolatey\lib\WizTree **fixed** the issue

**Comment by ferventcoder** [comment] 2019-05-20 16:15
Actually, I think this is related to #717. I'm going to close it as a duplicate

**Comment by ferventcoder** [comment] 2019-05-20 16:15
Duplicate of #717

**Comment by ferventcoder** [comment] 2019-05-20 16:16
I'm going to add a note over there to look at this issue for additional considerations.

**Closed by ferventcoder** 2019-05-20 16:15 UTC
Labels: Duplicate Issue
