### ISSUE TITLE
Allow the use of package.config files on upgrade

### ISSUE THREAD

**Issue by Spitzbub** [chocolatey/choco#1103] opened 2016-12-20 18:41 UTC
On install instead of specifying a package name you can use a package.config file to specify what packages/versions (plus courses and other options) to install. This though is not available for the upgrade command and thus it is not possible to upgrade multiple packages to multiple specific versions. Upgrade should be enhanced to support package.config

From gitter:

```
Russell Mora
@Spitzbub
Dec 19 11:55
Hi, does chocolatey CLI support specifying the pkg version with the name, like with apt I can say 'apt install pkg=version'? I looked in the documentation and couldn't find anything and tried it and it didn't work....
Richard Simpson
@RichiCoder1
Dec 19 11:56
@Spitzbub You mean like choco install <pgk> --version <version>?
Russell Mora
@Spitzbub
Dec 19 12:15
Yes, but I want to install multiple packages, so I would like to do choco install <pkg1>=<version1> <pkg2>=<version2> ...
I can of course use the packages.config file, but that only works for install. Usually I want to use choco upgrade <pkg1>=<version1> <pkg2>=<version2> ... because it will upgrade packages already installed and install packages that are not installed.
Rob Reynolds
@ferventcoder
Dec 19 13:24
@Spitzbub not like that, no, not yet supported. Can you file an issue so we can prioritize it?
Russell Mora
@Spitzbub
Dec 19 13:46
@ferventcoder What should I exactly file the issue for? I assume that the upgrade command doesn't take a package.config file rather than that you can't specify a version with a package name, correct?
Or both? :grinning:
Rob Reynolds
@ferventcoder
Dec 19 14:05
you can specify a version with package name, but not in the way you described. I think it may be preferable to allow upgrades from packages.config
```

**Comment by ferventcoder** [comment] 2016-12-21 03:02
Two things - you can link directly to the gitter conversation (preferred).

Also this is a dupe of #533

**Closed** 2016-12-28 17:29 UTC
Labels: Duplicate Issue
