### ISSUE TITLE
Show install location in package info

### ISSUE THREAD

**Issue by vertigo220** [chocolatey/choco#1568] opened 2018-05-10 04:06 UTC
The info page for installed packages should show where the application is installed (its path) and, ideally, display it as a link that opens file manager to that location.

**Comment by ferventcoder** [comment] 2018-05-10 04:30
Duplicate of #681

**Comment by ferventcoder** [comment] 2018-05-10 04:31
Howdy @vertigo220, I've marked this as a duplicate of #681. Please subscribe/comment on that issue. Thanks!

**Closed by ferventcoder** 2018-05-10 04:30 UTC
Labels: Duplicate Issue

**Comment by vertigo220** [comment] 2018-05-10 05:01
Done. Should I submit this as an issue in the GUI repo?
