### ISSUE TITLE
Listing all package versions when searching for an exact package name only returns the latest version

### ISSUE THREAD

**Issue by bender-the-greatest** [chocolatey/choco#2153] opened 2020-11-13 15:36 UTC
Running `choco list -a PACKAGENAME` or `choco search -a PACKAGENAME` will return all known versions of a package which are available. However, when you want to only see an exact package, e.g. `powershell-core` and not other packages which have `powershell-core` in the name or other metadata, adding `-e` to the argument list only returns the latest version of the package. For example:

```powershell
choco list -a powershell-core
```
Returns the following packages and versions:

```text
awslambdapscore 2.0.0.0
awslambdapscore 1.2.0.0
awslambdapscore 1.1.0.0
poshhosts 0.2.0
poshhosts 0.1.0
powershell.portable 6.0.4
powershell.portable 6.0.4.20180815
powershell.portable 6.1.0
powershell.portable 6.1.1
powershell.portable 6.2.4
powershell.portable 6.0.2
powershell.portable 6.0.2.20180614
powershell.portable 6.0.3
powershell.portable 6.2.0
powershell.portable 6.2.1
powershell.portable 6.2.2
powershell.portable 6.2.3
powershell.portable 7.0.0
powershell.portable 7.0.1
powershell.portable 7.0.2
powershell.portable 7.0.3
powershell-core 7.0.1
powershell-core 7.0.0
powershell-core 6.2.4
powershell-core 6.1.3
powershell-core 6.1.2
powershell-core 6.1.1
powershell-core 6.1.0.20181026
powershell-core 6.1.0
powershell-core 6.0.4
powershell-core 7.0.2
powershell-core 6.2.0
powershell-core 6.2.0.20190408
powershell-core 7.1.0
powershell-core 7.0.3
powershell-core 6.2.3
powershell-core 6.2.2
powershell-core 6.2.1.20190704
powershell-core 6.2.1
powershell-core 6.1.6
powershell-core 6.1.5
powershell-core 6.1.4
powershell-core 6.0.2.20180727
powershell-core 6.0.2.20180704
powershell-core 6.0.2
powershell-core 6.0.1
powershell-core 6.0.0
pwsh 7.0.2
pwsh 7.0.1
pwsh 7.0.0
pwsh 6.2.4
pwsh 6.2.0.20190408
pwsh 6.2.0
pwsh 6.1.3
pwsh 6.1.2
pwsh 6.1.1
pwsh 6.1.0.20181026
pwsh 6.1.0
pwsh 6.0.4
pwsh 6.0.0
pwsh 6.0.1
pwsh 7.0.3
pwsh 6.0.2.20180704
pwsh 6.1.4
pwsh 6.2.1
pwsh 6.2.2
pwsh 6.1.6
pwsh 6.2.3
pwsh 7.1.0
```

Adding `-e` for an exact name search curates the list only to the exact package name, but does not list all available versions:

```powershell
choco list -ae powershell-core
```

Returns:

```text
powershell-core 7.1.0
```

Separating the arguments makes no difference here. `-ae` exhibits the same behavior as `-a -e`. The behavior I'm expecting with `-ae` is to return all versions of the exact provided package name.

**Comment by ferventcoder** [comment] 2020-12-08 18:39
Yep, there is an existing issue for this. Let me dig it up. You can choco upgrade chocolatey --pre and see if that resolves it for you in the beta.

**Comment by ferventcoder** [comment] 2020-12-08 18:39
Duplicate of #1843

**Closed by ferventcoder** 2020-12-08 18:39 UTC
