### ISSUE TITLE
List install arguments

### ISSUE THREAD

**Issue by musm** [chocolatey/choco#1855] opened 2019-06-19 20:06 UTC
Hello `useRememberedArgumentsForUpgrades` is set to true 

I'd like to list the arguments for upgrades so I know which ones have been set

`choco list -lo` does not list them

Thanks

**Comment by ferventcoder** [comment] 2019-07-02 01:39
I believe this is a dupe of #1310. Best to subscribe to that one.

**Comment by ferventcoder** [comment] 2019-07-02 01:40
Duplicate of #1310

**Closed by ferventcoder** 2019-07-02 01:40 UTC
