### ISSUE TITLE
Cannot install multiple packages with upgrade command

### ISSUE THREAD

**Issue by Peter-Csatlos** [chocolatey/choco#2885] opened 2022-11-04 14:57 UTC
### What You Are Seeing?
With the `choco upgrade -y multiple package names` command if the packages are not installed, only the first packages is installed. 
Choco exits with exit code 1 and this warning line:
`Chocolatey upgraded 0/0 packages.`

### What is Expected?
Before the 1.2.0 update all packages got installed this way.

### How Did You Get This To Happen? (Steps to Reproduce)

Add the steps that allows US to reproduce your problem. For example.

1. I ran this command `choco upgrade -y chocolatey vcredist2012 greenshot lightshot slack vlc winrar wireshark zoom googlechrome totalcommander 7zip notepadplusplus dwgtrueview adobereader mc wireguard`
2. The first NOT installed packages gets installed.
3. choco exits with exit code 1, `Chocolatey upgraded 0/0 packages.`

### System Details

* OS Build: 10.0.19044.0
* Windows PowerShell version: 5.1.19041.1320
* Chocolatey version: 1.2.0

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

choco.summary.log and chocolatey.log:
[https://gist.github.com/Peter-Csatlos/85dd85b9e4a04af943b0d2f3de16230a](https://gist.github.com/Peter-Csatlos/85dd85b9e4a04af943b0d2f3de16230a)

</p>

</details>

**Comment by TheCakeIsNaOH** [comment] 2022-11-04 15:08
Duplicate of #2884

**Closed by TheCakeIsNaOH** 2022-11-04 15:08 UTC
