### ISSUE TITLE
Handle "strg + c" during installation are no trapped

### ISSUE THREAD

**Issue by timmjd** [chocolatey/choco#3338] opened 2023-09-29 10:25 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

If a user does install a package `choco install whatever` and during the installation presses `strg + c`, the current `chocolateyInstall.ps1` gets aborted. Sadly  the overall installation gets __not__ aborted, it seems only the context of the `chocolateyInstall.ps1` is stopped but the Chocolatey core continues it's logic. As a result, the package will be listed as __installed__ package - even so we stopped the actual installation and the package gets not finished.

To work aground this, we would need to react on the `strg + c` event and manually set the install state to failed (`Set-PowerShellExitCode`).

There might be a global way to solve this by registering a [trap](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_trap?view=powershell-5.1) for this to be implemented inside the Chocolatey core where the `chocolateyInstall.ps1` etc. scripts gets called and bypassing the state change from __uninstalled__ to __installed__ - so as a result aborting the installation with `strg + c` will not result in an __installed__ package.

### What is Expected?

If I abort the installed by `strg + c` and the package instalaltion was not finished, the package installation should be aborted or as a result, the package should be in state of __not installed__.

### How Did You Get This To Happen?

1. `choco install whatever`
2. Hit `strg + c` to interrupte the installer
3. Type `choco list` and you will see that `whatever` was installed successfully

### System Details

* Operating System: Windows 11
* Windows PowerShell version: 5.1
* Chocolatey CLI Version: 2.2.2
* Chocolatey Licensed Extension version: -
* Chocolatey License type: -
* Terminal/Emulator: cmd / powershell

### Installed Packages

```bash
-
```

### Output Log

```bash
-
```

**Comment by pauby** [comment] 2023-09-29 11:18
This is a duplicate of https://github.com/chocolatey/choco/issues/619

**Closed by pauby** 2023-09-29 11:18 UTC
Labels: Bug
