### ISSUE TITLE
Delay / slowness when updating all ~200 packages

### ISSUE THREAD

**Issue by virzak** [chocolatey/choco#3208] opened 2023-06-08 20:47 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

There's a delay between package upgrades in v2

### What is Expected?

Expect seeing packages flying by if upgrade is not needed

### How Did You Get This To Happen?

choco upgrade all -y

### System Details

* Operating System: Windows 11
* Windows PowerShell version: cmd
* Chocolatey CLI Version: 2

### Installed Packages

```bash
C:\Windows\System32>choco list
Chocolatey v2.0.0
7zip 22.1.0
7zip.install 22.1.0
acrylic-dns-proxy 2.1.1
act-cli 0.2.46
adb 34.0.1.20230514
adobereader 2023.3.20201.1
atom 1.63.1
atom.install 1.63.1
audacity 3.3.2
autohotkey.portable 2.0.2
awscli 2.11.26
azcopy10 10.19.0
azure-cli 2.49.0
azure-data-studio 1.44.0
azure-functions-core-tools 4.0.5198
beyondcompare 4.4.6.27483
blender 3.5.1
calibre 6.19.1
cascadiacode 2111.1.0
cascadiacodepl 2111.1.0
cascadiamono 2111.1.0
cascadiamonopl 2111.1.0
chocolatey 2.0.0
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
chocolatey-font-helpers.extension 0.0.4
chocolatey-misc-helpers.extension 0.0.4
chocolatey-windowsupdate.extension 1.0.5
cmake 3.26.4
cmake.install 3.26.4
cpu-z 2.6.0
cpu-z.install 2.6.0
curl 8.1.2
dd 0.6.3-beta1
deno 1.34.1
dns-benchmark 1.3.6668.20190425
docker 99.0.0
docker-cli 24.0.2
docker-desktop 4.19.0
DotNet4.5.2 4.5.2.20140902
DotNet4.6 4.6.81.20150925
DotNet4.6.1 4.6.1055.20170308
dotnet-6.0-desktopruntime 6.0.16
dotnet-6.0-sdk-1xx 6.0.116
dotnet-6.0-sdk-2xx 6.0.203
dotnet-6.0-sdk-3xx 6.0.311
dotnet-7.0-desktopruntime 7.0.5
dotnet-7.0-sdk 7.0.302
dotnet-7.0-sdk-1xx 7.0.105
dotnet-7.0-sdk-2xx 7.0.203
dotnet-7.0-sdk-3xx 7.0.302
dotnetcore-3.1-sdk 3.1.426
dotnetcore-3.1-sdk-4xx 3.1.426
dotnetcore-sdk 3.1.426
dotnet-desktopruntime 7.0.5
dotnetfx 4.8.0.20220524
dotnet-sdk 7.0.302
droidcamclient 6.5.2
ffmpeg 6.0.0
fiddler 5.0.20211.51073
filezilla 3.64.0
FiraCode 6.2.0
Firefox 114.0.0
geekbench 6.1.0
geekbench5 5.5.1
geekbench6 6.1.0
gh 2.30.0
git 2.41.0
git.install 2.41.0
github-desktop 3.2.3
GoogleChrome 114.0.5735.110
googleearthpro 7.3.6.20230128
gpu-z 2.53.0
grammarly-for-windows 1.0.33.520
handbrake 1.6.1
handbrake.install 1.6.1
heroku-cli 7.53.0.20220328
hxd 2.5.0
ilspy 8.0.0
imagemagick 7.1.1.1100
imagemagick.app 7.1.1.1100
InkScape 1.2.2.20230220
iTunes 12.12.9.4
jq 1.6.0
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
KB3063858 1.0.0
KB3118401 1.0.5
kindle 1.40.65535
less 633.0.0
linqpad7 7.7.15
linqpad7.install 7.7.15
maven 3.9.2
megasync 4.9.4
microsoftazurestorageexplorer 1.29.2
mingw 12.2.0.3042023
msbuild-structured-log-viewer 2.1.758
nano 7.2.25
nano-win 7.2.25
netfx-4.6.1-devpack 4.6.1055
netfx-4.6.2 4.6.2.20210905
netfx-4.6.2-devpack 4.6.1590.20210905
netfx-4.7.2 4.7.2
netfx-4.8.1 4.8.1
netfx-4.8.1-devpack 4.8.1
notepadplusplus 8.5.3
notepadplusplus.install 8.5.3
NSwagStudio 13.19.0
nuget.commandline 6.6.0
NugetPackageExplorer 6.0.64
nvm 1.1.9
nvm.install 1.1.11
obs-studio 29.1.2
oh-my-posh 17.0.0
openaudible 3.7.4
openjdk 20.0.1
openjdk11 11.0.16.20220913
openvpn 2.6.4.1
paint.net 5.0.6
postgresql 15.2.0
postgresql14 14.5.1
postgresql15 15.2.0
postman 10.14.2
PowerBI 2.117.984
powershell-core 7.3.4
powertoys 0.70.1
python 3.11.4
python3 3.11.4
python311 3.11.4
rclone 1.62.2
rclone.portable 1.62.2
resharper-clt 2023.1.2
resharper-clt.portable 2023.1.2
rsync 6.2.8
rufus 4.1.0
shfmt 3.6.0
signal 6.20.1
skype 8.98.0.206
speedtest 1.1.1.1
SQLite 3.42.0
sqlitebrowser 3.12.2
sqlitebrowser.install 3.12.2
sql-server-express 2022.16.0.1000
sql-server-management-studio 19.0.20209
sysinternals 2023.6.7
teamviewer 15.42.6
telegram 4.8.3
telegram.install 4.8.3
Temurin11 11.0.19.700
teracopy 3.9.7
thunderbird 102.12.0
UrlRewrite 2.1.20190828
utorrent 3.5.5.45271
vcredist140 14.36.32532
vcredist2008 9.0.30729.616104
vcredist2010 10.0.40219.32503
vcredist2013 12.0.40660.20180427
vcredist2015 14.0.24215.20170201
vcredist2017 14.16.27033
viber 18.8.0.4
vlc 3.0.18
vlc.install 3.0.18
vscode 1.78.2
vscode.install 1.78.2
Wget 1.21.4
WhatsApp 2.2323.4
windirstat 1.1.2.20161210
winfsp 2.0.23075
wireshark 4.0.6
yarn 1.22.19
youtube-dl 2021.12.17
youtube-dl-gui 0.4.0
youtube-dl-gui.install 0.4.0
zoom 5.14.10.17221
178 packages installed.
```

### Output Log

```bash
Won't let be paste because it is too long
```

**Comment by pauby** [comment] 2023-06-08 21:49
This is a duplicate of https://github.com/chocolatey/choco/issues/3183.

Please see the [upgrade guide](https://docs.chocolatey.org/en-us/guides/upgrading-to-chocolatey-v2-v6#optimizing-performance).

**Closed** 2023-06-09 06:30 UTC
Labels: Duplicate Issue
