### ISSUE TITLE
Compatibility with prerelease string starting with a number. Compatibility with GitVersion and NuGet v3.5+

### ISSUE THREAD

**Issue by xlegalles** [chocolatey/choco#1158] opened 2017-02-06 11:48 UTC
We use GitVersion to create semantic versions from git flow branches: it works perfectly with Nuget 3.5 but we get some trouble with Chocolatey:

### What You Are Seeing?
5.79.2-6297-eventstorem004 is not a valid version string

### What is Expected?
This is given by GitVersion for Nuget and it is supposed to work. If you use the same command, same nuspec with Nuget 3.5, it just works.

### How Did You Get This To Happen? (Steps to Reproduce)

```sh
Command line: "C:\ProgramData\chocolatey\choco.exe" pack C:\Users\legalles\AppData\Local\Temp\FakeChocolateyPack\Kautomate.Service.EventStore.5.79.2-6297-eventstorem0004.nuspec --version 5.79.2-6297-eventstorem004 -y -d
Received arguments: pack C:\Users\legalles\AppData\Local\Temp\FakeChocolateyPack\Kautomate.Service.EventStore.5.79.2-6297-eventstorem0004.nuspec --version 5.79.2-6297-eventstorem004 -y -d
The source 'https://chocolatey.org/api/v2/' evaluated to a 'normal' source type

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='pack'|
CacheLocation='C:\Users\legalles\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://chocolatey.org/api/v2/'|SourceType='normal'|
Debug='True'|Verbose='False'|Force='False'|Noop='False'|
HelpRequested='False'|RegularOutput='True'|QuietOutput='False'|
PromptForConfirmation='False'|AcceptLicense='True'|
AllowUnofficialBuild='False'|
Input='C:\Users\legalles\AppData\Local\Temp\FakeChocolateyPack\Kautomate.Service.EventStore.5.79.2-6297-eventstorem0004.nuspec'|

Version='5.79.2-6297-eventstorem004'|AllVersions='False'|
SkipPackageInstallProvider='False'|Prerelease='False'|ForceX86='False'|
OverrideArguments='False'|NotSilent='False'|
ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='6.1.7601.65536'|
Information.PlatformName='Windows 7'|
Information.ChocolateyVersion='0.10.3.0'|
Information.ChocolateyProductVersion='0.10.3'|
Information.FullName='choco, Version=0.10.3.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64Bit='True'|Information.IsInteractive='True'|
Information.IsUserAdministrator='True'|
Information.IsProcessElevated='False'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseFipsCompliantChecksums='False'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IncludeRegistryPrograms='False'|ListCommand.PageSize='25'|
ListCommand.Exact='False'|ListCommand.ByIdOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|FeatureCommand.Command='unknown'|
ConfigCommand.Command='unknown'|PinCommand.Command='unknown'|
_ Chocolatey:ChocolateyPackCommand - Normal Run Mode _
Chocolatey had an error occur:
System.ArgumentException: '5.79.2-6297-eventstorem004' is not a valid version string.
Parameter name: version
   at NuGet.SemanticVersion.Parse(String version)
   at chocolatey.infrastructure.app.services.NugetService.pack_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.pack_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
```

**Comment by pascalberger** [comment] 2017-02-18 06:50
This seems like the same issue NuGet < 3.5 had, that it couldn't handle pre-release tags starting with a number. There is already an open issue over at the GitVersion repository for providing version numbers which should work with NuGet < 3.5 and therefore also be suitable for Chocolatey: https://github.com/GitTools/GitVersion/issues/781

**Comment by ferventcoder** [comment] 2017-03-18 14:57
This is not NuGet. This uses NuGet.Core framework, but that doesn't mean it has some of the newest stuff yet. Perhaps we should better document this somewhere.

I'm going to tag this as related to https://github.com/chocolatey/choco/issues/508, as moving foward should resolve this issue.

**Comment by bbowman** [comment] 2017-03-30 05:53
+1 here. We are using GitVersion for our versions as well and ran into this. @ferventcoder I think this is why I hit the bad gateway error today (running choco push manually complains about the version string).

**Comment by ferventcoder** [comment] 2017-03-30 07:27
@bbowman thanks for logging this.

**Comment by subhiandrews** [comment] 2017-05-24 17:48
We are using 0.10.5 and it is still problem! Is there are an ETA on this?

**Comment by ferventcoder** [comment] 2017-05-24 17:55
Hi @subhiandrews - I am going to move this from the 0.10.x milestone to 0.10.7. Keep an eye on that milestone as it could change. Yes this is still a known issue, and it will be until a released version of Chocolatey (key in on the milestone for the fix version) is released.

**Comment by ferventcoder** [comment] 2017-05-24 17:56
Most likely the issue isn't the number, it is using "-" multiple times in the version string.

**Comment by ferventcoder** [comment] 2017-05-24 17:58
It sounds like this would need a fix on the server side as well to recognize this as a valid string. Let's get an issue created there as well. Please follow https://github.com/chocolatey/chocolatey.org/issues/516

**Comment by AdmiringWorm** [comment] 2017-05-26 21:41
@ferventcoder I don't think the issue is with multiple dashes in a pre-release version string, as that is what I did when I had to update the wixtoolset package once: https://chocolatey.org/packages/wixtoolset/3.11.0.1528-rc2-20170424
Could be it only happens if the first part of the pre-release string is a number though (just a thought).

**Comment by bbowman** [comment] 2017-05-26 21:44
Yeah I experienced that it's the number first in the prerelease string that is the problem.

**Comment by leovic0101** [comment] 2018-03-18 17:54
I am also getting a similar issue on Chocolatey 0.10.8. We are using semantic versioning 2.0 and the the format that I am using is 1.0.0-Dev.0001. It does seem to work with SemVer 1.0 (1.0.0-Dev0001).

It seems to be a Nuget issue although it seems to be supporting SemVer 2.0 (https://github.com/NuGet/Home/wiki/SemVer-2.0.0-support) 

Is there something I am missing?

Thanks.

**Comment by DiscoveringWorld** [comment] 2022-10-06 13:20
Any news on that to support v3 and not only v2 ?

**Comment by gep13** [comment] 2022-10-07 08:11
@DiscoveringWorld rather than posting the same question in multiple places, let's keep the conversation in once place.  The correct place to continue discussing this is in this issue: https://github.com/chocolatey/choco/issues/508

**Comment by TheCakeIsNaOH** [comment] 2023-07-14 22:59
Prerelease strings that start with a number are a part of semver v2, so this issue is a duplicate of  https://github.com/chocolatey/choco/issues/1610

**Closed by TheCakeIsNaOH** 2023-07-14 22:59 UTC
Labels: Improvement, 0 - Backlog, Customer, Requires NuGet.Client Change
