### ISSUE TITLE
[Feature Request] Respect Installed Package Architecture When Upgrading

### ISSUE THREAD

**Issue by cmulk** [chocolatey/choco#1194] opened 2017-03-09 16:19 UTC
Choco upgrade defaults to installing the package that matches the machine architecture, regardless of the architecture of the previously installed version.

For example, i am on a x64 machine, but I use the x86 version of notepadplusplus since it still has better support. I install it with the command below:
`choco install notepadplusplus.install --x86`

However, when I go to update everything with `choco upgrade all`, it tries to install the x64 version. The workaround is to pin the package and upgrade it individually with `choco upgrade notepadplusplus.install --x86`, but it would be nicer if it knew to respect the --x86 from the previous install automatically.

**Comment by ferventcoder** [comment] 2017-03-09 21:24
Howdy, this is coming in 0.10.4. The issue is #797, which would make this a duplicate of that. Feel free to comment or subscribe to that issue. Thanks!

**Closed by ferventcoder** 2017-03-09 21:24 UTC
